### DISCUSSION TITLE
Triggering an existing argo workflow from a kafka sensor

### DISCUSSION THREAD

**Discussion by oscarusuga** [argoproj/argo-events#1032] [Q&A] [answered]
Hello community!

I'm wondering if there is a way to create a kafka sensor that triggers an existing workflow created before the sensor. This is because I already have a workflow created in the `default` namespace and I need it to be triggered right after the kafka sensor receives a kafka message.

This is the sensor configuration I created but does not work:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
    name: kafka
spec:
    template:
        serviceAccountName: argo-events-sa
    dependencies:
        - name: test-dep
          eventSourceName: kafka
          eventName: publication
    triggers:
        - template:
              name: argo-workflow-trigger
              group: argoproj.io
              version: v1alpha1
              resource: workflows
              operation: submit
              source:
                  resource:
                      social-media
```

The existing workflow is named `social-media` and I also tried using the examples found in the repository: I tried with `special-workflow-trigger` and `trigger-source-configmap.yaml` with no luck.

Do you guys know a way to configure the kafka sensor to trigger an existing argo workflow?

Thank you very much!

**Comment by whynowy** [comment, marked as answer]
Do you mean `resubmit` a workflow? If that the case, use something like:

```
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: resubmit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: your-workflow-name
              spec:
                xxx
```
