### DISCUSSION TITLE
SNS Parameterization JSON handling.

### DISCUSSION THREAD

**Discussion by emanodame** [argoproj/argo-events#1059] [Q&A]
Hi all,

I have an SNS that I want to use to trigger workflows. 

Example message sent to SNS:

```
{
  "field1" : "test1",
  "field2" : "test2"
}
```

I want my sensor to directly parse this JSON and use the fields as arguments to start the workflow.

My sensor ( I've omitted part of the sensor for the sake of brevity) 

```
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: test-workflow-
                namespace: workflows
              spec:
                serviceAccountName: default
                arguments:
                  parameters:
                    - name: field1
                      value: "{{inputs.parameters.message}}"
                workflowTemplateRef:
                  name: creator-workflow
          parameters:
            - src:
                dependencyName: sns-consumer
                dataKey: body.Message.field1
              dest: spec.arguments.parameters.0.value
```

Essentially, the aim is to have 'field1' param from the SNS to be used as an input to creator-workflow.

The current issue im facing is that it does not pick up 'field1' and the full event payload object (context, data) gets sent as a paramter. I can also paste this here if it helps.
