### DISCUSSION TITLE
How to trigger an existing Argo Workflow?

### DISCUSSION THREAD

**Discussion by joyofdata** [argoproj/argo-events#1080] [Q&A] [answered]
Hello!

I wasn't able to figure out from the documentation how to trigger an existing Workflow residing in namespace "argo".

All examples I found trigger newly created Workflows - f.x.:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: whalesay
                ...
```
My current experimental set up is quite simple. I installed Argo Workflows as described in ns "argo" on GKE. That works fine. I can submit Workflows etc.

Then I installed Argo Events as described in ns "argo-events".

So, let's say I have a Workflow "workflow-xyz" in ns "argo" and I want to trigger it with a webhook via Argo Events. How would I have to specify the Sensor?

Thanks

Raffael

**Comment by joyofdata** [comment, marked as answer]
https://github.com/argoproj/argo-events/discussions/1032

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: resubmit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: test-wf
                namespace: argo
```
