### DISCUSSION TITLE
Trying to setup PubSub as event source - doesn't seem to work - help appreciated.

### DISCUSSION THREAD

**Discussion by ghost** [argoproj/argo-events#1092] [Q&A] [answered]
Hello,

I'm wondering if there is something wrong with my setup? I want to use PubSub as the event source.

- topic "argo-events" exists
- subscription "argo-events-sub" exists
- service account "argo-events@proj-dev.iam.gserviceaccount.com" with pubsub.admin role attached exists

I didn't find an error message, yet.
But if I send a message (gcloud pubsub topics publish argo-events --message='{"messag":"test"}') - nothing happens.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  nats:
    native:
      replicas: 3
      auth: token

---

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: pubsub-event-source
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events
  pubSub:
    example:
      jsonBody: true
      topic: argo-events
      subscriptionID: argo-events-sub


---

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-template
  namespace: argo
spec:
  entrypoint: whalesay
  serviceAccountName: psf-forecasting
  templates:
  - name: whalesay
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
      resources:
        limits:
          memory: 32Mi
          cpu: 100m

---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: pubsub-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: pubsub-event-source-dep
      eventSourceName: pubsub-event-source
      eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-test-
                namespace: argo
              spec:
                workflowTemplateRef:
                  name: test-template

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events
  namespace: argo-events
  annotations:
    iam.gke.io/gcp-service-account: argo-events@proj-dev.iam.gserviceaccount.com
```
