### DISCUSSION TITLE
How to trigger a different template depending on a message value?

### DISCUSSION THREAD

**Discussion by ghost** [argoproj/argo-events#1141] [Q&A]
Hello!

I have two WorkflowTemplates (T1, T2) which are supposed to be triggered by a PubSub message. So far - that works. But now I want to trigger T1 xor T2 depending on a value sent with the message. For some reason I just don't get this to work. Here's my EventSource and the Sensor:

```yaml
    apiVersion: argoproj.io/v1alpha1
    kind: EventSource
    metadata:
      name: pubsub-event-source-nyc
    spec:
      template:
        serviceAccountName: argo-events
      pubSub:
        examplex:
          jsonBody: true
          topic: argo-events-nyc
          subscriptionID: argo-events-nyc-sub
    
    ---
    
    apiVersion: argoproj.io/v1alpha1
    kind: Sensor
    metadata:
      name: pubsub-sensor-nyc
    spec:
      template:
        serviceAccountName: argo-events-sa
      dependencies:
        - name: pubsub-event-source-dep-a
          eventSourceName: pubsub-event-source-nyc
          eventName: examplex
          filters:
            data:
              - path: body.test
                type: string
                value:
                  - "a"
        - name: pubsub-event-source-dep-b
          eventSourceName: pubsub-event-source-nyc
          eventName: examplex
          filters:
            data:
              - path: body.test
                type: string
                value:
                  - "b"
      triggers:
        - template: #T1
            conditions: "pubsub-event-source-dep-a"
            name: argo-workflow-trigger-wnf59w3zv
            argoWorkflow:
              group: argoproj.io
              version: v1alpha1
              resource: workflows
              operation: submit
              source:
                resource:
                  apiVersion: argoproj.io/v1alpha1
                  kind: Workflow
                  metadata:
                    generateName: nyc-test-template-a-
                    namespace: argo
                  spec:
                    workflowTemplateRef:
                      name: nyc-test-template
        - template: #T2
            conditions: "pubsub-event-source-dep-b"
            name: argo-workflow-trigger-gtdz4ef
            argoWorkflow:
              group: argoproj.io
              version: v1alpha1
              resource: workflows
              operation: submit
              source:
                resource:
                  apiVersion: argoproj.io/v1alpha1
                  kind: Workflow
                  metadata:
                    generateName: nyc-test-template-b-
                    namespace: argo
                  spec:
                    workflowTemplateRef:
                      name: nyc-test-template
```

If body.test = "a" the first trigger (T1) should be activated, if body.test = "b" the second (T2).

Now, what happens is this:

- If I send `{"test":"a"}` - only T1 gets triggered - good
- If I send `{"test":"b"}` - nothing gets triggered - bad :/

Any ideas?

Thanks in advance

Raffael

**Comment by whynowy** [comment]
I believe you already got the solution to it in the other discussion.

In terms of multiple dependencies referencing same eventSourceName + eventName, it's actually not allowed in One sensor object, see https://github.com/argoproj/argo-events/blob/master/docs/more-about-sensors-and-triggers.md#duplicate-dependencies for detail. If you are running the latest version of Argo Events, you will see the error message in the Sensor status, the sensor POD will not be created.

**Reply by joyofdata** [reply]
Hey @whynowy,

> I believe you already got the solution to it in the other discussion.

Yes and no. Yes, as both questions revolve around the same problem. No, because it's still a different approach and I'd love to see how that would work.

> Due to technical reasons, same eventSourceName and eventName combo can not be referenced twice in one Sensor object. 

That's weird. I thought this is exactly the purpose of those filters. 

My approach seems to me like a logical combination of:

- https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/tutorials/06-trigger-conditions/sensor-01.yaml
- https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/tutorials/07-filters/sensor-data-filters.yaml

First shows usage of conditions based on "dependencies", the second show how filters are used in dependencies.

I don't get it :D

**Comment by karthik-desynova** [comment]
i guess  you can create a main template put conditional logic there based json value run diiferent reference template
```
  templates:
    - name: main                
      steps:
      - - name: t1
          templateRef:
            name: t1-reference
            template: main
          arguments:
            parameters:
              - name: id
                value: "{{`{{workflow.parameters.key}}`}}"
          when: ( "{{`{{workflow.parameters.id}}`}}" == "a" 

        - - name: t2
          templateRef:
            name: t2-reference
            template: main
          arguments:
            parameters:
              - name: id
                value: "{{`{{workflow.parameters.key}}`}}"
          when: ( "{{`{{workflow.parameters.id}}`}}" == "b" 


```
