### DISCUSSION TITLE
File EventSource pathRegexp for new Directory

### DISCUSSION THREAD

**Discussion by louiscpalma** [argoproj/argo-events#1178] [Q&A]
Trying to get a `file` EventSource to trigger on new directories in a local path.

## Directory Structure

I am mounting my PVC to the eventsource pod which contains a subtree similar to:
```
data
└── incoming
    └── 2021
        ├── 2021_04_06_03_26_47
        │   ├── dir1
        │   │   └── file3.txt
        │   ├── file1.txt
        │   └── file2.txt
        └── 2021_04_09_03_43_19
```
Would like to trigger ONE event for `/data/incoming/2021/2021_04_06_03_26_47` ... maybe this is not the intent of the `file` eventSource? 

## eventsource.yaml
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: dir-bundler
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /data/incoming
          name: incoming
    volumes:
      - name: incoming
        persistentVolumeClaim:
          claimName: data-incoming
  file:
    incoming-2021:
      polling: true
      watchPathConfig:
        directory: /data/incoming/2021
        pathRegexp: "2021_*"
      eventType: create
```

## sensor.yaml
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: dir-bundler
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: new-incoming
      eventSourceName: dir-bundler
      eventName: incoming-2021
  triggers:
    - template:
        name: file-workflow-trigger
        conditions: "new-incoming"
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            git:
              url: "git@my_repo.git"
              sshKeySecret:
                name: git-creds
                key: id_rsa
              filePath: workflows/process-incoming.yaml
              branch: "master"
          parameters:
            - src:
                dependencyName: new-incoming
                dataKey: name
              dest: spec.templates.0.inputs.parameters.0.value
```
