### DISCUSSION TITLE
Trigger Resource Parameterization (k8s resource) - Is this good behaviour?

### DISCUSSION THREAD

**Discussion by ChaosInTheCRD** [argoproj/argo-events#1205] [Ideas]
We have a use case in the project I am working on, where we trigger a workflow from a sensor, from a k8s resource `CREATE` dependency. The k8s resource in question is a CRD. 

for example's sake we can call it `kind: Song`, with the following manifest picked up by the eventSource:

```
apiVersion: chaosinthecrd/v1alpha1
kind: Song
metadata:
    name: midnight-in-peckham
spec:
    genre:
       name: electronic
    rating: 7
```

In the sensor itself, if I set a parameter in a template trigger as follows:
```
arguments:
   parameters:
   - name: genre
     value: "no-genre"
```

and then a parameter for that trigger, outside the template:
```
parameters:
  - src:
      dependencyName: song-CREATED
      dataKey: body.spec.genre.name
    dest: spec.arguments.parameters.0.value
```

Everything will work as expected. *However* - In the event that I was to create another resource of type `Song`, for example:
```
apiVersion: chaosinthecrd/v1alpha1
kind: Song
metadata:
    name: "emotional-intelligence"
spec:
    rating: 9
```
In this instance the field `spec.genre.name` is not populated. For me, the expected behaviour was for the template parameter to stay as the value configured by default in the sensor (i.e. `no-genre`) - However, it instead passes through the whole json body to the workflow, something like below:

```
Parameters
genre = {"apiVersion": "chaosinthecrd/v1alpha1","kind": "Song","metadata": {"name": "emotional-intelligence"},"spec": {"rating": 9}}
```

This is a little unhelpful in our case, as in the event that the field hasn't been populated (it's optional in the CRD), we want the sensor to back off to some default value. 

Is this possible? But moreover, if it isn't; how so? A feature like this would be very helpful 😊

I was looking at [this line in the Go code](https://github.com/argoproj/argo-events/blob/master/sensors/triggers/params.go#L170) - Is that where it is set?

Hopefully this all made sense. And thanks for building such a great tool!
