### DISCUSSION TITLE
Using K8S secret in http trigger

### DISCUSSION THREAD

**Discussion by oren-codefresh** [argoproj/argo-events#1225] [Q&A]
Hello,
I wonder whether there is a way to use K8S secret as a parameter of HTTP trigger in event source
In the example below I would like to set the X-Access-Token as the value retrieved from K8S secret
Thanks,
Oren.

**example** : 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:

  dependencies:
    - name: desired
      eventSourceName: git-source-1
      eventName: desired

  triggers:
    - template:
        conditions: desired
        name: http-trigger
        http:
          url: local.server.io
          payload:
            - src:
                dependencyName: desired
                dataKey: body
              dest: payload
          method: POST
          headers:
            Content-Type: application/json
            X-Access-Token: <K8S secret reference>
      retryStrategy:
        steps: 3
        duration: 3s
```
