### DISCUSSION TITLE
SQS Encoded message

### DISCUSSION THREAD

**Discussion by jowparks** [argoproj/argo-events#1243] [Q&A] [answered]
I have SQS Source/sensor hooked up and running for an S3 bucket that is generating create events to the SQS queue. The yamls I have for sensor and source are such:

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: aws-sqs-research-ingestor
spec:
  template:
    serviceAccountName: argo-events-sa
  sqs:
    research-ingestor:
      # jsonBody specifies that all event body payload coming from this
      # source will be JSON
      jsonBody: true
      # aws region
      region: us-east-1
      # name of the queue. The eventsource resolves the url of the queue from the queue name.
      queue: research-ingestor-dev
      # The duration (in seconds) for which the call waits for a message to arrive in the queue before returning.
      # MUST BE > 0 AND <= 20
      waitTimeSeconds: 20
```

Sensor:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: research-ingestor
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: aws-sqs-research-ingestor
      eventName: research-ingestor
  triggers:
    - template:
        name: research-ingestor-workflow
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: research-ingestor-workflow-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # this is the value that should be overridden
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.arguments.parameters.0.value
```

The output I am getting from the container has base64 encoded info in the container output:
<img width="556" alt="Screen Shot 2021-06-08 at 11 07 31 AM" src="https://user-images.githubusercontent.com/26990067/121235451-c3518700-c849-11eb-849d-c32a0a4fd6a8.png">

```

{"context":{"id":"31356533336162392d616566622d343661392d393166622d326334333263393533633436","source":"aws-sqs-research-ingestor","specversion":"1.0","type":"sqs","datacontenttype":"application/json","subject":"research-ingestor","time":"2021-06-08T16:38:18Z"},"data":"eyJtZXNzYWdlSWQiOiJhODliZWQ5Yy05N2VhLTRlNTItODE3Yi1mYWVkMDBlYWJmYzgiLCJtZXNzYWdlQXR0cmlidXRlcyI6bnVsbCwiYm9keSI6eyJSZWNvcmRzIjpbeyJldmVudFZlcnNpb24iOiIyLjEiLCJldmVudFNvdXJjZSI6ImF3czpzMyIsImF3c1JlZ2lvbiI6InVzLWVhc3QtMSIsImV2ZW50VGltZSI6IjIwMjEtMDYtMDhUMTY6MzU6MzIuMTUwWiIsImV2ZW50TmFtZSI6Ik9iamVjdENyZWF0ZWQ6UHV0IiwidXNlcklkZW50aXR5Ijp7InByaW5jaXBhbElkIjoiQVdTOkFST0FTSzY2TkI1SlZFU0k2QjVVWjpqb2UucGFya3NAaW52aXRhZS5jb20ifSwicmVxdWVzdFBhcmFtZXRlcnMiOnsic291cmNlSVBBZGRyZXNzIjoiNzEuMTkzLjE5NS4zMiJ9LCJyZXNwb25zZUVsZW1lbnRzIjp7IngtYW16LXJlcXVlc3QtaWQiOiI5SE5LQjdOOUFWN0pHV05KIiwieC1hbXotaWQtMiI6Ikl0THJscXBBY2JLdG1veFBaVDBERSt5cHhFQ1ZuUi9XOWxyR3lkNmd6cXdlVDJCT0NhZWhzWWZZbFlzUXZxODErZElOa0V6UFNJRy80RHNMaG1MbFZVQnFzOXFVOTJQTCJ9LCJzMyI6eyJzM1NjaGVtYVZlcnNpb24iOiIxLjAiLCJjb25maWd1cmF0aW9uSWQiOiJzMy11cGxvYWQtZXZlbnQiLCJidWNrZXQiOnsibmFtZSI6InJlc2VhcmNoLWluZ2VzdG9yLWRldiIsIm93bmVySWRlbnRpdHkiOnsicHJpbmNpcGFsSWQiOiJBMlRPN0ZOQVdCSTI4RSJ9LCJhcm4iOiJhcm46YXdzOnMzOjo6cmVzZWFyY2gtaW5nZXN0b3ItZGV2In0sIm9iamVjdCI6eyJrZXkiOiJzbW9sX2dub21hZF91cGxvYWQuY3N2Iiwic2l6ZSI6MjU4NzU1LCJlVGFnIjoiOWQ1YmUxMGQzZjkxZTRkMGFmYjM2MDEwMTZiOGFlOWMiLCJzZXF1ZW5jZXIiOiIwMDYwQkY5QzVDMjU1NTg2ODUifX19XX19"}
```

The `data` field is base64 encoded, is this expected? I added `jsonBody: true` to my event source and expected it to fix the encoding.

**Comment by whynowy** [comment, marked as answer]
`dataKey` needs to be specified in parameters, see an [example](https://github.com/argoproj/argo-events/blob/master/examples/sensors/data-filter-comparator-webhook.yaml#L52).

**Comment by jowparks** [comment]
That worked! Thanks @whynowy 

My fix was changing my workflow parameters like so:
```
 parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.message.data
              dest: spec.arguments.parameters.0.value
```
