### DISCUSSION TITLE
How to appoint instance id in a argo workflow trigger?

### DISCUSSION THREAD

**Discussion by scape7yu** [argoproj/argo-events#1266] [Q&A] [answered]
A sensor submit a workflow but the workflow keep pending, I submit the workflow through Argo Cli: argo submit xxx.yaml -n xxx, the workflow started and completed well.
The different between sensor submit and cli submit is that I appoint instance id "export ARGO_INSTANCEID=my-ci-controller" in the client, so, I think if I can appoint instance id in the sensor's yaml, the triggered workflow by sensor will work well.

Please help me.

**Comment by whynowy** [comment, marked as answer]
You can use a `k8s` trigger which talks to k8s API server to create objects, and put the instance-id in the annotation directly. 

https://github.com/argoproj/argo-events/blob/master/examples/sensors/mqtt-sensor.yaml#L15-L19

**Reply by scape7yu** [reply]
I create workflow through argoWorkflow, like this:
  triggers:
    - template:
        name: webhook-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit

but I didn't find any references in the doc to appoint the instance id in my yaml file.

**Reply by whynowy** [reply]
Instance ID is actually stored in workflow annotations.

Follow the example I gave, use `k8s` instead of `argoWorkflow` (and `create` instead of `submit` in `operation`), give the annotation in the workflow metadata.

In case you don't know what the annotation looks like, explore your existing workflow spec which you created manually.

**Reply by scape7yu** [reply]
Thank you very much, I got it.

**Reply by scape7yu** [reply]
It seem like that the annotation didn't work, the workflow keep pending.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
                annotations:
                  instanceID: my-ci-controller
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # the value will get overridden by event payload from test-dep
                    value: hello world
                templates:
                - name: whalesay
                  serviceAccountName: argo-events-sa
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.arguments.parameters.0.value

```

**Reply by scape7yu** [reply]
God, finally I find the instance id is not stored in annotations, it's stored in labels.

My problem is solved, thanks very much.

Here is the way to appoint instance id in workflow yaml:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: webhook-
  labels:
    workflows.argoproj.io/controller-instanceid: my-ci-controller
```
