### DISCUSSION TITLE
How to set Kubernetes resources on event source pods

### DISCUSSION THREAD

**Discussion by wsams** [argoproj/argo-events#1291] [Q&A]
Hi, I've configured a [GitHub `EventSource`](https://github.com/argoproj/argo-events/blob/master/api/event-source.md#githubeventsource), but the pods that are created lack Kubernetes resources. My namespace has a quota, so I'm wondering if it's possible to define resources without using something like a `LimitRange`?

Thanks,
Weldon

**Comment by whynowy** [comment]
`spec.template.container.resources`

**Reply by wsams** [reply]
Hi @whynowy , I'm not sure where this goes because all I'm defining is,

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - port: 12001
        targetPort: 12001
  github:
    maven:
      repositories:
        - owner: my-org
          names:
            - my-repo
      githubBaseURL: https://github.enterprise/api/v3/
      webhook:
        endpoint: /github-maven
        port: 12001
        method: POST
        url: https://example.com/github
        serverCertSecret:
          name: argo-eventsource-certs-2021-07-29
          key: cert-key
        serverKeySecret:
          name: argo-eventsource-certs-2021-07-29
          key: private-key
      events:
      - "push"
      webhookSecret:
        name: github-2021-07-29
        key: webhook-secret
      insecure: false
      active: true
      contentType: json
```

which results in a Pod being created. I'm not sure where the pod template is to define the container resources.

**Reply by wsams** [reply]
Likewise I'm deploying a `Sensor` like the following which creates Pods without resources.
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-maven-feature-branch
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: github-webhook-sensor
      eventSourceName: github
      eventName: maven
      filters:
        data:
          - path: body.ref
            type: string
            value:
              - "^refs/heads/feature/.+$"
          - path: body.after
            type: string
            value:
              - "^0+$"
            comparator: "!="

  triggers:
    - template:
        name: github-feature-branch-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              # ...
```

**Reply by wsams** [reply]
I believe the eventsource-controller and sensor-controller are creating a respective deployment which would create the pods I'm talking about. I just can't figure out where to define the resources because there aren't any containers I can configure. And I'm not seeing anything in the EventSource or Sensor field references that indicate I can define resources.

**Reply by whynowy** [reply]
In your event source spec:

```
spec:
  template:
    container:
      resources:
        xxxx
```
