### DISCUSSION TITLE
EventSource service type LoadBalancer

### DISCUSSION THREAD

**Discussion by bygui86** [argoproj/argo-events#1300] [Q&A]
Hi guys,

is it possible to define the default Service created by an EventSource as type `LoadBalancer`?

Example of EventSource:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitlab-example
spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: argo-events
        domain: ci
        component: event-source

  service:
    ports:
      - name: webhook
        port: 80
        targetPort: 12000

  gitlab:
    gitlab-go-event:
      projectID: xxx
      webhook:
        endpoint: /push/
        port: "12000"
        method: POST
        url: http://xxx.xxx.xxx.xxx
      events:
        - PushEvents
        - TagPushEvents
      accessToken:
        name: gitlab-ci-token
        key: token
      enableSSLVerification: false
      gitlabBaseURL: https://gitlab.com
```

Something like
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitlab-go-test
spec:
  ...

  service:
    type: LoadBalancer
    ports:
      - name: webhook
        port: 80
        targetPort: 12000

  gitlab:
    ...
```

I tried the example above but it does not affect the created Service.

Thanks a lot in advance for any help!!
