### DISCUSSION TITLE
Data filter list

### DISCUSSION THREAD

**Discussion by jp-gouin** [argoproj/argo-events#1400] [Q&A] [answered]
Hello,

Is it possible to fetch the first items of a list and data inside this list using filters data ?

I have this event input : 
```
{
	"type": "PUSH_ARTIFACT",
	"occur_at": 1586922308,
	"operator": "admin",
	"event_data": {
		"resources": [{
			"digest": "sha256:8a9e9863dbb6e10edb5adfe917c00da84e1700fa76e7ed02476aa6e6fb8ee0d8",
			"tag": "latest",
			"resource_url": "hub.harbor.com/test-webhook/debian:latest"
		}],
		"repository": {
			"date_created": 1586922308,
			"name": "debian",
			"namespace": "test-webhook",
			"repo_full_name": "test-webhook/debian",
			"repo_type": "private"
		}
	}
}
```

And i want to select the  `resource_url` in `body` 
I tried with `body.event_data.resources.0.resource_url` but no luck with that.

Plus i want to apply this regex on the result `(^((?!sig|metadata).)*$)` 

```
filters:
  data:
    - path: "body.event_data.resources.0.resource_url"
       type: string
       value:
          - "^((?!.sig|metadata).)*$"
```
is this possible ?
