### DISCUSSION TITLE
How to use Kustomize with the Sensor CRD

### DISCUSSION THREAD

**Discussion by putnam120** [argoproj/argo-events#1430] [Q&A]
I have created a Sensor that will cause an Argo Workflow to be run once a POST request is sent to my desired endpoint.  The workflow has two steps that run different containers say `step-1-container:tag1` and `step-2-container:tag2`. I would like to be able to use Kustomize to update these tags by specifying them in the `images:` field. I have not been able to accomplish this and was wondering if anyone could provide some guidance. Below is that I have:

Contents of `kustomconfig.yaml`
```
images:
  - path: spec/triggers[]/template/k8s/source/resource/spec/templates[]/container/image
    kind: Sensor
```

Contents of `kustomization.yaml`
```
...

configurations:
  - kustomconfig.yaml
 
images:
  - name: step-1-container
    newTag: tag1.1
  - name: step-2-container
    newTag: tag2v8

...
```

When I use the above and run `kubectl apply -k myDir/overlays/dev` I am still seeing that the specified containers are still using the old tags and not the ones specified in the `kustomization.yaml` file.
