### DISCUSSION TITLE
How to add path parameter and query parameter for HTTP Trigger of Sensor ?

### DISCUSSION THREAD

**Discussion by anencore94** [argoproj/argo-events#1460] [Q&A]
Threre are examples for how to add payload for HTTP trigger such as:
```yaml
    - template:
        name: report-trigger
        http:
          url: http://172.25.0.36:8080/reports/run
          payload:
            - src:
                dependencyName: test-dep
                dataKey: body.metadata.labels.pipeline/runid
              dest: kfp_run_id
          method: POST
          headers:
            accept: application/json
            Content-Type: application/json
      retryStrategy:
        steps: 3
        duration: 3s
```

However I'd like to request an HTTP such as 
```sh
curl -X 'PUT' \
  'http://172.25.0.36:8080/pipeline-ci-trials/8cbce8e7-a9e9-436f-952a-b4b26ddb9c96?status=SUCCEED' \
  -H 'accept: application/json'
```

where `8cbce8e7-a9e9-436f-952a-b4b26ddb9c96` and `SUCCEED` is a dynamic value from an event data.

There is a `parameters` field in https://github.com/argoproj/argo-events/blob/master/pkg/apis/sensor/v1alpha1/types.go#L410-L439, but I have no idea, how to use `Parameters`

Any Guide would be helpful. Thanks in advance :)
