### DISCUSSION TITLE
Why Argo event is always in state Pending?

### DISCUSSION THREAD

**Discussion by PavelDemyanenko** [argoproj/argo-events#1478] [Q&A] [answered]
Hi all, I've followed example here https://argoproj.github.io/argo-events/sensors/triggers/argo-workflow/ in minikube and after curl post i just get events in state pending with argo list -n argo-events. Could someone please point me what might be the problem about it?
https://i.stack.imgur.com/PRE1W.png

```
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argo-events
  name: operate-workflow-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operate-workflow-role
  namespace: argo-events
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - "*"
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operate-workflow-role-binding
  namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operate-workflow-role
subjects:
  - kind: ServiceAccount
    name: operate-workflow-sa
    namespace: argo-events
```

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  namespace: argo-events
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: message
                      # the value will get overridden by event payload from test-dep
                      value: hello world
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: `spec.arguments.parameters.0.value`
```

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    example:
      endpoint: /example
      method: POST
      port: "12000"
      url: ""
```

```
➜  ~ argo list -n argo-events
NAME            STATUS    AGE   DURATION   PRIORITY
webhook-5l7k6   Pending   14m   0s         0
webhook-445fl   Pending   19m   0s         0
webhook-xcqt8   Pending   2h    0s         0
```
