### DISCUSSION TITLE
way to trigger a workflow using webhook json payload

### DISCUSSION THREAD

**Discussion by karthik-desynova** [argoproj/argo-events#1505] [Q&A]
same as  #1141
im looking for a way to trigger a workflow using webhook json payload key for example if payload is {"action":"copy","id":"someid"}
on triggers
```
triggers:
    template:
    - "group1"
      "use this template if action key is 'copy'"
    - "group2"
      "use this template" if action key is 'move'"
```

i have created a example sensor file but, argo sersor is complaining that eventSourceName used multiple times.

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: testing-sensor
spec:
  template:
    serviceAccountName: argo 
  dependencies:
    - name: data
      eventSourceName: testhook
      eventName: test
      filters:
        data:
          - path: body.message
            type: string
            value:
              - copy
    
    - name: data1
      eventSourceName: testhook
      eventName: test
      filters:
        data:
          - path: body.message
            type: string
            value:
              - move
  triggers:
    - template:
        conditions: "data"
        name: group-1
        
    - template:
        conditions: "data1"
        name: group-2
```
