### DISCUSSION TITLE
Failed: invalid spec: templates.main.steps[0].myfork templates.myfork inputs.parameters.message was not supplied

### DISCUSSION THREAD

**Discussion by tooptoop4** [argoproj/argo-events#1537] [Q&A]
getting error in the title

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sqs
spec:
  template:
    serviceAccountName: argo-workflows-server
  dependencies:
    - name: test-dep
      eventSourceName: aws-sqs
      eventName: example-without-credentials
  triggers:
    - template:
        name: sqs-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: aws-sqs-workflow-
              spec:
                serviceAccountName: argo-workflows-server
                entrypoint: main
                arguments:
                  parameters:
                  - name: message
                    # tis is the value that should be overridden
                    value: hello world
                volumes:
                - name: aws-iam-token
                  projected:
                    defaultMode: 420
                    sources:
                    - serviceAccountToken:
                        audience: sts.amazonaws.com
                        expirationSeconds: 86400
                        path: token
                templates:
                  - name: main
                    steps:
                      - - name: myfork
                          template: myfork
                      - - name: aaa
                          template: aaa
                          when: "{{steps.myfork.outputs.parameters.targetparam}} == aaa"
                        - name: rrr
                          template: rrr
                          when: "{{steps.myfork.outputs.parameters.targetparam}} == rrr"
                    outputs:
                      parameters:
                        - name: stepresult
                          valueFrom:
                            expression: "steps['myfork'].outputs.parameters.targetparam == 'aaa' ? steps.aaa.outputs.result : steps.rrr.outputs.result"
              
                  - name: myfork
                    inputs:
                      parameters:
                      - name: message
                    container:
                      image: busybox:latest
                      env:
                        - name: AWS_ROLE_ARN
                          value: "arn:aws:iam::redact"
                        - name: AWS_WEB_IDENTITY_TOKEN_FILE
                          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
                      volumeMounts:
                      - name: aws-iam-token
                        mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
                      command: [ bash, -c ]
                      args: ["export msg='{{inputs.parameters.message}}';function urldecode() { : \"${*//+/ }\"; echo -e \"${_//%/\\\\x}\"; };buc=`echo \"$msg\" | /usr/bin/jq '.Message' -r | jq '.Records[0].s3.bucket.name' | tr -d '\"'`;key=`echo \"$msg\" | /usr/bin/jq '.Message' -r | jq '.Records[0].s3.object.key' | tr -d '\"'`;key=$(urldecode \"$key\" | tr -d '\"'); if [[ \"$key\" == *\"blaha\"* ]]; then   echo aaa > /tmp/target.txt;else echo rrr > /tmp/target.txt; fi; echo $key > /tmp/s3key.txt; echo \"$msg\" > /tmp/msg.txt"]
                    outputs:
                      parameters:
                      - name: s3keyparam
                        valueFrom:
                          path: /tmp/s3key.txt
                      - name: fullmsgparam
                        valueFrom:
                          path: /tmp/msg.txt
                      - name: targetparam
                        valueFrom:
                          path: /tmp/target.txt
                  - name: aaa
                    script:
                      image: python:alpine3.6
                      env:
                        - name: AWS_ROLE_ARN
                          value: "arn:aws:iam::redact"
                        - name: AWS_WEB_IDENTITY_TOKEN_FILE
                          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
                      volumeMounts:
                      - name: aws-iam-token
                        mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
                      command: [ python ]
                      source: |
                        print("aaa")
              
                  - name: rrr
                    script:
                      image: python:alpine3.6
                      env:
                        - name: AWS_ROLE_ARN
                          value: "arn:aws:iam::redact"
                        - name: AWS_WEB_IDENTITY_TOKEN_FILE
                          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
                      volumeMounts:
                      - name: aws-iam-token
                        mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
                      command: [ python ]
                      source: |
                        print("rrr")
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
```
