### DISCUSSION TITLE
Multiple workflows triggered on a single event

### DISCUSSION THREAD

**Discussion by chandanpjain** [argoproj/argo-events#1566] [Q&A]
We have configured an eventsource to watch on changes to an argo application and trigger argo workflow based on this event. Everytime this event is triggered, we are observing 4 workflows starting in parallel (a few seconds apart). Eventhough this is not creating any issue with the result we want, this is creating unnecessary noise. Could we get some help to understand what could be wrong in the follow filter we are using?

![image](https://user-images.githubusercontent.com/11813513/151242584-16dd42a8-1d0b-427f-8b56-116a368da09a.png)

```
spec:
  template:
    serviceAccountName: {{ .Values.serviceaccountname }}
  resource:
    {{ .Values.eventsource.eventname }}:
      group: argoproj.io
      version: v1alpha1
      resource: applications
      eventTypes:
        - UPDATE
      filter:
        afterStart: true
        fields:
          - key: status.sync.status
            operation: ==
            value: OutOfSync
          - key: status.operationState.phase
            operation: ==
            value: Failed
        labels:
          - key: app
            operation: ==
            value: foo
```
