### DISCUSSION TITLE
Retry for HTTP Trigger on unexpected or specific HTTP status codes

### DISCUSSION THREAD

**Discussion by richardfuchs** [argoproj/argo-events#1688] [Q&A]
With the Argo-Events Sensor 'HTTP Trigger' ([Docs][1]) it is possible to setup a 'retryStrategy' if e.g. the called service is not reachable or the connection is dropped:

```
  retryStrategy:
    steps: 3
    duration: 3s
```

It is also possible to add a 'policy' for allowed HTTP response status codes:
```
  policy:
    status:
      allow:
        - 200
        - 201
```

If the HTTP request returns an status-code that is not in the 'allow'-list an error is logged - but no retry is made.

Is it possible to configure a retry if the HTTP request returns a status-code that is not in the allow list and/or is it possible to configure a retry for specific status-codes?

  [1]: https://argoproj.github.io/argo-events/sensors/triggers/http-trigger/

**Comment by gmurray-8372** [comment]
I know this is a pretty old message, but I found this thread investigating the exact same problem.  I found the key is that you ***must*** set `atLeastOnce` to "true".

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-http-endpoint-always-fail-trigger
        http:
          url: <a URL>
          method: GET
          tls:
            insecureSkipVerify: true

      atLeastOnce: true # THIS VALUE MUST BE TRUE in order for the retryStrategy to actually do anything
      retryStrategy:
        steps: 5
        duration: 5s
        factor: 2.0
      policy:
        status:
          allow:
            - 200
            - 201
            - 204
```
