### DISCUSSION TITLE
Hook-Call if 'HTTP Trigger'-Sensor was not successful

### DISCUSSION THREAD

**Discussion by richardfuchs** [argoproj/argo-events#1690] [Q&A]
With the Argo-Events Sensor 'HTTP Trigger' ([Docs][1]) it is possible to setup a 'retryStrategy' and a 'policy':

```
  retryStrategy:
    steps: 3
    duration: 3s
  policy:
    status:
      allow:
        - 200
        - 201
```

If there is an error (e.g we reached the 'steps'-limit in 'retryStrategy' or the called service returns a status-code that is not in the 'allow'-list) – is it possible to invoke some hook? So that we can call some other service an tell it that the 'HTTP Trigger' was not successful?

  [1]: https://argoproj.github.io/argo-events/sensors/triggers/http-trigger/
