### DISCUSSION TITLE
Redis Parameterization JSON

### DISCUSSION THREAD

**Discussion by jrowinski3d** [argoproj/argo-events#1751] [General]
Hi,

I just wanted to see if anyone is using **Redis** as an EventSource and using complex string types to pass data to the argo-events sensor. I've been testing with the **cowsay** container to just extract a certain portion of my event.

I am sending the follow to a pub/sub: 

```
PUBLISH FOO '{"message": "hello", "message2": "bye"}'
```

I want to be able to only extract **message** into the container, but for some reason, I am getting the entire payload.

```
 _________________________________________
/ {"channel":"FOO","pattern":"","body":"{ \
| \"message\": \"hello\", \"message2\":       |
\ \"bye\"}"}                              /
 -----------------------------------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/

```

This is my current implementation:

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: redis
spec:
  redis:
    example:
      # HostAddress refers to the address of the Redis host/server
      hostAddress: redis.redis:6379
      namespace: argo
      password:
        name: redis
        key: redis-pass
        # Channels to subscribe to listen events.
      channels:
        - FOO

---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: redis
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: redis
      eventName: example
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: redis-
                namespace: argo
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          # https://argoproj.github.io/argo-events/tutorials/02-parameterization/#webhook-event-payload
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: THIS_WILL_BE_REPLACED
              dest: spec.arguments.parameters.0.value
        parameters:
          - src:
              dependencyName: test-dep
              dataKey: body.message
            dest: k8s.parameters.0.src.dataKey
```

If anyone has any ideas would be appreciated, or if I'm out to lunch on whether this is even possible with **redis**
