### DISCUSSION TITLE
argoWorflow creates duplicate name

### DISCUSSION THREAD

**Discussion by phspies** [argoproj/argo-events#1768] [Q&A]
I have a githib webhook configured which triggers a workflowtemplate. All this works but the name the sensor assign to the new workflow is static and doesn't allow for any subsequent workflows to be created from the same sensor until I delete the current workflow.

What is the process to randomize the name of the workflow being created?

    
```
     argoWorkflow:
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                labels:
                  workflows.argoproj.io/archive-strategy: always
                **name: prinubes-github-push**
              spec:
                workflowTemplateRef:
                  name: prinubes-build-push-template
          operation: create
```
