### DISCUSSION TITLE
Argo Event triggered on Argo Rollout promotion

### DISCUSSION THREAD

**Discussion by jay-jinjuwadia** [argoproj/argo-events#1830] [Q&A] [answered]
Hello All,

I want to trigger an HTTP request whenever there is a successful Argo Rollout promotion. Currently, I have the resource event source triggering every time the Rollout resource is updated, but this results in multiple events being sent instead of just one because creating pods, terminating pods, etc. all trigger the UPDATE event for Rollouts. Is there a way I can have Argo Events only send one event when the rollout is completed? I have attached the manifests I'm using below.

**Rollout**
```apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-step-completed.slack: deployments 
    notifications.argoproj.io/subscribe.on-rollout-aborted.slack: deployments
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: deployments  
    notifications.argoproj.io/subscribe.on-rollout-updated.slack: deployments  
    notifications.argoproj.io/subscribe.on-rollout-paused.slack: deployments  
spec:
  selector:
    matchLabels:
      app: my-app
  revisionHistoryLimit: 10
  template:
    spec:
      containers:
        - name: my-app
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
            requests:
              cpu: 25m
              memory: 128Mi
  strategy:
    blueGreen: 
      activeService: my-app
      previewService: my-app-preview
      autoPromotionEnabled: false
      previewReplicaCount: 2 
```

**Event Source**
```apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: my-event-source
  namespace: default
  labels:
    app: my-app
  finalizers:
    - eventsource-controller
spec:
  eventBusName: default
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    serviceAccountName: argo-events-sa
  resource:
    event-source:
      namespace: default
      filter:
        labels:
          - key: app
            operation: ==
            value: my-app
        fields:
          - key: status.phase
            operations: ==
            value: Healthy
        afterStart: true
      group: argoproj.io
      version: v1alpha1
      resource: rollouts
      eventTypes:
        - UPDATE
```

**Sensor**
```apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: my-sensor
  namespace: default
  labels:
    app: my-app
  annotations:
    sidecar.istio.io/inject: 'false'
  finalizers:
    - sensor-controller
spec:
  dependencies:
    - name: new-deployment
      eventSourceName: my-event-source
      eventName: event-source
  triggers:
    - template:
        name: my-app
        http:
          url: https://example.com
          method: GET
          headers:
            Content-Type: application/json
      policy:
        status:
          allow:
            - 200
            - 201 
  template:
    container:
      env:
        - name: DEBUG_LOG
          value: "true"
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    serviceAccountName: argo-events-sa
```

**Comment by erez-levi** [comment]
were you able to figure this out?

**Reply by jay-jinjuwadia** [reply, marked as answer]
Yeah, I put the filter logic in the Sensor instead of the event source, and filtered the events based on if the rollout resource was updated and if the service pointed to a new replica set (indicating that the rollout switched traffic).

Sensor:

```
kind: Sensor
metadata:
  name: my-sensor
  namespace: default
  labels:
    app: my-app
  annotations:
    sidecar.istio.io/inject: 'false'
  finalizers:
    - sensor-controller
spec:
  dependencies:
    - eventName: event-source
      eventSourceName: my-app-rollout-event-source
      name: rollout
    - eventName: event-source
      eventSourceName: my-app-service-event-source
      filters:
        data:
          - path: body.metadata.name
            type: string
            value:
              - ^my-app-service$
  triggers:
    - template:
        name: my-app
        http:
          url: https://example.com
          method: GET
          headers:
            Content-Type: application/json
      policy:
        status:
          allow:
            - 200
            - 201 
  template:
    container:
      env:
        - name: DEBUG_LOG
          value: "true"
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    serviceAccountName: argo-events-sa
   ```
   Event Source:
   ```
kind: EventSource
metadata:
  name: my-app-rollout-event-source
  namespace: default
  labels:
    app: my-app
  finalizers:
    - eventsource-controller
spec:
  eventBusName: default
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    serviceAccountName: argo-events-sa
  resource:
    event-source:
      namespace: default
      filter:
        labels:
          - key: app
            operation: ==
            value: my-app
        afterStart: true
      group: argoproj.io
      version: v1alpha1
      resource: rollouts
      eventTypes:
        - UPDATE
---
kind: EventSource
metadata:
  name: my-app-service-event-source
  namespace: default
  labels:
    app: my-app
  finalizers:
    - eventsource-controller
spec:
  eventBusName: default
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    serviceAccountName: argo-events-sa
  resource:
    event-source:
      namespace: default
      filter:
        labels:
          - key: app
            operation: ==
            value: my-app
        afterStart: true
      group: ""
      version: v1
      resource: services
      eventTypes:
        - UPDATE
   ```
   Keep in mind, that this will also execute the sensor when you perform a rollback from ArgoCD since a traffic switch will occur, but it was fine for my use case.
