### DISCUSSION TITLE
argo workflow submit error - duplicated node name

### DISCUSSION THREAD

**Discussion by defyjoy** [argoproj/argo-events#1881] [General]
I am working on argo and trying to learn but I am not finding what is the issue in this code to cause the error below --
```

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: argocd-dotnet-kafka-subscriber
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: github
      eventSourceName: github
      eventName: github-app # argocd-dotnet-kafka-event
  triggers:
    - template:
        name: trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: argocd-dotnet-kafka-
                namespace: workflows
              spec:
                entrypoint: build
                serviceAccountName: workflow
                volumes:
                  - name: regcred
                    secret:
                      secretName: regcred
                      items:
                        - key: .dockerconfigjson
                          path: config.json
                  - name: github-access
                    secret:
                      secretName: github-access
                      items:
                        - key: token
                          path: token
                        - key: user
                          path: user
                        - key: email
                          path: email
                templates:
                  - name: build
                    dag:
                      tasks:
                        - name: build
                          templateRef:
                            name: container-image
                            template: build-kaniko-git
                            clusterScope: true
                          arguments:
                            parameters:
                              - name: repo_url
                                value: "https://github.com/Workquark/argocd-dotnet-kafka-subscriber-deploy"
                              - name: repo_ref
                                value: ""
                              - name: repo_commit_id
                                value: ""
                              - name: container_image
                                value: joydeep1985/argocd-dotnet-kafka-subscriber-deploy
                              - name: container_tag
                                value: "latest"
                  - name: test
                    script:
                      image: alpine
                      command: [sh]
                      source: |
                        echo This is a testing simulation...
                        sleep 5
                      volumeMounts:
                        - name: github-access
                          mountPath: /.github/
          parameters:
            - src:
                dependencyName: github
                dataKey: body.repository.git_url
              dest: spec.templates.0.dag.tasks.0.arguments.parameters.0.value
            - src:
                dependencyName: github
                dataKey: body.ref
              dest: spec.templates.0.dag.tasks.0.arguments.parameters.1.value
            - src:
                dependencyName: github
                dataKey: body.after
              dest: spec.templates.0.dag.tasks.0.arguments.parameters.2.value
            - src:
                dependencyName: github
                dataKey: body.repository.name
              dest: spec.templates.0.dag.tasks.0.arguments.parameters.3.value
              operation: append
            - src:
                dependencyName: github
                dataKey: body.after
              dest: spec.templates.0.dag.tasks.0.arguments.parameters.4.value
            - src:
                dependencyName: github
                dataKey: body.repository.name
              dest: spec.templates.0.dag.tasks.1.arguments.parameters.4.value
            - src:
                dependencyName: github
                dataKey: body.after
              dest: spec.templates.0.dag.tasks.1.arguments.parameters.5.value
            - src:
                dependencyName: github
                dataKey: body.repository.name
              dest: spec.templates.0.dag.tasks.2.arguments.parameters.4.value
            - src:
                dependencyName: github
                dataKey: body.after
              dest: spec.templates.0.dag.tasks.2.arguments.parameters.5.value

```
And the ClusterWorkflowTemplate for build - 

```
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: container-image
spec:
  serviceAccountName: workflow
  templates:
    - name: build-kaniko-git
      inputs:
        parameters:
          - name: repo_url
          - name: repo_ref
            value: refs/heads/master
          - name: repo_commit_id
            value: HEAD
          - name: container_image
          - name: container_tag
      container:
        image: gcr.io/kaniko-project/executor:debug
        command: [/kaniko/executor]
        args:
          - --context={{inputs.parameters.repo_url}}#{{inputs.parameters.repo_ref}}#{{inputs.parameters.repo_commit_id}}
          - --destination={{inputs.parameters.container_image}}:{{inputs.parameters.container_tag}}
        volumeMounts:
          - name: regcred
            mountPath: /kaniko/.docker/
```
But what I receive error on webhook trigger is this - 

```
time="2022-04-20T01:25:40.089Z" level=fatal msg="Failed to submit workflow:
templates.build sorting failed: duplicated nodeName "
{"level":"error","ts":1650417940.0938516,"logger":"argo-events.sensor","caller":"sensors/listener.go:355","msg":"failed to execute a trigger","sensorName":"argocd-dotnet-kafka-subscriber","error":"failed to execute trigger: timed out waiting for the condition: failed to execute submit command for workflow : exit status 1","errorVerbose":"timed out waiting for the condition: failed to execute submit command for workflow : exit status 1\nfailed to execute trigger\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerOne\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:408\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:353\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:1581","triggerName":"trigger","triggeredBy":["github"],"triggeredByEvents":["32623564393765662d343331612d346333342d613166352d346230613238613735353163"],"stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:355"}

```

What am I doing wrong here ?
