### DISCUSSION TITLE
Trigger with configMapKeyRef

### DISCUSSION THREAD

**Discussion by jomach** [argoproj/argo-events#1899] [Q&A]
Hey I have the following sensor on argo events: 

```
triggers:
    - template:
        name: kafka-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: dh-tr-2-
              spec:
                arguments:
                  parameters:
                  - name: message
                    # Value will be overwritten
                    value: DummyValue
                  - name: task_name
                    value: transformation
                  - name: pipeline_tenant_id
                    valueFrom:
                      configMapKeyRef:
                        name: datahub-datatype-to-pipeline-id-config
                        # Dummy. To be replaced via injection
                        key: dummy
                workflowTemplateRef:
                  name: datahub-pipelines-argo2
          parameters:
            - src:
                dependencyName: kafka-message
                dataKey: body
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: kafka-message
                dataTemplate: "{{ .Input.body.datasetId | nospace | lower }}-"
              dest: metadata.generateName
              operation: append
            - src:
                dependencyName: kafka-message
                dataTemplate: "{{ .Input.body.datasetType | nospace }}"
              dest: spec.arguments.parameters.2.valueFrom.configMapKeyRef.key

```
when the workflow tries to start I get : 
"
Failed: failed to set global parameters: failed to set global parameter pipeline_tenant_id from configmap with name pipelines-git-branch and key branch: ConfigMap 'pipelines-git-branch' does not exist
"
The configmap exists. If I pass this into the workflowTemplate it works. But I need it on the trigger... 
Any ideas ?
