### DISCUSSION TITLE
Argo-events triggering multiple workflows

### DISCUSSION THREAD

**Discussion by jsingh-1** [argoproj/argo-events#1926] [Q&A]
Hello,
I am using `resource` type eventsource for monitoring events not in argo-events namespace but in other namespace lets say `ABC`. And have created a sensor to trigger a workflow in `ABC` namespace.
But when the event is created, eventsource is triggering multiple workflows, which is more weird that only one of them gets success and rest all fails. But again main question is why its triggering multiple workflows in the first place.

On top of this, if I am doing the exact thing in `argo-events` namespace, everything works fine as expected.
Did anyone faced any kind of this issue? 

Here is my eventsource file:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: resource-abc
spec:
  template:
    serviceAccountName: event-source-sa # assign a service account with `get`, `list` and `watch` permissions on the resource being watched.
  resource:
    example:
      # namespace to listen events within
      namespace: abc
      # resource group
      group: ''
      # resource version
      version: v1
      # resource kind
      resource: pods
      # type of events
      # possible values are ADD, DELETE, UPDATE
      # Optional
      eventTypes:
        - ADD
      filter:
        afterStart: true
```
