### DISCUSSION TITLE
Filters in argo eventsource

### DISCUSSION THREAD

**Discussion by jsingh-1** [argoproj/argo-events#1964] [General]
Hello Everyone,

I am looking for suggestions, on how to add filter in eventsource.
My requirement here is, I have created a eventsource on k8s resource with event-type "ADD".
And on detect of event, it should trigger a workflow.

Problem I am facing is, whenever the pod is getting created even though its not up and running or in healthy state, event is detected by eventsource and it triggers the workflow.

How can I add a filter or label , to check that once the pod is running, then only event should be triggered.

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: filter-event-source
  namespace: argo-events
spec:
  template:
    serviceAccountName: event-source-sa 
  resource:
    example:
      namespace: argo-events
      # resource group
      group: ''
      # resource version
      version: v1
      # resource kind
      resource: pods
      eventTypes:
        - ADD
      filter:
        afterStart: true
        prefix: test
        fields:
          - key: metadata.name
            operation: ==
            value: "test*"

```
