### DISCUSSION TITLE
Resource Eventsource: trigger on all workflows except....

### DISCUSSION THREAD

**Discussion by mefuller** [argoproj/argo-events#2019] [Q&A] [answered]
EDIT: Simply, I want to trigger a workflow that creates a custom log for every workflow except the argo-events workflows.
Therefore, I want to either put a label on the argo-events-triggered workflow or use the egnerated name as a filter in the event-source to exclude these, to not emit an event.

Is this possible?

**Comment by mefuller** [comment, marked as answer]
I answered my own question:

This may be done with a field filter, e.g.:
```
      filter:
        # This indicates only watch the events happened after the service start time.
        afterStart: true
        # labels and filters are meant to provide K8s API options to filter the object list that are being watched.
        # Please read https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api for more details.
#        # fields provide listing options to K8s API to watch objects
        fields:
#            # It's an extention of https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/.
#            # Unlike k8s field selector, any arbitrary field like "spec.serviceAccountName" is supported.
          - key: metadata.generateName
#            # Supported operations like =, ==, !=.
#            # Defaults to ==.
#            # optional.
            operation: "!="
#            # Value could a string or a regex like "my*"
            value: "automated-workflow-"
```
