### DISCUSSION TITLE
Conditional parameters

### DISCUSSION THREAD

**Discussion by panakour** [argoproj/argo-events#2056] [General]
I have a Sensor like bellow. I want to pass value in a parameter via condition like the bellow: 
.
<img width="705" alt="image" src="https://user-images.githubusercontent.com/12927166/176411581-7794bb9f-6a84-4048-a64b-24e9fa34e873.png">
But its not working, the contains function is available in Sprig http://masterminds.github.io/sprig/strings.html

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github
      eventSourceName: github
      eventName: mouxtin
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: -trigger-
                namespace: argo
              spec:
                arguments:
                  parameters:
                    - name: repo_full_name
                      value: mouxtin/core
                    - name: branch
                      value: master
                    - name: should-test
                      value: true
                workflowTemplateRef:
                  name: git-src-templates
          parameters:
            - src:
                dependencyName: github
                dataKey: body.repository.name
              dest: metadata.generateName
              operation: prepend
            - src:
                dependencyName: github
                dataKey: body.repository.full_name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: github
                dataTemplate: "{{ .Input.body.repository.name | contains 'reponame' }}"
              dest: spec.arguments.parameters.2.value

```
