### DISCUSSION TITLE
Single Sensor of Multiple Eventsource

### DISCUSSION THREAD

**Discussion by sharadhirao** [argoproj/argo-events#2233] [Q&A]
Hi Team,
I was also looking for the solution.

I have multiple eventsources, when any one of them triggers, I should be able to run the workflows. I have made values dynamic, so single sensor is enough for me. It feels like it should be possible to have a Sensor with multiple triggers defined and when any one of the dependencies triggers sensor should run.

I am not able access this link: https://github.com/argoproj/argo-events/blob/master/examples/sensors/webhook-http-dependency-groups.yaml as suggested by issue https://github.com/argoproj/argo-events/issues/174

Can you suggest a solution on this? @alexec

**Comment by sharadhirao** [comment]
Hi team, any suggestion on this?

**Comment by whynowy** [comment]
Check this out.

https://github.com/argoproj/argo-events/blob/master/docs/sensors/trigger-conditions.md

**Reply by sharadhirao** [reply]
Thanks a lot for response.
 One question is that: I need to run all the steps in single template workflow even if any one of dependencies triggers. So instead of writing condition in template, Can it be possible that I have some "or" kind of statement in dependencies itself?

**Reply by sharadhirao** [reply]
I need to define two eventsource name in the same dependency.
To Support multiple dependencies using the same dependency name with multiple eventsource and eventname in sensor. I am looking into something like this:
```
spec:
  dependencies:
    - name: test-dep
       - eventSourceName: webhook1
         eventName: webhook1 
       - eventSourceName: webhook2
         eventName: webhook2
```

Why i am looking for this is, In first step I am cloning git repository. That repo url i am getting from the payload. If i have different dependency names then it will not be automatic.
```
          parameters:
          - src:
              dependencyName: test-dep
              dataKey: body.repository.html_url
            dest: spec.templates.0.dag.tasks.0.arguments.parameters.0.value
```

Like this I am using dynamic parameters. Can you please look into this and suggest a solution? @whynowy 

Thanks in advance
