### DISCUSSION TITLE
Azure Events Hub - confusion in documentation and feature doesn't work?

### DISCUSSION THREAD

**Discussion by ognjen-it** [argoproj/argo-events#2441] [Q&A] [answered]
Hi all,

in the documentation, we can see that Azure Events Hub is in the list of Available event-sources:
https://argoproj.github.io/argo-events/concepts/event_source/
However, if you check EventSources / Setup, there is no Azure Events Hub.
https://argoproj.github.io/argo-events/eventsources/setup/amqp/

I checked in the code and Azure Events Hub exists in EventSoruces:
https://github.com/argoproj/argo-events/tree/master/eventsources/sources/azureeventshub

And, does anyone check if Azure Events Hub works as EventSoruce? I couldn't set it, here setup:
```
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: azure-events-hub
  namespace: argo
spec:
  azureEventsHub:
    landing:
      fqdn: tstestogi.servicebus.windows.net
      sharedAccessKeyName:
        name: azure-events-hub-parameters
        key: AZURE_EVENTS_HUB_ACCESS_KEY_NAME
      sharedAccessKey:
        name: azure-events-hub-parameters
        key: AZURE_EVENTS_HUB_ACCESS_KEY
      # Event Hub path/name
      hubName: landing

---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: mv-files
  namespace: argo
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: mv-files
      eventSourceName: azure-events-hub
      eventName: landing
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: mv-files-
                namespace: argo
              spec:
                entrypoint: mv-files-rp
                activeDeadlineSeconds: 360
                ttlStrategy:
                  secondsAfterCompletion: 360
                arguments:
                  parameters:
                  - name: message
                templates:
                - name: mv-files-rp
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: bash
                    imagePullPolicy: IfNotPresent
                    command: ["/bin/bash"]
                    args: 
                    - -c 
                    - echo -n '{{inputs.parameters.message}}'
          parameters:
            - src:
                dependencyName: mv-files
              dest: spec.arguments.parameters.0.value

```
And the message has never arrived. Here are the logs:
 
```
{"level":"info","ts":1674643491.0385115,"logger":"argo-events.eventsource","caller":"cmd/start.go:63","msg":"starting eventsource server","eventSourceName":"azure-events-hub","version":"v1.7.3"}
{"level":"info","ts":1674643491.0387578,"logger":"argo-events.eventsource","caller":"metrics/metrics.go:172","msg":"starting metrics server","eventSourceName":"azure-events-hub"}
{"level":"info","ts":1674643491.0431433,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:144","msg":"Not the LEADER, stand by ...","eventSourceName":"azure-events-hub"}
{"level":"info","ts":1674643491.6019645,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:153","msg":"Becoming a Candidate, stand by ...","eventSourceName":"azure-events-hub"}
{"level":"info","ts":1674643491.6021824,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:150","msg":"I'm the LEADER, starting ...","eventSourceName":"azure-events-hub"}
{"level":"info","ts":1674643491.6022165,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:405","msg":"Starting event source server...","eventSourceName":"azure-events-hub"}
{"level":"info","ts":1674643491.6025338,"logger":"argo-events.eventsource","caller":"eventbus/driver.go:34","msg":"eventBusConfig: {NATS:&NATSConfig{URL:nats://eventbus-default-stan-svc:4222,ClusterID:*eventbus-default,Auth:*token,AccessSecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:eventbus-default-client,},Key:client-auth,Optional:nil,},} JetStream:nil}","eventSourceName":"azure-events-hub"}
{"level":"info","ts":1674643491.6025865,"logger":"argo-events.eventsource","caller":"base/stan.go:48","msg":"NATS auth strategy: Token","eventSourceName":"azure-events-hub","clientID":"client-azure-events-hub-eventsource-mkl7m-d74c96d65-n99ss-453"}
{"level":"info","ts":1674643491.6057873,"logger":"argo-events.eventsource","caller":"base/stan.go:60","msg":"Connected to NATS server.","eventSourceName":"azure-events-hub","clientID":"client-azure-events-hub-eventsource-mkl7m-d74c96d65-n99ss-453"}
{"level":"info","ts":1674643491.606931,"logger":"argo-events.eventsource","caller":"base/stan.go:73","msg":"Connected to NATS streaming server.","eventSourceName":"azure-events-hub","clientID":"client-azure-events-hub-eventsource-mkl7m-d74c96d65-n99ss-453"}
{"level":"info","ts":1674643491.6069605,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:554","msg":"Eventing server started.","eventSourceName":"azure-events-hub"}
{"level":"info","ts":1674643491.6070044,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:432","msg":"starting eventbus connection daemon...","eventSourceName":"azure-events-hub"}
{"level":"info","ts":1674643491.6070983,"logger":"argo-events.eventsource","caller":"azureeventshub/start.go:65","msg":"started processing the Azure Events Hub event source...","eventSourceName":"azure-events-hub","eventSourceType":"azureEventsHub","eventName":"landing"}
{"level":"info","ts":1674643491.607121,"logger":"argo-events.eventsource","caller":"azureeventshub/start.go:69","msg":"retrieving the shared access key name...","eventSourceName":"azure-events-hub","eventSourceType":"azureEventsHub","eventName":"landing"}
{"level":"info","ts":1674643491.607153,"logger":"argo-events.eventsource","caller":"azureeventshub/start.go:75","msg":"retrieving the shared access key...","eventSourceName":"azure-events-hub","eventSourceType":"azureEventsHub","eventName":"landing"}
{"level":"info","ts":1674643491.6071723,"logger":"argo-events.eventsource","caller":"azureeventshub/start.go:83","msg":"connecting to the hub...","eventSourceName":"azure-events-hub","eventSourceType":"azureEventsHub","eventName":"landing"}
{"level":"info","ts":1674643491.6071916,"logger":"argo-events.eventsource","caller":"azureeventshub/start.go:121","msg":"gathering the hub runtime information...","eventSourceName":"azure-events-hub","eventSourceType":"azureEventsHub","eventName":"landing"}
{"level":"info","ts":1674643491.6998992,"logger":"argo-events.eventsource","caller":"azureeventshub/start.go:135","msg":"handling the partitions...","eventSourceName":"azure-events-hub","eventSourceType":"azureEventsHub","eventName":"landing"}

```
