### DISCUSSION TITLE
Argo workflows start step only on file change

### DISCUSSION THREAD

**Discussion by holotrack** [argoproj/argo-events#2628] [Q&A]
Hello, I'm trying to achieve same thing like [here](https://support.atlassian.com/bitbucket-cloud/docs/step-options/#Condition-changesets) or [here](https://support.atlassian.com/bitbucket-cloud/docs/step-options/#Condition-changesets). I want to start step in workflow conditionally only when files in the directory are changed. How to achieve it with Argo Workflows? Im was trying it with such sensor:

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: ephemeral-devops-api-sensor
spec:
  dependencies:
  - eventName: company
    eventSourceName: gitlab-es
    filters:
      data:
      - path: body.ref
        type: string
        value:
        - refs/heads/INGIO-0000-test-argo-workflows
      - path: body.repository.name
        type: string
        value:
        - api
      dataLogicalOperator: and
    name: gitlab-pr
  - eventName: company
    eventSourceName: gitlab-es
    filters:
      data:
      - path: '[body.commits.#.modified.@flatten,body.commits.#.added.@flatten,body.commits.#.removed.@flatten].@flatten.@flatten'
        type: string
        value:
        - test.txt
        - ./*
        - ./**
        - ./database/**
        - ./app/Schema/**
    name: gitlab-pr-migration
  eventBusName: argo-events-bus
  template:
    serviceAccountName: admin
  triggers:
  - template:
      conditions: gitlab-pr
      k8s:
        operation: create
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: body.checkout_sha
            dependencyName: gitlab
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: ephemeral-api-devops-
            spec:
              arguments:
                parameters:
                - name: checkout-sha
                - name: branch
                  value: dev
                - name: environment
                  value: devops
                - name: cluster
                  value: ephemeral
                - name: migration
                  value: false
              workflowTemplateRef:
                name: api-withmigration
      name: icon-trigger
  - template:
      conditions: gitlab-pr-migration
      k8s:
        operation: create
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: body.checkout_sha
            dependencyName: gitlab
        - dest: spec.arguments.parameters.1.value
          src:
            dataKey: '[body.commits.#.modified.@flatten,body.commits.#.added.@flatten,body.commits.#.removed.@flatten].@flatten.@flatten'
            dependencyName: gitlab
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: ephemeral-api-devops-
            spec:
              arguments:
                parameters:
                - name: checkout-sha
                - name: branch
                  value: dev
                - name: environment
                  value: devops
                - name: cluster
                  value: ephemeral
                - name: migration
                  value: true
              workflowTemplateRef:
                name: api-withmigration
      name: icon-trigger-withmigrations
```
This solution didn't work because second condition require replicated same eventSource which i do not want to (multiple dependencies can not use same eventSource) any other ida how to handleit this way?

The second approach which I tried was to forward files dataKey to parameter and use "when" to start step but too its not working:

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test-sensor
spec:
  template:
    serviceAccountName: admin
  eventBusName: argo-events-bus
  dependencies:
    - name: gitlab
      eventSourceName: gitlab-es
      eventName: ingenious
      filters:
        dataLogicalOperator: "and"
        data:
          # - path: "body.ref"
          #   type: "string"
          #   value:
          #     - "refs/heads/staging"
          - path: "body.repository.name"
            type: "string"
            value:
              - "api"
              - "iCON-web-app"
              - "icon-auth"
              - "icon-admin"
          # - path: "[body.commits.#.modified.@flatten,body.commits.#.added.@flatten,body.commits.#.removed.@flatten].@flatten.@flatten"
          #   type: string
          #   value:
          #     - ".database/*"
          #     - ".app/Schema/*"
  triggers:
  - template:
      name: workflow
      k8s:
        operation: create
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: gitlab-workflow-
            spec:
              entrypoint: whalesay
              arguments:
                parameters:
                - name: message
                  # value will get overridden by the event payload
                  value: hello world
              templates:
              - name: whalesay
                when: "{{workflow.parameters.message}} == XXXXXXXXXXXXXXXXXXX"
                inputs:
                  parameters:
                  - name: message
                container:
                  image: docker/whalesay:latest
                  command: [cowsay]
                  args: ["{{inputs.parameters.message}}"]
        parameters:
          - src:
              dependencyName: gitlab
              dataKey: "[body.commits.#.modified.@flatten,body.commits.#.added.@flatten,body.commits.#.removed.@flatten].@flatten.@flatten"
            dest: spec.arguments.parameters.0.value
```

Step even for such "when" is always executing even in "message" value there are not files named "XXXXX..." am i doing something wrong here?
