### DISCUSSION TITLE
Trigger workflow file from git in namespace other than default argo-events

### DISCUSSION THREAD

**Discussion by RitudhwajA** [argoproj/argo-events#2681] [Q&A]
Hi Everyone, I am trying to trigger a workflow file from a sensor in argo-events namespace. i am fetching workflow from git and want it to be executed in the nodes namespace. i see the workflow gets executed but in argo-events namespace where my sensor resides.

service account argo-workflow-sa has a rolebinding with an appropriate role in the nodes namespace.
could someone please guide me here is my sensor

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /git/argoproj
          name: argoproj
    volumes:
      - name: argoproj
        emptyDir: {}
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook-source
      eventName: discexpansion
  triggers:
    - template:
        name: workflow-trigger-1
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: Workflow
          namespace: nodes
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: hello-template-
                namespace: nodes
            git:
              url: "git-url"
              cloneDirectory: "/git/argoproj"
              creds:
                username:
                  name: github-secret
                  key: username
                password:
                  name: github-secret
                  key: password
              filePath: "workflows/hello-workflow.yaml"
              branch: "main"
```
