### DISCUSSION TITLE
Unable to trigger the workflow due to SSH agent requested but SSH_AUTH_SOCK not-specified

### DISCUSSION THREAD

**Discussion by iabhee** [argoproj/argo-events#2751] [Q&A]
I'm currently in the process of configuring a sensor to utilize Git as its trigger source. However, I've run into an obstacle where I'm encountering the error message '**SSH agent requested but SSH_AUTH_SOCK not-specified**.' Despite carefully verifying the SSH keys and the known_hosts file in accordance with the provided documentation, I'm still facing this issue.

To provide some context, the Git source originates from Azure DevOps. The versions of the tools I'm using are as follows:

**Argo Events: 2.4.0
Argo Workflows: 0.32.2
ArgoCD: v2.7.10**

For reference, here's a snippet of the sensor.yaml configuration file I'm working with:

Tried both options by passing the ssh key and as well as the username and password <PAT> 

I would greatly appreciate any insights or guidance on resolving this SSH authentication error and successfully setting up the sensor.

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /git/argoproj
          name: argoproj
        - mountPath: /secret
          name: git-ssh
        - mountPath: /etc/ssh
          name: known-hosts
    volumes:
      - name: argoproj
        emptyDir: {}
      - name: git-ssh
        secret:
          secretName: git-ssh
      - name: known-hosts
        secret:
          secretName: git-known-hosts
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: eventSource-dep
      eventSourceName: webhook
      eventName: workflowtrigger
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            git:
              url: "<ADO_REPO_URL>"
              # sshKeyPath: "/secret/key"
              cloneDirectory: "/git/argoproj"
              branch: "feature/events"
              namespace: argo-events
              creds: 
                username:
                  name: ado-auth-key
                  key: username
                password:
                  name: ado-auth-key
                  key: password
              filePath: "argo-workflow/workflow.yaml"
    - template:
        name: workflow-trigger-2
        k8s:
          operation: create
          source:
            git:
              url: "<SSH_URL_ADO_REPO>"
              cloneDirectory: "/git/argoproj1"
              sshKeyPath: "/secret/key"
              
              # sshKeySecret:
              #   name: git-ssh
              #   key: key
              filePath: "argo-workflow/workflow.yaml"
              branch: "feature/events"
```
