### DISCUSSION TITLE
How do I escape special characters in sensor trigger dest key?

### DISCUSSION THREAD

**Discussion by rkt2spc** [argoproj/argo-events#2777] [Q&A]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: my-sensor
spec:
  dependencies:
    - name: DEP
      eventSourceName: my-event-source
      eventName: my-event-name
  triggers:
    - template:
         name: webhook-pod-trigger
         k8s:
           operation: create
           source:
              ...
           parameters:
             - src:
                  dependencyName: DEP
                  dataKey: body.payload.label
               dest: metadata.labels.'my.company.co/value' # ????
```
