### DISCUSSION TITLE
Is it possible to apply kustomize to a k8s resource in sensor?

### DISCUSSION THREAD

**Discussion by NN624** [argoproj/argo-events#2876] [Q&A]
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: create-pod-sa # A service account has privileges to create a Pod
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-pod-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: hello-world-
              spec:
                containers:
                  - name: hello-container
                    args:
                      - "hello-world"
                    command:
                      - cowsay
                    image: "docker/whalesay:latest"
                    ports:
                  - containerPort: 80
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.containers.0.args.0
```
Is it possible to do a strategic merge using kustomize on the "hello-container" in the above code?
