### DISCUSSION TITLE
Example for an SQS event with https://www.localstack.cloud/

### DISCUSSION THREAD

**Discussion by hanneskaeufler** [argoproj/argo-events#2995] [Q&A] [answered]
I would love to get any pointers to how I can setup an Argo event listening to an (aws) SQS queue. Now this queue is not _actually_ in AWS, but instead emulated using https://www.localstack.cloud/.
I don't see anything in https://argoproj.github.io/argo-events/eventsources/setup/aws-sqs/ that would allow me to set a custom endpoint for where the queue is reachable? Googling didn't really find anything, so hoping somebody here has any ideas?

Thanks!

**Comment by juthrbog** [comment, marked as answer]
You can specify both `endpoint` and `queue` together in your `EventSource` to accomplish this.

For example:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: example
  namespace: localdev-example
spec:
  eventBusName: example
  sqs:
    example:
      jsonBody: true
      accessKey:
        name: example-sqs-creds
        key: access_key
      secretKey:
        name: example-sqs-creds
        key: secret_key
      region: us-east-1
      endpoint: <ENDPOINT FOR LOCALSTACK HERE>
      queue: <QUEUE NAME HERE>
```

In my case, I have localstack running in a k3d cluster so I have the following endpoint value: `localstack.default.svc.cluster.local:4566`. 

IIRC, if you're running localstack outside of k8s, your endpoint would probably be just `localhost:4566`.
