### DISCUSSION TITLE
Argo Event Source that filters both label and annotation

### DISCUSSION THREAD

**Discussion by morkalfon** [argoproj/argo-events#3010] [General]
I'm looking for a way to create an Argo EventSource that filters both label and annotation.

This is what I have so far:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: my-event-source
  namespace: test
spec:
  eventBusName: test
  resource:
    test-event:
      namespace: test
      group: ""
      version: v1
      resource: secrets
      eventTypes:
        - ADD
        - UPDATE
      filter:
        afterStart: true
        labels:
          - key: label
            value: specificValue
``` 

Any ideas?

Thanks!
