### DISCUSSION TITLE
502 Bad Gateway upon accessing the argo events webhook url

### DISCUSSION THREAD

**Discussion by ashishkurian** [argoproj/argo-events#3021] [General]
Hi There,

I am new to Argo events and I am trying to create use case, where I trigger a workflow upon receiving an argo event from my bitbucket server.

I think I have created all the necessary resources in my EKS cluster. However, when I try to call the webhook url, I get a **502 Bad gateway** error. I noticed that the k8s service that gets called from the webhook url, is of type Nodeport and I do not see any pods being added as end point to the service. This exaplains why I am getting a 502 Bad gateway error.

Is the BitbucketServer eventsource expected to create some pods in the cluster and get attached to the service?

I am attaching the manifest file I am deploying to my cluster.

```yaml
---
# Source: bitbucket-event-workflow/templates/event-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bitbucketserver-eventsource-service
  namespace: argocd
spec:
  ports:
  - port: 12000
    protocol: TCP
    targetPort: 12000
  selector:
    eventsource-name: bitbucketserver
  type: NodePort
---
# Source: bitbucket-event-workflow/templates/event-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitbucketserver-eventsource-ingress
  namespace: argocd
  annotations:
    alb.ingress.kubernetes.io/group.name: infra-ingress
    external-dns.alpha.kubernetes.io/hostname: argo-events.tde21270.company.corproot.net
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-2:*****:certificate/***********
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: alb
  rules:
    - host: argo-events.tde21270.company.corproot.net
      http:
        paths:
        - path: /events
          pathType: Prefix
          backend:
            service:
              name: bitbucketserver-eventsource-service
              port:
                number: 12000
---
# Source: bitbucket-event-workflow/templates/workflow-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate 
metadata:
  name: echo-git-event
spec:
  entrypoint: echo-git-event
  arguments:
    parameters:
    - name: git_event
      value: "value-to-be-overwritten"
  templates:
  - name: echo-git-event
    inputs:
      parameters:
      - name: git_event
    container:
      image: alpine:latest
      command: [echo -e, "The latest git event is\n {{inputs.parameters.git_event}}"]
---
# Source: bitbucket-event-workflow/templates/eventbus.yaml
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: "git-eventbus"
  namespace: argocd
spec:
  nats:
    native:
      replicas: 3
      auth: none
---
# Source: bitbucket-event-workflow/templates/eventsource.yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: bitbucketserver
  namespace: argocd
spec:
  eventBusName: "git-eventbus"
  bitbucketserver:
    config-tde-elasticpath:
      repositories:
        - projectKey: TDEREDPLAY
          repositorySlug: https://git.company.com/scm/tderedplay/config-tde-tde21270.git
      events:
        - "repo:push"
        - "repo:updated"
        - "repo:commit_comment_created"
        - "issue:created"
        - "issue:updated"
        - "issue:comment_created"
        - "pullrequest:created"
        - "pullrequest:updated"
        - "pullrequest:changes_request_created"
        - "pullrequest:changes_request_removed"
        - "pullrequest:approved"
        - "pullrequest:unapproved"
        - "pullrequest:fulfilled"
        - "pullrequest:rejected"
        - "pullrequest:comment_created"
        - "pullrequest:comment_updated"
        - "pullrequest:comment_deleted"
        - "pullrequest:comment_resolved"
        - "pullrequest:comment_reopened"
      webhook:
        endpoint: /events
        port: "12000"
        method: POST
        url: "https://argo-events.tde21270.company.corproot.net/events"
      deleteHookOnFinish: true
      bitbucketserverBaseURL: "https://git.company.com/rest"
---
# Source: bitbucket-event-workflow/templates/sensor.yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: bitbucket-sensor
  namespace: argocd
spec:
  eventBusName: "git-eventbus"
  template:
    serviceAccountName: argo-events-webhook-sa
  dependencies:
    - name: bitbucket-repo-event-dependency
      eventSourceName: bitbucketserver
      eventName: config-tde-elasticpath
  triggers:
    - template:
        name: bitbucket-repo-event-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: bitbucket-repo-event-trigger
              spec:
                entrypoint: echo-git-event
                arguments:
                  parameters:
                    - name: git_event
                      value: value-to-be-overwritten
                workflowTemplateRef:
                  name: echo-git-event
          parameters:
            - src:
                dependencyName: bitbucket-repo-event-dependency
                dataKey: body
              dest: spec.arguments.parameters.0.value

```
