### DISCUSSION TITLE
Argo Workflow Sensor parameterization

### DISCUSSION THREAD

**Discussion by dbeilin** [argoproj/argo-events#3062] [Q&A] [answered]
I have the following Sensor:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-pr-comment
spec:
  template:
    serviceAccountName: argo-workflows-server
  dependencies:
    - name: pr-comment-dep
      eventSourceName: github-argo-event-source
      eventName: pr-comment-trigger
      filters:
        data:
          - path: headers.X-Github-Event
            type: string
            value:
              - issue_comment
  triggers:
    - template:
        name: github-argo-template
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: "test"
              spec:
                entrypoint: main
                serviceAccountName: argo-workflows-server
                arguments:
                  parameters:
                    - name: pr_id
                      value: ""
                    - name: comment_body
                      value: ""
                    - name: repo_name
                      value: ""
                workflowTemplateRef:
                  name: ci-template
          parameters:
            - src:
                dependencyName: pr-comment-dep
                dataKey: body.issue.number
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: pr-comment-dep
                dataKey: body.comment.body
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: pr-comment-dep
                dataKey: body.repository.name
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: pr-comment-dep
                dataTemplate: "{{ .Input.body.repository.name }}-"
              dest: metadata.name

```
This Sensor is triggered by an EventSource which passes a payload from Github.

I'm trying to override the name of the workflow (`metadata.name`) by using `dataTemplate`. I want to concatenate the repo name along with other things, but for now I'm just trying to see if it works, which it doesn't.

I followed the [example](https://github.com/argoproj/argo-events/blob/stable/examples/sensors/trigger-with-template.yaml) from Argo but couldn't get it to work.

The EventSource pod doesn't show any errors, but the workflow doesn't get triggered.
I'm not sure how to solve this.
