### DISCUSSION TITLE
Value usage in Sensor data filters

### DISCUSSION THREAD

**Discussion by dbeilin** [argoproj/argo-events#3073] [General]
I have a question regarding [data filters](https://github.com/argoproj/argo-events/blob/master/api/sensor.md#datafilter).
I created the following Sensor:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-pr-comment
spec:
  template:
    serviceAccountName: argo-workflows-server
  dependencies:
    - name: pr-comment-dep
      eventSourceName: github-argo-event-source
      eventName: pr-comment-trigger
      filters:
        data:
          - path: headers.X-Github-Event
            type: string
            value:
              - issue_comment
          - path: body.comment.body
            type: string
            value:
              - "/test"
```

I've set `body.comment.body` to trigger on `/test` but noticed that it also works with anything else following that `/test` (i.e `/test <some-other-string>` would also trigger this Sensor).
I'm wondering if I should have used `template` instead of `value` along with some `sprig.contains()` for example, or what would be the best practice in this use case? Is there any scenario where `value`'s behavior of catching `/test <some-string>` changes in the future?

Thanks :)
