### DISCUSSION TITLE
Using git URL parameters within a sensor

### DISCUSSION THREAD

**Discussion by BillyMichael** [argoproj/argo-events#3352] [Q&A]
Is it possible to use parameters to specify the git URL within a sensor? It seems that the sensor works for the first event it receives but then sticks to the URL input and won't accept new parameter values. 

``` 
triggers:
  - parameters:
    - dest: k8s.source.git.branch
      src:
        dataKey: body.push.changes.0.new.name
        dependencyName: common_webhook
    - dest: k8s.source.git.url
      src:
        dataTemplate: '{{ printf "https://bitbucket.org/example-org/%s.git" .Input.body.repository.name  }}'
        dependencyName: common_webhook
    template:
      k8s:
        operation: create
        source:
          git:
            cloneDirectory: /git/argoproj
            creds:
              password:
                key: password
                name: example-secret
              username:
                key: username
                name: example-secret
            filePath: .argo-workflows/pipeline.yaml
```
