### DISCUSSION TITLE
is webhook event source "url" property required or optional?

### DISCUSSION THREAD

**Discussion by m-ronchi** [argoproj/argo-events#3456] [General]
from all the docs / examples, the only seemingly required properties are `endpoint`, `port` and `method`, e.g.:
```
spec:
  webhook:
    example:
      port: "12000"
      endpoint: /example1
      method: POST
```
but if I add [the jsonschema](https://raw.githubusercontent.com/argoproj/argo-events/refs/heads/master/api/jsonschema/schema.json) to my vscode, it says that `url` is also required.

which is it? my webhooks already work without `url` (I am calling them internally in the cluster using the svc endpoint) and also I have no idea what to put there or what effect it should have
