### DISCUSSION TITLE
Argo-Event Bus jetStreamExoit support distributed JWT Authentication?

### DISCUSSION THREAD

**Discussion by meDracula** [argoproj/argo-events#3516] [General]
Hi :wave: , I have a running Nats Cluster with Jetstream enabled. I want my eventbus to use this Jetstream. But it is unclear how when then **authentication method** is providing a credentials file (Docs: [JWT Authentication/Authorization](https://docs.nats.io/running-a-nats-service/configuration/securing_nats/auth_intro/jwt)).

**CAN I ?** and if so how should this one look like:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  jetstreamExotic:
    url: nats://xxxxx:xxx
    accessSecret:
      name: my-secret-name
      key: secret-key
    streamConfig: ""
```
