### DISCUSSION TITLE
Accessing Payload from SQS queue events

### DISCUSSION THREAD

**Discussion by gavin-crane** [argoproj/argo-events#3517] [Q&A]
I have a simple k3s cluster running locally on WSL. I have an SQS queue setup with an IAM user that has "AmazonSQSFullAccess" policy, and a secret with the access key and secret key applied. I have the following event source and sensor configured:

event-source:

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: aws-sqs
spec:
  sqs:
    example:
      # jsonBody specifies that all event body payload coming from this
      # source will be JSON
      jsonBody: true
      # accessKey contains information about K8s secret that stores the access key
      accessKey:
        # Key within the K8s secret whose corresponding value (must be base64 encoded) is access key
        key: accesskey
        # Name of the K8s secret that contains the access key
        name: aws-secret
      # secretKey contains information about K8s secret that stores the secret key
      secretKey:
        # Key within the K8s secret whose corresponding value (must be base64 encoded) is secret key
        key: secretkey
        # Name of the K8s secret that contains the secret key
        name: aws-secret
      # aws region
      region: us-east-1
      # name of the queue. The eventsource resolves the url of the queue from the queue name.
      queue: sqsqueue
      # The duration (in seconds) for which the call waits for a message to arrive in the queue before returning.
      # MUST BE > 0 AND <= 20
      waitTimeSeconds: 20
```

Sensor:

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: s3-sensor
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: aws-sqs
      eventName: example
  triggers:
    - template:
        name: log-trigger
        k8s:
          group: ""
          version: v1
          resource: pods
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: log-pod-
                labels: log-pod
              spec:
                containers:
                  - name: log-container
                    image: alpine
                    command: ["echo"]
                    args: ["S3 file upload event received:\n", ""]
                restartPolicy: Never
        parameters:
          - src:
              dependencyName: test-dep
              dataKey: body
              dest: spec.containers.0.args.1
```

The event source trigger is working. I send a message to the queue manually through the AWS SQS dashboard:
`{"text":"hello"}`
This triggers the pod creation, but the event message is empty when I inspect the pod logs.

```
># kubectl get pods -n argo-events
NAME                                         READY   STATUS      RESTARTS   AGE
aws-sqs-eventsource-flcxc-7754d979c6-wc2gd   1/1     Running     0          22h
controller-manager-7c585bd5c-6fz57           1/1     Running     0          24h
eventbus-default-stan-0                      2/2     Running     0          24h
eventbus-default-stan-1                      2/2     Running     0          24h
eventbus-default-stan-2                      2/2     Running     0          24h
log-pod-2tzsl                                0/1     Completed   0          70m
log-pod-bth9h                                0/1     Completed   0          109m
log-pod-fmc6h                                0/1     Completed   0          21s <- message added to SQS triggers pod creation
log-pod-ztdmg                                0/1     Completed   0          22s
s3-sensor-sensor-wqzrp-7d44b55598-gjc4h      1/1     Running     0          70m
># kubectl logs -n argo-events log-pod-fmc6h
S3 file upload event received:
 
>#

```
Any ideas as to what's causing the event body to be empty? Like I said earlier, the trigger is working, but I am unable to receive that payload data from the SQS queue from the triggered event.

Any help would be appreciated, thanks!
