### DISCUSSION TITLE
fetch trigger configuration from configmap/secret

### DISCUSSION THREAD

**Discussion by m-ronchi** [argoproj/argo-events#3628] [Q&A]
Hi, 
I am creating a slack trigger like this:
```
triggers:
    - template:
        name: slack-trigger
        slack:
          slackToken:
            name: slack-secret
            key: token
          channel: __PLACEHOLDER__
          message: hello world
      parameters:
        - src:
            dependencyName: event
            dataKey: body.channel
          dest: slack.channel
        - src:
            dependencyName: event
            dataKey: body.message # will become template eventually
          dest: slack.message
```
and I want to fill the channel (and potentially parts of the message) in a k8s configmap (or secret) instead of the event body.

I want different slack channels between dev and prod deployments but the template should be shared.
I also need different channels depending on the body (with internal mapping , e.g. body with `{key: "foo"}` will go to `bar`), I can use a lua/jq script for this
