### ISSUE TITLE
Cannot fetch AWS credentials from env

### ISSUE THREAD

**Issue by frostornge** [argoproj/argo-events#1000]
I'm using argo-events in EKS, so i just uses service account integrated with AWS IAM Role.

But source code does not seems to fetch AWS credentials from injected environment.

They just fetch credential information from volume only.

https://github.com/argoproj/argo-events/blob/97e4926c7c627dd833d5da8e2f261a7127ea94f3/eventsources/sources/awssqs/start.go#L69

Also, i'm currently using this definition
```
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: event-source
  namespace: dev
spec:
  template:
    serviceAccountName: service-account-name
  sqs:
    consent-receiver-event:
      jsonBody: true
      region: ap-northeast-2
      queue: queue-name
```

Please make these things work. thank you
