### ISSUE TITLE
CloudEvents compliance

### ISSUE THREAD

**Issue by paveq** [argoproj/argo-events#1015]
When sending CloudEvents compliant events to webhook endpoint, they get wrapped into another CloudEvents container by the EventSource, and JSON that was sent gets put to body of that.

**To Reproduce**
1. Send CloudEvents compliant object to webhook endpoint, such as:
`kubectl run curl --rm -i --tty --restart='Never' --image curlimages/curl:latest -- -X POST -d '{"specversion" : "1.0","type" : "com.example.someevent","source" : "/mycontext","id" : "A234-1234-1234","time" : "2018-04-05T17:31:00Z","datacontenttype" : "text/xml","data" : "<much wow=\"xml\"/>"}' http:/eventsource-svc/mystuff`

**Expected behavior**
It is at least possible for event generating system to set some fields such as _source_, _type_ and _id_ themselves. Current behaviour makes it difficult to implement eg. request-reply pattern, where event generating system generates unique id, and then later listens back the events related to that _id_ on another "topic"/type.

Of course these fields could be set on the body, but this makes CloudEvents compliance bit moot point, if CloudEvents is only used internally by Argo-Events.

**Comment by paveq** [comment]
_Subject_ is already set to event name, which probably is enough. Main issue is that _id_ cannot be given.

As idea, do you think webhook endpoint could support following "REST-api" style to allow event generating system to specify _id_ in request path?

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  webhook:
    environment.create:
      port: "12000"
      endpoint: /environment/create/{id}
      method: POST
```

Might be possible to extend into generic endpoint where all parameters can be given in the url path, like this:

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  webhook:
    port: "12000"
    endpoint: /{source}/{event}/{id}
    method: POST
```
