### ISSUE TITLE
Kafka EventSource is not able to start

### ISSUE THREAD

**Issue by oscarusuga** [argoproj/argo-events#1020]
**Description**
I have installed **argo-events** in my cluster as described in the documentation https://argoproj.github.io/argo-events/installation/

I also created the namespace _argo-events_ and created my kafka cluster in the _argo-events_ namespace as well.
I've created the following EventSource, afterwards:

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
    name: kafka-eventsource
spec:
    kafka-eventsource:
        mytopic:
            url: kafka.argo-events.svc.cluster.local:9092
            topic: socialmedia
            partition: "1"
```
When Kubernetes tries to create the POD for _kafka-eventsource_, throws the following error: `"logger":"argo-events.eventsource","caller":"cmd/main.go:61","msg":"failed to start eventsource server","eventSourceName":"kafka-eventsource","error":"no active event server running"`

I'm using the Google Kubernetes Engine with all permissions to create event sources, sensors and workflows. All pods were created under the argo-events namespace and I've verified that kafka is accessible from that URL but looks like the event source can't find any URL because I've tried deleting and creating new kafka deployments several times. Am I missing something or is this a bug?

**To Reproduce**
1. Install argo-events
2. Create a kafka cluster under the argo-events namespace (I also tried the default namespace with no success)
3. Create the kafka event source that I used
4. Check if the POD starts correctly

**Expected behavior**
The kafka-eventsource-pod should be started and run correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/60943440/104784053-6dbef580-5755-11eb-9d44-414036a5fb28.png)

**Environment:**
 - Google Kubernetes Engine: 1.17.13-gke.2600
 - Argo: 2.11.8
 - Argo Events: [e.g. v1.0.0]

Thank you very much for your time and effort.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
