### ISSUE TITLE
Include transport option for skipping tls certificate validation for Minio Event Source

### ISSUE THREAD

**Issue by divaybansal** [argoproj/argo-events#1027]
Currently, self-signed certificates or Custom CA's are not supported by the event source Minio.  This feature could be added by adding transport options to the minio event source specification.

The version of the minio-client that is used in the event source implementation provides a method **SetCustomTransport** for specifying this configuration. 

In the newer version from v7.0.0 for minio client, it is included as part of options for the client constructor.

**Comment by whynowy** [comment]
@divaybansal, thanks for you suggestion, would you like to raise a PR?

**Comment by divaybansal** [comment]
@whynowy, sure I can submit one in the next couple of days. Would you also like to move to the latest version of minio client library?

**Comment by whynowy** [comment]
> @whynowy, sure I can submit one in the next couple of days. Would you also like to move to the latest version of minio client library?

Sounds good, thanks @divaybansal

**Comment by rossigee** [comment]
I've been struggling with this too. I ended up creating a patch that adds a 'caCertificate' parameter to the Minio EventSource. For example...

```
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: incoming-docs
  namespace: whatever
spec:
  minio:
    docs-uploaded:
      bucket:
        name: incoming-documents-bucket
      endpoint: minio.domain.lan
      events:
        - s3:ObjectCreated:Put
        - s3:ObjectRemoved:Delete
      insecure: false
      accessKey:
        key: accessKey
        name: minio-staging-auth
      secretKey:
        key: secretKey
        name: minio-staging-auth
      caCertificate:
        key: caCertificate
        name: minio-staging-auth
```

It's working locally for me and has scratched my itch. For now, I'm just interested to see what comes out of the CI/CD pipeline from submitting it as a draft PR here.
