### ISSUE TITLE
Unable to decode an event from the watch stream: stream error

### ISSUE THREAD

**Issue by ttelfer** [argoproj/argo-events#103]
**Describe the bug**
Sensor doesn't trigger.

Sensor pod log:
```
{"level":"info","sensor-name":"operational-data","port":"9300","message":"sensor started listening"}

{"level":"info","sensor-name":"operational-data","message":"watching sensor updates"}

ERROR: logging before flag.Parse: E1014 19:09:35.791916       1 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 5; INTERNAL_ERROR

ERROR: logging before flag.Parse: E1014 19:19:35.889108       1 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 7; INTERNAL_ERROR 
```

**To Reproduce**
sensor.yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: operational-data
  namespace: argo-events
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    app: ami
spec:
  serviceAccountName: argo-events-sa
  imagePullPolicy: Always
  repeat: true
  signals:
    - name: calendar-gateway/calendar.barConfig
  triggers:
    - name: calendar-workflow-trigger
      resource:
        namespace: argo-events
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: argo-operational-data
              spec:
                entrypoint: test-parallel
                templates:
                - name: test-parallel
                  steps:
                  - - name: foo
                      template: test
                      arguments:
                        parameters:
                        - name: filename
                          value: "foo"
                    - name: bar
                      template: test
                      arguments:
                        parameters:
                        - name: filename
                          value: "bar"

                - name: test
                  inputs:
                    parameters:
                    - name: filename
                  container:
                    image: foodev.azurecr.io/base:latest
                    command: ["python3", "/project/foo/bar/{{inputs.parameters.filename}}.py"]
```

configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: calendar-gateway-configmap
  namespace: argo-events
data:
  calendar.barConfig: |-
    interval: 5m
```

gateway:
```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: calendar-gateway
  namespace: argo-events
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
    gateway-name: "calendar-gateway"
spec:
  deploySpec:
    containers:
    - name: "calendar-events"
      image: "argoproj/calendar-gateway"
      imagePullPolicy: "Always"
      command: ["/bin/calendar-gateway"]
    serviceAccountName: "argo-events-sa"
  configMap: "calendar-gateway-configmap"
  type: "calendar"
  dispatchMechanism: "HTTP"
  version: "1.0"
  watchers:
      sensors:
      - name: "calendar-sensor"
```

**Expected behavior**
Expected the two steps to execute in parallel.

**Environment (please complete the following information):**
 - Azure AKS 1.11.3

```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-09-28T15:20:58Z
  compiler: gc
  gitCommit: 0ed33881dc4355495f623c6f22e7dd0b7632b7c0
  gitTreeState: clean
  gitVersion: v1.12.0
  goVersion: go1.11
  major: "1"
  minor: "12"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-09-09T17:53:03Z
  compiler: gc
  gitCommit: a4529464e4629c21224b3d52edfe0ea91b072862
  gitTreeState: clean
  gitVersion: v1.11.3
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
```

```
$ argo version
argo: v2.2.0
  BuildDate: 2018-08-30T08:51:40Z
  GitCommit: af636ddd8455660f307d835814d3112b90815dfd
  GitTreeState: clean
  GitTag: v2.2.0
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```

**Additional information:**
Verified that this sensor worked:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: calendar-sensor
  namespace: argo-events
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    app: ami
spec:
  serviceAccountName: argo-events-sa
  imagePullPolicy: Always
  repeat: true
  signals:
    - name: calendar-gateway/calendar.barConfig
  triggers:
    - name: calendar-workflow-trigger
      resource:
        namespace: argo-events
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: argo-test-
              spec:
                entrypoint: test
                templates:
                - name: test
                  container:
                    image: foodev.azurecr.io/base:latest
                    command: ["python3", "/project/foo/bar/foo.py"]
```
