### ISSUE TITLE
Kafka Eventsource crashes and don't listen for messages

### ISSUE THREAD

**Issue by oscarusuga** [argoproj/argo-events#1031]
**Description**
I've created a Kafka Eventsource by following the tutorials and documentation. The kafka-eventsource pod starts successfully but it crashes and restarts every 4 minutes. Also, I send some messages to the kafka topic but the eventsource does not receive any of them, don't log it, and as a consequence, the kafka sensor does not execute the trigger.

The kafka-events was installed in the **argo-events** namespace as well as the kafka cluster. The argo-server is installed in the **default** namespace.

This is the kafka-eventsource file:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
    name: kafka
spec:
    kafka:
        publication:
            url: kafka-0:9092
            topic: socialmedia
            partition: "0"
            version: "2.7.0"
```

This is the kafka-sensor file:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
    name: kafka
spec:
    template:
        serviceAccountName: argo-events-sa
    dependencies:
        - name: test-dep
          eventSourceName: kafka
          eventName: publication
    triggers:
        - template:
              name: kafka-workflow-trigger
              k8s:
                  group: argoproj.io
                  version: v1alpha1
                  resource: workflows
                  operation: create
                  source:
                      resource:
                          apiVersion: argoproj.io/v1alpha1
                          kind: Workflow
                          metadata:
                              generateName: kafka-workflow-
                          spec:
                              entrypoint: whalesay
                              arguments:
                                  parameters:
                                      - name: message
                                          # the value will get overridden by the event payload from test-dep
                                        value: hello world
                              templates:
                                  - name: whalesay
                                    inputs:
                                        parameters:
                                            - name: message
                                    container:
                                        image: docker/whalesay:latest
                                        command: [cowsay]
                                        args: ["{{inputs.parameters.message}}"]
                  parameters:
                      - src:
                            dependencyName: test-dep
                        dest: spec.arguments.parameters.0.value
```

**To Reproduce**
1. Install argo events in the argo-events namespace.
2. Install the kafka cluster in the argo-events namespace.
3. Apply the kafka-eventsource configuration.
4. Apply the kafka-sensor configuration.
5. Send a message to the socialmedia topic.
6. Check the eventsource logs to see if the pod receives the message.

**Expected behavior**
The kafka-eventsource receives the message and the kafka-sensor triggers the argo workfow.

**Screenshots**
![image](https://user-images.githubusercontent.com/60943440/105525089-95124700-5cae-11eb-887d-28b6ed99716d.png)
 In the screenshot we can see the kafka-eventsource with several restarts and nothing happens after sending a message to the topic.

**Environment:**
 - Google Kubernetes Engine: 1.17.13-gke.2600
 - Argo: 2.11.8
 - Argo Events: v1.0.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
