### ISSUE TITLE
Documentation: Parse headers in  Sensor crd

### ISSUE THREAD

**Issue by dzirg44** [argoproj/argo-events#1034]
**Is your feature request related to a problem? Please describe.**
according to the 
https://argoproj.github.io/argo-events/setup/github/
we have 2 data section, body and headers, i am able to use body, but it is not so clear for me how to extract headers.

**Describe the solution you'd like**
```yaml
        data:
          - path: header
            type: string
            comparator: "="
            value:
                  - "X-github-event: push"
          # or something like
          - path: header.x-github-event
            type: string
            comparator: "="
            value:
                  - "X-github-event: push"
          - path: body.ref
            type: string
            comparator: "="
            value:
                  - "main"
```
maybe i missed something in the documentation)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
