### ISSUE TITLE
Sensors with invalid workflow is reported as "no workflow found"

### ISSUE THREAD

**Issue by atombender** [argoproj/argo-events#1039]
**Describe the bug**
As we work with sensors and workflows, sometimes we add a field at the wrong place or something else that apparently makes the workflow invalid. In this case, when the sensor triggers, Argo simply reports not finding the workflow:

```
github-sensor-wkh26-79dbdd6-kr5cq main 2021-01-27T13:52:30.736210604Z time="2021-01-27T13:52:30Z" level=warning msg="WorkflowTemplate is not of kind Workflow. Ignoring..."
github-sensor-wkh26-79dbdd6-kr5cq main 2021-01-27T13:52:30.736294974Z 2021/01/27 13:52:30 No Workflow found in given files
github-sensor-wkh26-79dbdd6-kr5cq main 2021-01-27T13:52:30.740553594Z {"level":"error","ts":1611755550.7400827,"logger":"argo-events.sensor","caller":"sensors/listener.go:160","msg":"failed to trigger actions","sensorName":"github","error":"failed to execute submit command for workflow : exit status 1","errorVerbose":"exit status 1\nfailed to execute submit command for workflow \ngithub.com/argoproj/argo-events/sensors/triggers/argo-workflow.(*ArgoWorkflowTrigger).Execute\n\t/home/runner/work/argo-events/argo-events/sensors/triggers/argo-workflow/argo-workflow.go:166\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:267\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.3\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:158\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.14.13/x64/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.3\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:160"}
```

`kubectl describe sensor` does not show any errors. The sensor pod does not log any errors on startup.

The state isn't reported anywhere, so the _only_ way (that I can see) to know that the workflow didn't execute properly (aside from the fact that it's not triggered) is to look in the sensor pod log.

**To Reproduce**
Create a sensor and put some invalid field in the workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa

  dependencies:
  - name: github
    eventSourceName: my-event-source
    eventName: my-event

  triggers:
  - template:
      name: argo-workflow-trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit

        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: WorkflowTemplate
            metadata:
              generateName: test-
              namespace: argo
              labels:
                workflows.argoproj.io/archive-strategy: "false"
            spec:
              entrypoint: main
              serviceAccountName: argo

              myInvalidField: "foo"  # Note invalid field

              templates:
              - name: main
                dag:
                  tasks:
                  - name: run
                    template: run

              - name: run
                script:
                  image: busybox:1.25.0
                  imagePullPolicy: Always
                  command: [sh]
                  source: |
                    set -eu
                    echo SUCCESS

              ttlStrategy:
                secondsAfterCompletion: 300
```

**Expected behavior**
The log message should explain how the workflow is invalid. Ideally, the sensor should be rejected on create/update if it is not valid.

**Environment (please complete the following information):**
 - Kubernetes: v1.17.14-gke.400
 - Argo: 2.12.5
 - Argo Events: 1.2.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by atombender** [comment]
We currently have a template that validates but fails with the same "no workflow" error:

```
$ argo template lint <(cat sensor.yml | yq -Y '.spec.triggers[0].template.argoWorkflow.source.resource')
WorkflowTemplate manifests validated
WorkflowTemplate manifests validated
```

How do I find out what's wrong with it?

**Comment by atombender** [comment]
By a process of elimination, we believe we narrowed it down to this, specified at the workflow level:

```
              retryStrategy:
                retryPolicy: onError
                limit: 10
```

Removing this causes the workflow to be applied.

I have tested workflows and workflow templates separately, and including those fields works fine, so I don't know what's going on.

**Comment by whynowy** [comment]
@atombender - Is `retryStrategy` under `workflowTemplate` a newer feature in Argo workflows? Could you change the trigger spec to following to see if it works.

```
  - template:
      name: argo-workflow-trigger
      k8s:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: create
...
```
