### ISSUE TITLE
Sprig templating library is out of date

### ISSUE THREAD

**Issue by tomgoren** [argoproj/argo-events#1042]
**Describe the bug**
`argo-events` uses Sprig v2.22.0 - this prevents us from using useful functions such as [`fromJson`](https://github.com/Masterminds/sprig/pull/223) - which are necessary when utilizing SQS as an eventSource.

**To Reproduce**
Given a parameter in a SQS sensor defined as:

```
          parameters:
            - src:
                dependencyName: test-dep
                dataTemplate: "{{ index (.Input.body | b64dec | fromJson) \"myKey\" }}"
              dest: spec.arguments.parameters.0.value
``` 

Sending a message such as:

```
aws sqs send-message --queue-url https://sqs.<region>.amazonaws.com/<aws_account_id>/<queue_name> --message-body '{"myKey": "myValue"}'
```
Results in:

```
failed to execute the src event template, falling back to key or value. err: template: param:1: function "fromJson" not defined
```

**Expected behavior**
The value should be parsed and used to override the parameter defined in the trigger.

**Environment (please complete the following information):**
 - Kubernetes: v1.17.12-eks-7684af
 - Argo: v2.12.5
 - Argo Events: v1.2.2

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
