### ISSUE TITLE
Event source requires too many permissions

### ISSUE THREAD

**Issue by dimitarKiryakov** [argoproj/argo-events#1063]
**Describe the bug**
Using this [type](https://argoproj.github.io/argo-events/setup/resource/) of `EventSource` requires a service account to be used with too permissive rights - > list, get, watch.
This means that providing `SA` with `Role` only to list a specific resource name would never work since the event source wants to list all resources in k8s namespace of this kind.
Example role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: producer-role
rules:
- apiGroups: ["argoproj.io"]
  resources: ["applications"]
  verbs: ["get","list", "watch"]
  resourceNames: ["producer"]
```
Example not working EventSource
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: resource
spec:
  template:
    serviceAccountName: argo-events-sa
  resource:
    example:
      namespace: argocd
      group: argoproj.io
      version: v1alpha1
      resource: applications
      eventTypes:
        - UPDATE
      filter:
        fields:
          - key: metadata.name
            operation: ==
            value: producer
          
```

**Expected behavior**
Having field for example `resourceName` :
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: resource
spec:
  template:
    serviceAccountName: argo-events-sa
  resource:
    example:
      namespace: argocd
      group: argoproj.io
      version: v1alpha1
      resource: applications
      **resourceName: producer**
      eventTypes:
        - UPDATE
          
```

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.18.6]
 - Argo: [e.g. v2.9.4]
 - Argo Events: [e.g. v1.0.0]

**Additional context**
In case using ArgoCD by multiple teams, we could not provide the option to list all applications in ArgoCD namespace(since ArgoCD does not support application CR in namespaces different than deployed one), because some applications could contain sensitive data 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
