### ISSUE TITLE
filters don't work as expected when the path contains "-" (a dash)

### ISSUE THREAD

**Issue by nnahaliel** [argoproj/argo-events#1069]
**Describe the bug**
When trying to filter out events according to request headers with a dash in their names, the sensor blocks all events.
This is required for working with GitHub webhooks, which send information like "X-GitHub-Event" that i wish to use.

**To Reproduce**
Add to data filters (for example) -  
```yaml
          - path: header.content-type
            type: string
            value:
              - ".*"
```
(I have a working sensor that never triggers anything once this filter is added)

**Expected behavior**
Filters should allow any kind of string that can be sent as a header

**Environment (please complete the following information):**
 - Kubernetes: v1.18.9
 - Argo: v2.12.8
 - Argo Events: v1.1.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@nnahaliel - I wasn't able to reproduce it, it works for me with `-` in the path. Could you verify?

**Comment by hamptonsmith** [comment]
I am also experiencing this issue on the following platform:

Kubernetes: Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1210", GitCommit:"199a41188dc0ca5d6d95b1cc7e8ba96e05f9dd0a", GitTreeState:"clean", BuildDate:"2021-02-05T18:03:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

Argo: argo: v3.0.0-rc2
  BuildDate: 2021-02-16T18:12:46Z
  GitCommit: ea3439c91c9fd0c2a57db0d8a5ccf2b9fb2454a3
  GitTreeState: clean
  GitTag: v3.0.0-rc2
  GoVersion: go1.13
  Compiler: gc
  Platform: linux/amd64

Argo Events: 1.2.3

---

Github reports it's sending this event:

**Headers**

```
...
Accept: */*
...
X-GitHub-Event: push
...
```

**Payload**

```
{
  "ref": "refs/heads/master",
  ...
```

These filters successfully trigger:

```
      filters:
        data:
          - path: headers.Accept
            type: string
            value:
              - ".*"
          - path: body.ref
            type: string
            value:
              - "refs/heads/master"
```

(Note that it seems to be called "headers" rather than "header" as the documentation suggests...)

These do not:

```
      filters:
        data:
          - path: headers.X-GitHub-Event
            type: string
            value:
              - ".*"
          - path: body.ref
            type: string
            value:
              - "refs/heads/master"
```
