### ISSUE TITLE
Support for multiple Github repositories to use the same Event

### ISSUE THREAD

**Issue by Hunter-Thompson** [argoproj/argo-events#1091]
**Is your feature request related to a problem? Please describe.**

For every repository in Github that I want a webhook for - I have to create a new Event since a single Event holds only a single repository. e.g

```
    pull_request:
      owner: example
      repository: demo-api-1  # <- Over here
      webhook:
        endpoint: /npm-pr
        port: "13000"
        method: POST
        url: https://example.com
      events:
        - "pull_request"
      apiToken:
        name: github-access
        key: token
      webhookSecret:
        name: github-access
        key: secret
      active: true
      contentType: json
  ```

**Describe the solution you'd like**

It would be great to be able to have a comma-delimited list of repos in the event instead of having only a single repo per event. e.g solution :

```
    pull_request:
      owner: example
      repository: demo-api-1, demo-api-2    <- Over here
      webhook:
        endpoint: /npm-pr
        port: "13000"
        method: POST
        url: https://example.com
      events:
        - "pull_request"
      apiToken:
        name: github-access
        key: token
      webhookSecret:
        name: github-access
        key: secret
      active: true
      contentType: json
 ```

**Describe alternatives you've considered**

[This](https://github.com/argoproj/argo-events/issues/976#issuecomment-757516121) comment offers a few workarounds, but, none of them are scalable solutions to this issue. 

**Additional context**

This feature is very useful when multiple repos are going to be using the same event.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
