### ISSUE TITLE
Argo events with calendar will result in Error due to lack of permission

### ISSUE THREAD

**Issue by MadDoxXimba** [argoproj/argo-events#1106]
**Describe the bug**

Following the documentation step by step will cause workflow triggered by an event into an error.

**To Reproduce**

```sh
kubectl create ns argo-events
kubectl ns argo-events
# same applies for master branch
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-workflows/v3.0.0-rc6/manifests/namespace-install.yaml
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/v1.2.3/manifests/namespace-install.yaml
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/v1.2.3/examples/eventbus/native.yaml
```

This is due to triggered workflow are executed under argo-events:default where default is the serviceaccount (and not configured)

Installing this service account fix the issue for me:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
  - patch
  - create
 ```

Used sensor and source event:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: calendar
spec:
  calendar:
    example-with-interval:
      schedule: "* * * * *"
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: calendar
spec:
  template:
    serviceAccountName: argo
  dependencies:
    - name: test-dep
      eventSourceName: calendar
      eventName: example-with-interval
  triggers:
    - template:
        name: calendar-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: calendar-workflow-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # value will get overridden by the event payload
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.arguments.parameters.0.value
```

**Expected behavior**

Succeed

**Screenshots**

**Environment (please complete the following information):**
 - minikube version: v1.17.1 
 - Argo: 3.0.0-rc-6 and master branch
 - Argo Events: 1.2.3 and master f667f532946b4f8b2248294db4b72d0a1dcb56dc

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
