### ISSUE TITLE
Customise the Github Event for Argo Events

### ISSUE THREAD

**Issue by avinashkumar1289** [argoproj/argo-events#1110]
I have a requirement that I need to look for only those github events when the pull request is created on a certain branch.
I don't see a way to customize the eventsource events.
What I am expecting is 

```
events:
         - pull_request:
             types: 
               - opened
              branches:
                - main
```
It will be good if eventsource can handle that otherwise we will end of triggering the sensor even if its not required and our trigger will have to handle the types and branches.
