### ISSUE TITLE
Ability to apply webhook data to Workflow labels for improved filtering

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-events#1113]
**Is your feature request related to a problem? Please describe.**
I would like to be able to take the contents of a Github webhook and apply the values as lables to the triggered workflow. 

The reason we'd use this is we use multiple repos, but link branch names across them. By setting the branch name as a workflow label and being able to filter by branch name in the Argo Workflows UI instantly gives us the visibility of build success/failure that we need.

Because metadata.labels sits above the .spec, there currently seems to be no way to apply these values.

**Describe the solution you'd like**
We already have a solution to set prometheus labels by dataKey, I'm requesting if we can increase the scope so that we could also set workflow labels in the same way.

**Describe alternatives you've considered**
I have tried to use Metrics as an alternative, but this is an antipattern and won't scale. It also takes users away from the Argo ui and towards something like Grafana. Similarly using the workflowMetadata option from Argo Workflows, but it seems one can't populate this with webhook data either.

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
I think this can be done by using parameter to set the labels. For example, https://github.com/argoproj/argo-events/blob/master/examples/sensors/aws-sns.yaml#L45, use `metadata.labels.xxx`.

**Comment by tim-sendible** [comment]
Thank you. This works after a bit of trial and error. The key is that 'xxx' isn't an array index, it's a named value for example given I have a label defined as such:

```
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                labels:
                  git_branch: ""
```

Then I need to set the parameter as follows:

```
            - src:
                dependencyName: pr
                dataKey: body.pull_request.head.ref
              dest: metadata.labels.git_branch
```
