### ISSUE TITLE
SQS Event Source does not properly log connection errors

### ISSUE THREAD

**Issue by delwaterman** [argoproj/argo-events#1114]
**Describe the bug**
When the SQS Event Source attempts to connect AWS SQS, it will return an error if there is an issue the connection. However, the error is never logged, because `StartListening` is run by [`common.Connect`](https://github.com/argoproj/argo-events/blob/master/eventsources/eventing.go#L344), the error is lost during retry steps, and the only error that appears in the logs is `failed to start listening eventsource`

**To Reproduce**
1. Create an SQS Event source 
    ```yaml
   apiVersion: argoproj.io/v1alpha1
   kind: EventSource
   metadata: 
     name: test-failing-sqs
   spec:
     sqs:
      sqs_message:
        jsonBody: true
        queue: does-not-exist
        region: us-east-1
    ```

2. Follow the logs of the event source pod

**Expected behavior**
An error log revealing the underlying issue.

**Environment (please complete the following information):**
 - Kubernetes: 1.16.15
 - Argo: 2.11.8
 - Argo Events: 1.1.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
