### ISSUE TITLE
Unsure of the best practice for a filter with multiple paths

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-events#1127]
**Describe the bug**
I've searched high and low but can't find a sensible approach for this.

Using a github webhook, I want to trigger a workflow when file(s) in a specific directory are added, removed or modified. The github webhook data will look something like this:

```
...
  "commits": [
    {
      "added": [
        "example/file"

      ],
      "removed": [
        "another/example"

      ],
      "modified": [
        "example/yetagain"
      ]
    }
  ],
...
```

I want to be able to write a filter like this that covers all these bases:
```
  dependencies:
    - name: modified
      eventSourceName: github
      eventName: github-argo-git-notifier
      filters:
        data:
          - path: 
              - body.commits.#.modified
              - body.commits.#.added
              - body.commits.#.removed
            type: string
            value:
              - "example/regex.+"
```
But I can't have an array under 'path'.
I can't have multiple filters because that is treated like an 'and' rather than an 'or'.
I can't have multiple dependencies beacuse I can't re-use the same event source name.

So I either have to duplicate the eventsource, which feels untidy and means I have to handle 3 of every github webhook - which doesn't scale, or have 3 sources for the same thing, which really doesn't scale, and I'm sure my workflows will go out of sync over time.

I'm really hoping that I'm just an idiot and there's a simple way round this.

I'm not really sure if this is a bug (in ether the software or documentation) or a question. I did try on Slack but got nothing useful.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
I think you have similar requirement to https://github.com/argoproj/argo-events/issues/1097, it will be achievable in next release, which is coming today.

**Comment by tim-sendible** [comment]
That does look promising @whynowy - will there be documentation to accompany the PR?

**Comment by tim-sendible** [comment]
I _believe_ that the following works for my requirements. If this is the case, please let me know and I'm happy to add an example or maybe enhance the documentation.

```
        data:
          - path: "[body.commits.#.modified.@flatten,body.commits.#.added.@flatten,body.commits.#.removed.@flatten].@flatten.@flatten"
            type: string
            value:
              - "example/regex.+"
```
