### ISSUE TITLE
Anti-affinity doesn't work

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-events#1137]
**Describe the bug**
When trying to apply anti-affinity in accordance with [the documentation](https://argoproj.github.io/argo-events/dr_ha_recommendations/#anti-affinity), the anti affinity rules are stripped from the deployed eventbus.

**To Reproduce**
1. Apply the following:
```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      replicas: 3
      auth: token
      persistence:
        storageClassName: gp2
        accessMode: ReadWriteOnce
        volumeSize: 5Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    controller: eventbus-controller
                    eventbus-name: default
                topologyKey: kubernetes.io/hostname
              weight: 100
```

2. Perform a kubectl get on the deployed eventbus to see what was deployed:

```
 apiVersion: argoproj.io/v1alpha1
 kind: EventBus
 metadata:
   finalizers:
   - eventbus-controller
   labels:
     app.kubernetes.io/instance: argo-events
   name: default
   namespace: argo-events
 spec:
   nats:
     native:
       auth: token
       persistence:
         accessMode: ReadWriteOnce
         storageClassName: gp2
         volumeSize: 5Gi
       replicas: 3
```

Anti affinity is stripped and therefore ignored at pod level.

**Expected behavior**
I expect to be able to copy/paste from the docs in order to achieve anti affinity.

**Screenshots**
**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.18.6] eks 1.19
 - Argo: [e.g. v2.9.4] 3.0 rc9
 - Argo Events: [e.g. v1.0.0] 3.0 rc1

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
