### ISSUE TITLE
Add top level boolean logic operator for signals

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#12]
**Is your feature request related to a problem? Please describe.**
With current Sensor spec, user can only use AND operator for multiple signals and it lacks support for complex signals circuiting. 

**Describe the solution you'd like**
Use "--" for OR operator and "-" for AND operator.

Example-
```
signals:
   -- name: time
      calender:
        interval: 10s
    - name: minioS3
      artifact:
        s3:
          bucket: hello
          endpoint: artifacts-minio.default:9000
          insecure: true
          accessKey:
            key: accesskey
            name: artifacts-minio
          secretKey:
            key: secretkey
            name: artifacts-minio
          event: s3:ObjectCreated:Put
          arn:
            partition: minio
            service: sqs
            region: us-east-1
            accountID: "1"
            resource: nats
        stream:
          nats:
            url: nats://example-nats-cluster:4222
            subject: bucketevents
   -- name: worklow-1
       resource:
         namespace: default
         group: "argoproj.io"
         version: "v1alpha1"
         kind: "Workflow"
         filter:
           prefix: scripts-bash
           labels:
             workflows.argoproj.io/phase: Succeeded 
      
```
