### ISSUE TITLE
Kafka event source: no active event server running and Kafka sensor: does not dispatch

### ISSUE THREAD

**Issue by MadDoxXimba** [argoproj/argo-events#1212]
**Describe the bug**

Hi, i'm testing out the kafka event source and kafka sensor examples: https://argoproj.github.io/argo-events/eventsources/setup/kafka. 

**Event Source**

```json
{"level":"info","ts":1620814014.4780571,"logger":"argo-events.eventsource","caller":"cmd/main.go:63","msg":"starting eventsource server","eventSourceName":"kafka","version":"vv1.3.0+7591146.dirty"}
{"level":"info","ts":1620814014.4782612,"logger":"argo-events.eventsource","caller":"metrics/metrics.go:172","msg":"starting metrics server","eventSourceName":"kafka"}
{"level":"info","ts":1620814014.4810283,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:122","msg":"Not the LEADER, stand by ...","eventSourceName":"kafka"}
{"level":"info","ts":1620814015.3544254,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:131","msg":"Becoming a Candidate, stand by ...","eventSourceName":"kafka"}
{"level":"info","ts":1620814015.355255,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:128","msg":"I'm the LEADER, starting ...","eventSourceName":"kafka"}
{"level":"info","ts":1620814015.3553903,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:309","msg":"Starting event source server...","eventSourceName":"kafka"}
{"level":"info","ts":1620814015.3563788,"logger":"argo-events.eventsource","caller":"driver/nats.go:93","msg":"NATS auth strategy: Token","eventSourceName":"kafka","clientID":"client-kafka-eventsource-g984s-58ff45bb8d-qpdgl-302"}
{"level":"info","ts":1620814015.3588736,"logger":"argo-events.eventsource","caller":"driver/nats.go:105","msg":"Connected to NATS server.","eventSourceName":"kafka","clientID":"client-kafka-eventsource-g984s-58ff45bb8d-qpdgl-302"}
{"level":"info","ts":1620814015.3620908,"logger":"argo-events.eventsource","caller":"driver/nats.go:118","msg":"Connected to NATS streaming server.","eventSourceName":"kafka","clientID":"client-kafka-eventsource-g984s-58ff45bb8d-qpdgl-302"}
{"level":"info","ts":1620814015.3621883,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:422","msg":"Eventing server started.","eventSourceName":"kafka"}
{"level":"info","ts":1620814015.3622308,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:332","msg":"starting eventbus connection daemon...","eventSourceName":"kafka"}
{"level":"info","ts":1620814015.362501,"logger":"argo-events.eventsource","caller":"kafka/start.go:78","msg":"start kafka event source...","eventSourceName":"kafka","eventSourceType":"kafka","eventName":"example"}
{"level":"info","ts":1620814015.3625581,"logger":"argo-events.eventsource","caller":"kafka/start.go:161","msg":"start kafka event source...","eventSourceName":"kafka","eventSourceType":"kafka","eventName":"example"}
{"level":"info","ts":1620814015.3625734,"logger":"argo-events.eventsource","caller":"kafka/start.go:165","msg":"connecting to Kafka cluster...","eventSourceName":"kafka","eventSourceType":"kafka","eventName":"example"}
{"level":"info","ts":1620814015.389459,"logger":"argo-events.eventsource","caller":"kafka/start.go:186","msg":"parsing the partition value...","eventSourceName":"kafka","eventSourceType":"kafka","eventName":"example","partition-id":"1"}
{"level":"info","ts":1620814015.3895614,"logger":"argo-events.eventsource","caller":"kafka/start.go:193","msg":"getting available partitions...","eventSourceName":"kafka","eventSourceType":"kafka","eventName":"example","partition-id":"1"}
{"level":"info","ts":1620814015.6654599,"logger":"argo-events.eventsource","caller":"kafka/start.go:199","msg":"verifying the partition exists within available partitions...","eventSourceName":"kafka","eventSourceType":"kafka","eventName":"example","partition-id":"1"}
{"level":"error","ts":1620814015.6655567,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:439","msg":"Erroring out, no active event server running","eventSourceName":"kafka","stacktrace":"github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:439\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:295"}
{"level":"info","ts":1620814015.665716,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:337","msg":"exiting eventbus connection daemon...","eventSourceName":"kafka"}
{"level":"error","ts":1620814015.6686988,"logger":"argo-events.eventsource","caller":"driver/nats.go:84","msg":"NATS connection lost","eventSourceName":"kafka","clientID":"client-kafka-eventsource-g984s-58ff45bb8d-qpdgl-302","stacktrace":"github.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).Connect.func1\n\t/home/runner/work/argo-events/argo-events/eventbus/driver/nats.go:84\ngithub.com/nats-io/nats%2ego.(*Conn).close.func1\n\t/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:3802\ngithub.com/nats-io/nats%2ego.(*asyncCallbacksHandler).asyncCBDispatcher\n\t/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2082"}
{"level":"error","ts":1620814015.6687121,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:296","msg":"failed to start","eventSourceName":"kafka","error":"no active event server running","errorVerbose":"no active event server running\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:442\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:295\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.14.15/x64/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:296"}
```
**Sensor**

Does not dispatch:

```yaml
Name:         kafka
Namespace:    kast
Labels:       <none>
Annotations:  <none>
API Version:  argoproj.io/v1alpha1
Kind:         Sensor
Metadata:
  Creation Timestamp:  2021-05-12T10:40:34Z
  Finalizers:
    sensor-controller
  Generation:  1
  Managed Fields:
    API Version:  argoproj.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:dependencies:
        f:template:
        f:triggers:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-05-12T10:40:34Z
    API Version:  argoproj.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"sensor-controller":
      f:status:
        .:
        f:conditions:
    Manager:         sensor-controller
    Operation:       Update
    Time:            2021-05-12T10:40:34Z
  Resource Version:  2812
  UID:               995b1b94-ca80-4976-8df1-062b984b7981
Spec:
  Dependencies:
    Event Name:         example
    Event Source Name:  kafka
    Name:               test-dep
  Template:
    Service Account Name:  operate-workflow-sa
  Triggers:
    Template:
      k8s:
        Group:      argoproj.io
        Operation:  create
        Parameters:
          Dest:  spec.arguments.parameters.0.value
          Src:
            Dependency Name:  test-dep
        Resource:             workflows
        Source:
          Resource:
            API Version:  argoproj.io/v1alpha1
            Kind:         Workflow
            Metadata:
              Generate Name:  kafka-workflow-
            Spec:
              Arguments:
                Parameters:
                  Name:    message
                  Value:   hello world
              Entrypoint:  whalesay
              Templates:
                Container:
                  Args:
                    {{inputs.parameters.message}}
                  Command:
                    cowsay
                  Image:  docker/whalesay:latest
                Inputs:
                  Parameters:
                    Name:  message
                Name:      whalesay
        Version:           v1alpha1
      Name:                kafka-workflow-trigger
Status:
  Conditions:
    Last Transition Time:  2021-05-12T10:40:34Z
    Status:                True
    Type:                  DependenciesProvided
    Last Transition Time:  2021-05-12T10:40:34Z
    Status:                True
    Type:                  Deployed
    Last Transition Time:  2021-05-12T10:40:34Z
    Status:                True
    Type:                  TriggersProvided
Events:                    <none>
```

**controller logs**

```json
{"level":"info","ts":1620813891.9073696,"logger":"argo-events.sensor-controller","caller":"cmd/main.go:135","msg":"starting sensor controller","version":"vv1.3.0+7591146.dirty"}
{"level":"info","ts":1620816034.977807,"logger":"argo-events.sensor-controller","caller":"sensor/resource.go:107","msg":"deployment is created","namespace":"kast","sensor":"kafka","deploymentName":"kafka-sensor-hvqbn"}
```

**To Reproduce**

Used minikube as POC environment.

**Kafka installation**

https://strimzi.io/docs/operators/in-development/quickstart.html#assembly-evaluation-str

Tried on argo-events and eventbus:
-  namespace installation
-  cluster-wide installation

**Expected behavior**
Events are published to event source and kafka sensor is dispatched

**Screenshots**

1. missing kafka sensor pod
2. wrong status for kafka-eventsource?

```sh
$ kubectl get pods

NAME                                       READY   STATUS    RESTARTS   AGE
argo-server-6fb6d4b7fb-2lq5l               1/1     Running   0          8m19s
eventbus-controller-96f86d586-nd52t        1/1     Running   0          8m33s
eventbus-default-stan-0                    2/2     Running   0          8m21s
eventbus-default-stan-1                    2/2     Running   0          8m6s
eventbus-default-stan-2                    2/2     Running   0          8m4s
eventsource-controller-5b9b5dd4b-6t96h     1/1     Running   0          8m33s
kafka-eventsource-97lqq-7f9dc97bfc-8gjtt   1/1     Running   0          5m54s
sensor-controller-77dbfb77bf-4hn8j         1/1     Running   0          8m33s
workflow-controller-d9cbfcc86-l2r8v        1/1     Running   0          8m19s

```

**Environment (please complete the following information):**
 - Minikube: v1.18.1
 - Argo: v3.0.2
 - Argo Events: v1.3.0 v1.3.1

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
