### ISSUE TITLE
Can't create namespace k8s object

### ISSUE THREAD

**Issue by ptzool** [argoproj/argo-events#1219]
I created a Sensor that contains a K8s object template. The template will create a namespace. But when I called the webhook a got the following error message.

argo: v3.0.3
argo-events: v1.3.1

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: dps-namespace-create
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: dps-namespace-webhook-dep
      eventSourceName: dps-namespace-webhook
      eventName: dps
  triggers:
    - template:
        name: create-namespace
        k8s:
          group: ""
          version: v1
          resource: namespaces
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Namespace
          parameters:
            - src:
                dependencyName: dps-namespace-webhook-dep
                dataKey: body.namespace
              dest: metadata.name
```

```
  "error": "Failed to execute trigger: timed out waiting for the condition: the server could not find the requested resource",
  "errorVerbose": "timed out waiting for the condition: the server could not find the requested resource\nfailed to execute trigger\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerOne\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:328\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:269\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents.func1.3\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:181\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.14.15/x64/src/runtime/asm_amd64.s:1373",
```

It doesn’t seem to be possible to create a namespace, regardless of whether or not you parameterize the name. For example, even this doesn’t work:

```
- template:
    name: test
    k8s:
      group: ""
      version: v1
      resource: namespaces
      operation: create
      source:
        resource:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: test
```
