### ISSUE TITLE
Introduce expression filters for events

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#1224]
**Is your feature request related to a problem? Please describe.**
The sensor event dependencies currently have data, context, and time filters which offer a limited set of filtering capabilities. Introduce a more powerful filter where the user can define an expression/s that are flexible enough to address every usecase.

**Describe the solution you'd like**
Add a new filter called `exprFilters`

```
exprFilters:
    - fields:
        - path: height
          name: field1
          type: number
        - path: weight
          name: field2
          type: number
      expr: (field2 / (field1 * field1)) > 20
    - fields:
        - path: weight
          name: field1
          type: number
      expr: field1 > 70
      name: filter2
  circuit: filter1 || filter2
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
