### ISSUE TITLE
 GatewaySpec should support imagePullSecrets

### ISSUE THREAD

**Issue by twiechert** [argoproj/argo-events#123]
**Describe the bug**
The `imagePullSecrets` entry is not supported in the GatewaySpec. This spec is used to define the webhook gateway configmap that will eventually lead to a deployment creation.

This fails, if images must be pulled from a registry that requires authentication. Currently, there does not seem to be a way to set the required field.

**To Reproduce**
Pull image from a registry proxy that requires authentication and pass `imagePullSecrets`:

```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: {{.component}}-webhook-gateway
  namespace: {{.namespace}}
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
    gateway-name: "{{.component}}-webhook-gateway"
spec:
  configMap: {{.component}}-webhook-gateway-configmap
  type: webhook
  dispatchMechanism: "HTTP"
  version: "1.0"
  deploySpec:
    imagePullSecrets:
      - name: {{.artifactoryStore}}
    containers:
    - name: {{.component}}-webhook-events
      image: OUR_SECURE_REGISTRY/argoproj/webhook-gateway
      imagePullPolicy: "IfNotPresent"
      command: ["/bin/webhook-gateway"]
```

**Expected behavior**
Field should be used in deployment creation to properly trigger registry authentication.
