### ISSUE TITLE
sensor parameter destination name instead of index

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-events#1230]
Is it possible to use the parameter names instead of index 0, 1, ..., etc?

e.g.
```spec.arguments.parameters.repo.value``` instead of ```spec.arguments.parameters.0.value```

```
parameters:
  - src:
      dependencyName: test-dep
      dataKey: body.pull_request.head.repo.clone_url
    dest: spec.arguments.parameters.0.value
  - src:
      dependencyName: test-dep
      dataKey: body.pull_request.head.ref
    dest: spec.arguments.parameters.1.value
```
