### ISSUE TITLE
Trigger's default parameter value not being applied

### ISSUE THREAD

**Issue by atombender** [argoproj/argo-events#1238]
I have a sensor with two dependencies in an `||`. When one dependency triggers, I want to ensure that the other dependency's parameter has a default value.

Here's my sensor, simplified:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  dependencies:
  - name: dep1
    eventSourceName: github
    eventName: dep1
    filters:
      data:
      - {path: body.check_suite.app.external_url, type: string, comparator: "=", value: ["https://circleci.com"]}
      - {path: body.check_suite.conclusion, type: string, comparator: "=", value: [success]}
  - name: dep2
    eventSourceName: github
    eventName: dep2
    filters:
      data:
      - {path: body.check_suite.app.external_url, type: string, comparator: "=", value: ["https://circleci.com"]}
      - {path: body.check_suite.conclusion, type: string, comparator: "=", value: [success]}

  triggers:
  - template:
      name: argo-workflow-trigger
      conditions: "dep1 || dep2"
      k8s:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: create

        parameters:
        - src:
            dependencyName: dep1
            dataKey: body.check_suite.head_sha
            value: main
          dest: spec.arguments.parameters.0.value
        - src:
            dependencyName: dep2
            dataKey: body.check_suite.head_sha
            value: main
          dest: spec.arguments.parameters.1.value

        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              labels:
                workflows.argoproj.io/archive-strategy: "false"
            spec:
              entrypoint: main
              arguments:
                parameters:
                - name: dep1_commit
                  value: main
                - name: dep2_commit
                  value: main
              workflowTemplateRef:
                name: test
```

If the sensor triggers on `dep1` or `dep2`, the `dataKey` is successfully extracted and stored in the right workflow parameter. However, the other parameter becomes empty, despite the fact that there is a `value` set on the `src`.

As you can see, I also tried providing a default value in the workflow's `parameters`, but the value still becomes empty.

Looking at the documentation, there's a discrepancy between the API docs and the guide. The [API docs](https://github.com/argoproj/argo-events/blob/master/api/sensor.md) say (my emphasis):

> Value is the default literal value to use for this parameter source **This is only used if the DataKey is invalid**. If the DataKey is invalid and this is not defined, this param source will produce an error.

The [parameterization tutorial](https://argoproj.github.io/argo-events/tutorials/02-parameterization/#default-values), on the other hand, suggests that `value` is used as a default value if the `dataKey` data is missing.

There's nothing in the sensor log about failing to read the event data, even though the code (from what I can read [here](https://github.com/argoproj/argo-events/blob/f47cb23c421fb8b423114b028d5da5efd4e39de4/sensors/triggers/params.go#L191)) should complain.

This leads me to think that maybe the dependency data logic _isn't_ executed if the dependency didn't trigger. In other words, with a conditions list like `dep1 || dep2`, then if `dep1` triggers, the parameter section for `dep2` is ignored and no value is set. However, it looks like `ResolveParamValue()` will not resolve anything if the event does not contain all dependencies.

~Using 1.2.0. I don't see anything relevant in the git log since then.~ Version 1.3.1.
