### ISSUE TITLE
Annotations in Argo Gateway Definition should be inherited by Deployment Template

### ISSUE THREAD

**Issue by twiechert** [argoproj/argo-events#125]
**Is your feature request related to a problem? Please describe.**
We need to add annotations to the implicitly created gateway deployments. However, neither the ``GatewaySpec``type supports annotations nor get the annotations on the Argo Gateway definition automatically passed to the deployment.

**Describe the solution you'd like**
When defining a gateway such as:
```
---
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: {{.component}}-webhook-gateway
  namespace: {{.namespace}}
  annotations:
    sidecar.istio.io/inject: "true"
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: {{.component}}
    gateway-name: "{{.component}}-webhook-gateway"
spec:
  configMap: {{.component}}-webhook-gateway-configmap
  type: webhook
  dispatchMechanism: "HTTP"
  transformerImage: argoproj/gateway-http-transformer
  version: "1.0"
  deploySpec:
    containers:
      - ...
    serviceAccountName: {{.component}}-sa
    imagePullSecrets:
      - name: {{.artifactoryStore}}

  serviceSpec:
    ...
```
it would be desired if the set of annotations get automatically passed to the created deployment.
