### ISSUE TITLE
Support Argo resume/stop node field selectors

### ISSUE THREAD

**Issue by lacarvalho91** [argoproj/argo-events#1257]
**Is your feature request related to a problem? Please describe.**

Using Argo CLI to resume via the `argoWorkflow` trigger as documented [here](https://argoproj.github.io/argo-events/sensors/triggers/argo-workflow/#argo-cli) does not support the use of [node field selectors](https://argoproj.github.io/argo-workflows/node-field-selector/).

**Describe the solution you'd like**

I would like it to be possible to configure node field selectors when using the `argoWorkflow` trigger template.

**Describe alternatives you've considered**
n/a

**Additional context**

As seen [here](https://github.com/argoproj/argo-events/blob/master/sensors/triggers/argo-workflow/argo-workflow.go#L162) only the Workflow name can be passed in.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by lacarvalho91** [comment]
Thinking this could be done by adding an `args` field? e.g.

```
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: resume
          args: ["--node-field-selector=inputs.parameters.foo.value=bar"]
```

Then we can reuse it for other commands e.g. field selector on stop command.
