### ISSUE TITLE
Allow to run workflows in other namespace than trigger namespace

### ISSUE THREAD

**Issue by twiechert** [argoproj/argo-events#126]
**Is your feature request related to a problem? Please describe.**
It should be possible to let the workflows be executed in other namespaces than the one the respective trigger is deployed in. The current implementation will create the workflow pods in the same namespace as the trigger.

**Describe the solution you'd like**
Allow for  a namespace entry in the workflow part of the trigger spec. 
```
      source:
        inline: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: hello-world-workflow-
            namespace: dev
```
It would be desirable if the namespace entry is respected and the workflow pods created in the ``dev``namespace .

**Additional context**
Argo and Argo Events are deployed in a dedicated Argo namespace but you want to deploy the actual workflows in a user namespace.

**Comment by VaibhavPage** [comment]
You can deploy sensor in one namespace and the trigger/workflow in separate namespace. There is no trigger pod but trigger spec is rather used to understand which K8 resource needs to be triggered, in this case an argo workflow

**Comment by VaibhavPage** [comment]
I see that namespace in `resource` spec is set to {{.namespace}}, which should be set to `dev` to deploy workflow in `dev` namespace.

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{.component}}-webhook-sensor
  namespace: {{.namespace}}
  annotations:
    sidecar.istio.io/inject: "true"
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: {{.component}}
spec:
  repeat: true
  serviceAccountName: {{.component}}-sa
  sensorImage: {{.sensorImage}}
  imagePullSecrets:
  - name: {{.artifactoryStore}}
  signals:
  - name: {{.component}}-webhook-gateway/webhook.fooConfig
  triggers:
  - name: {{.component}}-webhook-workflow-trigger
    resource:
      namespace: dev
      group: argoproj.io
      version: v1alpha1
      kind: Workflow
      parameters:
        - src:
            signal: {{.component}}-webhook-gateway/webhook.fooConfig
            path: message
            value: hello default
          dest: spec.arguments.parameters.0.value
      source:
        inline: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: hello-world-workflow-
            namespace: dev
          spec:
            entrypoint: whalesay
            imagePullSecrets:
              - name: {{.artifactoryStore}}
            arguments:
              parameters:
              - name: message
                value: "hello world"
            templates:
            - name: whalesay
              inputs:
                parameters:
                - name: message
              container:
                image: "{{.workflowImage}}"
                command: [cowsay]
                args: ["{{"{{inputs.parameters.message}}"}}"]
```
