### ISSUE TITLE
Allow to overrride TransformerImage and SensorImage

### ISSUE THREAD

**Issue by twiechert** [argoproj/argo-events#127]
**Is your feature request related to a problem? Please describe.**
Currently, these images are coded into the Argo Event sources  and there is no way to override these. Also, it is not possible to pass ImagePullSecrets. 

**Describe the solution you'd like**
- have an entry SensorImage in the SensorSpec
- let the sensor controller respect this entry
- add ability to pass ImagePullSecrets to sensoer deployment creation
- thus also have entry ``ImagePullSecrets``in SensorSpec

**Additional context**
Firstly, we need to fetch the image from our own corporate registry. Thus, we need to specify the registry prefix. Secondly, the  obtained from the official Docker registry seems to be broken. We had to rebuild the webhook-gateway and the transformer in order to make it work.

**Comment by VaibhavPage** [comment]
In case of sensor specs - Instead of adding separate fields for ImagePullSecrets and Image name etc,  we can provide something like `deploySpec` which is the complete pod spec.

For Transformer Image - we can add a field called `transformerImage` in gateway spec

**Comment by twiechert** [comment]
This sounds reasonable, we would appreciate it.

**Comment by antoinetran** [comment]
Hi @VaibhavPage , I think this issue neds to be opened again. The solution presented here is to override deploySpec like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  repeat: true
  deploySpec:
    containers:
    - name: sensor
      image: "argoproj/sensor:v0.6"
      imagePullPolicy: "Always"
      command: ["/bin/sensor"]
```
However this has changed in https://github.com/argoproj/argo-events/blob/v0.9.1/examples/sensors/webhook.yaml to:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    # do not remove
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
```
The deploySpec has been changed to spec.containers, until https://github.com/argoproj/argo-events/blob/v0.15.0/examples/sensors/webhook.yaml. At this point the container override simply disappeared.

My use case is the same as this topic author: change the registry server and to add a imagePullSecrets. Anyway to do that in latest version v1.7.6?
