### ISSUE TITLE
Allow SSL connections to Kafka, even when not using TLS authentication

### ISSUE THREAD

**Issue by signaleleven** [argoproj/argo-events#1277]
**Is your feature request related to a problem? Please describe.**

The kafka library used by argo-events supports SASL_SCRAM authentication over an SSL connection. See for instance https://github.com/Shopify/sarama/blob/master/examples/sasl_scram_client/main.go

However, when configuring an EventSource for kafka like in the snippet below, the Eventsource pod attempts to connect to Kafka in Plaintext.

```yaml
 kafka:
    cdm:
      url: blahblah-msk-endpoint.eu-central-1.amazonaws.com:9096
      topic: test
      jsonBody: true
      # partition id
      partition: "1"
      # optional backoff time for connection retries.
      # if not provided, default connection backoff time will be used.
      connectionBackoff:
        # duration in nanoseconds, or strings like "3s", "2m". following value is 10 seconds
        duration: 1000000000 # "10s" is reported invalid here, but that's another issue
        # how many backoffs
        steps: 5
        factor: 2
        jitter: 0.2
     # tls: TLS IS NOT the answer. TLS enables an SSL connection, but it's for client authentication using SSL. Something that MSK supports only with a very expensive private CA. AWS, amirite? 🤷 
      sasl:
        mechanism: SCRAM-SHA-512
        passwordSecret:
          key: password
          name: kafkauser
        userSecret:
          key: user
          name: kafkauser
```
```
namespace=orekit-fetcher, eventSourceName=kafka, eventSourceType=kafka, eventName=cdm, level=info, time=2021-07-14T16
:14:23Z, msg=start kafka event source...
namespace=orekit-fetcher, eventSourceName=kafka, eventSourceType=kafka, eventName=cdm, level=info, time=2021-07-14T16
:14:23Z, msg=connecting to Kafka cluster...
namespace=orekit-fetcher, eventSourceName=kafka, eventSourceType=kafka, eventName=cdm, level=error, time=2021-07-14T1
6:14:23Z, msg=failed to start listening eventsource
namespace=orekit-fetcher, eventSourceName=kafka, level=error, time=2021-07-14T16:14:23Z, msg=Erroring out, no active
event server running
namespace=orekit-fetcher, eventSourceName=kafka, level=info, time=2021-07-14T16:14:23Z, msg=exiting eventbus connecti
on daemon...
namespace=orekit-fetcher, eventSourceName=kafka, level=error, time=2021-07-14T16:14:23Z, msg=failed to start
namespace=orekit-fetcher, eventSourceName=kafka, level=error, time=2021-07-14T16:14:23Z, msg=NATS connection lost
```
 
AWS MSK does not allow to set up SASL_SCRAM while allowing plaintext connections, therefore I cannot connect to my MSK cluster with an EventSource.

**Describe the solution you'd like**
I believe Sarama allows to configure a TLS socket, without client authentication (but optional server certificate validation). However, there is no way, that I could find, to configure an EventSource to connect to Kafka with TLS, when not using TLS authentication.

**Describe alternatives you've considered**
I'm considering temporarily dropping TLS and Authentication in MSK to continue integrating argo-events with our systems, but that's not how I'd like to run in production.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@signaleleven - would you like to file a PR for it?

**Comment by signaleleven** [comment]
I've never written go code, and I don't know if I'd be able to. 
If I do try, I'll mention here that I started the effort. Meanwhile, if somebody with a ready dev setup for argo-events wants to try, it's up for grabs.

**Comment by whynowy** [comment]
@signaleleven - I assume allowing both sasl and tls to be configured together will solve the issue, correct?

**Comment by whynowy** [comment]
> @signaleleven - I assume allowing both sasl and tls to be configured together will solve the issue, correct?

Just checked the code, we actually already allow both sasl and tls configured together, could you try that?

**Comment by signaleleven** [comment]
AFAICT, TLS here implies using a client certificate for authentication. I do not want that. I want to make an SSL connection to the kafka cluster, but without providing a client certificate and key. Only the server has a SSL certificate.

And this seems to require a client secret.
https://github.com/argoproj/argo-events/blob/d19cb22c4b67dcd993c362b9c6310f29b035037a/common/util.go#L213

I didn't try to provide an empty one...

**Comment by signaleleven** [comment]
Oh maybe I see where I got confused. I will try.

**Comment by whynowy** [comment]
@signaleleven - I'm also confused 😐 , I don't have a kafka server with the setting like you mentioned handy, please let me know if you find anything.

**Comment by whynowy** [comment]
@signaleleven - I'm also confused 😐 , I don't have a kafka server with settings like you mentioned handy, please let me know if you find anything.

**Comment by usamaB** [comment]
Did this thing work?

**Comment by usamaB** [comment]
I have the same issue, We have MSK with SASL/SSL. And I'm unable to connect to it.  Any fix to this?
https://github.com/Shopify/sarama/issues/1944
The sarama library doesn't have this option I suppose.


Here are my logs with consumerGroup. If I use partitions the "Kafka client run out of available brokers" isn't there but still timed out. 
`{"level":"info","ts":1641920166.4959314,"logger":"argo-events.eventsource","caller":"kafka/start.go:78","msg":"start kafka event source...","eventSourceName":"kafka","eventSourceType":"kafka","eventName":"example"}                                                       │
│ {"level":"error","ts":1641920167.3069851,"logger":"argo-events.eventsource","caller":"kafka/start.go:119","msg":"Error creating consumer group client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","eventSourceName":"kafka","ev │
│ {"level":"info","ts":1641920167.3070822,"logger":"argo-events.eventsource","caller":"kafka/start.go:78","msg":"start kafka event source...","eventSourceName":"kafka","eventSourceType":"kafka","eventName":"example"}                                                       │
│ {"level":"error","ts":1641920168.1086795,"logger":"argo-events.eventsource","caller":"kafka/start.go:119","msg":"Error creating consumer group client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","eventSourceName":"kafka","ev │
│ {"level":"info","ts":1641920168.1088238,"logger":"argo-events.eventsource","caller":"kafka/start.go:78","msg":"start kafka event source...","eventSourceName":"kafka","eventSourceType":"kafka","eventName":"example"}                                                       │
│ {"level":"error","ts":1641920168.9209,"logger":"argo-events.eventsource","caller":"kafka/start.go:119","msg":"Error creating consumer group client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","eventSourceName":"kafka","event │
│ {"level":"info","ts":1641920168.9210088,"logger":"argo-events.eventsource","caller":"kafka/start.go:78","msg":"start kafka event source...","eventSourceName":"kafka","eventSourceType":"kafka","eventName":"example"}                                                       │
│ {"level":"error","ts":1641920169.7508693,"logger":"argo-events.eventsource","caller":"kafka/start.go:119","msg":"Error creating consumer group client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","eventSourceName":"kafka","ev │
│ {"level":"error","ts":1641920169.7509682,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:417","msg":"failed to start listening eventsource","eventSourceName":"kafka","eventSourceType":"kafka","eventName":"example","error":"timed out waiting for t │
│ {"level":"error","ts":1641920169.7510505,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:440","msg":"Erroring out, no active event server running","eventSourceName":"kafka","stacktrace":"github.com/argoproj/argo-events/eventsources.(*EventSourceA │
│ {"level":"info","ts":1641920169.7510972,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:338","msg":"exiting eventbus connection daemon...","eventSourceName":"kafka"}                                                                                  │
│ {"level":"error","ts":1641920169.769013,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:296","msg":"failed to start","eventSourceName":"kafka","error":"no active event server running","errorVerbose":"no active event server running\ngithub.com/arg │
│ {"level":"error","ts":1641920169.7691605,"logger":"argo-events.eventsource","caller":"driver/nats.go:84","msg":"NATS connection lost","eventSourceName":"kafka","clientID":"client-kafka-eventsource-glsrl-56f6f5857b-zfmc5-443","stacktrace":"github.com/argoproj/argo-even │
│                                                                                                                                                                                                                           `

**Comment by usamaB** [comment]
```
spec:
  kafka:
    example:
      url: "blahblah-msk-endpoint.eu-central-1.amazonaws.com:9096"
      topic: test
      jsonBody: true
      partition: 1
      connectionBackoff:
        duration: 10s
        steps: 5
        factor: 2
        jitter: 0.2
##    Enable SASL authentication (not to be used with TLS)
      sasl:
        mechanism: SCRAM-SHA-512
        passwordSecret:
          key: kafka-akhq
          name: team-secrets
        userSecret:
          key: user
          name: kafka-user-secret

```
