### ISSUE TITLE
401 Invalid Authorization Header error when using generic webhook EventSource to create github webhook at org level

### ISSUE THREAD

**Issue by YesemKebede** [argoproj/argo-events#1289]
**Describe the bug**
I am currently attempting to create a github webhook at github organization level using a generic webhook eventSource. I am using webhook eventsource since github eventSource only create webhook under repository level. My use case involves listning in for organizational events such as repository creating and deletion. I am able to successfully send post request via curl to the generic webhook eventsource. However, when I create a webhook on github that send events to the eventSource, it returns 401 Invalid Authorization Header error. It works fine when I remove the authSecret from the webhook eventSource. It seems like the eventSource fails to authenticate post requests coming from github because of the format of the post request. 

**To Reproduce**
1. Create secret in k8s
`kubectl create secret generic github-auth-secret --from-file=webhook=./token.txt`
2. Create generic webhook, 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: generic-webhook
spec:
  service:
    ports:
      - port: 80
        targetPort: 12000
  webhook:
    cleanup_repository:
      endpoint: "/cleanup"
      port: "12000"
      method: "POST"
      authSecret:
         name: github-auth-secret
         key: webhook
``` 
3. create webhook at github org level, I have tried multiple ways to provide the secret and have gotten the same error
![image](https://user-images.githubusercontent.com/47124628/127324289-5701c29d-98da-46fd-9fa7-aae179b1bdd6.png)

4. setup eventBus
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native: {}
```
5. create sensor
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: create-pod-sa # A service account has privileges to create a Pod
  dependencies:
    - name: generic-webhook
      eventSourceName: generic-webhook
      eventName: generic-webhook
  triggers:
    - template:
        name: webhook-pod-trigger
        k8s:
          group: ""
          version: v1
          resource: pods
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: hello-world-
              spec:
                containers:
                  - name: hello-container
                    args:
                      - "hello-world"
                    command:
                      - cowsay
                    image: "docker/whalesay:latest"
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.containers.0.args.0
```
6. Github webhook returns 401 Invalid Authorization Header

here is the error from eventSource pod
```
{"level":"error","ts":1627477069.6458514,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:140","msg":"invalid auth header","eventSourceName":"generic-webhook","eventSourceType":"webhook","eventName":"cleanup_repository","eventSourceName":"generic-webhook","eventName":"cleanup_repository","stacktrace":"github.com/argoproj/argo-events/eventsources/common/webhook.startServer.func2\n\t/home/runner/work/argo-events/argo-events/eventsources/common/webhook/webhook.go:140\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.14.15/x64/src/net/http/server.go:2041\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212\nnet/http.serverHandler.ServeHTTP\n\t/opt/hostedtoolcache/go/1.14.15/x64/src/net/http/server.go:2836\nnet/http.(*conn).serve\n\t/opt/hostedtoolcache/go/1.14.15/x64/src/net/http/server.go:1924"}

```
**Expected behavior**
The post request from github should authenticate and return 200

**Environment**
 - Kubernetes: v1.20.4-eks-6b7464
 - Argo Events: 1.3.1
 

**Additional context**
We use ambassador as api gateway and Cloudflare as DNS provider
