### ISSUE TITLE
EventSource (and Sensor) for multiple Gitlab Repos

### ISSUE THREAD

**Issue by bygui86** [argoproj/argo-events#1290]
**Describe the bug**
What's the best way/practice to have a single EventSource listening to multiple GitLab repos? While Sensor could run a different Workflow depending on the repo specifications (e.g. languages)? 

With the help of the examples [here](https://github.com/argoproj/argo-events/blob/master/examples/event-sources/gitlab.yaml) and documentation [here](https://github.com/argoproj/argo-events/blob/master/api/event-source.md#gitlabeventsource) (and something from Argo Workflows as well), I currently have a CI pipeline for a single GitLab repo with EventSource, Sensor and Workflow working together. 

"Creating individual EventSource and Sensor for every repo that requires a CI pipeline" could lead to a lot of boilerplate which is hard to manage and update. 
Also I believe each EventSource object will lead to a service and a deployment which could lead to a lot of resources consumption on Kubernetes cluster. 

**Expected behavior**
Something similar to GitHub, like under `repositories` in [this example](https://github.com/argoproj/argo-events/blob/master/examples/event-sources/github.yaml)

**Environment (please complete the following information):**
 - Kubernetes:   v1.19.9.gke-1900
 - Argo:   3.1.3
 - Argo Events:   1.4.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by paolocarta** [comment]
I find this issue really interesting. It would be great having a single event source for multiple gitlab repos, without having to specify multiple event names.

In this way it would be easier writing generic ci/cd pipelines using argo workflows and events.

**Comment by wsams** [comment]
It seems like the gitlab event source should implement the `repositories` property like the github event source.

**Comment by bygui86** [comment]
@wsams you are right!

For example in our project we have a microservices architecture with around 80 applications, each in its own repo... the way it is right now creates hundreds of duplicated lines in the EventSource! and accordingly also in the Sensor!

The final goal would be to have a single EventSource listing all repos, connected to a Sensor which will distinguish which pipe to trigger.

**Comment by whynowy** [comment]
Is a field `projectIDs` (`[]string`) good enough? @bygui86 @wsams @paolocarta

**Comment by bygui86** [comment]
@whynowy yeah something like that.

Just to know, is it possible to replace IDs with names?
Like
```yaml
  gitlab:
    example:
      repositories:
        - argo-events
        - argo-workflows
```

**Comment by whynowy** [comment]
Anybody wants to try a testing build?

`gcr.io/whynowy/argo-events:2.186`


- Use `projects` as below.
- Please also try with setting `secretToken`.


```
spec:
  gitlab:
    example:
      # Project namespace paths or IDs
      projectIDs:
        - "28590692"
        - whynowy1/test
        - whynowy/test1
...
      events:
        - PushEvents
        - TagPushEvents
      accessToken:
        key: token
        name: gitlab-access
      secretToken:
        key: token
        name: gitlab-secret
...
      deleteHookOnFinish: true
```
