### ISSUE TITLE
Cannot extract JSON parameters from SNS event source

### ISSUE THREAD

**Issue by rickihastings** [argoproj/argo-events#1295]
**Describe the bug**
When using the SNS event source, it's not possible to extract JSON parameters in a sensor when using `dataKey` or `dataTemplate`. The default example works, however it seems like the event source needs a `jsonBody` property similar to SQS.

**To Reproduce**
1. Set up an SNS event source (the default one will do).
2. Setup an event sensor like the one below (this is the default with the `dataKey` changed):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sns
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: aws-sns
      eventName: example
  triggers:
    - template:
        name: sns-workflow
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: aws-sns-worfklow-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # value will be overridden by the event payload
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.message
              dest: spec.arguments.parameters.0.value
```
3. Confirm the subscription in SNS and publish a message which has the body `{"message":"hello"}`
4. You'll see an unable to extract parameter error in the logs for the above sensor.

**Expected behavior**
I would expect the workflow to successfully start and display the "hello" message in the logs.

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: `v1.16.15-eks-cf75c9`
 - Argo: `v3.1.3`
 - Argo Events: `v1.3.1`

**Additional context**
- When using the log event source to debug this the message appears like this:
```json
{
  "header": [  ],
  "body": {
    "Type": "Notification",
    "MessageId": "***",
    "TopicArn": "***",
    "Message": "{\"message\":\"hello\"}",
    "Timestamp": "2021-08-02T07:25:12.532Z",
    "SignatureVersion": "1",
    "Signature": "***",
    "SigningCertURL": "***",
    "UnsubscribeURL": "***"
  }
}
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
I went through the source code as well as the sns doc provided by AWS, looks like the SNS messages are always in JSON format, and we alway treat them that way, that's why it's unlike SNS, `jsonBody` is not needed.

Please take a look at the sample SNS message like https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html, we respect the original message format, and the `message` field is always treated as a string, you need to parse it by your self. I think `sprig` template can help - https://github.com/argoproj/argo-events/blob/master/docs/tutorials/02-parameterization.md#sprig-templates


```json
{
  "Type" : "Notification",
  "MessageId" : "22b80b92-fdea-4c2c-8f9d-bdfb0c7bf324",
  "TopicArn" : "arn:aws:sns:us-west-2:123456789012:MyTopic",
  "Subject" : "My First Message",
  "Message" : "Hello world!",
  "Timestamp" : "2012-05-02T00:54:06.655Z",
  "SignatureVersion" : "1",
  "Signature" : "EXAMPLEw6JRN...",
  "SigningCertURL" : "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-f3ecfb7224c7233fe7bb5f59f96de52f.pem",
  "UnsubscribeURL" : "https://sns.us-west-2.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-west-2:123456789012:MyTopic:c9135db0-26c4-47ec-8998-413945fb5a96"
}
```

**Comment by rickihastings** [comment]
Yes this works perfectly. Thank you!

For anyone who stumbles upon this, the following template worked for me:

```
parameters:
  - src:
      dependencyName: event
      dataTemplate: "{{ (.Input.body.Message | mustFromJson).namespace }}"
    dest: metadata.namespace
```
