### ISSUE TITLE
Dynamic Dependencies in Sensors (listen to all events of a certain type)

### ISSUE THREAD

**Issue by daniel-codefresh** [argoproj/argo-events#1303]
### **Is your feature request related to a problem? Please describe.**
We'd like to be able to support a special type of Sensor Dependency that will allow a Sensor to listen to all events of a certain type. This dependency can be a "dynamic" dependency in a sense that it will update the Sensor deployment whenever new events of that type are added. 
For example: define a Sensor that will depend on all events of type GitHub.

### **Describe the solution you'd like**
Expand the Spec of the Sensor object and support 2 additional fields on the Dependency level:
* EventType - the type of events that the Sensor depends on (GitHub, GitLab, Calendar, etc)
* Condition - the condition between all of the events of that type to execute the trigger. Can be either: "Any" or "All" (execute the trigger if any / all of the events of that type are being published). This condition can be combined with the conditions that are specified on the Trigger level.
For example: 
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: dynamic-dep
spec:
  dependencies:
    - name: dep01
      eventType: github
      condition: any
    - name: dep02
      eventSourceName: webhook-es
      eventName: example
  triggers:
    - template:
        conditions: "dep01 && dep02"    # will produce "(dep01-1 || dep01-2 || dep01-3 ...) && dep02"
        name: trigger
        http:
          url: http://abc.com/hello
          method: GET
```

### **Describe alternatives you've considered**
* Omitting the Condition field and always use "Any" condition by default
* Support different variations of "dynamic" dependencies - depend on events not only by eventType as mentioned above, but also by eventName (listen to all events that are named "X" without specifying the eventSourceName as mentioned here: https://github.com/argoproj/argo-events/issues/1016).
For example:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: dynamic-dep
spec:
  dependencies:
    - name: dep01
      type: dynamic  # if the type is not specified the dependency will be considered as a regular dependency by default
      eventType: github # listen to all events of type GitHub
    - name: dep02
      type: dynamic 
      eventName: alert # listen to all events named "alert"
    - name: dep03
      eventSourceName: webhook-a
      eventName: example
  triggers:
    - template:
        name: trigger
        http:
          url: http://abc.com/hello
          method: GET
```

*I will be happy to implement and contribute this feature if you think it might be useful and the community sees value in it 👍*

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
