### ISSUE TITLE
feat: include filters in trigger condition

### ISSUE THREAD

**Issue by Hunter-Thompson** [argoproj/argo-events#1307]
**Is your feature request related to a problem? Please describe.**

We can run a certain workflow based on a trigger condition, which is tied to an event.

```
  dependencies:
    - name: dep01
      eventSourceName: webhook-a
      eventName: example01
```
```
    - template:
        conditions: "dep01"
        name: trigger01
        http:
          url: http://abc.com/hello1
          method: GET
 ```

But we cannot run a certain workflow based on a single filter. All filters need to pass for the workflows to run, which is a desired effect most of the time, but this does now allow us to run a certain workflow only when a certain filter has been matched.

Having filters in trigger dependencies would help in creating sensors that can trigger specific workflows based on filter data. 

**Describe the solution you'd like**

```
filters:
  - name: f01 	
    data:
      - path: body.value
        type: string
	    value:
	    	- "hello world"

dependencies:
	- name: dep01
	    eventSourceName: webhook-a
	    eventName: example01
 ```
 ```
     - template:
        conditions: "dep01 && f01"
        name: trigger01
        http:
          url: http://abc.com/hello1
          method: GET
 ```
Adding names to filters, and then using them in trigger conditions could allow this?

**Describe alternatives you've considered**

An alternative would be to create a new sensor with a different filter per repo.

**Use case**

If 2 repos use the same event and sensor, but one of them requires a privileged workflow to be ran, the only way to work around this is to create a new sensor.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
