### ISSUE TITLE
Not able to set `maxPayload` in spec Eventbus

### ISSUE THREAD

**Issue by BouweCeunen** [argoproj/argo-events#1309]
**Describe the bug**
```nats: maximum payload exceeded```

**To Reproduce**
1. Send payload bigger than 1Mi to EventBus

**Expected behavior**
Being able to set the `maxPayload` in the native EventBus spec.

```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      replicas: 3
      auth: token
      maxPayload: 65536
```

**Screenshots**
/

**Environment (please complete the following information):**
 - Kubernetes: v1.19.11
 - Argo Workflows: v3.1.6
 - Argo Events: v1.4.0

**Additional context**
/

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
