### ISSUE TITLE
Examples - Add port specification also to DeploymentSpec

### ISSUE THREAD

**Issue by twiechert** [argoproj/argo-events#132]
**Describe the bug**
The port specification in the example gateway deployment (https://github.com/argoproj/argo-events/blob/master/examples/gateways/webhook.yaml) is done on service level but left out on deployment/pod level.

**Expected behavior**
Example config should look like:
```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: webhook-gateway
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
    gateway-name: "webhook-gateway"
spec:
  configMap: "webhook-gateway-configmap"
  type: "webhook"
  dispatchMechanism: "HTTP"
  eventVersion: "1.0"
  imageVersion: "latest"
  deploySpec:
    containers:
    - name: "webhook-events"
      image: "argoproj/webhook-gateway"
      imagePullPolicy: "IfNotPresent"
      command: ["/bin/webhook-gateway"]
      ports:
        - name: http
          containerPort: 12000
    serviceAccountName: "argo-events-sa"
  serviceSpec:
    selector:
      gateway-name: "webhook-gateway"
    ports:
      - port: 12000
        targetPort: 12000
    type: LoadBalancer
  watchers:
    sensors:
    - name: "webhook-sensor"
```
Or the values provided on service level implictly copied to the deployment/pod by argo.

**Additional context**
In our case, omitting port specification on pod/deployment level caused our istio virtual services to be not reachable.
