### ISSUE TITLE
Argo Bearer Authentication Token Leakage

### ISSUE THREAD

**Issue by christophercutajar** [argoproj/argo-events#1336]
**Describe the bug**
There is a possiblility that Argo will log the authentication Bearer token in the logs and other areas when `dataKey` that doesn't exists is sent in the request payload.

**To Reproduce**
1. Create the below test sensor

<details>
<summary>Sensor</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: chris-test
spec:
  dependencies:
    - name: test-deb
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: example
        http:
          url: <URL>
          method: PUT
      parameters:
        - src:
            dependencyName: cluster
            dataKey: body.message
          dest: http.url
    - template:
        name: slack-trigger
        slack:
          channel: random
          message: "Chris test "
          slackToken:
            key: token
            name: slack-secret
      parameters:
        - src:
            dependencyName: test-deb
            dataKey: body.message
          dest: slack.message
          operation: append
        - src:
            dependencyName: test-deb
            dataKey: body.name
          dest: slack.message
          operation: append
```
</details>

2. Deploy webhook eventSource with authentication

```
    example:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /example
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST
      authSecret:
        name: webhook-secret
        key: my-token
```
 
3. Deploy local proxy so that curl can trigger the sensor
4. Execute the following `curl` command

```bash
curl -X POST -H "Authorization: $TOKEN" -d '{"message" : ok", "message2" : "ok" }' -H "Content-Type: application/json" http://localhost:12000/example
```

5. Check both Error logs and Slack message. These would both have the clear `Bearer` token 

Sensor Logs:

```bash
chris-test-nhnv5-769cb7ddd7-z997d main 2021-09-03T17:54:13.135291397+02:00 {"level":"info","ts":1630684453.1350772,"logger":"argo-events.sensor","caller":"sensors/listener.go:336","msg":"successfully processed the trigger","sensorName":"chris-test","triggerName":"example","triggerType":"HTTP","triggeredBy":["example"],"triggeredByEvents":["32313233646536662d616665622d343031342d386535372d376364666165643233613737"]}
chris-test-nhnv5-769cb7ddd7-z997d main 2021-09-03T17:54:13.135343746+02:00 Failed to get value by key: key body.message2 does not exist to in the event object
chris-test-nhnv5-769cb7ddd7-z997d main 2021-09-03T17:54:13.135351795+02:00 
chris-test-nhnv5-769cb7ddd7-z997d main 2021-09-03T17:54:13.135429825+02:00 {"level":"info","ts":1630684453.1353111,"logger":"argo-events.sensor","caller":"slack/slack.go:92","msg":"executing SlackTrigger","sensorName":"chris-test","triggerName":"slack-trigger","triggerType":"Slack"}
chris-test-nhnv5-769cb7ddd7-z997d main 2021-09-03T17:54:13.135487299+02:00 {"level":"info","ts":1630684453.1354084,"logger":"argo-events.sensor","caller":"slack/slack.go:118","msg":"posting to channel...","sensorName":"chris-test","triggerName":"slack-trigger","triggerType":"Slack","channelName":"random"}
chris-test-nhnv5-769cb7ddd7-z997d main 2021-09-03T17:54:13.304238841+02:00 {"level":"info","ts":1630684453.303901,"logger":"argo-events.sensor","caller":"slack/slack.go:173","msg":"message successfully sent to channelID with timestamp","sensorName":"chris-test","triggerName":"slack-trigger","triggerType":"Slack","message":"Chris test {\"header\":{\"Accept\":[\"*/*\"],\"Authorization\":[\"Bearer <REDACTED>\"],\"Content-Length\":[\"68\"],\"Content-Type\":[\"application/json\"],\"User-Agent\":[\"curl/7.64.1\"]},\"body\":{\"message\":\"ok\",\"message2\":\"ok\"}}","channelID":"C01CA2NHA5U","timestamp":"1630684453.006000"}
chris-test-nhnv5-769cb7ddd7-z997d main 2021-09-03T17:54:13.304302240+02:00 {"level":"info","ts":1630684453.3039887,"logger":"argo-events.sensor","caller":"slack/slack.go:174","msg":"finished executing SlackTrigger","sensorName":"chris-test","triggerName":"slack-trigger","triggerType":"Slack"}
chris-test-nhnv5-769cb7ddd7-z997d main 2021-09-03T17:54:13.304309688+02:00 {"level":"info","ts":1630684453.3040097,"logger":"argo-events.sensor","caller":"sensors/listener.go:336","msg":"successfully processed the trigger","sensorName":"chris-test","triggerName":"slack-trigger","triggerType":"Slack","triggeredBy":["example"],"triggeredByEvents":["32313233646536662d616665622d343031342d386535372d376364666165643233613737"]}
chris-test-nhnv5-769cb7ddd7-z997d main 2021-09-03T17:55:11.824514953+02:00 {"level":"info","ts":1630684511.8243096,"logger":"argo-events.sensor","caller":"driver/nats.go:189","msg":"finished evicting 0 cached IDs, time cost: 0 ms","sensorName":"chris-test","clientID":"client-853085897-86"}
chris-test-nhnv5-769cb7ddd7-z997d main 2021-09-03T17:56:11.824472783+02:00 {"level":"info","ts":1630684571.8242955,"logger":"argo-events.sensor","caller":"driver/nats.go:189","msg":"finished evicting 0 cached IDs, time cost: 0 ms","sensorName":"chris-test","clientID":"client-853085897-86"}
```

Slack Message:

```
Chris test {"header":{"Accept":["/"],"Authorization":["Bearer <REDACTED>"],"Content-Length":["68"],"Content-Type":["application/json"],"User-Agent":["curl/7.64.1"]},"body":{"message":"ok","message2":"ok"}}

```

**Expected behavior**
When a `dataKey` does not exists, I would expect that the sensor would throw an error without having the clear `Bearer` token in it.

**Environment (please complete the following information):**
 - Kubernetes: v1.18.20
 - Argo: v3.1.5
 - Argo Events: v1.7.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
