### ISSUE TITLE
Sensor not working even though event source sees pubsub messages?

### ISSUE THREAD

**Issue by ado120** [argoproj/argo-events#1347]
**Describe the bug**
Hey all, I'm at my wits end trying to get gcp pubsub working to create a simple pod on my cluster. I am assuming that the event source can listen to pubsub because I see this in the logs:

```
{"level":"info","ts":1631837201.72604,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:110","msg":"received GCP PubSub Message from topic","eventSourceName":"gcp-pubsub","eventSourceType"
:"pubsub","eventName":"example","topic":"argoevents-test","topicProjectID":"redacted","projectID":"redacted","subscriptionID":"argoevents-test-sub"}
{"level":"info","ts":1631837201.7261035,"logger":"argo-events.eventsource","caller":"gcppubsub/start.go:129","msg":"dispatching event...","eventSourceName":"gcp-pubsub","eventSourceType":"pubsub","event
Name":"example","topic":"argoevents-test","topicProjectID":"redacted","projectID":"redacted","subscriptionID":"argoevents-test-sub"}
{"level":"info","ts":1631837201.7295957,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:411","msg":"succeeded to publish an event","eventSourceName":"gcp-pubsub","eventName":"examp
le","eventSourceType":"pubsub","eventID":"redacted"}
```

However I see nothing of significance in the sensor pod logs that would indicate that it received something from the event bus to then trigger something.. 
```
{"level":"info","ts":1631837378.5544524,"logger":"argo-events.sensor","caller":"driver/nats.go:189","msg":"finished evicting 0 cached IDs, time cost: 0 ms","sensorName":"pubsub","clientID":"client-26477
49409-72"}
{"level":"info","ts":1631837438.5544558,"logger":"argo-events.sensor","caller":"driver/nats.go:189","msg":"finished evicting 0 cached IDs, time cost: 0 ms","sensorName":"pubsub","clientID":"client-26477
49409-72"}
{"level":"info","ts":1631837498.55446,"logger":"argo-events.sensor","caller":"driver/nats.go:189","msg":"finished evicting 0 cached IDs, time cost: 0 ms","sensorName":"pubsub","clientID":"client-2647749
409-72"}
```

I just see that over and over ^.. What can I do to troubleshoot this? I have no idea if I have a pubsub configuration issue or if it's something I misconfigured with argo-events.. Here is my sensor.yaml for reference

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: pubsub
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: gcp-pubsub
    eventName: test
  triggers:
  - template:
      name: payload
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: payload-
              labels:
                app: payload
            spec:
              containers:
              - name: hello
                image: alpine
                command: ["echo"]
                args: ["This is the message you sent me:\n", ""]
              restartPolicy: Never
        parameters:
          - src:
              dependencyName: payload
            dest: spec.containers.0.args.1
```
