### ISSUE TITLE
Calendar gateway error `time ids mismatch`

### ISSUE THREAD

**Issue by DmitryBe** [argoproj/argo-events#137]
**Describe the bug**
Calendar gateway error `time ids mismatch`

ConfigMap

```
apiVersion: v1
data:
  calendar.interval: 'schedule: */1 * * * *'
kind: ConfigMap
metadata:
  creationTimestamp: 2018-12-08T17:17:17Z
  labels:
    hash: 90cdc0d1d8ea38c3ea596b42621d273e
    owner: dmitry
  name: hello-world-cm
  namespace: argo-dev

```

Gateway log (calendar-events)

```
{"level":"info","gateway-name":"hello-world-gateway","caller":"/Users/vpage/go/src/github.com/argoproj/argo-events/gateways/watcher.go:42","message":"detected new k8 Event. Updating gateway resource."}
{"level":"info","gateway-name":"hello-world-gateway","config-id":"10258637","action":"Error","caller":"/Users/vpage/go/src/github.com/argoproj/argo-events/gateways/state.go:118","message":"k8 event"}
{"level":"info","gateway-name":"hello-world-gateway","config-name":"10258637","caller":"/Users/vpage/go/src/github.com/argoproj/argo-events/gateways/state.go:133","message":"updating gateway resource..."}
{"level":"error","gateway-name":"hello-world-gateway","config-name":"10258637","event-name":"hello-world-gateway-9v947","event-action":"Error","node-time-id":"331180292","event-time-id":"1278273452","caller":
"/Users/vpage/go/src/github.com/argoproj/argo-events/gateways/state.go:156","message":"time ids mismatch"}
{"level":"info","gateway-name":"hello-world-gateway","event-name":"hello-world-gateway-9v947","action":"Error","caller":"/Users/vpage/go/src/github.com/argoproj/argo-events/gateways/state.go:88","message":"ma
rking gateway k8 event as seen"}
```
