### ISSUE TITLE
GCP PubSub messages coming in as base64 encoded, unable to decrypt

### ISSUE THREAD

**Issue by ado120** [argoproj/argo-events#1371]
**Describe the bug**
Publishing a simple "test" message in gcp pubsub ui to a subscribed topic gives me the body as base64 encoded. Shouldn't argo workflows decrypt this on runtime?

**To Reproduce**
Event Source YAML
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gcp-pubsub
spec:
  pubSub:
    example:
      jsonBody: false
      projectID: foo
      topic: argoevents-test
      subscriptionID: argoevents-test-sub
      credentialSecret:
        name: my-secret
        key: secret-key
```

Sensor YAML
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: pubsubv2
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
  - name: payload
    eventSourceName: gcp-pubsub
    eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: special-trigger-
                namespace: argo-workflows
              spec:
                entrypoint: whalesay
                serviceAccountName: argo
                arguments:
                  parameters:
                    - name: message
                      # the value will get overridden by event payload from test-dep
                      value: hello world
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: payload
                dataKey: body
              dest: spec.arguments.parameters.0.value
```

this is the data key that is being received:
`{"id":"3185433714809118","body":"dGVzdA==","attributes":null,"publishTime":"2021-10-06 21:08:24.292 +0000 UTC"}`

Any help would be greatly appreciated
