### ISSUE TITLE
Eventsource hangs if Minio is not reachable

### ISSUE THREAD

**Issue by mseiwald** [argoproj/argo-events#1396]
**Describe the bug**
When creating a Minio eventsource but Minio is unavailable the eventsource just hangs indefinitely:

```
{"level":"info","ts":1635162258.4363985,"logger":"argo-events.eventsource","caller":"minio/start.go:80","msg":"setting up a minio client...","eventSourceName":"test","eventSourceType":"minio","eventName":"upload","bucketName":"test"}
{"level":"info","ts":1635162258.4364896,"logger":"argo-events.eventsource","caller":"minio/start.go:90","msg":"started listening to bucket notifications...","eventSourceName":"test","eventSourceType":"minio","eventName":"upload","bucketName":"test"}
{"level":"error","ts":1635162258.4380362,"logger":"argo-events.eventsource","caller":"minio/start.go:93","msg":"invalid notification","eventSourceName":"test","eventSourceType":"minio","eventName":"upload","bucketName":"test","error":"Get \"http://minio:9000/test/?location=\": dial tcp 10.101.132.232:9000: connect: connection refused","stacktrace":"github.com/argoproj/argo-events/eventsources/sources/minio.(*EventListener).StartListening\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/minio/start.go:93\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3.1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:387\ngithub.com/argoproj/argo-events/common.Connect.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:99\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.7-rc.0/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.7-rc.0/pkg/util/wait/wait.go:399\ngithub.com/argoproj/argo-events/common.Connect\n\t/home/runner/work/argo-events/argo-events/common/retry.go:98\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:386"}
```

After that nothing happens. The Pod stays in this state until deleted manually.

The responsible code is https://github.com/argoproj/argo-events/blob/master/eventsources/sources/minio/start.go#L88-L104. The ListenBucketNotification channel will be closed after such an error so the for loop ends. After that it just hangs at line 103 waiting for `<-ctx.Done()` forever...

**To Reproduce**
1. Make Minio unavailable (e.g. `kubectl scale`)
2. Create Minio Eventsource:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: test
  namespace: default
spec:
  eventBusName: default
  minio:
    upload:
      accessKey:
        key: accesskey
        name: admin
      bucket:
        name: test
      endpoint: minio:9000
      events:
      - s3:ObjectCreated:Put
      insecure: true
      secretKey:
        key: secretkey
        name: admin
```
3. Check logs of eventsource pod

**Expected behavior**
From my point of view the event source should just "crash" (process should exit) so that K8s can automatically restart it. If it restarts too quickly it would go into a crashloop and could recover automatically once Minio gets available again.

**Environment (please complete the following information):**
 - Kubernetes: v1.20.10
 - Argo: v3.1.13
 - Argo Events: v1.3.1

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
