### ISSUE TITLE
Allow me to set sensor/source kubernetes resource limits

### ISSUE THREAD

**Issue by tim-sendible** [argoproj/argo-events#1408]
**Is your feature request related to a problem? Please describe.**
I need to be able to set kubernetes requests/limits on every pod. This includes sensor/source pods.
I asked in Slack (no answer), and looking around it seems that that this is not possible.

**Describe the solution you'd like**
I'd expect to be able to write something like this and have the resources represented in the resulting pod:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: example-webhook-source
spec:
  replica: 2
  webhook:
    example:
      port: "12000"
      endpoint: /
      method: POST
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
```

**Describe alternatives you've considered**
A similar issue was raised in #736 but then closed without reason.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
