### ISSUE TITLE
cannot create resource "argo-events"

### ISSUE THREAD

**Issue by aprohorov-gd** [argoproj/argo-events#1418]
**Describe the bug**
All examples shows as how to use **k8s** trigger
```
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
```

But in doesn't work. 
error:
`failed to execute trigger: timed out waiting for the condition: default is forbidden: User \"system:serviceaccount:argo-events:operate-workflow-sa\" cannot create resource \"argo-events\" in API group \"\" at the cluster scope`

resource **always equal namespace name**. For example,  error in **default** namespace will be: 
`failed to execute trigger: timed out waiting for the condition: default is forbidden: User \"system:serviceaccount:default:operate-workflow-sa\" cannot create resource \"default\" in API group \"\" at the cluster scope`

To make it work we need to edit definition like this:
```
   triggers:
     - template:
         name: webhook-workflow-trigger
         k8s:
+          group: argoproj.io
+          version: v1alpha1
+          resource: workflows
           operation: create
           source:
             resource:
               apiVersion: argoproj.io/v1alpha1
               kind: Workflow
```

**To Reproduce**
Go thru "get started"

**Environment (please complete the following information):**
 - Kubernetes: v1.21.3
 - Argo: v3.2.0
 - Argo Events: v1.3.1
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
