### ISSUE TITLE
json schema check for webhook requests incorrect type

### ISSUE THREAD

**Issue by ilyagorban-codefresh** [argoproj/argo-events#1423]
**Describe the bug**
While validating using the jsonschema with `kubeconform` tool I got the following error for EventSource of webhook type:

`(EventSource): For field (root): Must validate one and only one schema (oneOf) - For field spec.service.ports.0.targetPort: Invalid type. Expected: string, given: integer`

The problem is that `targetPort` have to be `integer`, else the service of the webhook will not be created.

**To Reproduce**
Yaml with EventSource of webhook type that correctly installs on cluster (with creation of the related service) but fails in validation:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-eventsource
  labels:
    key: value4
spec:
  eventBusName: some-eventbus
  service:
    ports:
      - port: 80
        targetPort: 80
  github:
    push:
      owner: some-owner
      repository: some-repo
      webhook:
        endpoint: /some-endpoint/
        port: "80"
        method: POST
        url: https://some.url
      events:
        - push

      apiToken:
        name: github-token
        key: token

      insecure: true
      active: true
      contentType: json
```

Steps to reproduce the behavior of validation failure:
1. install `kubeconform` [tool](https://github.com/yannh/kubeconform)
2. launch in terminal where you saved the yamls above: `kubeconform -schema-location https://raw.githubusercontent.com/argoproj/argo-events/master/api/jsonschema/schema.json -strict -output tap .`
3. we should see failure of validation
4. after running `kubectl apply -f <file-with-integer-taget-port>.yaml`
5. we should see in the list of services `webhook-eventsource-eventsource-svc`

Steps to reproduce the behavior of service deployment failure:
1. replace `targetPort: 80` with `targetPort: "80"` as validation requests
2. run `kubectl apply -f <file-with-stringified-target-port>.yaml`
3. check in the list of services we should not find service `webhook-eventsource-eventsource-svc`

**Expected behavior**
Absence of errors on validation AND correctly deployed service of webhook. The type of `targetPort` should be `integer` and not `string`

**Environment (please complete the following information):**
 - Argo: v3.2.0-rc4
 - Argo Events: v1.5.2

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
