### ISSUE TITLE
Gitea webhook

### ISSUE THREAD

**Issue by nwmcsween** [argoproj/argo-events#1431]
**Is your feature request related to a problem? Please describe.**
Create a gitea eventsource

**Describe the solution you'd like**
As per feature req

**Describe alternatives you've considered**
Gitlab is a viable alternative but requires a huge install base of versioned deps.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@nwmcsween - would you like to contribute on it?

**Comment by blake-hamm** [comment]
After some deliberation with deepseek, I was able to get webhooks setup with gitea and argo events. I'm running gitea and argo events/workflows in the same cluster. First I deployed this argo EventSource webhook:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitea
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    push:
      port: "12000"
      endpoint: /push
      method: POST
```
Then I added some rbac for the argo events default role:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-workflow-role
  namespace: argo-events
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-workflow-rolebinding
  namespace: argo-events
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-events
roleRef:
  kind: Role
  name: argo-events-workflow-role
  apiGroup: rbac.authorization.k8s.io
```
I configured gitea ![like so](https://github.com/user-attachments/assets/1823557a-dcb4-487f-bc21-0db01cce5ea0) - notice it's pointing directly to my internal argo EventSource webhook service.

Finally, I deployed a custom sensor. This Sensor will:
- Check for commits to the `docker` directory
- Trigger an argo workflow (just hello world for now, but idea is to build and push docker images to Harbor)
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gitea-docker-changes
  namespace: argo-events
spec:
  dependencies:
    - name: gitea-push-event
      eventSourceName: gitea
      eventName: push
      filters:
        script: |-
          -- Check all commits for docker/ path changes
          for _, commit in ipairs(event.body.commits) do
              -- Check added files
              for _, path in ipairs(commit.added) do
                  if string.sub(path, 1, 7) == "docker/" then
                      return true
                  end
              end

              -- Check modified files
              for _, path in ipairs(commit.modified) do
                  if string.sub(path, 1, 7) == "docker/" then
                      return true
                  end
              end

              -- Check removed files
              for _, path in ipairs(commit.removed) do
                  if string.sub(path, 1, 7) == "docker/" then
                      return true
                  end
              end
          end

          -- No docker changes found
          return false
  triggers:
    - template:
        name: docker-change-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: docker-changes-
              spec:
                serviceAccountName: default
                entrypoint: main
                templates:
                  - name: main
                    container:
                      image: alpine:latest
                      command: [sh, -c]
                      args: ["echo 'Docker directory modified! Triggering workflow...'"]
```
