### ISSUE TITLE
cannot create k8s resource ingress

### ISSUE THREAD

**Issue by coawlion** [argoproj/argo-events#1432]
**Describe the bug**
```
- template:
        conditions: "create-editorx-dep"
        name: ingress-creation
        k8s:
          operation: create
          source:
            resource:
              apiVersion: networking.k8s.io/v1beta1
              kind: Ingress
              metadata:
                name: editorx-ingress-coawlion
                namespace: editorx
...
```
When using the above sensor trigger, it failed to create ingress.

```
{"level":"error","ts":1637112348.0356252,"logger":"argo-events.sensor","caller":"sensors/listener.go:302","msg":"failed to execute a trigger","sensorName":"webhook","error":"failed to execute trigger: timed out waiting for the condition: ingresss.networking.k8s.io is forbidden: User \"system:serviceaccount:argo-events:editorx-k8s-resource-sa\" cannot create resource \"ingresss\" in API group \"networking.k8s.io\" in the namespace \"editorx\"","errorVerbose":"timed out waiting for the condition: ingresss.networking.k8s.io is forbidden: User \"system:serviceaccount:argo-events:editorx-k8s-resource-sa\" cannot create resource \"ingresss\" in API group \"networking.k8s.io\" in the namespace \"editorx\"\nfailed to execute trigger\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerOne\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:355\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:300\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:1581","triggerName":"ingress-creation","triggeredBy":["create-editorx-dep"],"triggeredByEvents":["65633634313066362d303134372d343733322d393963392d353636633636313836393538"],"stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:302"}

```

Notice that, it tries to create resource `ingresss` instead of `ingresses`

**To Reproduce**
1. Use webhook trigger as event-source
2. Trigger k8s resource ingress

**Expected behavior**
Ingress created as a result of trigger

**Environment (please complete the following information):**
 - Kubernetes: v1.20.6
 - Argo: NA
 - Argo Events: v1.8.0 (argo/argo-events helm)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
