### ISSUE TITLE
Sensor expression filter "not really mutual exclusive"

### ISSUE THREAD

**Issue by bygui86** [argoproj/argo-events#1442]
**Describe the bug**
I created a Sensor containing some dependencies on different kind of events, coming from an EventSource listening for GitLab webhook events.
I'm trying to filter those events basing on a list of expressions declared under `spec.dependencies.[].filters.exprs.[]`).
At the first failing expression (`spec.dependencies.[].filters.exprs.[].expr`), the Sensor just discards the event without evaluating all following expressions in the list.

**To Reproduce**
It's pretty difficult to reproduce exactly my environment, because it requires:
- GitLab account
- GitLab repository
- GitLab webhook configured to point ArgoEvents EventSource
- EventSource deployed and exposed on the internet

Anyway here the steps to reproduce:
1. Deploy ArgoEvents Sensor
2. Trigger a GitLab webhook event with a commit or a change to a MR
3. Look at Sensor logs, searching for something like
```json
{"level":"error","ts":1638190242.5967605,"logger":"argo-events.sensor","caller":"sensors/listener.go:174","msg":"failed to apply filters","sensorName":"sbt-gitlab-mr","error":"path body.object_attributes.oldrev does not exist","stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents.func1.2\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:174\ngithub.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).processEventSourceMsg\n\t/home/runner/work/argo-events/argo-events/eventbus/driver/nats.go:229\ngithub.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).SubscribeEventSources.func1\n\t/home/runner/work/argo-events/argo-events/eventbus/driver/nats.go:150\ngithub.com/nats-io/stan%2ego.(*conn).processMsg\n\t/home/runner/go/pkg/mod/github.com/nats-io/stan.go@v0.6.0/stan.go:863\ngithub.com/nats-io/nats%2ego.(*Conn).waitForMsgs\n\t/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2211"}
```

Here the Sensor:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gitlab-sensor
spec:
  replicas: 1
  dependencies:
    - name: gitlab-dependency
      eventSourceName: gitlab-event-source
      eventName: gitlab-event
      filters:
        exprs:
          # expression 1
          # GitLab webhook event always contains fields "event_type", "object_attributes.work_in_progress", "object_attributes.state", "object_attributes.action", so no issue here
          - expr: event_type == "merge_request" && work_in_progress == false && state == "opened" && action == "open"
            fields:
              - name: event_type
                path: body.event_type
              - name: work_in_progress
                path: body.object_attributes.work_in_progress
              - name: state
                path: body.object_attributes.state
              - name: action
                path: body.object_attributes.action
          # expression 2
          # GitLab webhook event does not always contain field "object_attributes.oldrev", in this case the evaluationa process stops here ignoring all following expressions
          - expr: event_type == "merge_request" && work_in_progress == false && state == "opened" && action == "update" && oldrev != ""
            fields:
              - name: event_type
                path: body.event_type
              - name: work_in_progress
                path: body.object_attributes.work_in_progress
              - name: state
                path: body.object_attributes.state
              - name: action
                path: body.object_attributes.action
              - name: oldrev
                path: body.object_attributes.oldrev
          # expression 3
          # This expression is never evaluated as GitLab webhook event does not always contain fiel "object_attributes.oldrev" and the evaluation process stops before reaching this expression
          - expr: event_type == "merge_request" && work_in_progress == false && state == "opened" && action == "update" && title_previous =~ "Draft:.*"
            fields:
              - name: event_type
                path: body.event_type
              - name: work_in_progress
                path: body.object_attributes.work_in_progress
              - name: state
                path: body.object_attributes.state
              - name: action
                path: body.object_attributes.action
              - name: title_previous
                path: body.changes.title.previous
  triggers:
    - template:
        conditions: gitlab-dependency
        name: gitlab-trigger
        # ...
```

**Expected behaviour**
Expressions listed in the filter are mutual exclusive: the first one that matches, triggers corresponding action declared in the Sensor.
**This behaviour is fine, as soon as ALL expressions are evaluated.**
Right now at the first failure (e.g. "path ... does not exist") the evaluation process gets interrupted and all following expressions are completely ignored. This cannot be the right behaviour, otherwise it does not make sense to allow the declaration of multiple mutual exclusive expressions.

I found the piece of code responsible for filtering events here: https://github.com/argoproj/argo-events/blob/master/sensors/dependencies/filter.go
And here the method:
```go
// filterExpr applies expression based filters against event data
func filterExpr(filters []v1alpha1.ExprFilter, event *v1alpha1.Event) (bool, error) {
	if filters == nil {
		return true, nil
	}
	if event == nil {
		return false, fmt.Errorf("nil event")
	}
	payload := event.Data
	if payload == nil {
		return true, nil
	}
	var js *json.RawMessage
	if err := json.Unmarshal(payload, &js); err != nil {
		return false, err
	}
	var jsData []byte
	jsData, err := json.Marshal(js)
	if err != nil {
		return false, err
	}

	for _, filter := range filters {
		parameters := map[string]interface{}{}
		for _, field := range filter.Fields {
			result := gjson.GetBytes(jsData, field.Path)
			if !result.Exists() {
				return false, fmt.Errorf("path %s does not exist", field.Path)
			}
			parameters[field.Name] = result.Value()
		}
		if len(parameters) == 0 {
			continue
		}
		expr, err := govaluate.NewEvaluableExpression(filter.Expr)
		if err != nil {
			return false, err
		}
		result, err := expr.Evaluate(parameters)
		if err != nil {
			return false, err
		}
		if result == true {
			return true, nil
		}
	}

	return false, nil
}
```

In my opinion we should fix the method above, like following:
```go
// filterExpr applies expression based filters against event data
func filterExpr(filters []v1alpha1.ExprFilter, event *v1alpha1.Event) (bool, error) {
	if filters == nil {
		return true, nil
	}
	if event == nil {
		return false, fmt.Errorf("nil event")
	}
	payload := event.Data
	if payload == nil {
		return true, nil
	}
	var js *json.RawMessage
	if err := json.Unmarshal(payload, &js); err != nil {
		return false, err
	}
	var jsData []byte
	jsData, err := json.Marshal(js)
	if err != nil {
		return false, err
	}

	errMsgs := make([]string, 0)
	for _, filter := range filters {
		parameters := map[string]interface{}{}
		for _, field := range filter.Fields {
			result := gjson.GetBytes(jsData, field.Path)
			if !result.Exists() {
				errMsgs = append(errMsgs, fmt.Sprintf("path %s does not exist", field.Path))
				continue
			}
			parameters[field.Name] = result.Value()
		}
		if len(parameters) == 0 {
			continue
		}
		expr, err := govaluate.NewEvaluableExpression(filter.Expr)
		if err != nil {
			errMsgs = append(errMsgs, err.Error())
			continue
		}
		result, err := expr.Evaluate(parameters)
		if err != nil {
			errMsgs = append(errMsgs, err.Error())
			continue
		}
		if result == true {
			return true, nil
		}
	}

	return false, errors.New(strings.Join(errMsgs, " / "))
}
```

We should fix also all other filtering options allowing list of mutual exclusive matches (e.g. data).

**Environment (please complete the following information):**
 - Kubernetes:   `v1.19.14-gke.1900`
 - Argo:   `v3.1.3`
 - Argo Events:   `v1.4.0`

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍  reaction to this issue! We often sort issues this way to know what to prioritise.
