### ISSUE TITLE
Not able to extract parameter values with multiple dependencies

### ISSUE THREAD

**Issue by naveenb30** [argoproj/argo-events#1458]
I have 2 SQS queues and have sensor configuration with trigger conditions `import-dep || test-dep`, I should be able to trigger the workflow with parameters extracted from body if anyone of the queue has message in it and it is working but for some reason I'm able to extract  values only from one dependency but other dependency is passing empty values to workflow even though it has messages in it

**To Reproduce**
Create event source:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: aws-sqs
spec:
  sqs:
    example:
      jsonBody: true
      region: us-east-1
      queue: data.fifo
      waitTimeSeconds: 20
      queueAccountId: "XXXXXXXXXX"
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: import-sqs
spec:
  sqs:
      import:
      jsonBody: true
      region: us-east-1
      queue: import.fifo
      waitTimeSeconds: 20
      queueAccountId: "XXXXXXXXXX"
```

create sensor using:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sqs
spec:
  template:
    serviceAccountName: argo
  dependencies:
    - name: test-dep
      eventSourceName: aws-sqs
      eventName: example
    - name: import-dep
      eventSourceName: import-sqs
      eventName: import
  triggers:
    - template:
        conditions: "import-dep || test-dep"
        name: sqs-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: aws-sqs-workflow-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: provider
                    - name: date
                    - name: record_date
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: provider
                        - name: date
                        - name: record_date
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.provider}} {{inputs.parameters.date}} {{inputs.parameters.record_date}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.provider
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.date
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: test-dep
                dataKey: body.record_date
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: import-dep
                dataKey: body.provider
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: import-dep
                dataKey: body.date
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: import-dep
                dataKey: body.record_date
              dest: spec.arguments.parameters.2.value
```

**Expected behavior**
Should be able to get parameter values from dependency `test-dep` or  `import-dep`, but only getting parameter values from one dependency. Also if I use different `dataKey` I'm getting correct parameter values, but I have to change my message structure here to make it work
example:
```
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.provider1
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.date1
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: test-dep
                dataKey: body.record_date1
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: import-dep
                dataKey: body.provider2
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: import-dep
                dataKey: body.date2
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: import-dep
                dataKey: body.record_date2
              dest: spec.arguments.parameters.2.value
```

**Environment (please complete the following information):**
 - Kubernetes: v.1.21
 - Argo: v3.2.4
 - Argo Events: v1.5.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
