### ISSUE TITLE
Add filtering feature to EventSource 

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1459]
When event sources watch events from an external data source (for example a Kafka topic), it ingests all the messages to the system, however the sensor might only be interested in some of the messages. Currently this is achieved by the [filtering](https://github.com/argoproj/argo-events/blob/master/docs/tutorials/07-filters.md) feature defined in sensor dependencies. This makes too many redundant messages flowing into the system (EventBus).

It would be better to have filtering features on event sources, to reduce the messages from the source part.

**Comment by bygui86** [comment]
@whynowy good idea, but I would not "move" filtering out of Sensor, but maybe better "add" filtering also at EventSource level. Considering that I'm trying to improve filtering with the new PR  #1490

**Comment by sarabala1979** [comment]
@dpadhiar is going work this feature

**Comment by sarabala1979** [comment]
```yaml
 filters:
        expression: (.message.id > 100 &&  body.message.id < 1000) && (.content.type == "json")  && (.content.type == "json")
         && (.content.type == "json") && (.content.type == "json") && (.content.type == "json")
```
