### ISSUE TITLE
Sensor triggers an Argo Workflow with wrong name

### ISSUE THREAD

**Issue by bygui86** [argoproj/argo-events#1473]
**Describe the bug**
A GitLab push triggers a Workflow through a Sensor, the name of the repo and the revision should be used as Workflow name/title but actually it's not. The repo name is concatenated with "the name of the previous Workflow".

![Screenshot 2021-12-17 at 17 04 01](https://user-images.githubusercontent.com/22518997/146573558-d7d615d8-13ba-43c9-bc95-681d7191e0df.png)

Se you can see in the screenshot above, the name of the last pipeline should be `hdp-reader-master-xyz` but actually it is `hdp-readercassandra-data-toolcassandra-data-tooldie-data-b4kmdp`, which is the concatenation of `hdp-reader` and the name of the previous Workflow `cassandra-data-toolcassandra-data-tooldie-data-back-fillerscr9d` (which is wrong as well).

Pods names are also wrong:
```
$ k get pods -n cicd-pipelines

NAME                                                                         READY   STATUS      RESTARTS   AGE
hdp-readercassandra-data-toolcassandra-data-tooldie-data-b4kmdp-1452109180   0/2     Completed   0          6m36s
hdp-readercassandra-data-toolcassandra-data-tooldie-data-b4kmdp-18957375     0/2     Completed   0          12m
hdp-readercassandra-data-toolcassandra-data-tooldie-data-b4kmdp-2296098792   0/2     Completed   0          5m36s
hdp-readercassandra-data-toolcassandra-data-tooldie-data-b4kmdp-2428497093   0/2     Completed   0          11m
hdp-readercassandra-data-toolcassandra-data-tooldie-data-b4kmdp-2763366116   0/2     Completed   0          13m
hdp-readercassandra-data-toolcassandra-data-tooldie-data-b4kmdp-2948167393   0/2     Completed   0          10m
hdp-readercassandra-data-toolcassandra-data-tooldie-data-b4kmdp-891922674    0/2     Error       0          7m36s
```

**PLEASE NOTE**
- This never happened in the previous version v1.4.0.
- It cannot be a GitLab issue as I checked webhook events and the repo name is correctly reported.

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure a GitLab repo with a webhook pointing to your k8s cluster where Argo Events is deployed, exposed and ready to receive events
2. Push anything to the GitLab repo and wait until the Workflow starts
3. Try multiple times as it seems to happen after triggering 2 Workflows
4. See weird Workflow name/title in the UI

**Expected behavior**
Workflow name should correspond to the repository name, in the example above `hdp-reader-mater-xyz` should be the correct name.

**Environment (please complete the following information):**
 - Kubernetes:    `v1.21.5-gke.1302`
 - Argo:   `v3.2.4`
 - Argo Events:   `v1.5.3`

**Additional context**
Kubernetes cluster is provided by GKE (private cluster).

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by bygui86** [comment]
@whynowy I will try to upgrade to v1.5.5 to see whether this bug is still there.

**Comment by bygui86** [comment]
@whynowy the upgrade didn't solve anything and Argo Events does not work well anymore.

Now I get this error in the Sensor:

```json
{"level":"error","ts":1640093210.553201,"logger":"argo-events.sensor","caller":"sensors/listener.go:315","msg":"failed to execute a trigger","sensorName":"sbt-gitlab-master-tags","error":"failed to execute trigger: timed out waiting for the condition: Workflow.argoproj.io \"signals-commonsignals-commonsignals-commonallocation-enginghtc4\" is invalid: [metadata.generateName: Invalid value: \"signals-commonsignals-commonsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-mrsignals-commonsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-mrsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-bets_propallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-developstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemastrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemastrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemasignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-developorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-serviceallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-teststrategy-risk-targetingallocation-engines-commonsignals-common-developallocation-engines-commonsignals-common-developsignals-common-develop-\": must be no more than 253 characters, metadata.generateName: Invalid value: \"signals-commonsignals-commonsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-mrsignals-commonsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-mrsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-bets_propallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-developstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemastrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemastrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemasignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-developorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-serviceallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-teststrategy-risk-targetingallocation-engines-commonsignals-common-developallocation-engines-commonsignals-common-developsignals-common-develop-\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]","errorVerbose":"timed out waiting for the condition: Workflow.argoproj.io \"signals-commonsignals-commonsignals-commonallocation-enginghtc4\" is invalid: [metadata.generateName: Invalid value: \"signals-commonsignals-commonsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-mrsignals-commonsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-mrsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-bets_propallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-developstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemastrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemastrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemasignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-developorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-serviceallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-teststrategy-risk-targetingallocation-engines-commonsignals-common-developallocation-engines-commonsignals-common-developsignals-common-develop-\": must be no more than 253 characters, metadata.generateName: Invalid value: \"signals-commonsignals-commonsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-mrsignals-commonsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-mrsignals-commonallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-bets_propallocation-engines-commonallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testallocation-engines-commonallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testallocation-engines-commonsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-testsignals-generators-commonstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-developstrategy-commonstrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemastrategy-commonstrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemastrategy-commonsignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-signals_generator_schemasignals-generators-commonorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-developorder-generators-commonallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-serviceallocation-engines-commonstrategy-risk-targetingallocation-engines-commonsignals-common-feature-data-service-teststrategy-risk-targetingallocation-engines-commonsignals-common-developallocation-engines-commonsignals-common-developsignals-common-develop-\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]\nfailed to execute trigger\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerOne\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:368\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:313\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:1581","triggerName":"gitlab-py-pack-trigger","triggeredBy":["gitlab-py-pack-dependency"],"triggeredByEvents":["66316264333233392d633032662d346537392d613065312d303131393030616364303737"],"stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:315"}
```

There is a sort of loop concatenating names of sequential events...
Can someone please give me feedback about this?

Thanks for any tip

**Comment by bygui86** [comment]
The issue seems to be in the Sensor templates.parameters, here an extract:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: external
spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: argo-events
        domain: ci
        component: sensor
      annotations:
        providers: "http, slack"

    serviceAccountName: argo-events-sensor
    securityContext:
      runAsUser: 1001

  dependencies:
    - name: http-py-pack-dependency
      eventSourceName: sbt
      eventName: http-py-pack-event
    - name: slack-py-pack-dependency
      eventSourceName: sbt
      eventName: slack-py-pack-event

  triggers:
    - template:
        conditions: http-py-pack-dependency
        name: http-py-pack-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            configmap:
              namespace: argo-events
              name: py-pack-workflow-store
              key: py-pack.yaml
          parameters:
            # generate name
            # *** ISSUE in generating Workflow names should be here ***
            - src:
                dependencyName: http-py-pack-dependency
                dataTemplate: '{{ .Input.body.repo_name | replace "_" "-" | replace "/" "-" | replace " " "-" | lower }}'
              dest: metadata.generateName
              operation: append
            - src:
                dependencyName: http-py-pack-dependency
                value: "-"   # fix value
              dest: metadata.generateName
              operation: append
            - src:
                dependencyName: http-py-pack-dependency
                dataTemplate: '{{ .Input.body.revision | replace "/" "-" | replace "_" "-" }}'
              dest: metadata.generateName
              operation: append
            - src:
                dependencyName: http-py-pack-dependency
                value: "-"   # fix value
              dest: metadata.generateName
              operation: append
            # labels
            - src:
                dependencyName: http-py-pack-dependency
                dataTemplate: '{{ .Input.body.repo_name | replace "_" "-" | replace "/" "-" | replace " " "-" | lower }}'
              dest: metadata.labels.repo
              operation: append
            - src:
                dependencyName: http-py-pack-dependency
                dataTemplate: '{{ .Input.body.revision | replace "/" "-" | replace "_" "-" }}'
              dest: metadata.labels.revision
              operation: append
            # values
            - src:
                dependencyName: http-py-pack-dependency
                dataKey: body.repo_url
              dest: spec.arguments.parameters.0.value   # repo_url
            - src:
                dependencyName: http-py-pack-dependency
                dataTemplate: '{{ .Input.body.repo_url | replace "https://gitlab.com/" "" }}'
              dest: spec.arguments.parameters.1.value   # context_path
            - src:
                dependencyName: http-py-pack-dependency
                dataKey: body.revision
              dest: spec.arguments.parameters.2.value   # revision
            - src:
                dependencyName: http-py-pack-dependency
                value: "http-trigger"
              dest: spec.arguments.parameters.3.value # checkout_sha

    - template:
        conditions: slack-py-pack-dependency
        name: slack-py-pack-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            configmap:
              namespace: argo-events
              name: py-pack-workflow-store
              key: py-pack.yaml
          parameters:
            # generate name
            - src:
                dependencyName: slack-py-pack-dependency
                dataTemplate: '{{- $s := .Input.text -}}{{- $l := splitList " " $s -}}{{ index $l 0 | replace "_" "-" | replace "/" "-" | replace " " "-" | lower }}'
              dest: metadata.generateName
              operation: append
            - src:
                dependencyName: slack-py-pack-dependency
                value: "-"   # fix value
              dest: metadata.generateName
              operation: append
            - src:
                dependencyName: slack-py-pack-dependency
                dataTemplate: '{{- $s := .Input.text -}}{{- $l := splitList " " $s -}}{{ index $l 2 | replace "/" "-" | replace "_" "-" }}'
              dest: metadata.generateName
              operation: append
            - src:
                dependencyName: slack-py-pack-dependency
                value: "-"   # fix value
              dest: metadata.generateName
              operation: append
            # labels
            - src:
                dependencyName: slack-py-pack-dependency
                dataTemplate: '{{- $s := .Input.text -}}{{- $l := splitList " " $s -}}{{ index $l 0 | replace "_" "-" | replace "/" "-" | replace " " "-" | lower }}'
              dest: metadata.labels.repo
              operation: append
            - src:
                dependencyName: slack-py-pack-dependency
                dataTemplate: '{{- $s := .Input.text -}}{{- $l := splitList " " $s -}}{{ index $l 2 | replace "/" "-" | replace "_" "-" }}'
              dest: metadata.labels.revision
              operation: append
            # values
            - src:
                dependencyName: slack-py-pack-dependency
                dataTemplate: '{{- $s := .Input.text -}}{{- $l := splitList " " $s -}}{{ index $l 1 }}'
              dest: spec.arguments.parameters.0.value   # repo_url
            - src:
                dependencyName: slack-py-pack-dependency
                dataTemplate: '{{- $s := .Input.text -}}{{- $l := splitList " " $s -}}{{ index $l 1 | replace "https://gitlab.com/" "" }}'
              dest: spec.arguments.parameters.1.value   # context_path
            - src:
                dependencyName: slack-py-pack-dependency
                dataTemplate: '{{- $s := .Input.text -}}{{- $l := splitList " " $s -}}{{ index $l 2 }}'
              dest: spec.arguments.parameters.2.value   # revision
            - src:
                dependencyName: slack-py-pack-dependency
                value: "slack-trigger"
              dest: spec.arguments.parameters.4.value # checkout_sha
```
