### ISSUE TITLE
SQS eventsource not able to get sts credentials

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#1485]
creating this event source gave below error.

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: aws-sqs
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
          name: aws-iam-token
      env:
        - name: AWS_ROLE_ARN
          value: "arn:aws:iam::redact:role/redact"
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    volumes:
      - name: aws-iam-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 86400
              path: token
  sqs:
    example-without-credentials:
      region: "eu-west-1"
      queue: "somename"
      waitTimeSeconds: 20
```

```
{"level":"info","ts":1640322992.9525466,"logger":"argo-events.eventsource","caller":"awssqs/start.go:67","msg":"started processing the AWS SQS event source...","eventSourceName":"aws-sqs","eventSourceType":"sqs","eventName":"example-without-credentials"}
{"level":"info","ts":1640322992.9527712,"logger":"argo-events.eventsource","caller":"awssqs/start.go:80","msg":"fetching queue url...","eventSourceName":"aws-sqs","eventSourceType":"sqs","eventName":"example-without-credentials"}
{"level":"error","ts":1640323113.2503262,"logger":"argo-events.eventsource","caller":"awssqs/start.go:90","msg":"Error getting SQS Queue URL","eventSourceName":"aws-sqs","eventSourceType":"sqs","eventName":"example-without-credentials","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.amazonaws.com/\": dial tcp 54.239.29.25:443: i/o timeout","stacktrace":"github.com/argoproj/argo-events/eventsources/sources/awssqs.(*EventListener).StartListening\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/awssqs/start.go:90\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3.1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:396\ngithub.com/argoproj/argo-events/common.Connect.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:107\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4-rc.0/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4-rc.0/pkg/util/wait/wait.go:399\ngithub.com/argoproj/argo-events/common.Connect\n\t/home/runner/work/argo-events/argo-events/common/retry.go:106\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:395"}
```

i'm on latest version
