### ISSUE TITLE
[NEWBIE] Does data filter allow partial matches?

### ISSUE THREAD

**Issue by fentonfentonfenton** [argoproj/argo-events#1515]
**Describe the bug**
Given a data filter
```
    - name: pull-request-labeled
    ...
      filters:
        data:
          - path: body.action
            type: string
            value:
              - labeled
...
```

which triggers one workflow

and a data filter

```
    - name: pull-request-labeled
    ...
      filters:
        data:
          - path: body.action
            type: string
            value:
              - unlabeled
...
```
which triggers another workflow.

I am getting the workflow 1) triggered by both payloads and the workflow 2) triggered by an `unlabeled` payload only.

**To Reproduce**

I did some investigation and think (too new to the code) it might be down to `regexp.match`
https://github.com/argoproj/argo-events/blob/f91e05905ae55094912ff1153b80fd3736db7727/sensors/dependencies/filter.go

```
package main

import (
	"fmt"
	"regexp"
)

func main() {
	re := regexp.MustCompile(`labeled`)
	fmt.Println(re.Match([]byte(`unlabeled`)))
	fmt.Println(re.Match([]byte(`labeled`)))

}
```
```
true
true
```

**Expected behavior**
Change the regexp match so output is..

```
false
true
```

**Additional context**
I wish I could be less vague, but I am new to the codebase and might be misunderstanding this.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
