### ISSUE TITLE
dataKey missing from argo_archived_workflows persistence table

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#1520]
I created kind: Sensor and last part of yaml has this:

```
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
```

but these values like dataKey don't show up in the persistence table: argo_archived_workflows
