### ISSUE TITLE
Allow setting sensor parameters by names

### ISSUE THREAD

**Issue by Nizar-opt** [argoproj/argo-events#1534]
**Is your feature request related to a problem? Please describe.**
[sjson](https://github.com/tidwall/sjson) package has a feature to [Allow for updating values using queries and wildcards.](https://github.com/tidwall/sjson/commit/0bc94ab89f8a5d8cea208fb1146f65aa92064119) which was introduced in v1.2.0.

argo-events still use [v1.1.1](https://github.com/argoproj/argo-events/blob/18ca4a1316886f7f984bfc13e1cced412aca197a/go.mod#L67) which only allows setting paths by index:
```yaml
            # sjson v1.1.1
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
```

**Describe the solution you'd like**
if argo-events upgraded sjson to >=v1.2.0 it would be possible to set parameters by names. e.g:
```yaml
            # sjson v1.2.4
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.#(name=="message").value #instead of spec.arguments.parameters.0.value
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@Nizar-opt - would you like to submit a PR to upgrade it?

**Comment by Nizar-opt** [comment]
@whynowy sure

**Comment by dellnoantechnp** [comment]
Environment info:
> Version: argo-events:v1.8.1
> Helm chart: argo-events 2.4.1
---

I checked argo-event version 1.6.0 

I think `triggers.template.argoWorkflow.parameters.dest` is [sjson](https://github.com/tidwall/sjson) library.

So, both `dest: spec.arguments.parameters.0.value` and `dest: spec.arguments.parameters.#(name=="ENV").value` is same result. 

But isn't .
```yaml
kind: Sensor
spec:
  triggers:
    - template:
        argoWorkflow:
          source:
            resource:
             ...
             spec:
               arguments:
                 parameters:
                   - name: var1
                   - name: ENV
          parameters:
            - src:
                dependencyName: ci-java-dependency
                dataKey: body.ref
              dest: spec.arguments.parameters.0.value                   <---  It's worked
            - src:
                dependencyName: ci-java-dependency
                dataTemplate: '{{ .Input.body.ref | trimPrefix "refs/heads/" | lower }}'
              dest: spec.arguments.parameters.#(name=="ENV").value            <--- Isn't work
```

I got this sensor pod config on env `SENSOR_OBJECT` output:

```shell
kubectl get pod -n workflows test-sensor-pp6gj-785f674886-jhxlx -o jsonpath=''{.spec.containers[].env[?(@.name=="SENSOR_OBJECT")].value}' | base64 -d | jq '.spec.triggers[0].template.argoWorkflow.parameters'
```
```json
[
  {
    "src": {
      "dependencyName": "ci-java-dependency",
      "dataKey": "body.ref"
    },
    "dest": "spec.arguments.parameters.1.value"
  },
  {
    "src": {
      "dependencyName": "ci-java-dependency",
      "dataTemplate": "{{ .Input.body.ref | trimPrefix \"refs/heads/\" | lower }}"
    },
    "dest": "spec.arguments.parameters.#(name==\"ENV\").value"       <----- looks like correct
  },
  .....
```

But, argo-event `sensor` pod log line:
```log
time="2024-04-24T06:51:20.046Z" level=fatal msg="Failed to submit workflow: rpc error: code = InvalidArgument desc = spec.arguments.ENV.value is required"
```

What's wrong ??

**Comment by Nizar-opt** [comment]
@dellnoantechnp  this format expects an existing `value` key to be updated, it doesn't append a new key. Just add an empty `value` key like below:
```yaml
             spec:
               arguments:
                 parameters:
                   - name: var1
                   - name: ENV
                     value: ""
```
