### ISSUE TITLE
AMQP EventSource connection stuck at "started processing" state

### ISSUE THREAD

**Issue by eriadam** [argoproj/argo-events#1545]
**Describe the bug**

The EventSource is added without any issues, but there is no visible connection to RabbitMQ. When looking at the pod's log I see  that the connection process keeps printing `"started processing the AMQP event source..."` without any error message.

```
{"level":"info","ts":1643026693.572316,"logger":"argo-events.eventsource","caller":"cmd/start.go:63","msg":"starting eventsource server","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","version":"v1.5.6"}
{"level":"info","ts":1643026693.5732281,"logger":"argo-events.eventsource","caller":"metrics/metrics.go:172","msg":"starting metrics server","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026693.5783186,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:122","msg":"Not the LEADER, stand by ...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.479639,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:131","msg":"Becoming a Candidate, stand by ...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.4800801,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:128","msg":"I'm the LEADER, starting ...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.4801247,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:318","msg":"Starting event source server...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.480536,"logger":"argo-events.eventsource","caller":"driver/nats.go:93","msg":"NATS auth strategy: Token","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","clientID":"client-argo-events-rabbitmq-event-source-dev-sandbox-eventsource-h2v62-675"}
{"level":"info","ts":1643026694.4826007,"logger":"argo-events.eventsource","caller":"driver/nats.go:105","msg":"Connected to NATS server.","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","clientID":"client-argo-events-rabbitmq-event-source-dev-sandbox-eventsource-h2v62-675"}
{"level":"info","ts":1643026694.4841583,"logger":"argo-events.eventsource","caller":"driver/nats.go:118","msg":"Connected to NATS streaming server.","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","clientID":"client-argo-events-rabbitmq-event-source-dev-sandbox-eventsource-h2v62-675"}
{"level":"info","ts":1643026694.4841876,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:438","msg":"Eventing server started.","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.484225,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:341","msg":"starting eventbus connection daemon...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox"}
{"level":"info","ts":1643026694.4842942,"logger":"argo-events.eventsource","caller":"amqp/start.go:66","msg":"started processing the AMQP event source...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","eventSourceType":"amqp","eventName":"fileUploadSucceess"}
{"level":"info","ts":1643026715.7225106,"logger":"argo-events.eventsource","caller":"amqp/start.go:66","msg":"started processing the AMQP event source...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","eventSourceType":"amqp","eventName":"fileUploadSucceess"}
{"level":"info","ts":1643026727.787872,"logger":"argo-events.eventsource","caller":"amqp/start.go:66","msg":"started processing the AMQP event source...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","eventSourceType":"amqp","eventName":"fileUploadSucceess"}
{"level":"info","ts":1643026742.1286154,"logger":"argo-events.eventsource","caller":"amqp/start.go:66","msg":"started processing the AMQP event source...","eventSourceName":"argo-events-rabbitmq-event-source-dev-sandbox","eventSourceType":"amqp","eventName":"fileUploadSucceess"}
```

(UPDATE: `DEBUG` logs don't show more info either.)

I have a managed Amazon MQ instance and use the `amqps://` protocol, and username and password to connect. I provide no additional TLS configuration.

**Expected behavior**
Connection succeeds or an error is thrown.

**Environment (please complete the following information):**
 - Kubernetes: v1.21 (AWS EKS)
 - Argo: v3.2.6
 - Argo Events: v1.5.6

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by eriadam** [comment]
I found that the [connection error is not immediately logged](https://github.com/argoproj/argo-events/blob/befe7ea5d924c382de519b1f684e33a94d95983e/eventsources/sources/amqp/start.go#L110) to the console as the connection retry/backoff logic kicks in. Only when the `common.Connect` returns, would the error be printed.

```
2022-01-25T21:29:30.784Z	INFO	argo-events.eventsource	eventsources/eventing.go:347	exiting eventbus connection daemon...	{"eventSourceName": "argo-events-rabbitmq-event-source-dev-sandbox-2"}
2022-01-25T21:29:30.786Z	ERROR	argo-events.eventsource	driver/nats.go:84	NATS connection lost	{"eventSourceName": "argo-events-rabbitmq-event-source-dev-sandbox-2", "clientID": "client-argo-events-rabbitmq-event-source-dev-sandbox-2-eventsourch4bpl-23"}
github.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).Connect.func1
	/home/runner/work/argo-events/argo-events/eventbus/driver/nats.go:84
github.com/nats-io/nats%2ego.(*Conn).close.func1
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.13.0/nats.go:4720
github.com/nats-io/nats%2ego.(*asyncCallbacksHandler).asyncCBDispatcher
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.13.0/nats.go:2523
2022-01-25T21:29:30.786Z	FATAL	argo-events.eventsource	eventsources/eventing.go:305	failed to start	{"eventSourceName": "argo-events-rabbitmq-event-source-dev-sandbox-2", "error": "no active event server running", "errorVerbose": "no active event server running\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:458\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:304\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:1581"}
github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func1
	/home/runner/work/argo-events/argo-events/eventsources/eventing.go:305
```

**Comment by eriadam** [comment]
Also, if I get rid of the secret with the username and password and specify them in the URL instead `amqps://username:password@rabbit-instance`, the connection works without a problem

**Comment by whynowy** [comment]
Can you share the eventsource spec?

**Comment by eriadam** [comment]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: rabbitmq-event-source
  namespace: argo-events-dev-sandbox
spec:
  eventBusName: event-bus
  replicas: 1
  template:
    container:
      env:
        - name: DEBUG_LOG
          value: "true"
  amqp:
    fileUploadSucceess:
      url: "amqps://****"
      jsonBody: true
      exchangeName: "dev.ms.edge-upload"
      exchangeType: "topic"
      routingKey: "upload.succeeded"
      connectionBackoff:
        duration: 10s
        steps: 3
        factor: 1
        jitter: 0.2
      exchangeDeclare:
        durable: true
        autoDelete: false
        internal: false
        noWait: false
      queueDeclare:
        name: "dev-argo-events-file-upload-queue"
        durable: true
        autoDelete: false
        exclusive: true
        noWait: false
      queueBind:
        noWait: false
      consume:
        consumerTag: "dev-argo-events-file-upload-consumer-tag"
        autoAck: true
        exclusive: false
        noLocal: false
        noWait: false
      auth:
        username:
          name: rabbit-mq-credentials
          key: username
        password:
          name: rabbit-mq-credentials
          key: password
      tls:

```
