### ISSUE TITLE
Calendar events firing, but Workflow not triggered.

### ISSUE THREAD

**Issue by groodt** [argoproj/argo-events#155]
**Describe the bug**
Trying to use the Calendar Gateway to trigger an Argo Workflow. The event appears to be firing, but the Workflow is not triggered.

**To Reproduce**
1. apply the following k8s spec to an argo-events installation (argo namespace)
```
---
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  labels:
    gateway-name: calendar-gateway
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
  name: calendar-gateway
  namespace: argo
spec:
  configMap: calendar-gateway-configmap
  deploySpec:
    containers:
    - command:
      - /bin/calendar-gateway
      image: argoproj/calendar-gateway
      imagePullPolicy: Always
      name: calendar-events
    serviceAccountName: argo-events-sa
  dispatchMechanism: HTTP
  eventVersion: "1.0"
  imageVersion: latest
  type: calendar
  watchers:
    sensors:
    - name: example-pipeline-sensor
---
apiVersion: v1
data:
  example-pipeline: 'schedule: 30 * * * *'
kind: ConfigMap
metadata:
  name: calendar-gateway-configmap
  namespace: argo
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
  name: example-pipeline-sensor
  namespace: argo
spec:
  imagePullPolicy: Always
  imageVersion: latest
  repeat: true
  serviceAccountName: argo-events-sa
  signals:
  - name: calendar-gateway/example-pipeline
  triggers:
  - name: example-pipeline-trigger
    resource:
      group: argoproj.io
      kind: Workflow
      namespace: argo
      source:
        inline: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: hello-world-
          spec:
            entrypoint: whalesay
            templates:
              - name: whalesay
                container:
                  args:
                    - "hello world"
                  command:
                    - cowsay
                  image: "docker/whalesay:latest"
      version: v1alpha1
```

**Expected behavior**
I expect the workflow to be scheduled on the hour at 30 minutes past the hour as per the cron schedule.
