### ISSUE TITLE
Multiple workflows triggered on a single event

### ISSUE THREAD

**Issue by chandanpjain** [argoproj/argo-events#1576]
### Discussed in https://github.com/argoproj/argo-events/discussions/1566

<div type='discussions-op-text'>

<sup>Originally posted by **chandanpjain** January 27, 2022</sup>
We have configured an eventsource to watch on changes to an argo application and trigger argo workflow based on this event. Everytime this event is triggered, we are observing 4 workflows starting in parallel (a few seconds apart). Eventhough this is not creating any issue with the result we want, this is creating unnecessary noise. Could we get some help to understand what could be wrong in the follow filter we are using?

![image](https://user-images.githubusercontent.com/11813513/151242584-16dd42a8-1d0b-427f-8b56-116a368da09a.png)

```
spec:
  template:
    serviceAccountName: {{ .Values.serviceaccountname }}
  resource:
    {{ .Values.eventsource.eventname }}:
      group: argoproj.io
      version: v1alpha1
      resource: applications
      eventTypes:
        - UPDATE
      filter:
        afterStart: true
        fields:
          - key: status.sync.status
            operation: ==
            value: OutOfSync
          - key: status.operationState.phase
            operation: ==
            value: Failed
        labels:
          - key: app
            operation: ==
            value: foo
```</div>

**Comment by whynowy** [comment]
Can you use a `log` trigger to see how many events the event source watched? I believe there were 4. Compare those events to see if there's anything to distinguish them.

**Comment by chandanpjain** [comment]
Hi @whynowy - thanks for your `log` trigger suggestion.
The differences observed between events is a list of fields like `generation`, `resourceVersion`, `status` and `reconcileAt`. My guess is `status` is the one causing multiple triggers as the argocd application is transitioning between `Healthy`, `Progressing`, `Running`, `Failed` statuses.

We are not really sure how we can distinguish events to consider only the first one and not the others.

**Comment by chandanpjain** [comment]
We have picked up one of our paused projects again and continuing on the previous comment, with additional condition `status.health.status == Healthy`, we were able to get the number of triggers from 4 to 2. Any insights to avoid the duplicate trigger is really appreciated. 

Our current filters
```
  resource:
    check-app-updates:
      eventTypes:
        - UPDATE
      filter:
        afterStart: true
        createdBy: null
        fields:
          - key: status.sync.status
            operation: '=='
            value: OutOfSync
          - key: status.operationState.phase
            operation: '=='
            value: Failed
          - key: status.health.status
            operation: '=='
            value: Healthy
          - key: metadata.labels.app
            operation: '=='
            value: foo
      group: argoproj.io
      namespace: argocd
      resource: applications
      version: v1alpha1
```
