### ISSUE TITLE
Limit Triggers To a branch or Pull Requests

### ISSUE THREAD

**Issue by MazenElzanaty** [argoproj/argo-events#1605]
**Is your feature request related to a problem? Please describe.**
Currently I'm using argo workflows to build and push a docker image, so I only want to do that for a specific branch

**Describe the solution you'd like**
A way to limit the events in the event source to branches

**Comment by whynowy** [comment]
You can use the filtering feature in either eventsource or sensor.

https://github.com/argoproj/argo-events/blob/master/docs/eventsources/filtering.md

https://github.com/argoproj/argo-events/tree/master/docs/sensors/filters

**Comment by iamnst19** [comment]
@whynowy can you please provide a sample I can use for bitbucket?
```
filter:
  data:
    - path: "ref" # Path to the branch reference in the event payload
      type: "string"
      value:
        - "refs/heads/release" # The branch name you want to match

```
