### ISSUE TITLE
The \ is added to the end of the file event .name payload, making the workflow impossible to trigger

### ISSUE THREAD

**Issue by eferos93** [argoproj/argo-events#1636]
**Describe the bug**
When triggering a workflow and passing payload data to the workflow name, it happens \ at the end, making the workflow unable to start.
Here's the sensor code:
This is the sensor.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: directory-sensor
  namespace: tesi-fabrici
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
  - name: directory-es 
    eventSourceName: directory-event-source
    eventName: directoryCreated
  triggers:
    - template:
        name: url-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            url:
              path: "https://raw.githubusercontent.com/eferos93/genomic-pipeline/main/miseq-wf-event.yaml"
              verifycert: false 
          parameters:
            - src:
                dependencyName: directory-es
                dataKey: name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: directory-es
                # dataTemplate: "{{ .Input.name | substr 0 17 | trimSuffix '\\' }}"
                dataTemplate: "{{ .Input.name }}"
              #   dataKey: name'
              dest: metadata.name
              operation: prepend
```
the EventSource
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: directory-event-source
  namespace: tesi-fabrici
spec:
  template: 
    container:
      volumeMounts:
        - mountPath: /test_dir
          name: test-dir
    volumes: 
      - name: test-dir
        nfs: 
          server: 10.128.2.231
          path: /tesi_fabrici
  file:
    directoryCreated:
      polling: true
      watchPathConfig:
        directory: "/test_dir/watched_dir/"
        pathRegexp: "^([0-9]*)_([A-Z0-9]*)_([0-9]*)_000000000-([A-Z0-9]*)"
      eventType: CREATE
```

and the workflow
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  # generateName: production-workflow-
  name: "-workflow" #substituded by sensor
  namespace: tesi-fabrici
spec:
  serviceAccountName: tesi-fabrici-user
  volumes:
    - name: external-volume-test
      nfs: 
        server: 10.128.2.231
        path: /tesi_fabrici
    - name: external-volume-prod
      nfs: 
        server: 10.128.2.231
        path: /illumina_run
  entrypoint: genomic-workflow
  arguments:
    parameters:
      - name: input-dir
        value: ' ' # this will be overwritten by sensor
      - name: base-input-dir
        value: "{{='genomic_data_test/watched_dir/' + workflow.parameters['input-dir']}}"
      - name: base-output-dir
        value: "{{='genomic_data_test/output/' + workflow.parameters['input-dir'] }}"
  templates:
    - name: genomic-workflow
      parallelism: 4
      steps:
        - - name: data-handling-step
            templateRef:
              name: genomic-workflow-template
              template: data-handling
            arguments:
              parameters:
                - name: input-dir
                  value: "{{workflow.parameters.base-input-dir}}"
                - name: samples-output-path
                  value: "{{=workflow.parameters['base-output-dir'] + '/dataframes'}}"
                - name: samples-filename
                  value: "samples.csv"

        - - name: bcl2fastq-step
            templateRef:
              name: genomic-workflow-template
              template: bcl2fastq-prod
            arguments:
              parameters:
                - name: sample-sheet-path
                  value: "{{=jsonpath(steps['data-handling-step'].outputs.result, '$.sample-sheet-path')}}" 
                - name: input-path
                  value: "{{workflow.parameters.base-input-dir}}"
                - name: fastq-dir
                  value: "{{=workflow.parameters['base-output-dir'] + '/0.FASTQ'}}"
        
        - - name: fastqc-step
            templateRef:
              name: genomic-workflow-template
              template: fastqc
            arguments:
              parameters:
                - name: threads
                  value: "2"
                - name: output-dir
                  value: "{{=workflow.parameters['base-output-dir'] + '/1.FASTQC'}}"
                - name: input-file1
                  value: "{{item.file1}}"
                - name: input-file2
                  value: "{{item.file2}}"
                - name: input-dir
                  value: "{{=workflow.parameters['base-output-dir'] + '/0.FASTQ/'}}"
            withParam: "{{=jsonpath(steps['data-handling-step'].outputs.result, '$.fastq-names')}}"

        - - name: multiqc-step
            templateRef:
              name: genomic-workflow-template
              template: multiqc
            arguments:
              parameters:
                - name: input-output-dir
                  value: "{{=workflow.parameters['base-output-dir'] + '/1.FASTQC'}}"
                - name: ignore-param
                  value: "Undetermined*"
                - name: qc-name
                  value: multiqc_results
```

When the sensor perceives the event, it fails to trigger the workflow, because it appends \ at the end and therefore the name is not valid. 
I tried to use Sprig functions to remove it, but it appears that the \ is appended after the functions are applied.

Does anybody know if this is an intended feature or a bug?

**Error**
namespace=tesi-fabrici, sensorName=directory-sensor, level=info, time=2022-02-15T12:37:17Z, msg=time="2022-02-15T12:37:17.373Z" level=error msg="Create request failed: Workflow.
argoproj.io \"220211_M70903_0039_000000000-K7V7F-workflow\" is invalid: metadata.name: Invalid value: \"220211_M70903_0039_000000000-K7V7F-workflow\": a lowercase RFC 1123 subdo
main must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-
z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
namespace=tesi-fabrici, sensorName=directory-sensor, level=info, time=2022-02-15T12:37:17Z, msg=time="2022-02-15T12:37:17.373Z" level=fatal msg="Failed to submit workflow: rpc e
rror: code = InvalidArgument desc = Workflow.argoproj.io \"220211_M70903_0039_000000000-K7V7F-workflow\" is invalid: metadata.name: Invalid value: \"220211_M70903_0039_000000000
-K7V7F-workflow\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'ex
ample.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
namespace=tesi-fabrici, sensorName=directory-sensor, triggerName=url-workflow-trigger, level=error, time=2022-02-15T12:37:17Z, msg=failed to execute a trigger

  **Expected behavior**
I expect not have a \ at the end of the payload.

**Environment (please complete the following information):**
Kubernetes: 1.21.1
kubectl: v1.23.1
Argo: v3.2.6+db7d90a.dirty
Argo Events: 1.5.6

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
