### ISSUE TITLE
Trigger argoworkflow from cluster workflow template and workflow template

### ISSUE THREAD

**Issue by rwong2888** [argoproj/argo-events#1678]
Would like the ability to trigger argo workflow with cluster workflow template or workflow template

**Comment by zhongdai** [comment]
This can be done, and here is the example `Sensor`, it triggers a `Workflow` based on a `ClusterWorkflowTemplate` - `cluster-workflow-template-submittable`.

Just be noted,

- The triggered `Workflow` will be running in `argo-events`, but not in `argo`
- You need to create a `ServiceAccount` with proper permission in `argo-events`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-webhook-1
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: es-webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger-1
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: cluster-wftmpl-triggered-by-sensor-1-
                # namespace: argo-events
              spec:
                serviceAccountName: workflow-pods-sa # default is `default`
                nodeSelector:
                  usage: generic-workload
                entrypoint: whalesay-template
                arguments:
                  parameters:
                  - name: message
                    value: "from workflow not cluster template"
                workflowTemplateRef:
                  name: cluster-workflow-template-submittable
                  clusterScope: true
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.message
              dest: spec.arguments.parameters.0.value
```
