### ISSUE TITLE
Long running sensors

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#17]
**Is your feature request related to a problem? Please describe.**
When a signal resolves, we resolve the state of sensor (consider it contains only one signal). If the sensor is repeatable, we reinitialize the sensor after the trigger is complete. But in case of signals like webhook, we want to keep HTTP server running and want to stop the signal only if it runs past certain predefined time or user/some process stops the signal.

**Describe the solution you'd like**
Add "type" to signal which specifies whether a signal is resolved when a single event occurs or it lives as long as specified timeout occurs. Timeout will be optional field, as we may want to keep the sensor running. 

example-

1) 
```
signals:
  - name: signal1
     mqtt:
        url: tcp://localhost:1883
        type: singular
        topic: hello
    name: signal2
```

2)
```
signals:
  - name: signal2
    webhook:
        port: 9000
        endpoint: "/app"
        method: "POST"
        type: continuous
        timeout: 10000s
```
