### ISSUE TITLE
Add custom key-value pair to sensor trigger payload

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-events#1776]
**Is your feature request related to a problem? Please describe.**
We want to enrich a Nats message with a json payload. The payload contains key-value pairs based on the sensor itself, not on the dependency. Thus, the key-value pairs needed to be set in the payload are not part of the payload of the dependency.

**Describe the solution you'd like**
I would like to add a key-value pair to the payload which does not have a source in the dependency event payload. Like shown with the following example of `someKey: someValue` in the trigger payload.

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: minio-sensor
spec:
  dependencies:
    - name: test-dep
      eventSourceName: minio
      eventName: example
  triggers:
    - template:
        name: nats-trigger
        nats:
          # NATS Server URL
          url: nats.argo-events.svc:4222
          # Name of the subject
          subject: minio-events
          payload:
            - someKey: someValue
            - src:
                dependencyName: test-dep
                dataKey: notification.0.s3.object.key
              dest: fileName
```

**Describe alternatives you've considered**
Reading the docs I have currently not found any way to do what I want to do.

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
