### ISSUE TITLE
Overwrite revisionHistoryLimit for Sensor Deployment

### ISSUE THREAD

**Issue by nice-pink** [argoproj/argo-events#1786]
**Is your feature request related to a problem? Please describe.**
When working on the sensors the ArgoCD UI gets pretty messy showing all these old sensor replica sets. It would be nice to be able to set the _revisionHistoryLimit_ of the sensor deployment.

**Describe the solution you'd like**
Use _revisionHistoryLimit_ in sensor to overwrite/set _revisionHistoryLimit_ in sensor deployment.

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-name
spec:
  revisionHistoryLimit: 0
  template:
    serviceAccountName: argo-events-sa
```

**Describe alternatives you've considered**
Set default _revisionHistoryLimit_ in a global argo-events config.

**Additional context**
-

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
