### ISSUE TITLE
Error creating stream with race condition

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1808]
Seeing following error when starting everything from scratch:

{"level":"info","ts":1649054772.4931114,"logger":"argo-events.sensor","caller":"cmd/start.go:73","msg":"starting sensor server","sensorName":"calendar","version":"latest+3ec3713.dirty"}
{"level":"info","ts":1649054772.4936495,"logger":"argo-events.sensor","caller":"metrics/metrics.go:172","msg":"starting metrics server","sensorName":"calendar"}
{"level":"info","ts":1649054772.496852,"logger":"argo-events.sensor","caller":"leaderelection/leaderelection.go:135","msg":"Not the LEADER, stand by ...","sensorName":"calendar"}
{"level":"info","ts":1649054773.285409,"logger":"argo-events.sensor","caller":"leaderelection/leaderelection.go:144","msg":"Becoming a Candidate, stand by ...","sensorName":"calendar"}
{"level":"info","ts":1649054773.2858882,"logger":"argo-events.sensor","caller":"leaderelection/leaderelection.go:141","msg":"I'm the LEADER, starting ...","sensorName":"calendar"}
{"level":"info","ts":1649054773.2862754,"logger":"argo-events.sensor","caller":"base/jetstream.go:75","msg":"NATS auth strategy: Basic","sensorName":"calendar"}
{"level":"info","ts":1649054773.2909963,"logger":"argo-events.sensor","caller":"base/jetstream.go:97","msg":"Connected to NATS Jetstream server.","sensorName":"calendar"}
{"level":"error","ts":1649054778.270138,"logger":"argo-events.sensor","caller":"base/jetstream.go:114","msg":"Error calling StreamInfo for Stream '%s': %v","sensorName":"calendar","default":"context deadline exceeded","stacktrace":"github.com/argoproj/argo-events/eventbus/jetstream/base.(*Jetstream).CreateStream\n\t/Users/jwang21/workspace/argoproj/argo-events/eventbus/jetstream/base/jetstream.go:114\ngithub.com/argoproj/argo-events/eventbus/jetstream/base.(*Jetstream).Init\n\t/Users/jwang21/workspace/argoproj/argo-events/eventbus/jetstream/base/jetstream.go:45\ngithub.com/argoproj/argo-events/eventbus/jetstream/sensor.(*SensorJetstream).Initialize\n\t/Users/jwang21/workspace/argoproj/argo-events/eventbus/jetstream/sensor/sensor_jetstream.go:54\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents.func1\n\t/Users/jwang21/workspace/argoproj/argo-events/sensors/listener.go:110\ngithub.com/argoproj/argo-events/common.Connect.func1\n\t/Users/jwang21/workspace/argoproj/argo-events/common/retry.go:107\nk8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1\n\t/Users/jwang21/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:220\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/Users/jwang21/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/Users/jwang21/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:226\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/Users/jwang21/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:421\ngithub.com/argoproj/argo-events/common.Connect\n\t/Users/jwang21/workspace/argoproj/argo-events/common/retry.go:106\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).listenEvents\n\t/Users/jwang21/workspace/argoproj/argo-events/sensors/listener.go:109\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).Start.func1\n\t/Users/jwang21/workspace/argoproj/argo-events/sensors/listener.go:67"}
{"level":"info","ts":1649054778.2705145,"logger":"argo-events.sensor","caller":"base/jetstream.go:136","msg":"Will use this stream config:\n '{default  [default.*.*] Limits 0 50000 -1 DiscardOld 168h0m0s 0 0 File 3 false  5m0s <nil> <nil> [] false false false false}'","sensorName":"calendar"}

**Reproduce:**
1. Create a JetStream EventBus;
2. `kubectl apply` following yaml, you will see the error from either the event source pod or the sensor pod.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: calendar
spec:
  calendar:
    example1:
      interval: 30s
    example2:
      interval: 10s
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: calendar
spec:
  dependencies:
    - name: test-dep
      eventSourceName: calendar
      eventName: example2
  triggers:
    - template:
        name: http-trigger1
        http:
          url: https://medium.com/
          method: GET
      retryStrategy:
        steps: 3
        durations: 2s
    - template:
        name: log-trigger
        log: {}
```
