### ISSUE TITLE
currenttimestamp format?

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#1812]
my sensor is complaining about dataTemplate format

```
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataTemplate: "{{ now | unixEpoch }}-"
              dest: metadata.generateName
              operation: append
```
