### ISSUE TITLE
Bitbucket eventsource returns error from eventsource controller

### ISSUE THREAD

**Issue by BabySpinach** [argoproj/argo-events#1826]
When deploying the bitbucket event source to k8s, the event source controller returns an error.

kubectl get eventsources shows my eventsource with no errors.

Controller throws when trying to read the yaml.

Details:

Argo events version from running manifest: 1.6.0
Argo events API version references for yaml and crds: 1.6.0

Event source yaml:
`
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: "bitbucket"
  namespace: "argo"
spec:
  bitbucket:
    deleteHookOnFinish: "true"
    webhook:
      endpoint: "/push"
      port: "12000"
      method: "POST"
      url: "https://argo-bitbucket-webhook.<my-domain-removed>"
    auth:
      basic:
        password:
          key: "password"
          name: "bitbucket-creds"
        username:
          key: "username"
          name: "bitbucket-creds"
    # events to listen to
    # Visit https://support.atlassian.com/bitbucket-cloud/docs/manage-webhooks/
    events:
      - repo:push
    projectKey: "argo-bitbucket-webhook"
    owner: "<removed my product owner>"
    repositorySlug: "argo-workflow-examples-app"
  service:
    ports:
      - port: "12000"
        targetPort: "12000"
  eventBusName: "eventbus-controller"
`

Event source controller error response: k logs argo-events-eventsource-controller-659464979d-5cg8m

`reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.6/tools/cache/reflector.go:167: Failed to watch *v1alpha1.EventSource: failed to list *v1alpha1.EventSource: v1alpha1.EventSourceList.Items: []v1alpha1.EventSource: v1alpha1.EventSource.Spec: v1alpha1.EventSourceSpec.Bitbucket: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|nFinish":"true","eve|..., bigger context ...|"name":"bitbucket-creds"}}},"deleteHookOnFinish":"true","events":["repo:push"],"owner":"my-org|..`

Expected behavior:
The controller loads the eventsource and configures a bitbucket webhook. No parsing error is thrown.

**Comment by daniel-codefresh** [comment]
Hey @BabySpinach ! By looking at the yaml you've provided here it seems that it has lots of issues here but none of them got to do with the logic of the Bitbucket event source. 
This is the correct version of the yaml (please note the comments inside the yaml):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: "bitbucket"
  namespace: "argo"
spec:
  bitbucket:
    push: # You must have an event name under the event type, and the event definition should be under the event name
      deleteHookOnFinish: true # The type of this field is boolean, therefore you cannot wrap its value inside " "
      webhook:
        endpoint: "/push"
        port: "12000"
        method: "POST"
        url: "https://argo-bitbucket-webhook.<my-domain-removed>"
      auth:
        basic:
          password:
            key: "password"
            name: "bitbucket-creds"
          username:
            key: "username"
            name: "bitbucket-creds"
      events:
        - repo:push
      projectKey: "argo-bitbucket-webhook"
      owner: "<removed my product owner>"
      repositorySlug: "argo-workflow-examples-app"
  service:
    ports:
      - port: 12000 # The type of this field is integer, therefore you cannot wrap its value inside " "
        targetPort: "12000"
  eventBusName: "my-eventbus" # The previous value here was "eventbus-controller" which I'm pretty sure is a mistake because this field should refer to a name of an EventBus resource and not the controller
```

Please refer to the EventSource [specification](https://github.com/argoproj/argo-events/blob/master/api/event-source.md#argoproj.io/v1alpha1.EventSourceSpec) for more info. 
TIP: you could prevent similar mistakes in the future by validating your yamls using the existing [json schema](https://github.com/argoproj/argo-events/blob/master/api/jsonschema/schema.json) from the repo, or by installing a [Validating Admission Webhook](https://argoproj.github.io/argo-events/validating-admission-webhook/) in your cluster.
