### ISSUE TITLE
HA Sensor has very frequent Leadership changes when running in GKE

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-events#1850]
**Describe the bug**
Running a Sensor with 2 replicas in GKE. Every few minutes I see in the leader's log:
2022-04-14T20:59:31.177Z	INFO	argo-events.sensor	leaderelection/leaderelection.go:153	Becoming a Follower, stand by ...	{"sensorName": "webhook"}

Note that I am also trying an HA (Calendar) EventSource and it doesn't seem to be happening there.

**To Reproduce**
Run this Sensor:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  replicas: 2
  template:
    container:
      image: docker.io/julievogelman/argo-events:fmea
      env:
        - name: DEBUG_LOG
          value: "true"


  eventBusName: jetstream-ex

  dependencies:
    - name: test-dep-a
      eventSourceName: webhook
      eventName: example
    - name: test-dep-b
      eventSourceName: webhook
      eventName: example2
    - name: test-dep-c
      eventSourceName: webhook
      eventName: example3
  triggers:
    - template:
        conditions: "test-dep-a && test-dep-b && test-dep-c"
        conditionsReset: 
          - byTime:
              cron: "14 16 * * *"
              timezone: America/Los_Angeles
        name: trigger-1
        http:
          url: http://abc.com/hello1
          method: GET
    - template:
        conditions: "test-dep-b"
        name: trigger-2
        http:
          url: http://abc.com/hello1
          method: GET
```

**Environment (please complete the following information):**
 - Kubernetes: v1.21.6-gke.1503
 - Argo Events: tried with latest master as well as latest Docker image, which I presume is 1.6.3.

**Additional context**
Happens both with STAN and Jetstream bus.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
