### ISSUE TITLE
Parameterization tutorial last step does not work

### ISSUE THREAD

**Issue by oscar6echo** [argoproj/argo-events#1855]
**Describe the bug**

Trigger template parameterization does not work.

**To Reproduce**
Follow the steps in tutorial https://argoproj.github.io/argo-events/tutorials/02-parameterization/#trigger-template-parameterization

In particular, update sensor:
```sh
kubectl -n argo-events apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/tutorials/02-parameterization/sensor-05.yaml
```
Then test with curl:

```sh
curl -d '{"dependencyName":"test-dep", "dataKey": "body.message", "dest": "spec.arguments.parameters.0.value", "message": "amazing!!"}' -H "Content-Type: application/json" -X POST http://localhost:12000/example
```

**Expected behavior**

What is described in the tutorial ie.:

```
    ___________
    < amazing!! >
    -----------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
    ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

What I see instead is the default message value:

```
    ___________
    < hello world !! >
    -----------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
    ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

**Environment (please complete the following information):**
 - Kubernetes: v1.23.3
 - Argo: latest as of 16apr22
 - Argo Events: v1.6.3

**Additional context**

Then I fiddled around the sensor definition and tried:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: message
                      value: toto
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
          # parameters:
          #   - src:
          #       dependencyName: test-dep
          #       dataKey: body.message
          #     dest: spec.arguments.parameters.0.value
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: THIS_WILL_BE_REPLACED
              dest: spec.arguments.parameters.0.value
            # - src:
            #     dependencyName: THIS_WILL_BE_REPLACED
            #     dataKey: THIS_WILL_BE_REPLACED
            #   dest: THIS_WILL_BE_REPLACED
        parameters:
          # - src:
          #     dependencyName: test-dep
          #     dataKey: body.dependencyName
          #   dest: parameters.0.src.dependencyName
          - src:
              dependencyName: test-dep
              dataKey: body.dataKey
            dest: parameters.0.src.dataKey
          # - src:
          #     dependencyName: test-dep
          #     dataKey: dest
          #   dest: parameters.0.dest
```

In this case the following curl:

```sh
curl -d '{ "dataKey": "body.message", "message": "amazing!!"}' -H "Content-Type: application/json" -X POST http://localhost:12000/example
```
yields the following result:

```
 _________________________________________ 
/ {"header":{"Accept":["*/*"],"Content-Le \
| ngth":["52"],"Content-Type":["applicati |
| on/json"],"User-Agent":["curl/7.68.0"]} |
| ,"body":{"dataKey":"body.message","mess |
\ age":"amazing!!"}}                      /
 ----------------------------------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
```

So this bug seems at least loosely connected with that described in issue #1752   
But it shows in the first steps the [documentation tutorials](https://argoproj.github.io/argo-events/tutorials/02-parameterization/#trigger-template-parameterization).  

Or did I miss something ?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
