### ISSUE TITLE
Cannot connect Kafka event source to Confluent cloud cluster

### ISSUE THREAD

**Issue by krgn** [argoproj/argo-events#1874]
**Describe the bug**

I have attempted to connect to a Confluent cloud cluster using the Kafka event source. Confluent requires SASL/PLAIN for authentication, so I have plugged in known good values into the the `Secret` (and also verified that the event source _is_ picking them up correctly) yet source can't connect with this error:

```
namespace=argo-dev, eventSourceName=kafka-source, eventSourceType=kafka, eventName=gcs-events, level=error, time=2022-04-20T19:55:46Z, msg=Error creating consumer group client: kafka: client has run out of available brokers to talk to (Is your cluster re
achable?)
namespace=argo-dev, eventSourceName=kafka-source, eventSourceType=kafka, eventName=gcs-events, level=info, time=2022-04-20T19:56:04Z, msg=start kafka event source... 
namespace=argo-dev, eventSourceName=kafka-source, eventSourceType=kafka, eventName=gcs-events, level=error, time=2022-04-20T19:56:05Z, msg=Error creating consumer group client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

These are example resources:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-user
  namespace: argo-dev
type: Opaque
data:
  user: "the api key in plain text"
  password: "the secret key in plain text"

--- 
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka-source
  namespace: argo-dev
spec:
  template:
    container:
      env:
        - name: DEBUG_LOG
          value: "true"
  kafka:
    gcs-events:
      url: confluents-boostrap-server-url:9092
      topic: gcs-events
      sasl:
        mechanism: PLAIN
        userSecret:
          key: user
          name: kafka-user
        passwordSecret:
          key: password
          name: kafka-user
      jsonBody: true
      connectionBackoff:
        duration: 10s
        steps: 5
        factor: 2
        jitter: 0.2
      consumerGroup:
        groupName: argo-consumer-group
        oldest: false
        rebalanceStrategy: range
```

After digging a little, finding this comment [here](https://github.com/influxdata/telegraf/issues/7985#issuecomment-814464404) I built a small `go` program that mimics the event source to test if I can reproduce the behavior. This is the `go` program config snippet:

```go
	config.Net.SASL.Enable = true
	config.Net.SASL.Handshake = true
	config.Net.SASL.Mechanism = sarama.SASLMechanism("PLAIN")
	config.Net.SASL.User = "****************"
	config.Net.SASL.Password = "****************************************************************"
        /* it only works when enabling TLS */
	config.Net.TLS.Enable = true
	config.Net.TLS.Config = &tls.Config{
		InsecureSkipVerify: true,
		ClientAuth:         0,
	}
```

Indeed, when commenting the TLS bits, the client fails to connect. Only with `InsecureSkipVerify` and TLS enabled the client successfully connects to the cluster.

I did try to add the following to the config:

```
      tls:
        insecureSkipVerify: true
```

However, this unfortunately also didn't work. The [example configuration](https://github.com/argoproj/argo-events/blob/c80e8080e1804db5cf811184a1c35578d8891924/examples/event-sources/kafka.yaml#L36) states that TLS _must not_ be used with SASL, which could be why this isn't supported. 

**To Reproduce**
1. Create a `Secret` with API key & secret
2. Create a `kafka` event-source configured to your Confluent cloud cluster in the manner detailed above
3. Watch the logs on the resulting container/event-source
5. See error

**Expected behavior**

Should be able to connect to Confluent cluster style clusters (SASL/PLAIN + TLS enabled w/o cert validation).

**Environment (please complete the following information):**
 - Kubernetes:  v1.20.15-gke.2500
 - Argo: v3.2.6
 - Argo Events: v1.6.3

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
