### ISSUE TITLE
event flow diagram not showing eventsource icon

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#1927]
**Describe the bug**
The workflows are being triggered ok but the event source icon is just missing from the 'event flow' diagram

**To Reproduce**
eventsource yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  revisionHistoryLimit: 0
  replicas: 3
  template:
    serviceAccountName: argo-workflows-server
    priorityClassName: system-cluster-critical
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  eventsource-name: webhook
                  controller: controller-manager
              topologyKey: topology.kubernetes.io/zone
            weight: 100
    container:
      resources:
        requests:
          cpu: "5m"
          memory: 45Mi
      volumeMounts:
        - name: certs-volume
          mountPath: /etc/ssl/certs
    volumes:
      - name: certs-volume
        configMap:
          name: ca-bundle
  bitbucketserver:
    bitbucket:
      repositories:
        - projectKey: "redact"
          repositorySlug: "redact"
      webhook:
        endpoint: /bitbucket
        port: "12000"
        method: POST
      events:
        - repo:refs_changed
      webhookSecret:
        # Name of the K8s secret that contains the webhook secret
        name: bitbucketserver-access
        # Key within the K8s secret whose corresponding value (must be base64 encoded) is the webhook secret
        key: secret
      accessToken:
        # Name of the K8s secret that contains the webhook secret
        name: bitbucketserver-access
        # Key within the K8s secret whose corresponding value (must be base64 encoded) is the webhook secret
        key: secret
      bitbucketserverBaseURL: https://redact/rest
```

sensor yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  revisionHistoryLimit: 0
  replicas: 3
  template:
    serviceAccountName: argo-workflows-server
    priorityClassName: system-cluster-critical
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  sensor-name: webhook
                  controller: controller-manager
              topologyKey: topology.kubernetes.io/zone
            weight: 100
    container:
      resources:
        requests:
          cpu: "10m"
          memory: 50Mi
  dependencies:
    - name: btest-dep
      eventSourceName: webhook
      eventName: bitbucket
  triggers:
    - template:
        name: bitbucket-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: bitbucket-workflow-
              spec:
                serviceAccountName: argo-workflows-server
                onExit: exit-handler
                entrypoint: whalesay
                volumes:
                  - name: aws-iam-token
                    projected:
                      defaultMode: 420
                      sources:
                        - serviceAccountToken:
                            audience: sts.amazonaws.com
                            expirationSeconds: 86400
                            path: token
                arguments:
                  parameters:
                    - name: message
                      # tis is the value that should be overridden
                      value: hello world
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    steps:
                      - - name: parse-messages
                          template: parse-message
                          arguments:
                            parameters:
                              - name: message
                                value: "{{inputs.parameters.message}}"

                  - name: parse-message
                    inputs:
                      parameters:
                        - name: message
                    metadata:
                      annotations:
                        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
                    container:
                      image: stedolan/jq:master
                      volumeMounts:
                        - name: aws-iam-token
                          mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
                      command: [bash, -c]
                      args: [ "echo x > /tmp/gitbranch.txt" ]
                    outputs:
                      parameters:
                        - name: git-branch
                          valueFrom:
                            path: /tmp/gitbranch.txt
                  - name: exit-handler
                    inputs:
                      parameters:
                        - name: message
                    steps:
                      - - name: notify
                          template: sendmail
                          arguments:
                            parameters:
                              - name: body
                                value: |-
                                  {{inputs.parameters.message}}
                  - name: sendmail
                    inputs:
                      parameters:
                        - name: body
                    outputs: {}
                    metadata: {}
                    script:
                      name: ''
                      image: python:3.10.4-slim
                      command:
                        - python
                      env: {}
                      resources: {}
                      volumeMounts:
                        - name: aws-iam-token
                          mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
                      source: |
                        redact
                    volumes:
                      - name: aws-iam-token
                        projected:
                          sources:
                            - serviceAccountToken:
                                audience: sts.amazonaws.com
                                expirationSeconds: 86400
                                path: token
                          defaultMode: 420

          parameters:
            - src:
                dependencyName: btest-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
```

**Expected behavior**
eventsource icon shows in event flow diagram

**Screenshots**
![image](https://user-images.githubusercontent.com/33283496/166893014-f58205cd-48c5-42de-9f41-6a0a41aed3b9.png)

**Environment (please complete the following information):**
 - Argo Events: 1.7.0
