### ISSUE TITLE
Jetstream EventBus doesn't work on arm64

### ISSUE THREAD

**Issue by ondrejmo** [argoproj/argo-events#1940]
**Describe the bug**

Jetstream `EventsBus` doesn't work on arm64 architecture.

**To Reproduce**

1. Install argo-events as described in [v1.7.0 release notes](https://github.com/argoproj/argo-events/releases/tag/v1.7.0)
2. Create `EventBus`
    ```yaml
    apiVersion: argoproj.io/v1alpha1
    kind: EventBus
    metadata:
      name: default
    spec:
      jetstream:
        version: 2.8.1  # see 'version' section below
    ````
3. Pods scheduled to arm64 nodes will fail with the following error in the output of the `reloader` container, other two containers in the pod are working as expected.
    ```
    standard_init_linux.go:228: exec user process caused: exec format error
    ```

**Expected behavior**

All Jetstream-required images should support arm64, same as the nats/native images do.

**Environment:**
 - Kubernetes: `1.23.6`
 - Argo: `v3.3.5`
 - Argo Events: `v1.7.0`

**Proposed solution**

The problem seems to be with the `natsio/nats-server-config-reloader:0.6.3` image, when I change its version/tag (in [ConfigMap/argo-events-controller-config](https://github.com/argoproj/argo-events/blob/v1.7.0/manifests/base/controller-manager/controller-config.yaml)) to `0.7.0` everything seems to work as expected.
