### ISSUE TITLE
Jetstream stateful set resource requests/limits aren't set correctly.

### ISSUE THREAD

**Issue by obanby** [argoproj/argo-events#1988]
**Describe the bug**

When using the jetstream event-bus operator, we can set the resource limits and requests on the three containers (main, reloader, and metrics). However, there are two problems:

1- Setting `MetricsContainerTemplate` resource requests/limits results in setting the reloader container resources requests/limits.

2- Setting `ReloaderContainerTemplate` resources requests/limits will not set the reloader container or the metrics container.

**To Reproduce**
1- install Argoevents version 1.7.0
2- deploy a jetsteam event-bus customresource

```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  jetstream:
    annotations:
      sidecar.istio.io/inject: 'false'
    version: 2.8.1
    containerTemplate:
      resources:
        limits:
          cpu: 1
          memory: 300Mi
        requests:
          cpu: 1
          memory: 300Mi
    metricsContainerTemplate:
      resources:
        limits:
          cpu: 0.5
          memory: 200Mi
        requests:
          cpu: 0.5
          memory: 200Mi
    reloaderContainerTemplate:
      resources:
        limits:
          cpu: 0.5
          memory: 200Mi
        requests:
          cpu: 0.5
          memory: 200Mi
```
3- inspect and observe the generated event-bus statefulset resource limits on each container using `kubectl get eventbus-default-js -o yaml`

**Expected behavior**

The expected behaviour is to have the correct resource requests/limits set on the respective container. 

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: 1.22
 - Argo Events: 1.7.0

**Additional context**

I have looked at the code and noticed that the containers are referenced using ordinal idx which has lead to this bug. I will be opening a PR to fix this issue shortly. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
