### ISSUE TITLE
Conditionals "when" not working

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-events#199]
Trying the conditional "when" based on global var {{workflow.parameters.gerritevent}}, but the
steps with "when" is never executed and the work flow doesn't excecute the onExit: exit-handler either!

```
              templates:
                  steps:                        
                  - - name: gerrit-checkout
                      template: gerrit-checkout  
                      
                  - - name: compile
                      template: compile
                      arguments:
                        artifacts:
                        - name: source
                          from: "{{steps.gerrit-checkout.outputs.artifacts.source}}"

                  - - name: unittests-componenttests
                      template: unittests-componenttests
                      arguments:
                        artifacts:
                        - name: source
                          from: "{{steps.gerrit-checkout.outputs.artifacts.source}}"

                  - - name: publish-artifacts-arm
                      template: publish-artifacts-arm
                      when: "{{workflow.parameters.gerritevent}} == change-merged"
                      arguments:
                        artifacts:
                        - name: compiled
                          from: "{{steps.compile.outputs.artifacts.compiled}}"

                  - - name: build-and-push-docker-image-to-registry
                      template: build-and-push-docker-image-to-registry
                      when: "{{workflow.parameters.gerritevent}} == change-merged"
                      arguments:
                        artifacts:
                        - name: source
                          from: "{{steps.gerrit-checkout.outputs.artifacts.source}}"               
```
