### ISSUE TITLE
Allow resource requests/limits for EventSource and Sensor pods

### ISSUE THREAD

**Issue by mjhuber** [argoproj/argo-events#1990]
**Is your feature request related to a problem? Please describe.**
Currently pods generated from EventSource and Sensor objects do not permit specifying container resource requests and limits.  EventSourceSpec.Template [contains many of the PodSpec fields](https://github.com/argoproj/argo-events/blob/master/api/event-source.md#template), but not resources.

The ability to explicitly specify this parameter is important for organizations that require resource requests/limits be specific on pods before they are admitted.  

**Describe the solution you'd like**
The ability to specify pod resources in EventSource and Sensor objects, e.g.,

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: tutorial-webhook
  namespace: argo-events
spec: {}
  template:
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
  webhook: {}
```

**Describe alternatives you've considered**

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by yann-soubeyrand** [comment]
Hello @mjhuber,

I think you can use the following template to achieve this
```
template:
  container:
    resources:
      requests:
        cpu: 1m
        memory: 15M
```

**Comment by mjhuber** [comment]
> 

🤦🏻 rtfm fail.  works with both `Sensor` and `EventSource` objects, e.g., 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: tutorial-webhook
spec:
  template:
    container:
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 50Mi
```

thanks for the help!
