### ISSUE TITLE
Add to webhook event source  HTTP headers custom or change gitlab event source madatory fields

### ISSUE THREAD

**Issue by DiegoFlop** [argoproj/argo-events#1998]
> **Is your feature request related to a problem? Please describe.**

On create a webhook event source type with security and use this event source on gitlab projects hooks.
I get **Hook executed successfully but returned HTTP 401 Invalid Authorization Header**.
This happen because with  webhook event source type only allow use security based on token on header Authorization, but projects hooks on gitlab use a custom header **X-Gitlab-Token HTTP**.
This is a problem because Its force to me use endpoints without security and everyone can send any request to this endpoint, and force me to validate all field of request before send to sensor. 
Its very tedious and complex.

I don't want to use gitlab event source because I don't need create hooks with gitlab event source and the access and secrets tokens are mandatory on gitlab event source.

I create projects hooks on gitlab with other automatization for this reason I don't need gitlab event source to create hooks, another reason is that I am using the same endpoint for multiples projects with the same sensor and dislike that I will have modify event sourse existing to add another project to create hooks.

**Describe the solution you'd like**
I believe that we have 2 options:

1. That gitlab event source only needed to create the fields .spec.gitlab.[NAME].webhook and the another fields are optional
3. That webhook event source has and new field of array list type with you can add custom headers that expected on eventbus

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitlab
spec:
...
  gitlab:
    example:
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        customHeaders:
        - name: X-Gitlab-Token HTTP
          value: xxxxxxxxxxxxxxxxxxx
        - name: custom
          value: xxxxxxxxxxx
...
```
**Environment** (please complete the following information):

**Kubernetes**: v1.22.9
**Argo**: v3.3.5
**Argo Events**: v1.7.0
**Executor**: emissary
**eventbus**: jetstream

**Describe alternatives you've considered**

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

---
## Update 1

After apply gitlab event source with empty project and webhook token, I saw that I can send request without this token with curl anyway

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: example-es
spec:
  replicas: 3
  service:
    ports:
      - port: 12000
        targetPort: 12000
  gitlab:
    example:
      projects: 
      - ""
      webhook:
        endpoint: /example
        port: "12000"
        method: POST
        url: https://example.com
      events:
        - PushEvents
      accessToken:
        key: token
        name: gitlab-access
      secretToken:
        key: token
        name: gitlab-secret
      enableSSLVerification: true
      gitlabBaseURL: https://gitlab.example.com
      deleteHookOnFinish: false
```
As I don't need that event-source create webhook, the accessToken hasn't permissions on gitlab

I don't need create webhooks with that event source, that's why the accessToken hasn't permissions on gitlab but I create the webhook manually, when I configure the webhook with secretToken appears to be well, however I can send a request with any tool such us curl without that secretToken

This is a very risk of security
