### ISSUE TITLE
Add field name on template of sensors crd spec.triggers.

### ISSUE THREAD

**Issue by DiegoFlop** [argoproj/argo-events#2010]
**Is your feature request related to a problem? Please describe.**
In order to use kustomize to merge several configuration files and make them easier to maintain, it would be convenient to add in spec.triggers the name field in the crd of the sensors.

This way it would be very convenient to work with separate files and use kustomize to merge them.

**Describe the solution you'd like**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor
spec:
  eventBusName: jetstream
  replicas: 3 
  dependencies:
    - name: depend_1
      ...
    - name: depend_2
      ...
    - name: depend_3
      ...
    - name: depend_4
      ...
  triggers: 
    - name: template_1
      template:
        conditions: "depend_1"
        name: depend_1-template
        k8s:
          ...
      parameters:
        ...
    - name: template_2
      template:
        conditions: "depend_2"
        name: depend_2-template
        k8s:
          ...
      parameters:
        ...
    - name: template_3
      template:
        conditions: "depend_3"
        name: depend_3-template
        k8s:
          ...
      parameters:
        ...
    - name: template_4
      template:
        conditions: "depend_4"
        name: depend_4-template
        k8s:
          ...
      parameters:
        ...
```

**Describe alternatives you've considered**

**Additional context**
For the dependencies we have achieved it modifying the schema.json and merge it correctly but for the triggers not having a unique field it is not possible to make the merge with separate files.

**kustomization.yaml**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: argo-events

openapi:
  path: ./schema.json

patches:
# event-sources
- path: ./overlays/event-sources/1.yaml
- path: ./overlays/event-sources/2.yaml
- path: ./overlays/event-sources/3.yaml
- path: ./overlays/event-sources/4.yaml
- path: ./overlays/event-sources/5.yaml

# sensors
- path: ./overlays/sensors/1.yaml
- path: ./overlays/sensors/2.yaml
- path: ./overlays/sensors/3.yaml
- path: ./overlays/sensors/4.yaml
- path: ./overlays/sensors/5.yaml
```

**base sensor.yaml**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor
spec:
  eventBusName: jetstream
  replicas: 3 
  template:
    serviceAccountName: operate-workflow-sa
  dependencies: []
  triggers: []
```

** example one of file to merge sensor1.yaml**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor
spec:
  eventBusName: jetstream
  replicas: 3 
  dependencies:
    - name: depend_1
      eventSourceName: eventsource_1
      eventName: depend_1
  triggers:
    - template:
        name: depend_1-template
        ...
```

When I merge multiple files kustomize write only   last file configuration

With eventSources works correctly

with sensor 
I had modify schema.json to add the next line for dependencies works
```
"io.argoproj.sensor.v1alpha1.SensorSpec": {
      "description": "SensorSpec represents desired sensor state",
      "properties": {
        "dependencies": {
          "description": "Dependencies is a list of the events that this sensor is dependent on.",
          "items": {
            "$ref": "#/definitions/io.argoproj.sensor.v1alpha1.EventDependency"
          },
          "type": "array",
          "x-kubernetes-patch-merge-key": "eventName",
          "x-kubernetes-patch-strategy": "merge"
        }
...
```
Adding the name field for the template object of the sensors we can modify the schema.json so that kustomize works correctly.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
