### ISSUE TITLE
Duplicate workflows triggered on calendar schedule

### ISSUE THREAD

**Issue by jfouchard** [argoproj/argo-events#202]
**Describe the bug**
When using a schedule it seems like two instances are triggered every time.  The calendar-gateway logs show two events being fired: 
```
2019-03-05T18:07:59Z | info  | msg: expected next calendar event |  event-source-name:test2
2019-03-05T18:07:59Z | info  | msg: new event received, dispatching to gateway client |  event-source-name:test2
2019-03-05T18:08:00Z | info  | msg: expected next calendar event |  event-source-name:test2
2019-03-05T18:08:00Z | info  | msg: new event received, dispatching to gateway client |  event-source-name:test2
```

Interval events do not appear to have this issue. 

**To Reproduce**
My Spec:
```
    spec:
      containers:
      - command:
        - /bin/gateway-client
        env:
        - name: GATEWAY_NAMESPACE
          value: argo-events
        - name: GATEWAY_EVENT_SOURCE_CONFIG_MAP
          value: argo-events-config-calendar-gateway-auto
        - name: GATEWAY_NAME
          value: argo-events-config-calendar-gateway-auto
        - name: GATEWAY_CONTROLLER_INSTANCE_ID
          value: argo-events
        - name: GATEWAY_CONTROLLER_NAME
          value: gateway-controller
        - name: GATEWAY_SERVER_PORT
          value: "9330"
        image: argoproj/gateway-client
        imagePullPolicy: Always
        name: gateway-client
        resources: {}
      - command:
        - /bin/calendar-gateway
        env:
        - name: GATEWAY_NAMESPACE
          value: argo-events
        - name: GATEWAY_EVENT_SOURCE_CONFIG_MAP
          value: argo-events-config-calendar-gateway-auto
        - name: GATEWAY_NAME
          value: argo-events-config-calendar-gateway-auto
        - name: GATEWAY_CONTROLLER_INSTANCE_ID
          value: argo-events
        - name: GATEWAY_CONTROLLER_NAME
          value: gateway-controller
        - name: GATEWAY_SERVER_PORT
          value: "9330"
        image: argoproj/calendar-gateway
        imagePullPolicy: Always
        name: calendar-events
        resources: {}
      serviceAccountName: argo-events-sa
```

And the configMap:
```
data:
  test2: 'schedule: 08 * * * *'
```
**Expected behavior**
A single event to be fired.

**Screenshots**

**Environment (please complete the following information):**
 Argo deployed via helmfiles @ latest.

Note, I'm pretty new to Argo, so this could certainly be a config issue - I just don't see where at all.
