### ISSUE TITLE
Submit-from in Sensor not possible with WorkflowTemplates

### ISSUE THREAD

**Issue by PhilippWitzmann** [argoproj/argo-events#2044]
**Describe the bug**
When trying to trigger a workflowTemplate from a sensor and eventSource, it is failing with the message: failed to execute trigger: timed out waiting for the condition: invalid kind WorkflowTemplate

This is propably related to: https://github.com/argoproj/argo-events/pull/1941 

**To Reproduce**
1. Create a sensor with WorkflowTemplate as a Resource to submit-from. Snippet:
```
[...]
    - template:
        name: my-trigger
        argoWorkflow:
          operation: submit-from
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                name: buildkit
[...]
```
2. Create an eventSource which produces the dependency needed for above trigger to trigger. Snippet:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    example:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /example
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST
```
3. local port forward the eventsource && curl an event `k port-forward service/webhook-eventsource-svc 12000` `curl -X POST -H "Content-Type: application/json" -d '{"message": "hello-world"}' localhost:12000/example`
4. k logs <sensor pod>
6. See `{"level":"error","ts":1655901171.428397,"logger":"argo-events.sensor","caller":"sensors/listener.go:346","msg":"failed to execute a trigger","sensorName":"webhook","error":"failed to execute trigger: timed out waiting for the condition: invalid kind WorkflowTemplate","errorVerbose":"timed out waiting for the condition: invalid kind WorkflowTemplate\nfailed to execute trigger\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerOne\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:399\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:344\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:1581","triggerName":"my-trigger","triggeredBy":["test-dep"],"triggeredByEvents":["34323238613839302d376166382d346638332d393834332d646539323834363933383739"],"stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:346"}`

**Expected behavior**
A workflow based on the specified WorkflowTemplate should be created

**Environment (please complete the following information):**
 - Kubernetes: 1.21.3
 - Argo: 2.3.3
 - Argo Workflows: 3.3.6 
 - Argo Events: v1.7.1

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Submitting from WorkflowTemplate is not supported right now - it's easy to add it, questions:

1. Does submitting from WorkflowTemplate with parameters often used?
2. Is there any parameter option when submitting from other kinds (e.g. Workflow, CronWorkflow)?

**Comment by PhilippWitzmann** [comment]
We are still at the very beginning of our argo events + workflow journey. We are planning to replace our CI System (gitlab CI) with mentioned stack, so our usecase will be primarily predefined dag tasks, which WorkflowTemplates seems to cover perfectly fine for us. 

An example generic workflow template would be to clone a git repo. Input parameters (coming from GitLab MR Event) would be the repository url and branch to checkout. From there on, our "pipeline" would continue.

We figured out this workaround, which works, but isn't really pretty or an optimal solution imho:


`
sensor.yaml
[...}
    - template:
        name: my-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: Workflow
          operation: submit
          metadata:
            generateName: workflow-template-
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: buildkit-template-
              spec:
                workflowTemplateRef:
                  name: buildkit
                arguments:
                  parameters:
                    - name: branch
                      value: foo
          parameters:
            - src:
                dependencyName: test-dep
                dataTemplate: {{ "{{ .Input.body.message }}" | quote }}
              dest: spec.arguments.parameters.0.value`

**Comment by Nizar-opt** [comment]
I think passing parameters to the workflowTemplate is needed, but looks like `submit-from` operation does not take parameters into consideration. 

https://github.com/argoproj/argo-events/blob/54ab013ded5aaf387116a346c7718fd46d2f8e4c/sensors/triggers/argo-workflow/argo-workflow.go#L163-L174


@whynowy What do you think about adding workflowTemplate as a source?

```
...
    - template:
        name: my-trigger
        argoWorkflow:
          operation: submit
          source:
            workflowTemplate: 
              name: hello-world
              namespace: default
```

> Submitting from WorkflowTemplate is not supported right now - it's easy to add it, questions:
> 
> 1. Does submitting from WorkflowTemplate with parameters often used?
> 2. Is there any parameter option when submitting from other kinds (e.g. Workflow, CronWorkflow)?

**Comment by whynowy** [comment]
> I think passing parameters to the workflowTemplate is needed, but looks like `submit-from` operation does not take parameters into consideration.
> 
> https://github.com/argoproj/argo-events/blob/54ab013ded5aaf387116a346c7718fd46d2f8e4c/sensors/triggers/argo-workflow/argo-workflow.go#L163-L174
> 
> @whynowy What do you think about adding workflowTemplate as a source?
> 
> ```
> ...
>     - template:
>         name: my-trigger
>         argoWorkflow:
>           operation: submit
>           source:
>             workflowTemplate: 
>               name: hello-world
>               namespace: default
> ```
> 
> > Submitting from WorkflowTemplate is not supported right now - it's easy to add it, questions:
> > 
> > 1. Does submitting from WorkflowTemplate with parameters often used?
> > 2. Is there any parameter option when submitting from other kinds (e.g. Workflow, CronWorkflow)?

Actually there's a field named `args` can be passed in `argoWorkflow` trigger, so we only need to enable `workflowTemplate` for `submit-from`, then it will work.

**Comment by omBratteng** [comment]
> Actually there's a field named `args` can be passed in `argoWorkflow` trigger, so we only need to enable `workflowTemplate` for `submit-from`, then it will work.

Do you mean this field name `args` https://github.com/argoproj/argo-events/blob/stable/examples/sensors/special-workflow-trigger.yaml#L17-L19 ?

How would one send parameters into it, like these https://github.com/argoproj/argo-events/blob/stable/examples/sensors/special-workflow-trigger.yaml#L42-L46?

**Comment by whynowy** [comment]
> > Actually there's a field named `args` can be passed in `argoWorkflow` trigger, so we only need to enable `workflowTemplate` for `submit-from`, then it will work.
> 
> Do you mean this field name `args` https://github.com/argoproj/argo-events/blob/stable/examples/sensors/special-workflow-trigger.yaml#L17-L19 ?
> 

- Yes.

> How would one send parameters into it, like these https://github.com/argoproj/argo-events/blob/stable/examples/sensors/special-workflow-trigger.yaml#L42-L46?

- Unfortunately, I don't think dynamic arguments will work....

**Comment by omBratteng** [comment]
> * Unfortunately, I don't think dynamic arguments will work....

Ah, that's unfortunate.

I am still configuring and setting up argo-events in conjunction with argo-events, so I've adjusted one of the examples into this
```yaml
---
# Source: da-bevaring/templates/workflows/workflow.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-inner-dag
spec:
  entrypoint: inner-diamond
  arguments:
    parameters:
      - name: innerA
      - name: innerB
      - name: innerC
      - name: innerD
  templates:
    - name: whalesay-template
      inputs:
        parameters:
        - name: message
      container:
        image: docker/whalesay
        command:
          - cowsay
        args:
          - "{{inputs.parameters.message}}"
    - name: inner-diamond
      inputs: {}
      outputs: {}
      metadata: {}
      dag:
        tasks:
          - name: inner-A
            arguments:
              parameters:
                - name: message
                  value: "{{workflow.parameters.innerA}}"
            templateRef:
              name: workflow-template-whalesay-template
              template: whalesay-template
          - name: inner-B
            template: whalesay-template
            arguments:
              parameters:
                - name: message
                  value: "{{workflow.parameters.innerB}}"
            depends: inner-A
          - name: inner-C
            template: whalesay-template
            arguments:
              parameters:
                - name: message
                  value: "{{workflow.parameters.innerC}}"
            depends: inner-A
          - name: inner-D
            arguments:
              parameters:
                - name: message
                  value: "{{workflow.parameters.innerD}}"
            templateRef:
              name: workflow-template-whalesay-template
              template: whalesay-template
            depends: inner-B && inner-C
```

With then sensor
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: amqp
spec:
  template:
    serviceAccountName: argo-workflow-operator # This is defined in the argo-workflow-operator-rbac.yaml file
  dependencies:
    - name: test-dep
      eventSourceName: amqp
      eventName: rabbitmq
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: workflow-template-inner-dag-
              spec:
                arguments:
                  parameters:
                  - name: innerA
                  - name: innerB
                  - name: innerC
                  - name: innerD
                workflowTemplateRef:
                  name: workflow-template-inner-dag
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: test-dep
                dataKey: body.innerA
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: test-dep
                dataKey: body.innerB
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: test-dep
                dataKey: body.innerC
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: test-dep
                dataKey: body.innerD
```

And it seems to work, just a bit tedious to duplicate all those dynamic parameters, I'll probably end up with writing them as helm templates, to reduce a bit of manual writing.
