### ISSUE TITLE
native EventBus does not start pods

### ISSUE THREAD

**Issue by dodizzle** [argoproj/argo-events#2045]
**Describe the bug**
When I attempt to add the native eventbus to the k8s cluster it does create the service but fails to start any pods.
At no point do pods appear.

**To Reproduce**
Install argo-events via the helm chart(I am using version 2.0.0)
Install the native eventbus
```
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml
```
The service will be created, but no pods appear.

**Expected behavior**
I expect 3 eventbus pods running in the specified namespace.

**Environment (please complete the following information):**
 - Kubernetes: 1.21.11-gke.1900
 - Argo Workflows: v3.3.6
 - Argo Events: v1.7.0

**Additional context**
I think this a new problem as I spun an argo-events a few months ago and it worked fine.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
What do you see in the controller log? And can you post what you see with `kubectl get eb default -o yaml`?

**Comment by dodizzle** [comment]
Here is the error from the events controller
```
    "level": "error",
    "ts": 1656341026.9205558,
    "logger": "argo-events.eventbus-controller",
    "caller": "installer/installer.go:34",
    "msg": "installation error",
    "namespace": "helix-jobs",
    "eventbus": "default",
    "error": "failed to get nats streaming version, err: \"eventBus.nats\" not found in the configuration",
```
And here is the config for eb/default
```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"EventBus","metadata":{"annotations":{},"name":"default","namespace":"argo"},"spec":{"nats":{"native":{"auth":"token","replicas":3}}}}
  creationTimestamp: "2022-06-27T14:58:12Z"
  finalizers:
  - eventbus-controller
  generation: 1
  name: default
  namespace: argo
  resourceVersion: "495019890"
  uid: 793668fa-477c-45d6-9cab-b947bfe5bfcb
spec:
  nats:
    native:
      auth: token
      replicas: 3
status:
  conditions:
  - lastTransitionTime: "2022-06-27T14:59:34Z"
    status: "True"
    type: Configured
  - lastTransitionTime: "2022-06-27T14:59:34Z"
    message: Failed to build a statefulset spec
    reason: BuildStatefulSetFailed
    status: "False"
    type: Deployed
  config: {}
```

**Comment by whynowy** [comment]
Can you reinstall argo-events with the approach mentioned in the release notes? https://github.com/argoproj/argo-events/releases. The helm chart for Argo Events is maintained by community users, which might be missing something.

**Comment by dodizzle** [comment]
Closing this ticket as the issue was with the helm chart which does not provide default version numbers for either native or jetstream. 
After I added those configs for the argo-events service the eventbus began to work.
```
configs:
  jetstream:
    versions:
    - version: "2.8.1"
      natsImage: nats:2.8.1
      metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
      configReloaderImage: natsio/nats-server-config-reloader:0.6.3
      startCommand: /nats-server
  nats:
    versions: 
    - version: 0.22.1
      natsStreamingImage: nats-streaming:0.22.1
      metricsExporterImage: natsio/prometheus-nats-exporter:0.9.3
```
