### ISSUE TITLE
Add Docker events as signal

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#21]
**Is your feature request related to a problem? Please describe.**
Docker offers multitude of events on different types of docker objects. It will be useful to capture these events and trigger workflows. 

**Describe the solution you'd like**
Proposed sensor - 

```
apiVersion: core.events/v1alpha1
kind: Sensor
metadata:
  name: docker-example
  namespace: cloud-native-scheduler
  labels:
    sensors.core.events/controller-instanceid: axis
spec:
  repeat: true
  signals:
    - name: docker
      docker:
        type: "container"
        action: "create"
        # https://docs.docker.com/engine/reference/commandline/ps/#filtering
        filters:
          name: "hello-world"
          label: "myLabel=myValue"
  triggers:
    - name: done-workflow
      resource:
        namespace: cloud-native-scheduler
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        artifactLocation:
          s3:
            bucket: workflows
            key: hello-world.yaml
            endpoint: minio-service.cloud-native-scheduler:9000
            insecure: true
            accessKey:
              key: accesskey
              name: artifacts-minio
            secretKey:
              key: secretkey
              name: artifacts-minio
```
