### ISSUE TITLE
filtering not working as expected while sensing sqs events

### ISSUE THREAD

**Issue by ankur6ue** [argoproj/argo-events#2101]
**Describe the bug**
The body of a sqs message shows up as base64 encrypted, which seems to make sensor filtering not work 

**To Reproduce**
1. Create sensor using:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws
spec:
  template:
    serviceAccountName: k8s-resource-sa
  dependencies:
    - name: sns
      eventSourceName: aws-sns
      eventName: example
    - name: sqs
      eventSourceName: aws-sqs
      eventName: example
      transform:
        jq: ".body.message = \"added by sensor transform\""
      jsonBody: true
      filters:
        data:
          - path: body.greeting
            type: string
            value:
              - "hello"
              - "hey"
```
Send message to sqs queue
aws sqs send-message --queue-url https://queue.amazonaws.com/aws-account-id/speech2text-queue --message-body '{"id":4,"greeting":"heyy","message":"tbd"}'

**Expected behavior**
filtering should not pass

** Actual behavior**
Filtering passes:
sensor log:
{"level":"info","ts":1658606516.1695075,"logger":"argo-events.sensor","caller":"sensors/listener.go:407","msg":"successfully processed trigger 'aws-sqs-workflow-trigger'","sensorName":"aws","triggerName":"aws-sqs-workflow-trigger","triggerType":"Kubernetes","triggeredBy":["sqs"],"triggeredByEvents":["37643036666364632d356361322d343436642d393436342d366139663466373239343966"]}

Now if I add base64 decoding template like so:
```
transform:
        jq: ".body.message = \"added by sensor transform\""
      jsonBody: true
      filters:
        data:
          - path: body.greeting
            type: string
            value:
              - "hello"
              - "hey"
            template: "{{ b64dec .Input }}"
```
Then I can't get filtering to pass, no matter what I pass as the greeting:
aws sqs send-message --queue-url https://queue.amazonaws.com/aws-account-id/speech2text-queue --message-body '{"id":4,"greeting":"hey","message":"tbd"}'

sensor log:
{"level":"warn","ts":1658606774.841051,"logger":"argo-events.sensor","caller":"sensors/listener.go:197","msg":"Event [ID '30373238326433612d386163372d346565312d383638302d643137346330353134663239', Source 'aws-sqs', Time '2022-07-23T20:06:14Z', Data '{\"body\":{\"greeting\":\"hey\",\"id\":4,\"message\":\"added by sensor transform\"},\"messageAttributes\":null,\"messageId\":\"9c078eb4-1bee-4d71-ac2a-08bb542d10ec\"}'] discarded due to filtering","sensorName":"aws","triggerName":"aws-sqs-workflow-trigger"}

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: v1.23]
 - Argo Events: [v1.7]

**Additional context**
Also not sure how jsonbody: true setting interacts with the base64 decoding.. while setting 
jsonBody: true
      filter: # filter field
        expression: "(body.id == 4)"

filtering works correctly on the event source (but not the sensor)
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
