### ISSUE TITLE
Cannot use headers in dataTemplate

### ISSUE THREAD

**Issue by CRASH-Tech** [argoproj/argo-events#2104]
I'm trying to get inner json from webhook headers.
The header is inner json: `{"project": "test"}`

And it not working:
```
            - src:
                dependencyName: webhook-gitlab-tag
                dataTemplate: {{ (.Input.headers.X-Gitlab-Token.0 | mustFromJson).project }}
              dest: metadata.labels.test
              operation: append
```

But if I use a .Input.body - all works:
```
            - src:
                dependencyName: webhook-gitlab-tag
                dataTemplate: {{ (.Input.body.X-Gitlab-Token.0 | mustFromJson).project }}
              dest: metadata.labels.test
              operation: append
```
