### ISSUE TITLE
amqp evensource not working with single log "started processing the AMQP event source..."

### ISSUE THREAD

**Issue by ArieLevs** [argoproj/argo-events#2107]
**Describe the bug**
similar to #1545, the issue still happening

no error message, nothing crashing, logs from event source:
```
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=starting eventsource server
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=starting metrics server
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=Not the LEADER, stand by ...
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=Becoming a Candidate, stand by ...
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=I'm the LEADER, starting ...
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=Starting event source server...
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=eventBusConfig: {NATS:&NATSConfig{URL:nats://eventbus-default-stan-svc:4222,ClusterID:*eventbus-de
fault,Auth:*token,AccessSecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:eventbus-default-client,},Key:client-auth,Optional:nil,},} JetStream:nil}
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=NATS auth strategy: Token
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=Connected to NATS server.
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=Connected to NATS streaming server.
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=Eventing server started.
namespace=classifier, eventSourceName=rabbitmq-develop, level=info, time=2022-07-25T20:44:48Z, msg=starting eventbus connection daemon...
namespace=classifier, eventSourceName=rabbitmq-develop, eventSourceType=amqp, eventName=newTask, level=info, time=2022-07-25T20:44:48Z, msg=started processing the AMQP event source...
namespace=classifier, eventSourceName=rabbitmq-develop, eventSourceType=amqp, eventName=newTask, level=info, time=2022-07-25T20:44:48Z, msg=started processing the AMQP event source...
namespace=classifier, eventSourceName=rabbitmq-develop, eventSourceType=amqp, eventName=newTask, level=info, time=2022-07-25T20:44:48Z, msg=started processing the AMQP event source...
namespace=classifier, eventSourceName=rabbitmq-develop, eventSourceType=amqp, eventName=newTask, level=info, time=2022-07-25T20:44:48Z, msg=started processing the AMQP event source...
```

EventSource resource looks like:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: rabbitmq-develop
spec:
  amqp:
    newTask:
      url: amqps://****:5671
      jsonBody: true
      exchangeName: "test"
      exchangeType: direct
      routingKey: hello
      connectionBackoff:
        duration: 10s
        steps: 5
        factor: 2
        jitter: 0.2
      exchangeDeclare:
        durable: true
        autoDelete: false
        internal: false
        noWait: false
      queueDeclare:
        name: "test"
        durable: true
        autoDelete: false
        exclusive: true
        noWait: false
      auth:
        username:
          name: rabbitmq-secrets
          key: username
        password:
          name: rabbitmq-secrets
          key: password
```

**Expected behavior**
Connection succeeds or an error is thrown.

**Environment:**
 - Kubernetes: v1.22.9
 - Argo: None
 - Argo Events: v1.7.1

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
