### ISSUE TITLE
Can’t pass large data from an event source into an artifact

### ISSUE THREAD

**Issue by kamiltalipov** [argoproj/argo-events#2147]
**Describe the bug**
Trying to pass large data from some event source (e.g. kafka) into an artifact will create a huge manifest.
As a result created workflow will fail with `exec user process caused: argument list too long`.

**To Reproduce**
1. Create a sensor that passes data from event source to artifact.
<details><summary>example.yaml</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: large-artifact-issue
  namespace: argo
spec:
  dependencies:
    - eventName: example
      eventSourceName: kafka
      name: test-dep
  triggers:
    - template:
        name: large-artifact-issue-workflow
        k8s:
          operation: create
          parameters:
            - dest: spec.templates.0.steps.0.0.arguments.artifacts.0.raw.data
              src:
                dataKey: body
                dependencyName: test-dep
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: large-artifact-issue-
                labels:
                  process: large-artifact-issue
              spec:
                entrypoint: main
                podGC:
                  strategy: OnWorkflowSuccess
                templates:
                  - name: main
                    steps:
                    - - name: cat-event-data
                        template: cat-event-data
                        arguments:
                          artifacts:
                          - name: event-data
                            raw:
                              data: ''
                  - name: cat-event-data
                    inputs:
                      artifacts:
                        - name: event-data
                          path: /tmp/event_data
                    container:
                        image: busybox:latest
                        command: ["cat"]
                        args: ["/tmp/event_data"]
                    activeDeadlineSeconds: 43200
                ttlStrategy:
                  secondsAfterCompletion: 600
```

</details>

2. Send some large data to the event source.

3. Trigger will create a new workflow. 

4. Created workflow will fail with `exec user process caused: argument list too long`.

**Expected behavior**
Created workflow would run normally.

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: AWS EKS 1.22
 - Argo: 3.3.8
 - Argo Events: 1.7.1

**Additional context**
I think it would be nice if Argo Events would be able to initiate artifacts directly without passing data through manifest.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
