### ISSUE TITLE
Argo Event with SSO RBAC enabled

### ISSUE THREAD

**Issue by maxisam** [argoproj/argo-events#2176]
**Describe the bug**
Connection closed to api/v1/stream/events/argo-workflows?listOptions.fieldSelector=involvedObject.kind=EventSources,involvedObject.name=webhook

**To Reproduce**

1. Enable SSO.RBAC
2. Create a webhook event source as the example from the doc

**Expected behavior**
Should be able to see logs when login as Admin user

**Screenshots**
<img width="487" alt="image" src="https://user-images.githubusercontent.com/456807/188732722-dd9f4bc3-8dd9-49ab-ae52-eb7c22db4868.png">

If I add the following code to argo-workflows-admin, it will work as expected

```yml
      -   apiGroups:
            - ''
          resources:
            - pods
            - pods/log
          verbs:
            - get
            - list
            - watch
```

<img width="976" alt="image" src="https://user-images.githubusercontent.com/456807/188732745-3db7ae46-6b0d-4c60-ae2b-70b337878db0.png">

**Environment (please complete the following information):**
 - Kubernetes: 1.19.4
 - Argo: v3.3.9
 - Argo Events:  v1.7.1

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
