### ISSUE TITLE
ArgoEvents controller that crashes when misconfiguring a Kafka EventSource.

### ISSUE THREAD

**Issue by JimmyTrackoen-Adeo** [argoproj/argo-events#2185]
# ArgoEvents controller that crashes when misconfiguring a Kafka EventSource.

Hi there,
We have found that when a user configures an EventSource as follows:

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka
spec:
  kafka:
    example:
      connectionBackoff:
        duration: 10s 
        factor: 2
        jitter: 0.2 
        steps: 5
      consumerGroup:
        groupName: XXXX
        oldest: true
        rebalanceStrategy: range
      jsonBody: false
      limitEventsPerSecond: 1
      partition: ""
      sasl:
        mechanism: PLAIN
        passwordSecret:
          key: password
          name: XXXX 
        userSecret:
          key: username
          name: XXXX 
      topic: XXXX 
      url: 
      - XXXX 
      version: 2.5.0
      tls:
        caCertSecret: null
```
The ArgoEvents controller goes down, causing an interruption of this service for all other ArgoEvents users on the cluster.
Above is the manager controller stacktrace:
```
pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/reflector.go:167: Failed to watch *v1alpha1.EventSource: failed to list *v1alpha1.EventSource: json: cannot unmarshal array into Go struct field KafkaEventSource.items.spec.kafka.url of type string
```

By filling in the URL appropriately
```
url: valeur
```

And by removing the unused TLS part the controller becomes available again.

ArgoEvents version: v1.7.1
GKE Cluster version: v1.22.12-gke.500

Note: We have reproduced this problem on several of our clusters

Possible to fix this problem?
