### ISSUE TITLE
docs: add example of a sensor triggering an existing workflowtemplate defined outside of sensor file

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#2234]
workflowtemplate can be already defined/deployed to normal argo-workflows UI ie 
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gpu-job-test
....all logic
```

then sensor can trigger it, ie https://github.com/argoproj/argo-events/discussions/1247#discussioncomment-871368 without having all the step logic in the sensor file

```
spec:
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: test
  triggers:
    - template:
        name: webhook-sensor-test
        argoWorkflow:
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: gpu-test-workflow
                namespace: argo
              spec:
                workflowTemplateRef:
                  name: gpu-job-test
```
