### ISSUE TITLE
Parameterization a block of k8s resource (set of key values)

### ISSUE THREAD

**Issue by GoshaDo** [argoproj/argo-events#2263]
**Is your feature request related to a problem? Please describe.**
Hi, I am trying to parametrize an entire block of k8s trigger using payload. the payload converted to string and can't be injected to overwrite the block. 

**Describe the solution you'd like**
I would suggest the following usage:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: example
  namespace: argocd
spec:
  template:
    serviceAccountName: argo-wf
  dependencies:
    - name: example-dep
      eventSourceName: example-event-source
      eventName: event-test
  triggers:
    - template:
        name: example-template
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: injected-block-
              spec:
                entrypoint: main
                arguments:
                  parameters:
                    - name: message
                      value: hello world
                serviceAccountName: argo-wf  
                templates:
                  - name: main
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args:
                        - "hello world"
          parameters:
            - src:
                dependencyName: example-dep
                dataKey: body.injected
              dest: spec.templates.0.container
```

while the data of the payload is:
```
{
  "injected": {
    "image": "alpine",
    "command": [
      "echo"
    ],
    "args": [
      "injected"
    ]
  }
}
```

This should overwrite the spec.templates.0.container block entirely 

**Describe alternatives you've considered**
To pass the logic to different component to dynamically create the yaml and then injected it to cluster with the sensor.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
