### ISSUE TITLE
Argo Events stopped working, fails to start

### ISSUE THREAD

**Issue by arielweinberger** [argoproj/argo-events#2275]
**Describe the bug**
We have been using Argo Events for a while now (~30 days) without an issue.
All of a sudden, it stopped working and re-installing Argo Events does not seem to work.

It's a cluster-wide installation, using the helm chart (v2.0.6). This is the configuration:
```yml
createAggregateRoles: true
webhook:
  enabled: true
configs:
  jetstream:
    versions:
    - version: 2.8.2-alpine
      natsImage: nats:2.8.2-alpine
      metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
      configReloaderImage: natsio/nats-server-config-reloader:0.7.0
      startCommand: nats-server
  nats:
    versions:
    - version: 0.22.1
      natsStreamingImage: nats-streaming:0.22.1
      metricsExporterImage: natsio/prometheus-nats-exporter:0.8.0
```

The `argo-events-controller-manager` pod crashes with the following logs:
```
{"level":"fatal","ts":1666717701.9851613,"logger":"argo-events.eventbus-controller","caller":"cmd/start.go:62","msg":"unable to get a controller-runtime manager","error":"Get \"https://172.20.0.1:443/api?timeout=32s\": dial tcp 172.20.0.1:443: i/o timeout","stacktrace":"github.com/argoproj/argo-events/controllers/cmd.Start\n\t/home/runner/work/argo-events/argo-events/controllers/cmd/start.go:62\ngithub.com/argoproj/argo-events/cmd/commands.NewControllerCommand.func1\n\t/home/runner/work/argo-events/argo-events/cmd/commands/controller.go:20\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918\ngithub.com/argoproj/argo-events/cmd/commands.Execute\n\t/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19\nmain.main\n\t/home/runner/work/argo-events/argo-events/cmd/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/proc.go:250"}
```

No additional logs or error messages.

I have tried installing Argo Events to the same cluster via YAML manifest files as instructed in the docs:
```
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml
```
And the same is happening.

**To Reproduce**
Not sure how to reproduce this since we have been running this for over 30 days without an issue.
As of now, uninstalling and re-installing does not fix the issue.

**Expected behavior**
I expect the Argo Events pods to become green and run successfully.

**Environment (please complete the following information):**
 - Kubernetes: v1.21 (AWS EKS)
 - Argo: v2.5.0
 - Argo Events: v1.7.3

**Additional context**
-

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
