### ISSUE TITLE
Kafka Event Source not connecting to Jetstream Event Bus

### ISSUE THREAD

**Issue by dspeck1** [argoproj/argo-events#2316]
**Describe the bug**
The Kafka Event Source is not connecting to the Jetstream Event Source and erroring out pod.  Also tried NATS as well.  Getting Event Source Server cannot be created.  I thought the Event Source Server was now longer supposed to be created according to this post?

https://blog.argoproj.io/argo-events-v1-7-theres-a-new-bus-in-town-21949e915771

Running Argo events 1.7.2

**To Reproduce**

Deploy Argo events 1.7.2
Install Events Bus with this configuration
```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  jetstream:
    version: 2.8.2
    replicas: 3
    startArgs:
      - "-D"
```
Install kafka source with this config. 

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka
  namespace: argo-events
spec:
  example:
    #eventBusName: default
    kafka:
      url: my-cluster-kafka-bootstrap.kafka:9092
      topic: test-topic
      jsonBody: true
      consumerGroup:
        groupName: test-group
        oldest: false
        rebalanceStrategy: range
```

**Expected behavior**
Kafka Event Source does not error and crashloopbackoff.

**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.18.6]
 - Argo: [e.g. v2.9.4]
 - 
 - Argo Events: [e.g. v1.0.0]
 - 1.7.3

**Additional context**

```
namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=starting eventsource server
namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=Starting event source server...
namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=starting metrics server
namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=eventBusConfig: {NATS:nil JetStream:&JetStreamConfig{
URL:nats://eventbus-default-js-svc.argo-events.svc.cluster.local:4222,AccessSecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectRefer
ence{Name:eventbus-default-js-client-auth,},Key:client-auth,Optional:nil,},StreamConfig:duplicates: 300s
maxage: 168h
            maxbytes: -1
                        maxmsgs: 50000
                                      replicas: 3
                                                 ,}}
                                                    namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=N
ATS auth strategy: Basic
namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=Connected to NATS Jetstream server.
namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=No need to create Stream 'default' as it already exis
ts
namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=NATS auth strategy: Basic
namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=Connected to NATS Jetstream server.
namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=Eventing server started.
namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=starting eventbus connection daemon...
namespace=argo-events, eventSourceName=kafka, level=error, time=2022-11-18T18:05:11Z, msg=Erroring out, no active event server running
namespace=argo-events, eventSourceName=kafka, level=info, time=2022-11-18T18:05:11Z, msg=exiting eventbus connection daemon...
namespace=argo-events, eventSourceName=kafka, level=error, time=2022-11-18T18:05:11Z, msg=NATS connection lost
namespace=argo-events, eventSourceName=kafka, level=fatal, time=2022-11-18T18:05:11Z, msg=failed to start eventsource server
```
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
