### ISSUE TITLE
Workflow template for Sensor

### ISSUE THREAD

**Issue by FaKod** [argoproj/argo-events#232]
**Is your feature request related to a problem? Please describe.**
The K8s-Sigs tool kustomize (https://github.com/kubernetes-sigs/kustomize) can be used to patch yamls (stock K8s ressources and CRDs). Using it together with Triggers (https://github.com/argoproj/argo-events/blob/master/docs/trigger-guide.md) and Workflows makes it impossible to patch e.g. a Workflows ServiceAccount, because `inline` adds a simple string

**Describe the solution you'd like**
We have something similar in a Deployment, that is a POD template. 
So my solution would be something like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
. . .
source:
  template:
    apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    . . . 
```

**Describe alternatives you've considered**
The other options defining a Trigger (S3, ConfigMap, etc.) are possible, but more complex. What I want to do is a simple `kustomize build . | kubectl apply -f -`
