### ISSUE TITLE
 Kafka event source with consumer groups don't work anymore

### ISSUE THREAD

**Issue by samj1912** [argoproj/argo-events#2358]
**Describe the bug**
Kafka events with consumer groups no longer work.

This is due to an upgrade on shopify samara that introduced "groupstrategies" that are incompatible with "strategy" set by argo events.

This causes 1.7.4 to error with 

> Consumer.Group.Rebalance.GroupStrategies and Consumer.Group.Rebalance.Strategy cannot be set at the same time

if an event source is provided which looks like - 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: example
spec:
  kafka:
    example:
      url: url:9092
      topic: topic
      jsonBody: true
      consumerGroup:
        groupName: my-group
```

This is because by default samara sets a group strategy of range and argo also sets a strategy of range which causes it to error out due to PR - 
https://github.com/Shopify/sarama/commit/d66826a07ad05307df603d525f8dbf11875222c0

We should either downgrade back to samara 1.36.x or fix the code at https://github.com/argoproj/argo-events/blob/6c076960bba59a73d67e195d8f54eb96cf7e113e/eventsources/sources/kafka/start.go#L97

to use group strategies.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.18.6] 1.22.x
 - Argo: [e.g. v2.9.4] 3.3.1
 - Argo Events: [e.g. v1.0.0] 1.7.4

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
