### ISSUE TITLE
invalid memory address or nil pointer dereference on sensor creating

### ISSUE THREAD

**Issue by keaxu-exp** [argoproj/argo-events#237]
**Describe the bug**

Following https://github.com/argoproj/argo-events/blob/master/README.md `Install` and `Get Started` step by step.

when create webhook sensors by running
```
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/examples/sensors/webhook-http.yaml
```

see this in sensor-controller pod logs

```
time="2019-03-18T07:04:57Z" level=info msg="watching sensor-controller config map updates"
time="2019-03-18T07:04:57Z" level=info msg="detected ConfigMap update. updating the sensor-controller config."
ERROR: logging before flag.Parse: E0318 07:07:32.762087       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/vaibhav/go/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:522
```

**Expected behavior**
As mentioned on doc, once sensor resource is created, sensor controller will create corresponding sensor pod and a ClusterIP service.

**Screenshots**
<img width="1043" alt="Screen Shot 2019-03-18 at 12 09 26 AM" src="https://user-images.githubusercontent.com/37673226/54549838-25232f00-4968-11e9-85de-f1e03ef0f062.png">

**Environment:**
 - Mac OS X Mojave v10.14.3
 - Minikube v0.34.1

**Comment by VaibhavPage** [comment]
Which image tag are you using? If latest, please switch to v0.8.2

**Comment by keaxu-exp** [comment]
I am using ```https://raw.githubusercontent.com/argoproj/argo-events/master/hack/k8s/manifests/sensor-controller-deployment.yaml```

which has content:
```
# The sensor-controller listens for changes on the sensor CRD and creates sensor executor jobs
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sensor-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sensor-controller
    spec:
      serviceAccountName: argo-events-sa
      containers:
      - name: sensor-controller
        image: argoproj/sensor-controller
        imagePullPolicy: Always
        env:
          - name: SENSOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SENSOR_CONFIG_MAP
            value: sensor-controller-configmap
```
