### ISSUE TITLE
gitlab eventsource support for groups

### ISSUE THREAD

**Issue by jwillker** [argoproj/argo-events#2386]
**Is your feature request related to a problem? Please describe.**
My company has a GitLab with a lot of groups and subgroups with thousands of projects, so if I want to create an event source to listen to all my company webhooks or a particular group is a huge pain to write all in an EventsSource object, and maintain this updated is another pain, because everyday new projects die and born.

E.g:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  annotations:
  name: gitlab-webhook
  namespace: argo-events
spec:
  gitlab:
    my-company:
      events:
      - JobEvents
      gitlabBaseURL: https://gitlab.my-company.com/api/v4
      projects:
      - my-company/group1/subgroup1/projectA
      - my-company/group1/subgroup1/projectB
      - my-company/group1/subgroup1/projectC
      - my-company/group2/subgroup1/projectA
      - my-company/group2/subgroup72/projectZ
      - ....
```
I have about 8k projects now :cry: 

**Describe the solution you'd like**
It would be nice if the GitlabEventSource had a new field, `group` that accepts a group path and create the webhook at the group level instead of a specific project. This allows us to receive events from a specific group or all the groups of the company.

**Describe alternatives you've considered**
Other solutions that I can take is create a EventsSource to a unique project and use their listener URL to create manually a webook in some GitLab groups. This works I have tested but its is ugly and depend of manual actions for each Group.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
