### ISSUE TITLE
Jetstream Support for NATS EventSource and Sensor

### ISSUE THREAD

**Issue by joelcomp1** [argoproj/argo-events#2409]
**Is your feature request related to a problem? Please describe.**
I can't see any way to use the existing NATS Event Source or Sensor to connect to a jetstream subject.

**Describe the solution you'd like**
A way to update the existing EventSource / Sensor with a jetstream flag, maybe as simple as defining the stream. If left undefined then would fall back to NATS

**Describe alternatives you've considered**
Not using Argo Events since I can't use it to trigger on Jetstream messages.

**Additional context**
I can't see if this is already implemented anywhere but it doesn't seem to be supported.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by justinfx** [comment]
Hey @joelcomp1, why was this request completed back in Jan 2023? I didn't see any introduction of this feature and I am now about to create my own new request for it. Was there some external discussion where the maintainers said they didn't want to move forward with it? Or did you decide to just not use Argo Events because of the lack of the EventSource?

**Comment by joelcomp1** [comment]
The feature already exists in argo events its just not well documented.  i.e.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name:  test
spec:
  template:
    container:
      imagePullPolicy: IfNotPresent
  dependencies:
    - name: test
      eventSourceName: webhooks
      eventName: test
  triggers:
    - template:
        name: test
        nats:
          url: nats://nats-nats-cluster.nats:4222
          subject: test
          stream: blah
          payload:
            - src:
                dependencyName: test
                dataKey: body
              dest: body
```

hopefully that helps!
