### ISSUE TITLE
Support Backoff Feature for Calendar Schedule/Interval Job

### ISSUE THREAD

**Issue by keaxu-exp** [argoproj/argo-events#242]
**Is your feature request related to a problem? Please describe.**
Feature Request

**Describe the solution you'd like**
Backoff for scheduling. 
For instance, if a workflow takes 2 mins to run, but scheduled every minute. The second run is waiting until first run complete.

Configurable execution policy. 
e.g. Users are able to configure that if first run failed, when it's time to exec second run, is that gonna be drop on the floor, or run it anyway.

**Comment by VaibhavPage** [comment]
#60

**Comment by VaibhavPage** [comment]
I am thinking of adding following fields to a trigger 
```
# optional
policy:
    # define a linear or exponential backoff
    backoff:
        steps:
       duration:
       jitter:
      factor:
   # Becasue we support triggering any K8s resource, the only way to determine a resource is in either success or failure stage is to look at the labels on the resource.
    criteria:
        success:
            map[string]string
        failure:
            map[string]string
    # determines whether sensor should transition to error state if the backoff times out and yet the resource neither transitioned into success or failure.
    errorOnBackoffTimeout: false
```

And in sensor spec, 

`continueOnFailedRound: false
`

will be set to determine whether the sensor should transition into error if previous round of triggers were unsuccessful
