### ISSUE TITLE
Event processed multiple times (Azure Event Hub)

### ISSUE THREAD

**Issue by boehb-efs** [argoproj/argo-events#2475]
**Describe the bug**
We have the following structure:
- Argo Workflows (v3.4.3)
- Argo Events (v1.7.3)
- Azure Event Hub, 2 partitions

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-mgmt
spec:
  jetstream:
    version: latest
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: accessmanager-commit
  namespace: argo-mgmt
spec:
  azureEventsHub:
    accessmanager:
      fqdn: <our-eventhub>.servicebus.windows.net
      sharedAccessKeyName:
        name: azure-event-source
        key: sharedAccessKeyName
      sharedAccessKey:
        name: azure-event-source
        key: sharedAccessKey
      hubName: accessmanager-commit
```

Recently, we noticed that events are sometimes processed multiple times, i.e. the sensor is run through multiple times, although the event is only triggered once. The logs of the sensor suggest that the event was received multiple times, although it was only sent once.

Do you have any ideas on how to best approach the problem?

I tried using Kafka-Trigger instead with username="$ConnectionString" and password="{YOUR.EVENTHUBS.CONNECTION.STRING}" (as suggested here: https://learn.microsoft.com/en-us/azure/event-hubs/azure-event-hubs-kafka-overview#shared-access-signature-sas) - however no event was processed at all :-/

**Expected behavior**
Every event is processed exactly one time.

**Environment (please complete the following information):**
- Argo Workflows (v3.4.3)
- Argo Events (v1.7.3)
- Azure Event Hub, 2 partitions

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
