### ISSUE TITLE
Support Azure Managed Identity for Azure Service Bus event-source

### ISSUE THREAD

**Issue by o-fedorov** [argoproj/argo-events#2476]
**Is your feature request related to a problem? Please describe.**

Using **Azure Managed Identity** is a recommended way to authenticate _Service Bus_ clients. It is more secure comparing to _Shared Access Policy_ and _Shared Access Signature_ (SAP/SAS), and requires less effort to configure and maintain.

It is similar to **GKE Workload Identity**, that is [already supported](https://github.com/argoproj/argo-events/issues/503) by Argo Events.

Currently, _Azure Service Bus event-source_ supports only configuration via a _connection string_, which allows authorization with SAP/SAS only. It is not possible to utilize _Azure Managed Identity_ this way, since the later requires authorization via _Azure Active Directory_, and not SAP/SAS.

More details on the authorization methods: <https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-authentication-and-authorization>

**Describe the solution you'd like**

Go client for Azure Service Bus has a constructor that allows to use Azure AD for authorization ([link](https://github.com/Azure/azure-sdk-for-go/blob/a8700a4c87c8a63382b608d3ff2d03533a6f76bc/sdk/messaging/azservicebus/client.go#L72)).

It requires for users to only supply `fullyQualifiedNamespace`, while `credential` parameter can have a default value set to [DefaultAzureCredential](https://github.com/Azure/azure-sdk-for-go/blob/a8700a4c87c8a63382b608d3ff2d03533a6f76bc/sdk/azidentity/default_azure_credential.go#L54), that supports multiple ways of authorization, including Azure Managed Identity.

I see it as the following manifest:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: event-source
spec:
  eventBusName: eventbus
  template:
    metadata:
      labels:
        # Bind AAD Pod Identity, for more details visit
        # https://learn.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity
        aadpodidbinding: azure-identity-binding
  azureServiceBus:
    example:
      # queueName is the name of the queue to listen to
      queueName: test
      # jsonBody specifies that all event body payload coming from this
      # source will be JSON
      jsonBody: true
      # fullyQualifiedNamespace is the Service Bus namespace name
      fullyQualifiedNamespace: myservicebus.servicebus.windows.net
```

Note two differences comparing to the [existing example](https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/event-sources/azure-service-bus.yaml):

* `aadpodidbinding` label binds a managed identity to a pod.
* `fullyQualifiedNamespace` is used instead of `connectionString`, to indicate that Azure AD should be used for authorization, instead of SAP/SAS.

**Describe alternatives you've considered**

- For some projects, using a connection string is not an option. There can be a security requirement to use Azure AD.
- Except of using a Managed Identity, [DefaultAzureCredential](https://github.com/Azure/azure-sdk-for-go/blob/a8700a4c87c8a63382b608d3ff2d03533a6f76bc/sdk/azidentity/default_azure_credential.go#L54) also supports other ways for authorization, such as using a client secret, or a certificate. They can be configured with environment variables and pod secrets.

**Additional context**

The project I currently work on uses Argo Events. We would like to use it to get events from Azure Service Bus as well, but, unfortunately, SAP/SAS is not an option for us, we can only use a Managed Identity. Without Managed Identity support we, unfortunately, will not be able to use Argo Events for Azure Service Bus.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
