### ISSUE TITLE
username and password auth support for mqtt eventsource not working

### ISSUE THREAD

**Issue by BebbiBraeu** [argoproj/argo-events#2482]
**Describe the bug**
According to #2324 (related to #1863), the ability to use username and password authentication was added to MQTT eventsources with argo events 1.7.5. We updated our environment but are still unable to use the authentication. When adding a MQTT eventsource with the auth tag, either trough kubectl apply or the argo UI, the tag is ignored and gets removed in the UI. As our MQTT broker is user managed, the eventsource is unable to connect.

**To Reproduce**
1. Create eventsource yaml
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: mqtt
spec:
  mqtt:
    example:
      url: <cluster-url>
      topic: "test/#"
      jsonBody: true
      clientId: "1"
      auth:
        username:
          name: mqtt-secret
          key: user
        password:
          name: mqtt-secret
          key: password
```
2. Apply yaml either through kubectl apply or in argo UI
3. Check eventsource in argo UI
4. Check eventsource log in kubernetes pod

**Expected behavior**
Created eventsource connects to MQTT broker with provided credentials.

**Screenshots**
![image](https://user-images.githubusercontent.com/65661809/220672620-7dd5d92b-e19d-40ae-892a-84c3670d5ba0.png)
(removed url)

![image](https://user-images.githubusercontent.com/65661809/220672399-9ce681b7-ee30-4ecc-9d8d-93ff13e54968.png)

**Environment (please complete the following information):**
 - Kubernetes: v1.20.6
 - Argo: v3.4.3
 - Argo Events: v1.7.5

**Additional context**
I assume this is some kind of issue with the validation of the json schema.
The updated json schema looks good in the PR, so maybe the update failed on our side.
I am not the admin of our cluster but I am in close contact with him and can consult him if questions arise.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
