### ISSUE TITLE
Airgap for argo-events jetstream

### ISSUE THREAD

**Issue by antoinetran** [argoproj/argo-events#2504]
**Is your feature request related to a problem? Please describe.**
In a air-gapped environment with a private registry that is a mirror of dockerhub, we cannot override Argo-Events Jetstream to take the images from private registry.

**Describe the solution you'd like**
A configuration to specify:

- registry prefix (for all images)
- image override for each NATS images (in case the registry prefix is not enough)
- imagePullSecrets for registry authentication (already implemented according to https://github.com/argoproj/argo-events/blob/master/api/event-bus.md#argoproj.io/v1alpha1.JetstreamBus)

**Describe alternatives you've considered**
No workaround.

**Additional context**
Ideally something like this::
```
# https://argoproj.github.io/argo-events/eventbus/jetstream/
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  jetstream:
    imagePullSecrets: [ "regcred" ]
    #version: latest # Do NOT use "latest" but a specific version in your real deployment
    version: 2.9.12
    natsImage: artifactory.X.fr:443/lisa-docker/nats:2.9.12
    metricsExporterImage: artifactory.X.fr:443/lisa-docker/natsio/prometheus-nats-exporter:0.9.1
    configReloaderImage: artifactory.X.fr:443/lisa-docker/natsio/nats-server-config-reloader:0.7.0
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
