### ISSUE TITLE
Controller-manager crashes in loop on incorrect EventSource (Github webhook)

### ISSUE THREAD

**Issue by zelig81** [argoproj/argo-events#2517]
**Describe the bug**
Controller-manager pod crashes in a loop on incorrect EventSource of Github webhook type.

**To Reproduce**
1. Create the EventSource from the manifest down below
2. See error

**Expected behavior**
Update the status of EventSource on failure (it will help to update ArgoCD application status using a custom healthcheck(to-be-created).

**Screenshots**
Restart of Controller-manager due to application crash. `kubectl describe -l app=controller-manager`:
```
...
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 12 Mar 2023 16:36:49 +0200
      Finished:     Sun, 12 Mar 2023 16:39:10 +0200
...
```

3 last messages of Controller-manager:
```
controller-manager W0312 14:38:24.742282       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1alpha1.EventSource: json: cannot unmarshal object into Go struct field GithubEventSource.items.spec.github.repositories of type []v1alpha1.OwnedRepositories

controller-manager E0312 14:38:24.742312       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.EventSource: failed to list *v1alpha1.EventSource: json: cannot unmarshal object into Go struct field GithubEventSource.items.spec.github.repositories of type []v1alpha1.OwnedRepositories

controller-manager {"level":"fatal","ts":1678631950.0073829,"logger":"argo-events.eventbus-controller","caller":"cmd/start.go:182","msg":"unable to run eventbus controller","error":"failed to wait for sensor-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"github.com/argoproj/argo-events/controllers/cmd.Start\n\t/home/runner/work/argo-events/argo-events/controllers/cmd/start.go:182\ngithub.com/argoproj/argo-events/cmd/commands.NewControllerCommand.func1\n\t/home/runner/work/argo-events/argo-events/cmd/commands/controller.go:34\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\ngithub.com/argoproj/argo-events/cmd/commands.Execute\n\t/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19\nmain.main\n\t/home/runner/work/argo-events/argo-events/cmd/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.5/x64/src/runtime/proc.go:250"}
```

**Environment (please complete the following information):**
 - Kubernetes: 1.24
 - Argo: 3.4.4
 - Argo Events: 1.7.6

**Additional context**
<details><summary>EventSource that triggers the crash loopback</summary>

```yaml
# Info on GitHub Webhook: https://developer.github.com/v3/repos/hooks/#create-a-hook
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: git-my-precious
  labels:
    eventsource-name: git-my-precious
spec:
  eventBusName: eventbus
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    push:
      repositories:
        owner: my-precious # here is the source of the error - it had to be a list of objects instead of an object
        names:
        - ilya-test-1
      webhook:
        endpoint: /
        port: "12000"
        method: POST
        url: http://my.precious.url.com
      events:
        - push

      apiToken:
        name: github-token
        key: token
      webhookSecret:
        name: github-token
        key: secret

      insecure: true
      active: true
      contentType: json

    pull_request:
      repositories:
      - owner: my-precious # correct way to configure list of repositories
        names:
        - ilya-test-1
      webhook:
        endpoint: /
        port: "12000"
        method: POST
        url: http://my.precious.url.com
      events:
        - pull_request

      apiToken:
        name: github-token
        key: token
      webhookSecret:
        name: github-token
        key: secret

      insecure: true
      active: true
      contentType: json

```

</details>

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
