### ISSUE TITLE
feat: Support URLs for SQS and SNS event sources

### ISSUE THREAD

**Issue by harry1989** [argoproj/argo-events#2518]
**Is your feature request related to a problem? Please describe.**
Presently SQS and SNS event source accept just the name in their config but not an optional URL pointing to queue/topic. Accepting optional config to URL can help in testing workflows locally using [localstack](https://github.com/localstack/localstack).

**Describe the solution you'd like**
Change `SQSEventSource ` and `SNSEventSource` to accept optional parameters of `queueURL` and `topicURL` parameters. Use these URLs directly instead of computing while invoking AWS APIs. 

**Describe alternatives you've considered**
None, presently working with creating actual SQS/SNS topics for testing. This is costly and not scalable, we are already using localstack and would like to use it with argo events.  

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by harry1989** [comment]
Closing this we can achieve this by using `endpoint` attribute of sqsEventSource. 

```
sqs:
  example:
      # point to custom url instead of aws, useful with localstack 
      endpoint: http://172.18.0.3:4566
      queue: hello-world-queue
      region: us-east-1
      jsonBody: true
```
