### ISSUE TITLE
The new EventBus is unstable

### ISSUE THREAD

**Issue by Nizar-opt** [argoproj/argo-events#2521]
**Describe the bug**
After upgrading argo-events to v1.7.6 with Jetstream v2.9.12, we noticed that sometimes the triggers do not get passed to Sensors after being received by EventSources, we knew that by tracking their logs. When we checked the EventBus logs it was throwing bunch of errors and warnings, we tried to restart the Statefulset of the EventBus and that temporarily solved the issue for the stuck events but it happens every now and then. We also tried to wipe up all the resources on staging and reinstall argo-events but that didn't help, the errors and warnings are still there.

**To Reproduce**
_Steps to reproduce the behavior:_
Not sure what exactly produces this issue but for us we just upgraded to the aforementioned versions. 

**Expected behavior**
_A clear and concise description of what you expected to happen._
We Expect the EventBus it to pass all events to the sensors and stop showing those errors and warnings.

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes:  v1.23.14-gke.1800 
 - Argo: v3.4.4
 - Argo Events: v1.7.6
 - Jetstream: v2.9.12

**Additional context**
EventBus:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  jetstream:
    # kubectl describe configmap argo-events-controller-config
    version: 2.9.12
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              controller: eventbus-controller
              eventbus-name: default
          topologyKey: kubernetes.io/hostname
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                controller: eventbus-controller
                eventbus-name: default
            topologyKey: failure-domain.beta.kubernetes.io/zone
    persistence:
      storageClassName: standard
      accessMode: ReadWriteOnce
      volumeSize: 20Gi
    nodeSelector:
      cloud.google.com/gke-nodepool: argo-events
    tolerations:
    - key: "app"
      operator: "Equal"
      value: "argo-events"
      effect: "NoSchedule"
    # streamConfig: |             # see default values in argo-events-controller-config
    #   maxAge: 24h
    # settings: |
    #   max_file_store: 1GB       # see default values in argo-events-controller-config
    # startArgs:
    #   - "-D"                    # debug-level logs
```

EventBus logs:
```
[7] 2023/03/14 11:37:26.959200 [WRN] RAFT [8cyM8diw - C-R3F-DdAB1rw2] Wrong index, ae is &{leader:7zgMgllI term:78 commit:1200051 pterm:78 pindex:1200052 entries: 1}, index stored was 4161743, n.pindex is 1200052
[7] 2023/03/14 11:37:26.972781 [WRN] RAFT [WIs1b7tQ - C-R3F-Xj0HQyMv] Wrong index, ae is &{leader:8cyM8diw term:17 commit:1022417 pterm:17 pindex:1022417 entries: 1}, index stored was 2599127, n.pindex is 1022417
[7] 2023/03/14 11:37:26.972801 [WRN] RAFT [WIs1b7tQ - C-R3F-Xj0HQyMv] Error storing entry to WAL: raft: could not store entry to WAL
[7] 2023/03/14 11:37:26.972808 [WRN] RAFT [WIs1b7tQ - C-R3F-Xj0HQyMv] Expected first catchup entry to be a snapshot and peerstate, will retry
[7] 2023/03/14 11:37:27.014255 [WRN] RAFT [8cyM8diw - C-R3F-BP15x3p5] Wrong index, ae is &{leader:7zgMgllI term:92 commit:1198767 pterm:92 pindex:1198768 entries: 1}, index stored was 3374342, n.pindex is 1198768
[7] 2023/03/14 11:37:27.014464 [WRN] RAFT [8cyM8diw - C-R3F-jn33EcWz] Wrong index, ae is &{leader:7zgMgllI term:62 commit:582051 pterm:62 pindex:582051 entries: 1}, index stored was 1401266, n.pindex is 582051
[7] 2023/03/14 11:37:27.023563 [WRN] RAFT [8cyM8diw - C-R3F-FzXl8kpb] Wrong index, ae is &{leader:7zgMgllI term:70 commit:1197525 pterm:70 pindex:1197525 entries: 1}, index stored was 6520404, n.pindex is 1197525
[7] 2023/03/14 11:37:27.024032 [WRN] RAFT [8cyM8diw - C-R3F-YDqGIIIk] Wrong index, ae is &{leader:7zgMgllI term:72 commit:1197393 pterm:72 pindex:1197394 entries: 1}, index stored was 3414300, n.pindex is 1197394
[7] 2023/03/14 11:37:27.025365 [WRN] RAFT [8cyM8diw - C-R3F-uWUgUj3E] Wrong index, ae is &{leader:7zgMgllI term:73 commit:1255351 pterm:73 pindex:1255351 entries: 1}, index stored was 6916351, n.pindex is 1255351
[7] 2023/03/14 11:37:27.027598 [WRN] RAFT [8cyM8diw - C-R3F-5G7kG0SS] Wrong index, ae is &{leader:7zgMgllI term:103 commit:1194532 pterm:103 pindex:1194532 entries: 1}, index stored was 3392648, n.pindex is 1194532
[7] 2023/03/14 11:37:27.287277 [WRN] RAFT [8cyM8diw - C-R3F-u1l1oCSv] Wrong index, ae is &{leader:7zgMgllI term:75 commit:1192713 pterm:75 pindex:1192715 entries: 1}, index stored was 3408644, n.pindex is 1192715
[7] 2023/03/14 11:37:27.287300 [WRN] RAFT [8cyM8diw - C-R3F-u1l1oCSv] Error storing entry to WAL: raft: could not store entry to WAL
[7] 2023/03/14 11:37:27.287306 [WRN] RAFT [8cyM8diw - C-R3F-u1l1oCSv] Expected first catchup entry to be a snapshot and peerstate, will retry
[7] 2023/03/14 11:37:27.401871 [WRN] RAFT [WIs1b7tQ - C-R3F-AcF70zAW] Wrong index, ae is &{leader:7zgMgllI term:36 commit:1026192 pterm:36 pindex:1026192 entries: 1}, index stored was 2540322, n.pindex is 1026192
[7] 2023/03/14 11:37:27.402278 [WRN] RAFT [WIs1b7tQ - C-R3F-Xj0HQyMv] Wrong index, ae is &{leader:8cyM8diw term:17 commit:1022417 pterm:17 pindex:1022417 entries: 1}, index stored was 2599128, n.pindex is 1022417
[7] 2023/03/14 11:37:27.402510 [WRN] RAFT [WIs1b7tQ - C-R3F-wNa5K94Z] Wrong index, ae is &{leader:8cyM8diw term:19 commit:1030305 pterm:19 pindex:1030305 entries: 1}, index stored was 2532139, n.pindex is 1030305
[7] 2023/03/14 11:37:27.405980 [WRN] RAFT [WIs1b7tQ - C-R3F-aaLQog9g] Wrong index, ae is &{leader:7zgMgllI term:23 commit:1204187 pterm:23 pindex:1204189 entries: 1}, index stored was 2825208, n.pindex is 1204189
[7] 2023/03/14 11:37:27.424485 [WRN] RAFT [8cyM8diw - C-R3F-YDqGIIIk] Wrong index, ae is &{leader:7zgMgllI term:72 commit:1197393 pterm:72 pindex:1197394 entries: 1}, index stored was 3414301, n.pindex is 1197394
[7] 2023/03/14 11:37:27.424521 [WRN] RAFT [8cyM8diw - C-R3F-YDqGIIIk] Expected first catchup entry to be a snapshot and peerstate, will retry
[7] 2023/03/14 11:37:27.426105 [WRN] RAFT [8cyM8diw - C-R3F-uWUgUj3E] Wrong index, ae is &{leader:7zgMgllI term:73 commit:1255351 pterm:73 pindex:1255351 entries: 1}, index stored was 6916352, n.pindex is 1255351
[7] 2023/03/14 11:37:27.426123 [WRN] RAFT [8cyM8diw - C-R3F-uWUgUj3E] Error storing entry to WAL: raft: could not store entry to WAL
[7] 2023/03/14 11:37:27.426129 [WRN] RAFT [8cyM8diw - C-R3F-uWUgUj3E] Expected first catchup entry to be a snapshot and peerstate, will retry
[7] 2023/03/14 11:37:27.432721 [WRN] RAFT [8cyM8diw - C-R3F-FzXl8kpb] Wrong index, ae is &{leader:7zgMgllI term:70 commit:1197525 pterm:70 pindex:1197525 entries: 1}, index stored was 6520405, n.pindex is 1197525
[7] 2023/03/14 11:37:27.433123 [WRN] RAFT [8cyM8diw - C-R3F-FzXl8kpb] Error storing entry to WAL: raft: could not store entry to WAL
[7] 2023/03/14 11:37:27.433438 [WRN] RAFT [8cyM8diw - C-R3F-FzXl8kpb] Expected first catchup entry to be a snapshot and peerstate, will retry
[7] 2023/03/14 11:37:27.434694 [WRN] RAFT [8cyM8diw - C-R3F-DdAB1rw2] Wrong index, ae is &{leader:7zgMgllI term:78 commit:1200051 pterm:78 pindex:1200052 entries: 1}, index stored was 4161744, n.pindex is 1200052
[7] 2023/03/14 11:37:27.435015 [WRN] RAFT [8cyM8diw - C-R3F-DdAB1rw2] Error storing entry to WAL: raft: could not store entry to WAL
[7] 2023/03/14 11:37:27.435262 [WRN] RAFT [8cyM8diw - C-R3F-DdAB1rw2] Expected first catchup entry to be a snapshot and peerstate, will retry
[7] 2023/03/14 11:37:27.464820 [WRN] RAFT [WIs1b7tQ - C-R3F-b0Nd8ZmT] Wrong index, ae is &{leader:7zgMgllI term:17 commit:1027934 pterm:17 pindex:1027934 entries: 1}, index stored was 2529228, n.pindex is 1027934
[7] 2023/03/14 11:37:27.546190 [WRN] RAFT [8cyM8diw - C-R3F-jn33EcWz] Wrong index, ae is &{leader:7zgMgllI term:62 commit:582051 pterm:62 pindex:582051 entries: 1}, index stored was 1401267, n.pindex is 582051
[7] 2023/03/14 11:37:27.546713 [WRN] RAFT [8cyM8diw - C-R3F-jn33EcWz] Error storing entry to WAL: raft: could not store entry to WAL
[7] 2023/03/14 11:37:27.547585 [WRN] RAFT [8cyM8diw - C-R3F-BP15x3p5] Wrong index, ae is &{leader:7zgMgllI term:92 commit:1198767 pterm:92 pindex:1198768 entries: 1}, index stored was 3374343, n.pindex is 1198768
[7] 2023/03/14 11:37:27.547895 [WRN] RAFT [8cyM8diw - C-R3F-BP15x3p5] Error storing entry to WAL: raft: could not store entry to WAL
[7] 2023/03/14 11:37:27.573393 [WRN] RAFT [WIs1b7tQ - C-R3F-bUtAa2mN] Wrong index, ae is &{leader:7zgMgllI term:16 commit:1023066 pterm:16 pindex:1023066 entries: 1}, index stored was 2593367, n.pindex is 1023066
[7] 2023/03/14 11:37:27.585461 [WRN] RAFT [WIs1b7tQ - C-R3F-AcF70zAW] Wrong index, ae is &{leader:7zgMgllI term:36 commit:1026192 pterm:36 pindex:1026192 entries: 1}, index stored was 2540323, n.pindex is 1026192
[7] 2023/03/14 11:37:27.588730 [WRN] RAFT [WIs1b7tQ - C-R3F-wNa5K94Z] Wrong index, ae is &{leader:8cyM8diw term:19 commit:1030305 pterm:19 pindex:1030305 entries: 1}, index stored was 2532140, n.pindex is 1030305
[7] 2023/03/14 11:37:27.606063 [WRN] RAFT [WIs1b7tQ - C-R3F-Xj0HQyMv] Wrong index, ae is &{leader:8cyM8diw term:17 commit:1022417 pterm:17 pindex:1022417 entries: 1}, index stored was 2599129, n.pindex is 1022417
[7] 2023/03/14 11:37:27.610101 [WRN] RAFT [WIs1b7tQ - C-R3F-aaLQog9g] Wrong index, ae is &{leader:7zgMgllI term:23 commit:1204187 pterm:23 pindex:1204189 entries: 1}, index stored was 2825209, n.pindex is 1204189
[7] 2023/03/14 11:37:27.612894 [WRN] RAFT [WIs1b7tQ - C-R3F-b0Nd8ZmT] Wrong index, ae is &{leader:7zgMgllI term:17 commit:1027934 pterm:17 pindex:1027934 entries: 1}, index stored was 2529229, n.pindex is 1027934
[7] 2023/03/14 11:37:27.638330 [WRN] RAFT [8cyM8diw - C-R3F-js97UcZk] Wrong index, ae is &{leader:7zgMgllI term:89 commit:1199332 pterm:89 pindex:1199332 entries: 1}, index stored was 3391403, n.pindex is 1199332
[7] 2023/03/14 11:37:27.638357 [WRN] RAFT [8cyM8diw - C-R3F-js97UcZk] Expected first catchup entry to be a snapshot and peerstate, will retry
[7] 2023/03/14 11:37:27.638608 [WRN] RAFT [8cyM8diw - C-R3F-u1l1oCSv] Wrong index, ae is &{leader:7zgMgllI term:75 commit:1192713 pterm:75 pindex:1192715 entries: 1}, index stored was 3408645, n.pindex is 1192715
[7] 2023/03/14 11:37:27.639221 [WRN] RAFT [8cyM8diw - C-R3F-PoNbqXVG] Wrong index, ae is &{leader:7zgMgllI term:110 commit:1199336 pterm:110 pindex:1199337 entries: 1}, index stored was 6865177, n.pindex is 1199337
[7] 2023/03/14 11:37:27.639237 [WRN] RAFT [8cyM8diw - C-R3F-PoNbqXVG] Error storing entry to WAL: raft: could not store entry to WAL
[7] 2023/03/14 11:37:27.639242 [WRN] RAFT [8cyM8diw - C-R3F-PoNbqXVG] Expected first catchup entry to be a snapshot and peerstate, will retry
[7] 2023/03/14 11:37:27.699318 [WRN] RAFT [8cyM8diw - C-R3F-YDqGIIIk] Wrong index, ae is &{leader:7zgMgllI term:72 commit:1197393 pterm:72 pindex:1197394 entries: 1}, index stored was 3414302, n.pindex is 1197394
[7] 2023/03/14 11:37:27.700469 [WRN] RAFT [8cyM8diw - C-R3F-uWUgUj3E] Wrong index, ae is &{leader:7zgMgllI term:73 commit:1255351 pterm:73 pindex:1255351 entries: 1}, index stored was 6916353, n.pindex is 1255351
[7] 2023/03/14 11:37:27.701954 [WRN] RAFT [8cyM8diw - C-R3F-FzXl8kpb] Wrong index, ae is &{leader:7zgMgllI term:70 commit:1197525 pterm:70 pindex:1197525 entries: 1}, index stored was 6520406, n.pindex is 1197525
[7] 2023/03/14 11:37:27.702162 [WRN] RAFT [8cyM8diw - C-R3F-DdAB1rw2] Wrong index, ae is &{leader:7zgMgllI term:78 commit:1200051 pterm:78 pindex:1200052 entries: 1}, index stored was 4161745, n.pindex is 1200052
[7] 2023/03/14 11:37:27.704481 [WRN] RAFT [8cyM8diw - C-R3F-BP15x3p5] Expected first catchup entry to be a snapshot and peerstate, will retry
[7] 2023/03/14 11:37:27.785664 [WRN] RAFT [8cyM8diw - C-R3F-jn33EcWz] Expected first catchup entry to be a snapshot and peerstate, will retry
[7] 2023/03/14 11:37:27.906409 [WRN] RAFT [8cyM8diw - C-R3F-5G7kG0SS] Wrong index, ae is &{leader:7zgMgllI term:103 commit:1194532 pterm:103 pindex:1194532 entries: 1}, index stored was 3392649, n.pindex is 1194532
[7] 2023/03/14 11:37:27.907047 [WRN] RAFT [8cyM8diw - C-R3F-5G7kG0SS] Error storing entry to WAL: raft: could not store entry to WAL
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by ferboz** [comment]
From nats release note [v2.9.12](https://github.com/nats-io/nats-server/releases/tag/v2.9.12) 

Quote:
`NOTE: regressions were found in this release. Please skip this and go directly to the [v2.9.14 release](https://github.com/nats-io/nats-server/releases/tag/v2.9.14).`

**Comment by Nizar-opt** [comment]
looks like argo-events 1.7.6 does not support v2.9.14 yet, EventBus status:
```yaml
status:
  conditions:
    - lastTransitionTime: '2023-03-20T15:04:40Z'
      status: 'True'
      type: Configured
    - lastTransitionTime: '2023-03-20T15:04:40Z'
      message: >-
        failed to get jetstream version, err: unsupported version "2.9.14",
        supported versions:
        "latest,2.8.1,2.8.1-alpine,2.8.2,2.8.2-alpine,2.9.1,2.9.12"
      reason: JetStreamStatefulSetFailed
      status: 'False'
      type: Deployed
```
