### ISSUE TITLE
Template labels are ignored for sensors and eventsources

### ISSUE THREAD

**Issue by mbruner** [argoproj/argo-events#2551]
**Describe the bug**
Labels from `sensor/spec/template/metadata/labels` and `eventsource/spec/template/metadata/labels` are ignored.

**To Reproduce**
Create sensor:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor
spec:
  dependencies:
    ...
  triggers:
    ...
  metadata:
    labels:
      app: value
```
Sensor pods will have only:
```yaml
labels:
  controller: sensor-controller
  owner-name: sensor
  sensor-name: sensor
```

**Expected behavior**
Pod labels contain `app: value`

**Environment (please complete the following information):**
 - Argo Events: [e.g. v1.7.6]

**Additional context**
It seems like the problem is here:
https://github.com/argoproj/argo-events/blob/master/controllers/sensor/resource.go#L294-L296
https://github.com/argoproj/argo-events/blob/master/controllers/eventsource/resource.go#L334-L336

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
