### ISSUE TITLE
Add a templateRef as an option for a trigger source

### ISSUE THREAD

**Issue by drew-viles** [argoproj/argo-events#2573]
**Is your feature request related to a problem? Please describe.**
No, not as such. It's more a way of organising how workflows are configured around sensors.

**Describe the solution you'd like**
It'd be nice to be able to set a template ref as an option for a sensor trigger.

Something like
```
spec:
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            templateRef:
              name: another-workflow
              template: the-workflow-template 
```

**Describe alternatives you've considered**
The only other alternative is to configure the workflow in-line which can get messy for large workflows.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
