### ISSUE TITLE
SNS and SQS Examples don't work, more instructions and docs need

### ISSUE THREAD

**Issue by keaxu-exp** [argoproj/argo-events#258]
I am trying to deploy SNS and SQS gateways following readme and examples, but none of them works.

I think I am missing multiple things, but first of all I want confirm how to write configmap.yaml

For creds, I am doing following things:

```
    accessKey:
      name: aws-secret
      key: {my aws_access_key_id }
    secretKey:
      name aws-secret
      key: {my aws_secret_access_key}
```

what 'name' fields should I put there ? leave it as 'aws-secret' ?

**Comment by VaibhavPage** [comment]
`name` within `accessKey` and `secretKey` refers to K8s secret that contains your AWS creds.

 If you don't already have a secret that holds your AWS credentials, you need to create it and then refer the name of the secret in configmap. 
e.g. 

aws secret = 
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  accesskey: YWNjZXNz
  secretkey: c2VjcmV0
```

So, the accessKey and secretKey within configmap will look like - 

   ```
 accessKey:
      name: aws-secret
      key: accesskey
secretKey:
      name aws-secret
      key: secretkey
```

**Comment by keaxu-exp** [comment]
For SQS gateway, should I see sqs gateway pod creating after:
```
k apply -n argo-events -f gateway.yaml
```
?

I am following this:
1) created secret of Opaque as you send me
2) applied sqs gateway configmap yaml as following:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-sqs-gateway-configmap
data:
  notification_1: |-
    accessKey:
      name: aws-secret
      key: accesskey
    secretKey:
      name aws-secret
      key: secretkey
    region: "us-west-2"
    queue: "my-test-queue"
    waitTimeSeconds: 10
```

3) applied sqs gateway yaml as following:
```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: aws-sqs-gateway
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
    gateway-name: "aws-sqs-gateway"
spec:
  processorPort: "9330"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  deploySpec:
    metadata:
      name: "aws-sqs-gateway"
      labels:
        gateway-name: "aws-sqs-gateway"
    spec:
      containers:
        - name: "gateway-client"
          image: "argoproj/gateway-client:v0.8.3"
          imagePullPolicy: "Always"
          command: ["/bin/gateway-client"]
        - name: "aws-sqs-events"
          image: "argoproj/aws-sqs-gateway:v0.8.3"
          imagePullPolicy: "Always"
          command: ["/bin/aws-sqs-gateway"]
      serviceAccountName: "argo-events-sa"
  configMap: "aws-sqs-gateway-configmap"
  eventVersion: "1.0"
  type: "aws-sqs"
  watchers:
    sensors:
      - name: "aws-sqs-sensor"
```
After step 3) nothing happen. I don't see according sqs pod creating. 
I also tried lastest image, but same behavior.

**Comment by VaibhavPage** [comment]
The spec looks wrong. Shouldn't this be https://github.com/argoproj/argo-events/blob/master/examples/gateways/aws-sqs.yaml ?

**Comment by keaxu-exp** [comment]
Oh yes. Ok now I have pods running:
```
NAME                                  READY   STATUS    RESTARTS   AGE
aws-sqs-gateway                       2/2     Running   0          25m
aws-sqs-sensor                        1/1     Running   0          6m
```

and I can see sensor service runing (it that suppose to have only sqs-sensor service? )
```
aws-sqs-sensor-svc
```

But When I trigger SQS, nothing happen in argo-events. Any Ideas ? any more AWS networking setup required ?

**Comment by VaibhavPage** [comment]
sqs-sensor service should be there as expected.  

Can you check the logs of gateway pod?

**Comment by keaxu-exp** [comment]
```
klf -n argo-events aws-sqs-gateway -c aws-sqs-events
```
just one line
```
starting gateway server
```

**Comment by VaibhavPage** [comment]
Let me try to reproduce it

**Comment by VaibhavPage** [comment]
I am able to get the events from sqs queue. Can you try again?

**Comment by keaxu-exp** [comment]
Does my log seem normal? Which image version are you using?

**Comment by VaibhavPage** [comment]
I am using `latest` image. You can also use `v0.8.3` or `v0.9`

**Comment by keaxu-exp** [comment]
Here is my configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-sqs-gateway-configmap
data:
  notification_1: |-
    accessKey:
      name: aws-secret
      key: accesskey
    secretKey:
      name aws-secret
      key: secretkey
    region: "us-west-2"
    queue: "my-sqs-test-queue"
    waitTimeSeconds: 10
```

gateway (same as example)
```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: aws-sqs-gateway
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
    gateway-name: "aws-sqs-gateway"
spec:
  processorPort: "9330"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  template:
    metadata:
      name: "aws-sqs-gateway"
      labels:
        gateway-name: "aws-sqs-gateway"
    spec:
      containers:
        - name: "gateway-client"
          image: "argoproj/gateway-client:v0.8.3"
          imagePullPolicy: "Always"
          command: ["/bin/gateway-client"]
        - name: "aws-sqs-events"
          image: "argoproj/aws-sqs-gateway:v0.8.3"
          imagePullPolicy: "Always"
          command: ["/bin/aws-sqs-gateway"]
      serviceAccountName: "argo-events-sa"
  configMap: "aws-sqs-gateway-configmap"
  eventVersion: "1.0"
  type: "aws-sqs"
  watchers:
    sensors:
      - name: "aws-sqs-sensor"
```
sensor (same as example)
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sqs-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor:v0.8.3"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  dependencies:
    - name: "aws-sqs-gateway:notification_1"
  triggers:
    - template:
        name: sqs-workflow
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: aws-sqs-workflow-
            spec:
              entrypoint: whalesay
              arguments:
                parameters:
                - name: message
                  # this is the value that should be overridden
                  value: hello world
              templates:
              - name: whalesay
                inputs:
                  parameters:
                  - name: message
                container:
                  image: docker/whalesay:latest
                  command: [cowsay]
                  args: ["{{inputs.parameters.message}}"]
      resourceParameters:
        - src:
            event: "aws-sqs-gateway:notification_1"
          dest: spec.arguments.parameters.0.value
```

see this in `aws-sqs-gateway gateway-client` logs:

```
2019-04-02T16:47:18Z | error | msg: event source is not valid |  event-source-name:notification_1 gateway-name:aws-sqs-gateway gateway-namespace:argo-events validation-failure:"failed to parse event source. err: error converting YAML to JSON: yaml: line 6: mapping values are not allowed in this context"
```

**Comment by VaibhavPage** [comment]
Looks like some indentation problem with `notification_1` data.

**Comment by VaibhavPage** [comment]
@nstott did you face any issue with sqs gateway like above?

**Comment by nstott** [comment]
no, I didn't
my cm seems to work
```
apiVersion: v1
data:
  notification: |-
    accessKey:
      name: aws
      key: accesskey
    secretKey:
      name: aws
      key: secretkey
    region: "us-west-2"
    queue: "test-trigger"
    waitTimeSeconds: 20
kind: ConfigMap
metadata:
  creationTimestamp: 2019-04-02T18:56:42Z
...
```
everything is working well

**Comment by keaxu-exp** [comment]
Thanks! I got cm work. 

but got SQS auth issue now.

I apply my secret yaml file in the same namespace of gateway.

my secret yaml:

```
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  accesskey: <my access key>
  secretkey: <my secret key>
```

find this in gateway logs:

```
error="rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Post https://sqs.us-west-2.amazonaws.com/: net/http: invalid header field value \"AWS4-HMAC-SHA256 Credential=\\x00\\xa2\\x00 b\\x80\\\\\\xb4\\x8b\\\\n@Y\\x0e\\x00/20190402/us-west-2/sqs/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=...
```

AWS Credential should be  
```
<access-key-id>/<date>/<aws-region>/<aws-service>/aws4_request
```

what in logs `\\x00\\xa2\\x00 b\\x80\\\\\\xb4\\x8b\\\\n@Y\\x0e\\x00` is definitely not my `<access-key-id>`

How does gateway pick aws creds ?
seems like it doesn't pick my access key id correctly.
