### ISSUE TITLE
Kafka Trigger - `unexpected EOF` error

### ISSUE THREAD

**Issue by snooyen** [argoproj/argo-events#2580]
**Describe the bug**
We want to produce messages on our MSK Cluster for S3 Bucket Object Events.  
`S3 Bucket Object Event` -> `SNS` -> `ArgoEvents SNS Event Source` -> `ArgoEvents JetStream EventBus` -> `ArgoEvents Sensor w/ Kafka Trigger` -> `MSK Cluster`

We've validated the `S3 Bucket Object Event` -> `ArgoEvents Sensor w/ LogTrigger` already.  The missing piece is producing the message on our MSK Cluster.

When attempting to produce a message on our `AWS MSK Cluster`, we are facing a crypting `unexpected EOF (x3)` error.
We've already verified routing/security group configurations between our EKS cluster and MSK cluster via AWS Reachability Analyzer AND via other services running on the same EKS cluster that talk to our MSK cluster.

Also tried with only one broker in the `kafka.url` error but hit the same error.

Error Message:
```json
{
    "level": "info",
    "ts": 1681852034.6398003,
    "logger": "argo-events.sensor",
    "caller": "sensor/trigger_conn.go:348",
    "msg": "Triggering actions after receiving dependency s3-sns-kafka-event-source-dep",
    "sensorName": "s3-sns-kafka-events",
    "triggerName": "kafka-trigger"
} {
    "level": "error",
    "ts": 1681852035.4367816,
    "logger": "argo-events.sensor",
    "caller": "sensors/trigger.go:104",
    "msg": "failed to new a Kafka trigger",
    "sensorName": "s3-sns-kafka-events",
    "triggerName": "kafka-trigger",
    "error": "kafka: client has run out of available brokers to talk to: 3 errors occurred:\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n",
    "stacktrace": "github.com/argoproj/argo-events/sensors.(*SensorContext).GetTrigger\n\t/home/runner/work/argo-events/argo-events/sensors/trigger.go:104\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerOne\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:377\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:354"
} {
    "level": "error",
    "ts": 1681852035.436886,
    "logger": "argo-events.sensor",
    "caller": "sensors/listener.go:356",
    "msg": "Failed to execute a trigger",
    "sensorName": "s3-sns-kafka-events",
    "error": "invalid trigger kafka-trigger, could not find an implementation",
    "triggerName": "kafka-trigger",
    "triggeredBy": ["s3-sns-kafka-event-source-dep"],
    "triggeredByEvents": ["62386564613733322d636161322d346334632d393332302d653264343630623863363632"],
    "stacktrace": "github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:356"
}
```

**To Reproduce**
1. Apply Sensor Configuration
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: s3-sns-kafka-events
spec:
  dependencies:
    - name: s3-sns-kafka-event-source-dep
      eventSourceName: s3-sns-kafka-events
      eventName: s3-sns-events
  triggers:
    - template:
        name: kafka-trigger
        kafka:
          # Kafka URL
          url: b-2.sandbox-msk-cluster.kafka.us-west-2.amazonaws.com:9094,b-3.sandbox-msk-cluster.kafka.us-west-2.amazonaws.com:9094,b-1.sandbox-msk-cluster.kafka.us-west-2.amazonaws.com:9094
          # Name of the topic
          topic: s3-sns-events
          payload:
            - src:
                dependencyName: s3-sns-kafka-event-source-dep
                dataKey: notification.0.s3.object.key
              dest: fileName
            - src:
                dependencyName: s3-sns-kafka-event-source-dep
                dataKey: notification.0.s3.bucket.name
              dest: bucket

```
2. Create / Delete S3 Object

**Expected behavior**
Message produced on MSK Cluster

**Environment (please complete the following information):**
 - Kubernetes: v1.23.16-eks-48e63af
 - ArgoCD: v2.4.11
 - Argo Events: v1.7.6

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by snooyen** [comment]
This looks like it's related to #1277. Specifically [this comment](https://github.com/argoproj/argo-events/issues/1277#issuecomment-1071039350) in the thread.

Our MSK Clusters are not using TLS/SASL/SCRAM authentication, but we ARE using TLS Encryption for connections between our brokers/clients.

Amending our Sensor configuration as follows helped moved me along (to a different, but more workable error)
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: s3-sns-kafka-events
spec:
  dependencies:
    - name: s3-sns-kafka-event-source-dep
      eventSourceName: s3-sns-kafka-events
      eventName: s3-sns-events
  triggers:
    - template:
        name: kafka-trigger
        kafka:
          tls:
            insecureSkipVerify: true
          # Kafka URL
          url: b-2.sandbox-msk-cluster.kafka.us-west-2.amazonaws.com:9094,b-3.sandbox-msk-cluster.kafka.us-west-2.amazonaws.com:9094,b-1.sandbox-msk-cluster.kafka.us-west-2.amazonaws.com:9094
          # Name of the topic
          topic: s3-sns-events
          payload:
            - src:
                dependencyName: s3-sns-kafka-event-source-dep
                dataKey: notification.0.s3.object.key
              dest: fileName
            - src:
                dependencyName: s3-sns-kafka-event-source-dep
                dataKey: notification.0.s3.bucket.name
              dest: bucket
```
