### ISSUE TITLE
Sensor not loading workflowMetadata of ArgoWorflowTrigger

### ISSUE THREAD

**Issue by paco-sisutech** [argoproj/argo-events#2582]
**Describe the bug**
Trying to add workflowMetadata to Workflow of a sensor make workflow hang without changing status/phase
**To Reproduce**
Given this Workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: "get-services"
spec:
  serviceAccountName: operate-workflow-sa
  workflowMetadata:
    labelsFrom:
        repo:
            expression: workflow.parameters.example
  arguments:
    parameters:
      - name: example
        value: example-1
  entrypoint: runner
  templates:
    - name: runner
      steps:
        - - name: get-services
            templateRef:
              name: get-services
              template: get-services
            arguments:
              parameters:
                - name: serviceName
                  value: '{{input.parameters.example}}

```

Works when running it in argo-workflows but when added to a sensor like this one:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-build-image-and-sync
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: build-image-dep
      eventSourceName: webhook
      eventName: build-image
  triggers:
    - template:
        name: build-image-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: "get-services"
              spec:
                serviceAccountName: operate-workflow-sa
                workflowMetadata:
                  labelsFrom:
                      repo:
                          expression: workflow.parameters.example
                arguments:
                  parameters:
                    - name: example
                      value: example-1
                entrypoint: runner
                templates:
                  - name: runner
                    steps:
                      - - name: get-services
                          templateRef:
                            name: get-services
                            template: get-services
                          arguments:
                            parameters:
                              - name: serviceName
                                value: '{{input.parameters.example}}
```

then it will not start up, it will appear and the pod would be created but without the metadata and will not run
**Expected behavior**
Workflow would show the metadata labels and workflow would run normally

**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.24.10]
 - Argo: [e.g. v3.4.7]
 - Argo Events: [e.g. v1.7.6]

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
