### ISSUE TITLE
Add consumer group to Kafka gateway

### ISSUE THREAD

**Issue by michielhub** [argoproj/argo-events#264]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the option to add a consumer group to the Kafka config for clarity and monitoring purposes.

**Describe the solution you'd like**
Possibility to put Kafka consumer group in kafka-gateway-configmap yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-gateway-configmap
data:
  foo: |-
    url: kafka.argo-events:9092
    topic: foo
    partition: "0"
    consumer-group: "test-group-1"
```
