### ISSUE TITLE
Sensor dependency is reacting to unrelated eventsource message

### ISSUE THREAD

**Issue by corkupine** [argoproj/argo-events#2650]
**Describe the bug**
We have two SQS EventSources polling two different queues. On the other end of the EventBus, we've got multiple sensors that are reacting to messages found in the EventBus.

The issue is that a Sensor that has a dependency only on one EventSource is executing triggers when events are added by another EventSource.

Either dependencies are broken, or I don't understand how they are supposed to work. My understanding is that specifying the `eventSourceName` and `eventName` would scope that dependency and the events it reacts to, to events that originated from that EventSource and specific Event. Otherwise, I'm not sure what those would be used for.

Here is what the EventSources and Sensors look like (more or less):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: aws-sqs-a
spec:
  template:
    serviceAccountName: es-sa-a
  sqs:
    queue-a:
      region: us-east-1
      queue: queue-a
      waitTimeSeconds: 20
      jsonBody: true
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: aws-sqs-b
spec:
  template:
    serviceAccountName: es-sa-b
  sqs:
    queue-b:
      region: us-east-1
      queue: queue-b
      waitTimeSeconds: 20
      jsonBody: true
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-a
spec:
  template:
    serviceAccountName: s-sa-a
  dependencies:
    - name: dependency-a
      eventSourceName: aws-sqs-a
      eventName: queue-a
      filters:
        dataLogicalOperator: "and"
        data:
          - path: "body.detail-type"
            type: "string"
            comparator: "!="
            value: 
              - "type-1"
  triggers:
    - template:
        name: http-trigger-a
        http:
          url: "http://service/api/v1"
          payload:
            - src:
                dependencyName: dependency-a
                dataKey: body
              dest: body
          method: POST
      retryStrategy:
        steps: 3
        duration: 3s
      policy:
        status:
          allow:
            - 200
            - 201
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-b
spec:
  dependencies:
      - name: dependency-b
      eventSourceName: aws-sqs-b
      eventName: queue-b
      filters:
        dataLogicalOperator: "and"
        data:
          - path: "body.detail-type"
            type: "string"
            value:
              - "type-2"
  triggers:
    - template:
        name: http-trigger-b
        http:
          url: "http://service-b/api/v1"
          payload:
            - src:
                dependencyName: dependency-b
                dataKey: body
              dest: body
          method: POST
      retryStrategy:
        steps: 3
        duration: 3s
      policy:
        status:
          allow:
            - 200
            - 201
```
When a message is found in AWS queue `queue-b` and sent to the bus as an event by EventSource `aws-sqs-b`, somehow `sensor-a` picks up the event (assuming it matches the filter) and `http-trigger-a` processes it, despite the fact that the dependency `eventSourceName` is `aws-sqs-a` and `eventName` is `queue-a`.

**To Reproduce**
1. Configure Argo Events similarly to the above
2. Drop a message into `queue-b` that matches the filter specified in `dependency-a` in `sensor-a`

**Expected behavior**
The event is picked up and processed by `sensor-b`

**Screenshots**
The event is picked up and processed by `sensor-a`

**Environment (please complete the following information):**
 - Kubernetes: 1.24
 - Argo Events: image v1.7.1

**Additional context**
The manifest above is simplified to make understanding the problem easier.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by corkupine** [comment]
In an attempt to see if I could prevent the sensor from picking up events from the wrong EventSource, I added more configuration to `sensor-a`, thinking that more constraints might help. However, the trigger is still processing events I don;t want it to.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-a
spec:
  template:
    serviceAccountName: s-sa-a
  dependencies:
    - name: dependency-a
      eventSourceName: aws-sqs-a
      eventName: queue-a
      filters:
        context:
          source: aws-sqs-a
          subject: queue-a
        data:
          - path: "body.detail-type"
            type: "string"
            comparator: "!="
            value: 
              - "type-1"
        dataLogicalOperator: and
      filtersLogicalOperator: and
  triggers:
    - template:
        conditions: "dependency-a"
        name: http-trigger-a
        http:
          url: "http://service/api/v1"
          payload:
            - src:
                dependencyName: dependency-a
                dataKey: body
              dest: body
          method: POST
      retryStrategy:
        steps: 3
        duration: 3s
      policy:
        status:
          allow:
            - 200
            - 201
```
