### ISSUE TITLE
Race conditions in sensor

### ISSUE THREAD

**Issue by abaguas** [argoproj/argo-events#2660]
**Describe the bug**
The argo sensor crashed right after receiving a batch of requests.

**To Reproduce**
Not reproducible, seems to be a race condition.

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: v1.26.3
 - Argo Events: v1.8.0

**Config**
ArgoEvents is calls a webhook, but I think the error is more generic and not really dependent on the config
```
    template:
      http:
        method: POST
        payload:
        - dest: dataref
          src:
            dataKey: body.dataref
            dependencyName: configchange
        - dest: traceparent
          src:
            dataKey: body.traceparent
            dependencyName: configchange
            value: ""
        url: http://config-downloader:9090/
```

**Logs**
```
{"level":"info","ts":1686904703.0876606,"logger":"argo-events.sensor","caller":"http/http.go:194","msg":"Making a http request...","sensorName":"cc-configchange","triggerName":"configchange","triggerType":"HTTP","url":"http://config-downloader:9090/opt-osagavira-etc/policy.surfers.conf"}
{"level":"info","ts":1686904703.087826,"logger":"argo-events.sensor","caller":"sensor/trigger_conn.go:348","msg":"Triggering actions after receiving dependency configchange","sensorName":"cc-configchange","triggerName":"configchange","sensorName":"cc-configchange"}
{"level":"info","ts":1686904703.0881736,"logger":"argo-events.sensor","caller":"http/http.go:194","msg":"Making a http request...","sensorName":"cc-configchange","triggerName":"configchange","triggerType":"HTTP","url":"http://config-downloader:9090/opt-osagavira-etc/policy.ptc.conf"}
{"level":"info","ts":1686904703.1868587,"logger":"argo-events.sensor","caller":"sensors/listener.go:423","msg":"Successfully processed trigger 'configchange'","sensorName":"cc-configchange","triggerName":"configchange","triggerType":"HTTP","triggeredBy":["configchange"],"triggeredByEvents":["62333238313764342d333730382d343332352d396563342d663866313433653965643465"]}
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 188 [running]:
github.com/argoproj/argo-events/sensors/triggers/nats.NewNATSTrigger(0xc000682d00, 0xc00161ed00, 0x2e68632e6e65706f?, 0x2e72657473756c63?)
	/home/runner/work/argo-events/argo-events/sensors/triggers/nats/nats.go:70 +0x1d7
github.com/argoproj/argo-events/sensors.(*SensorContext).GetTrigger(0xc000b22000, {0x3b6c688?, 0xc000e30050?}, 0xc00161ed00)
	/home/runner/work/argo-events/argo-events/sensors/trigger.go:120 +0x70e
github.com/argoproj/argo-events/sensors.(*SensorContext).triggerOne(0xc000b22000, {0x3b6c688?, 0xc000e30050}, 0xc000682d00, {0xc0009e9ea0, {0x0, 0x0, 0x0}, 0x0, 0x0, ...}, ...)
	/home/runner/work/argo-events/argo-events/sensors/listener.go:383 +0x36b
github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit(0xc000b22000, {0x3b6c688, 0xc000e30050}, 0xc000682d00, {0xc0009e9ea0, {0x0, 0x0, 0x0}, 0x0, 0x0, ...}, ...)
	/home/runner/work/argo-events/argo-events/sensors/listener.go:360 +0x165
created by github.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions
	/home/runner/work/argo-events/argo-events/sensors/listener.go:350 +0x6ea
```
Complete logs attached:
[argoventscrash.txt](https://github.com/argoproj/argo-events/files/11770363/argoventscrash.txt)
