### ISSUE TITLE
Duplicated Gitlab webhooks when using Eventsource with HA

### ISSUE THREAD

**Issue by paolocarta** [argoproj/argo-events#2682]
**Describe the bug**

I have an EventSource with 2 replicas for different Gitlab events. The EventSource is responsible for creating the webhooks on the configured repos. When having HA we see duplicated webhooks, probably due to some concurrency issues between the replicas.

**To Reproduce**
1. Create an EventSource with 2 replicas
2. Create a Gitlab event which creates a webhook
3. You will notice often duplicated hooks

**Expected behavior**
I would expect not seeing duplicated webhooks in the repo.

**Screenshots**
<img width="410" alt="Screen Shot 2023-06-27 at 4 40 15 PM" src="https://github.com/argoproj/argo-events/assets/4989554/fa5a171e-75cd-4ddf-b211-36cc0e8bcb42">

**Environment:**
 - Argo: v3.4.7
 - Argo Events: v1.7.6

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@daniel-codefresh - could you take a look?

**Comment by sonbui00** [comment]
@paolocarta Just take some test and check. I think this may have duplicate trigger from Gitlab side. I also see some issue report about Gitlab Webhook Duplication on Gitlab

**Comment by bygui86** [comment]
@sonbui00 

> @paolocarta Just take some test and check. I think this may have duplicate trigger from Gitlab side.

We opened this issue (@paolocarta and me work together on this) right after taking some tests. We never saw duplicated triggers from GitLab side before scaling out the EventSource to 2 replicas (trying to achieve HA).

> I also see some issue report about Gitlab Webhook Duplication on Gitlab

Can you please give some links?

To be more precise, these are the steps to reproduce this issue:
1. Deploy an EventSource configured with 2 replicas and some GitLab repos with one or more webhooks for push, tag or MR events
2. After some seconds, go to each Gitlab repo and check webhooks
3. You will notice often duplicated hooks

Please note: this issue does not happen for each single GitLab repo configured in the EventSource, but for some out of all.

**Comment by sonbui00** [comment]
@bygui86 These are some link 
https://github.com/n8n-io/n8n/issues/2042
https://gitlab.com/gitlab-org/gitlab-foss/-/issues/15

Today I've tested with latest version of Argo Workflow and Argo Event.
I've used Gitlab Event source from examples - with replicas 2:
[examples/event-sources/gitlab.yaml](https://github.com/argoproj/argo-events/blob/master/examples/event-sources/gitlab.yaml)
And the I just use curl to push a message.

```
Argo: v3.4.7
Argo Events: v1.7.6
```
Do you think the issue only happend on this version?

**Comment by bygui86** [comment]
@sonbui00 sorry but you missed the point I described right above and in general the description of the issue itself.

The event in ArgoEvents are duplicated because webhhoks are duplicated at creation time by Argo Events EventSource.
There is no need for curl to verify this issue.

Having:
- a GitLab EventSource with replicas=2
- some GitLab repos configured in the EventSource to automatically created the webhook
at webhook creation time it seems that EventSource replicas does not coordinate themselves and they end up creating 2 webhooks in some of configured repos.

In the example you mentioned , in some repos of the list under `projects` (we have many, like 100) the EventSource creates 2 webhooks instead of just one:
```yaml
# More info on GitLab project hooks: https://docs.gitlab.com/ce/api/projects.html#add-project-hook
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitlab
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  gitlab:
    example:
      # Project namespace paths or IDs
      projects:
        - "whynowy/test"
        - "3"
      # GitLab will send events to following port and endpoint
      webhook:
        # [...]
      events:
        - PushEvents
        - TagPushEvents
      accessToken:
        # [...]
      secretToken:
        # [...]
[...]
```
