### ISSUE TITLE
Unable to connect kafka-eventsource to Kafka broker url

### ISSUE THREAD

**Issue by wesleyscholl** [argoproj/argo-events#2684]
**Describe the bug**
After multiple configurations and troubleshooting, I am unable to connect the kafka-eventsource to the Kafka broker url.

**To Reproduce**
1. Followed the setup instructions here: [Argo Kafka Setup](https://argoproj.github.io/argo-events/eventsources/setup/kafka/#setup) and here: [Kubernetes-kafka](https://github.com/Yolean/kubernetes-kafka)
3. Attempted using various urls - kafka.argo-events:9092, localhost:9092, kafka-broker:9092 and http://localhost:9092
4. Attempted using various kafka broker configurations - [Youlean kafka config](https://github.com/Yolean/kubernetes-kafka/blob/master/kafka/50kafka.yml) and [Alternative kafka configuration](https://levelup.gitconnected.com/how-to-deploy-apache-kafka-with-kubernetes-9bd5caf7694f)
5. Published new messages in kafka to the configured topic.
6. All unable to read new messages created in the configured Kafka topic. 

**Expected behavior**
Argo eventsource should read new messages from the configured topic and kickoff a workflow.

**Screenshots, Configurations, and Logs**

<details open>
<summary>Eventsource yaml</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka
spec:
  kafka:
    example:
      url: kafka.argo-events:9092
# attempted using kafka.argo-events:9092, localhost:9092, kafka-broker:9092 and http://localhost:9092
      topic: topic-2
# attempted using topic-1/2/3/4/5/etc and matched to each kafka message topic
      jsonBody: true
      partition: "1"
      connectionBackoff:
        duration: 10s
        steps: 5
        factor: 2
        jitter: 0.2
```
</details>

<details>
<summary>Kafka sensor & workflow trigger</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: kafka
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: kafka
      eventName: example
  triggers:
    - template:
        name: kafka-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: kafka-workflow-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
```
</details>

<details>
<summary>Logs from EventSource/kafka</summary>

```bash
namespace=argo-events, eventSourceName=kafka, eventSourceType=kafka, eventName=example, level=info, time=2023-06-28T17:38:17Z, msg=connecting to Kafka cluster...
namespace=argo-events, eventSourceName=kafka, eventSourceType=kafka, eventName=example, level=info, time=2023-06-28T17:38:17Z, msg=start kafka event source...
namespace=argo-events, eventSourceName=kafka, eventSourceType=kafka, eventName=example, level=info, time=2023-06-28T17:38:17Z, msg=start kafka event source...
namespace=argo-events, eventSourceName=kafka, eventSourceType=kafka, eventName=example, level=info, time=2023-06-28T17:38:17Z, msg=connecting to Kafka cluster...
namespace=argo-events, eventSourceName=kafka, eventSourceType=kafka, eventName=example, level=info, time=2023-06-28T17:38:17Z, msg=start kafka event source...
namespace=argo-events, eventSourceName=kafka, eventSourceType=kafka, eventName=example, level=info, time=2023-06-28T17:38:17Z, msg=start kafka event source...
namespace=argo-events, eventSourceName=kafka, eventSourceType=kafka, eventName=example, level=info, time=2023-06-28T17:38:17Z, msg=connecting to Kafka cluster...
```
</details>

<details>
<summary>The event flow configured in the UI</summary>

<img width="1188" alt="Screenshot 2023-06-28 at 1 22 48 PM" src="https://github.com/argoproj/argo-events/assets/128409641/c036b2fa-0984-4668-9ee5-69a04e24f5a0">
</details>

<details>
<summary>Kafka-broker port forward</summary>

<img width="497" alt="Screenshot 2023-06-28 at 1 40 57 PM" src="https://github.com/argoproj/argo-events/assets/128409641/fbdec91f-edf2-4978-8389-6b9715b23a2f">
</details>

<details>
<summary>Kafka messages</summary>

<img width="447" alt="Screenshot 2023-06-28 at 1 43 04 PM" src="https://github.com/argoproj/argo-events/assets/128409641/ce066fe1-8e6d-4180-962c-3bbb6116680a">
</details>

<details>
<summary>Initial kafka yaml config</summary>

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
      annotations:
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: init-config
        image: solsson/kafka:initutils@sha256:8988aca5b34feabe8d7d4e368f74b2ede398f692c7e99a38b262a938d475812c
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ['/bin/bash', '/etc/kafka-configmap/init.sh']
        volumeMounts:
        - name: configmap
          mountPath: /etc/kafka-configmap
        - name: config
          mountPath: /etc/kafka
        - name: extensions
          mountPath: /opt/kafka/libs/extensions
      containers:
      - name: broker
        image: solsson/kafka:2.5.1@sha256:5c52620bd8e1bcd47805eb8ca285843168e1684aa27f1ae11ce330c3e12f6b0c
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLASSPATH
          value: /opt/kafka/libs/extensions/*
        - name: KAFKA_LOG4J_OPTS
          value: -Dlog4j.configuration=file:/etc/kafka/log4j.properties
        - name: JMX_PORT
          value: "5555"
        ports:
        - name: inside
          containerPort: 9092
        - name: outside
          containerPort: 9094
        - name: jmx
          containerPort: 5555
        command:
        - ./bin/kafka-server-start.sh
        - /etc/kafka/server.properties.$(POD_NAME)
        lifecycle:
          preStop:
            exec:
             command: ["sh", "-ce", "kill -s TERM 1; while $(kill -0 1 2>/dev/null); do sleep 1; done"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            # This limit was intentionally set low as a reminder that
            # the entire Yolean/kubernetes-kafka is meant to be tweaked
            # before you run production workloads
            memory: 600Mi
        readinessProbe:
          tcpSocket:
            port: 9092
          timeoutSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /etc/kafka
        - name: data
          mountPath: /var/lib/kafka/data
        - name: extensions
          mountPath: /opt/kafka/libs/extensions
      volumes:
      - name: configmap
        configMap:
          name: broker-config
      - name: config
        emptyDir: {}
      - name: extensions
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
```
</details>

<details>
<summary>Alternative kafka broker yaml</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
  namespace: kafka
spec:
  ports:
  - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 10.43.56.121:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-broker:9092
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092
```
</details>

**Environment (please complete the following information):**
 - Kubernetes: v1.25.9
 - Argo: v3.4.7
 - Argo Events: v1.7.6
 - MacOS: 13.4 (22F66)

**Additional context**

I'm thinking it could be a networking issue, as I've had issues connecting to other kubernetes pods and docker containers. Did I configure something wrong? Please advise.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
