### ISSUE TITLE
Failed to create a deployment when enable SASL authentication

### ISSUE THREAD

**Issue by yichen-li-system1** [argoproj/argo-events#2685]
**Describe the bug**
Hi guys, I have created an event source for Kafka that should connect the Confluent Kafka cluster. 
Here is my yaml file 
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka
spec:
  kafka:
    example:
      url: my.confluent.cloud:9092
      topic: "test-topic"
      sasl:
        mechanism: PLAIN
        passwordSecret:
          key: password
          name: <Plain text from confluent API key>
        userSecret:
          key: user
          name: <Plain text from confluent API key>
      jsonBody: true
      partition: "1"
      connectionBackoff:
        duration: 10s
        steps: 5
        factor: 2
        jitter: 0.2
```
After creating an event source with it, the status shows the error `Failed to create a deployment`. 
![image](https://github.com/argoproj/argo-events/assets/95650314/895fa2b2-19c7-47ca-9dac-60ca9f67f81f)

Just for the purpose to compare, I delete `sasl` from the yaml file above and tired it again. 
Of course, it is running but hanging at the step of  `msg=connecting to Kafka cluster...`
![image](https://github.com/argoproj/argo-events/assets/95650314/1f9cfa70-ba63-408b-a780-dadce38b3c67)

Is anyone have any idea about it? 
Am I missing something here?  
I would really appreciate any kind of helps. 

**Environment (please complete the following information):**
 - Kubernetes: v1.26.3
 - Argo: v3.4.8
 - Argo Events: v1.7.6

**Additional context**
I am running Argo workflow and Argo Events locally under Minikube. 
The Kafka cluster I am trying to connect is hosted on Confluent. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
```yaml
        passwordSecret:
          key: password
          name: <Plain text from confluent API key>
        userSecret:
          key: user
          name: <Plain text from confluent API key>
```

The username and password are supposed to be store in k8s secrets, where the name is the secret name, key is the entry key in the secret.
