### ISSUE TITLE
nodeSelector in Workflow causes sensor to fail

### ISSUE THREAD

**Issue by pplavetzki** [argoproj/argo-events#271]
**Describe the bug**
When the sensor executes the trigger if I have a nodeSelector value the sensor fails to process the trigger.
```
2019-04-17T15:20:00Z | error | msg: trigger failed to execute |  error="v1alpha1.Workflow.Spec: v1alpha1.WorkflowSpec.Templates: []v1alpha1.Template: v1alpha1.Template.NodeSelector: ReadString: expects \" or n, but found t, error found in #10 byte of ...|ume.wfs\":true}},{\"co|..., bigger context ...|:\"get-project\",\"nodeSelector\":{\"argo.volume.wfs\":true}},{\"container\":{\"env\":[{\"name\":\"AUTH\",\"valueFr|..." sensor-name:webhook-nats-streaming trigger-name:argo-workflow
```

**To Reproduce**
1. Add a label to a node
2. In the sensor, in the workflow source, add a nodeSelector
3. Execute an event that triggers the sensor.

**Expected behavior**
The workflow is executed as expected.  I've verified that submitting this workflow directly using the argo cli works as expected.

**Environment (please complete the following information):**
 - v1.11.3, 3 masters, 4 workers
 - Argo Events: v0.8.1
 - Argo Version v2.2.0

**Additional context**
Here is a snippet of the workflow:
```
                - name: test
                  container:
                    image: testing-service:build7
                    imagePullPolicy: IfNotPresent
                    volumeMounts:
                      - name: install-config-data
                        mountPath: /var/config
                      - name: project-data
                        mountPath: /var/data
                      - name: log-data
                        mountPath: /var/log
                    env:
                      - name: AUTH
                        valueFrom:
                          secretKeyRef:
                            name: auth
                            key: auth_token
                      - name: WORKFLOW_SERVICE_KEY
                        value: "install-junos-os"
                    resources:
                      requests:
                        memory: 128Mi
                        cpu: 300m
                  nodeSelector:
                    argo.volume.wfs: true
```
