### ISSUE TITLE
Sensor passing in Azure Service Bus event payload to workflow trigger as it is thereby ignoring data key

### ISSUE THREAD

**Issue by sudivate** [argoproj/argo-events#2717]
**Describe the bug**
Sensor passing in Azure Service Bus event payload to workflow trigger as it is thereby ignoring data key

**Event Source**
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: azure-service-bus
spec:
  azureServiceBus:
    trigger-workflow:
      queueName: trigger
      jsonBody: true
      decodeMessage: true
      connectionString:
        key: azure-service-bus-connection-string
        name: azure-service-bus-connection-string
```

**Sensor**
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: azure-service-bus
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: trigger-dep
      eventSourceName: azure-service-bus
      eventName: trigger-workflow
  triggers:
    - template:
        name: workflow-trigger
        argoWorkflow:
            operation: submit
            source:
              resource:
                apiVersion: argoproj.io/v1alpha1
                kind: Workflow
                metadata:
                  generateName: trigger-workflow-
                spec:
                  arguments:
                    parameters:
                      - name: image
                      - name: command
                  entrypoint: run
                  workflowTemplateRef:
                    name: trigger-workflow
            parameters:
              - src:
                  dependencyName: trigger-dep
                  datakey: body.name
                dest: spec.arguments.parameters.0.value
              - src:
                  dependencyName: trigger-dep
                  datakey: body.command
                dest: spec.arguments.parameters.1.value
```
**Message**
```
import os, json
from azure.servicebus import ServiceBusClient, ServiceBusMessage
servicebus_client = ServiceBusClient.from_connection_string(conn_str=os.environ['SERVICE_BUS_CONNECTION_STRING'])
with servicebus_client:
    sender = servicebus_client.get_queue_sender(queue_name="trigger")
    with sender:
        message = ServiceBusMessage('{"image": "hello-world", "command": "run"}')
        sender.send_messages(message)
```

 **Workflow triggers with parameter as entire payload with data encoded in Base64**

```
{
  "context": {
    "id": "32336336353266332d663036652d343630342d613339632d303364363030663630363638",
    "source": "azure-service-bus",
    "specversion": "1.0",
    "type": "azureServiceBus",
    "datacontenttype": "application/json",
    "subject": "trigger",
    "time": "2023-07-19T00:20:46Z"
  },
  "data": "eyJhcHBsaWNhdGlvblByb3BlcnRpZXMiOm51bGwsImJvZHkiOnsiaW1hZ2UiOiJoZWxsby13b3JsZCIsImNvbW1hbmQiOiJydW4ifSwiY29udGVudFR5cGUiOm51bGwsImNvcnJlbGF0aW9uSUQiOm51bGwsImVucXVldWVkVGltZSI6IjIwMjMtMDctMTlUMDA6MjA6NDYuNzAxWiIsIm1lc3NhZ2VJRCI6Ijg4ODE4MzJmLTg0OTUtNGY5OC1hNWM2LWY0NTU0ZTM0N2VmZCIsInJlcGx5VG8iOm51bGwsInNlcXVlbmNlTnVtYmVyIjoyMDgyOTE0ODI3NjU4ODU1NCwic3ViamVjdCI6bnVsbH0="
}
```
**Decoding Base64 data**

````
{
  "applicationProperties": null,
  "body": {
    "image": "hello-world",
    "command": "run"
  },
  "contentType": null,
  "correlationID": null,
  "enqueuedTime": "2023-07-19T00:20:46.701Z",
  "messageID": "8881832f-8495-4f98-a5c6-f4554e347efd",
  "replyTo": null,
  "sequenceNumber": 20829148276588554,
  "subject": null
}
````
**Expected behavior**
Expecting `datakey:body.image` and `datakey:body.command` to be resolved to appropriate fields from the payload.

 - Argo Workflows: [v3.4.8]
 - Argo Events: [v1.8.0]
