### ISSUE TITLE
Gitlab gateway: x509: failed to load system roots and no roots provided 

### ISSUE THREAD

**Issue by xannz** [argoproj/argo-events#273]
**Describe the bug**
After deploying the Gitlab gateway and gateway configmap I get the following error:
```
error | msg: failed to receive event from stream |  error="rpc error: code = Unknown desc = failed to add project hook. err: Post https://<GITLAB-URL>/api/v4/projects/1137/hooks: x509: failed to load system roots and no roots provided" event-source-name:project_1 gateway-name:gitlab-gateway gateway-namespace:argo-events
```

**To Reproduce**
The gateway:
```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: gitlab-gateway
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
    gateway-name: "gitlab-gateway"
spec:
  processorPort: "9330"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  template:
    metadata:
      name: "gitlab-gateway"
      labels:
        gateway-name: "gitlab-gateway"
    spec:
      containers:
        - name: "gateway-client"
          image: "argoproj/gateway-client"
          imagePullPolicy: "Always"
          command: ["/bin/gateway-client"]
        - name: "gitlab-events"
          image: "argoproj/gitlab-gateway"
          imagePullPolicy: "Always"
          command: ["/bin/gitlab-gateway"]
      serviceAccountName: "argo-events-sa"
  service:
    metadata:
      name: gitlab-gateway-svc
    spec:
      selector:
        gateway-name: "gitlab-gateway"
      ports:
        - port: 12000
      type: NodePort
  configMap: "gitlab-gateway-configmap"
  type: "gitlab"
  eventVersion: "1.0"
  watchers:
    sensors:
      - name: "gitlab-sensor"
```
Configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-gateway-configmap
data:
  project_1: |-
    id: 5
    projectId: "1137"
    hook:
     endpoint: "/push"
     port: "12000"
    event: "PushEvents"
    accessToken:
      key: token
      name: observer
    enableSSLVerification: false
    gitlabBaseUrl: "https://<GITLAB-URL>"
```

**Expected behavior**
The certificate to be trusted.

**Additional context**
I changed the Loadbalancer service to Nodeport and a NGINX is setup up to reverse proxy to the gateway service.

**Comment by VaibhavPage** [comment]
Can you mount your certs and key in gateway pod as showcased in https://github.com/argoproj/argo-events/blob/master/examples/gateways/secure-webhook.yaml

The `hook` in your configuration will then need to modified to refer cert and key like, 

```
    hook:
     endpoint: "/push"
     port: "12000"
     # serverCertPath refers to file where certificate is stored
     serverCertPath: "/etc/secret-volume/cert"
     # serverKeyPath refers to file where private key is stored
     serverKeyPath: "/etc/secret-volume/key"
```
