### ISSUE TITLE
Multiple sns event sources not working

### ISSUE THREAD

**Issue by ashishagg** [argoproj/argo-events#274]
I am trying to deploy one gateway, two event sources (different sns topics) and one sensor.
Following the event source example [here](https://github.com/argoproj/argo-events/blob/master/examples/event-sources/aws-sns.yaml). The only difference is I have a different topic arn on http-port 13000. I am not using https. 

Http server starts up on 13000 and 12000 as I am able to telnet on these two ports. Curl behaves differently.
```
curl <gateway-service>:12000 => returns empty response
```

```
curl <gateway-service>:13000 => return 404 (page not found)
```

I suspect the routes are not setup correctly for 13000 port. Please note that I am adding a second sns event source(another topic arn) after I get the single-event-source working end to end. 
 
**To Reproduce**
1. Deploy [gateway](https://github.com/argoproj/argo-events/blob/master/examples/gateways/aws-sns.yaml) 
2. Deploy sns event sources as mentioned above. 
3. Deploy sns sensor.
4. AWS/SNS subscription remains in a pending state. 

**Expected behavior**
AWS/SNS subscription should complete.

This is how my sns-event-sources.yaml looks like
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-sns-event-source
  labels:
    # do not remove
    argo-events-event-source-version: v0.10
data:
  example: |-
    # topic arn
    topicArn: "arn:aws:sns:us-east-1:11111111:topic-event-1"
    # hook contains configuration for the HTTP server running in the gateway.
    # AWS will send events to following port and endpoint
    hook:
     # endpoint to listen events on
     endpoint: "/"
     # port to run HTTP server on
     port: "12000"
     # url the gateway will use to register at AWS.
     # This url must be reachable from outside the cluster.
     # The gateway pod is backed by the service defined in the gateway spec. So get the URL for that service AWS can reach to.
     url: "http://myelb/topic-event-1"
    # accessKey contains information about K8s secret that stores the access key
    accessKey:
      # Key within the K8s secret whose corresponding value (must be base64 encoded) is access key
      key: accesskey
      # Name of the K8s secret that contains the access key
      name: aws-secret
    # secretKey contains information about K8s secret that stores the secret key
    secretKey:
      # Key within the K8s secret whose corresponding value (must be base64 encoded) is secret key
      key: secretkey
      # Name of the K8s secret that contains the secret key
      name: aws-secret
    # aws region
    region: "us-east-1"
  example-another: |-
    # topic arn
    topicArn: "arn:aws:sns:us-east-1:11111111:topic-event-2"
    # hook contains configuration for the HTTP server running in the gateway.
    # AWS will send events to following port and endpoint
    hook:
     # endpoint to listen events on
     endpoint: "/"
     # port to run HTTP server on
     port: "13000"
     # url the gateway will use to register at AWS.
     # This url must be reachable from outside the cluster.
     # The gateway pod is backed by the service defined in the gateway spec. So get the URL for that service AWS can reach to.
     url: "http://myelb/topic-event-2"
    # accessKey contains information about K8s secret that stores the access key
    accessKey:
      # Key within the K8s secret whose corresponding value (must be base64 encoded) is access key
      key: accesskey
      # Name of the K8s secret that contains the access key
      name: aws-secret
    # secretKey contains information about K8s secret that stores the secret key
    secretKey:
      # Key within the K8s secret whose corresponding value (must be base64 encoded) is secret key
      key: secretkey
      # Name of the K8s secret that contains the secret key
      name: aws-secret
    # aws region
    region: "us-east-1"
```
