### ISSUE TITLE
Replace controller-manager's `spec/template/spec/containers/0/env/0/value` with `spec/template/spec/containers/0/env/0/valueFrom/fieldRef/fieldpath`

### ISSUE THREAD

**Issue by jblsk** [argoproj/argo-events#2778]
**Is your feature request related to a problem? Please describe.**
Hard-coded `ARGO_EVENTS_IMAGE` env value with `image-name:tag` String is awkward to patch if we want to patch deployment's container `image` field, i.e. when using private image registry instead of pulling from public `quay.io/argoproj` directly
 
**Describe the solution you'd like**
Update in `install.yaml` env `ARGO_EVENTS_IMAGE` value with a reference:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: argo-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-manager
  template:
    metadata:
      labels:
        app: controller-manager
    spec:
      containers:
      - args:
        - controller
        env:
        - name: ARGO_EVENTS_IMAGE
          valueFrom:
            fieldRef:
              fieldPath: spec.containers[0].image
...
```

**Describe alternatives you've considered**
Currently, we patch the String value using `kustomizetion.yaml` with:
```yaml
# keep the image below in sync with images/0/newName and actual imageTag
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: docker.my-company.com/argoproj/argo-events:v1.8.0
  target:
    kind: Deployment
    name: controller-manager
```

**Additional context**
When the value of the `ARGO_EVENTS_IMAGE` env will be fetched as a reference from deployment, using `kustomization.yaml` with `images` transformer will suffice, and the patch won't be necessary anymore:
```yaml
images:
  - name: quay.io/argoproj/argo-events
    newName: docker.my-company.com/argoproj/argo-events
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
