### ISSUE TITLE
Workflow is not triggred consistently, missing events using aws sqs

### ISSUE THREAD

**Issue by simGudim** [argoproj/argo-events#2794]
**Describe the bug**
We have an Argo Sensor with a trigger configured using aws sqs and s3 notification. Each time we upload a file to a particular bucket/key we should expect the workflow to be triggered. However, sometime the workflow gets triggered and sometimes it does not. We are certain that the payload is making it's way to sqs, because we can see the invocation through sqs console monitoring. Sometimes it requires 3 or more uploads to trigger the workflow, and sometime it gets triggered right away. We have looked at the logs of eventbus pods, event-source pods and sensor pods. There are errors in eventbus pods which I am not certain are normal. The eventBus,. Sensor and and EventSource are all created on the same namespace, which means that we can Argo Events installed with managed namespaces. We also have multiple events configured using the same SQS

**To Reproduce**
```yaml

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: something
spec:
  template:
    serviceAccountName: argo-events-sa
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "eks.amazonaws.com/nodegroup"
              operator: In
              values: ["management"]
  dependencies:
    - name: some-condition
      eventSourceName: some-data-from-s3
      eventName: some-event
      filters:
        data:
          - path: body.Records.0.s3.object.key
            type: string
            value:
              - ".*some.json"
          - path: body.Records.0.s3.bucket.name
            type: string
            value:
              - ".*some-bucket"
  triggers:
    - template:
        name: some-workflow
        argoWorkflow:
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: some-listener-
                labels:
                  app: some-listener
              spec:
                arguments:
                  parameters:
                    - name: message
                      value: 0
                workflowTemplateRef:
                  name: some-listener-template
          operation: submit
          parameters:
            - src:
                dependencyName: some-condition
                dataKey: body
              dest: spec.arguments.parameters.0.value
          group: argoproj.io
          version: v1alpha1
          resource: Workflow
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eventbus-default-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      controller: eventbus-controller
      eventbus-name: default
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      auth: token
      persistence:
        accessMode: ReadWriteOnce
        volumeSize: 20Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "eks.amazonaws.com/nodegroup"
                operator: In
                values: ["management"]
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    controller: eventbus-controller
                    eventbus-name: default
                topologyKey: kubernetes.io/hostname
              weight: 100
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: some-data-from-s3
spec:
  replicas: 1
  template:
    serviceAccountName: some-sa
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "eks.amazonaws.com/nodegroup"
            operator: In
            values: ["management"]
  sqs:
    some-event:
      jsonBody: true
      region: us-east-1
      queue: some-queue
      waitTimeSeconds: 20
```

**Expected behavior**
Consistently trigger the workflow once a file gets uploaded to s3

**Screenshots**
logs from eventbus-default-stan-0
```bash

[1] 2023/09/08 11:43:54.183903 [INF] STREAM: Starting nats-streaming-server[eventbus-default] version 0.22.1
[1] 2023/09/08 11:43:54.183936 [INF] STREAM: ServerID: 7T4ZpFvRUQ6MCgYOcBulE9
[1] 2023/09/08 11:43:54.183938 [INF] STREAM: Go version: go1.16.6
[1] 2023/09/08 11:43:54.183940 [INF] STREAM: Git commit: [27f1d60]
[1] 2023/09/08 11:43:54.187506 [INF] Starting nats-server
[1] 2023/09/08 11:43:54.187519 [INF]   Version:  2.3.3
[1] 2023/09/08 11:43:54.187521 [INF]   Git:      [aaba459]
[1] 2023/09/08 11:43:54.187523 [INF]   Name:     NBMTUAZZE6CUMANQX7WUJY6VG6VHRD37BM5Y42EATKVJE6IRPXWBD6C3
[1] 2023/09/08 11:43:54.187525 [INF]   ID:       NBMTUAZZE6CUMANQX7WUJY6VG6VHRD37BM5Y42EATKVJE6IRPXWBD6C3
[1] 2023/09/08 11:43:54.187528 [INF] Using configuration file: /etc/stan-config/stan.conf
[1] 2023/09/08 11:43:54.189799 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2023/09/08 11:43:54.189863 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2023/09/08 11:43:54.190093 [INF] Server is ready
[1] 2023/09/08 11:43:54.190116 [INF] Cluster name is 7T4ZpFvRUQ6MCgYOcBulIz
[1] 2023/09/08 11:43:54.190120 [WRN] Cluster name was dynamically generated, consider setting one
[1] 2023/09/08 11:43:54.190152 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2023/09/08 11:43:54.201895 [ERR] Error trying to connect to route (attempt 1): lookup for host "eventbus-default-stan-0.eventbus-default-stan-svc.electric-eye.svc": lookup eventbus-default-stan-0.eventbus-default-stan-svc.electric-eye.svc on 10.100.0.10:53: no such host
[1] 2023/09/08 11:43:54.218787 [INF] STREAM: Recovering the state...
[1] 2023/09/08 11:43:54.228370 [ERR] Error trying to connect to route (attempt 1): lookup for host "eventbus-default-stan-2.eventbus-default-stan-svc.electric-eye.svc": lookup eventbus-default-stan-2.eventbus-default-stan-svc.electric-eye.svc on 10.100.0.10:53: no such host
[1] 2023/09/08 11:43:54.230434 [INF] STREAM: Recovered 1 channel(s)
[1] 2023/09/08 11:43:54.230911 [INF] STREAM: Cluster Node ID : eventbus-default-stan-0
[1] 2023/09/08 11:43:54.230924 [INF] STREAM: Cluster Log Path: /data/stan/logs
[1] 2023/09/08 11:43:54.230927 [INF] STREAM: Cluster known peers:
[1] 2023/09/08 11:43:54.230937 [INF] STREAM: peer 1: "eventbus-default-stan-1"
[1] 2023/09/08 11:43:54.230942 [INF] STREAM: peer 2: "eventbus-default-stan-2"
[1] 2023/09/08 11:43:54.236844 [ERR] Error trying to connect to route (attempt 1): lookup for host "eventbus-default-stan-1.eventbus-default-stan-svc.electric-eye.svc": lookup eventbus-default-stan-1.eventbus-default-stan-svc.electric-eye.svc on 10.100.0.10:53: no such host
[1] 2023/09/08 11:43:54.447125 [INF] STREAM: Message store is RAFT_FILE
[1] 2023/09/08 11:43:54.447139 [INF] STREAM: Store location: /data/stan/store
[1] 2023/09/08 11:43:54.447175 [INF] STREAM: ---------- Store Limits ----------
[1] 2023/09/08 11:43:54.447177 [INF] STREAM: Channels:                  100 *
[1] 2023/09/08 11:43:54.447180 [INF] STREAM: --------- Channels Limits --------
[1] 2023/09/08 11:43:54.447182 [INF] STREAM:   Subscriptions:          1000 *
[1] 2023/09/08 11:43:54.447183 [INF] STREAM:   Messages     :       1000000 *
[1] 2023/09/08 11:43:54.447186 [INF] STREAM:   Bytes        :       1.00 GB
[1] 2023/09/08 11:43:54.447188 [INF] STREAM:   Age          :       72h0m0s
[1] 2023/09/08 11:43:54.447190 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2023/09/08 11:43:54.447192 [INF] STREAM: ----------------------------------
[1] 2023/09/08 11:43:57.328935 [INF] 192.168.140.6:43064 - rid:9 - Route connection created
[1] 2023/09/08 11:43:57.329098 [ERR] 192.168.140.6:43064 - rid:9 - Rejecting connection, cluster name "6ajmwy6HUBhvJI8G2RACoA" does not match "7T4ZpFvRUQ6MCgYOcBulIz"
[1] 2023/09/08 11:43:57.329124 [INF] 192.168.140.6:43064 - rid:9 - Router connection closed: Cluster Name Conflict
[1] 2023/09/08 11:43:57.329135 [ERR] 192.168.140.6:43064 - rid:9 - cluster name from remote server conflicts
[1] 2023/09/08 11:43:59.372811 [INF] 192.168.140.6:43072 - rid:12 - Route connection created
[1] 2023/09/08 11:44:00.277663 [INF] 192.168.140.6:6222 - rid:16 - Route connection created
[1] 2023/09/08 11:44:00.280268 [INF] 192.168.140.6:6222 - rid:16 - Router connection closed: Duplicate Route
[1] 2023/09/08 11:44:01.461292 [INF] STREAM: server became leader, performing leader promotion actions
[1] 2023/09/08 11:44:01.469859 [INF] STREAM: finished leader promotion actions
[1] 2023/09/08 11:44:01.469877 [INF] STREAM: Streaming Server is ready
[1] 2023/09/08 11:44:03.768802 [INF] 192.168.145.118:50488 - rid:25 - Route connection created
[1] 2023/09/08 11:44:03.769109 [INF] Cluster name updated to uZ0bjd3otG03yexI0HsfZe
[1] 2023/09/08 11:44:03.769130 [INF] 192.168.140.6:43072 - rid:12 - Router connection closed: Cluster Name Conflict
[1] 2023/09/08 11:44:03.769503 [INF] 192.168.145.118:50488 - rid:25 - Router connection closed: Client Closed
[1] 2023/09/08 11:44:04.752746 [INF] STREAM: server lost leadership, performing leader stepdown actions
[1] 2023/09/08 11:44:04.752832 [INF] STREAM: finished leader stepdown actions
[1] 2023/09/08 11:44:04.829503 [INF] 192.168.145.118:50504 - rid:27 - Route connection created
[1] 2023/09/08 11:44:04.842159 [INF] 192.168.140.6:60778 - rid:28 - Route connection created
[1] 2023/09/08 11:44:04.869575 [INF] 192.168.140.6:6222 - rid:29 - Route connection created
[1] 2023/09/08 11:44:04.870087 [INF] 192.168.140.6:6222 - rid:29 - Router connection closed: Duplicate Route
[1] 2023/09/08 11:44:05.300582 [INF] 192.168.145.118:6222 - rid:30 - Route connection created
[1] 2023/09/08 11:44:05.301352 [INF] 192.168.145.118:6222 - rid:30 - Router connection closed: Duplicate Route
[1] 2023/09/08 11:44:08.340711 [INF] STREAM: server became leader, performing leader promotion actions
[1] 2023/09/08 11:44:08.342166 [INF] STREAM: finished leader promotion actions
[1] 2023/09/08 11:44:08.342179 [INF] STREAM: Streaming Server is ready
[1] 2023/09/08 11:49:38.356646 [ERR] STREAM: [Client:client-4100777791-16] Timed out on heartbeats
[1] 2023/09/08 11:49:38.356978 [ERR] STREAM: [Client:client-4100777791-1] Timed out on heartbeats
[1] 2023/09/08 11:49:38.357003 [ERR] STREAM: [Client:client-aws-sqs-sat-data-from-s3-eventsource-l77lv-7f47cd4554-dprdf-705] Timed out on heartbeats
[1] 2023/09/08 11:49:38.357009 [ERR] STREAM: [Client:client-616546318-18] Timed out on heartbeats
[1] 2023/09/08 12:10:39.312220 [ERR] STREAM: [Client:client-4100777791-85] Timed out on heartbeats
[1] 2023/09/08 12:10:39.477013 [ERR] STREAM: [Client:client-616546318-59] Timed out on heartbeats
[1] 2023/09/08 13:03:21.862904 [ERR] STREAM: [Client:client-2188390512-16] Timed out on heartbeats

```

logs from eventbus-default-stan-1:

```bash
Defaulted container "stan" out of: stan, metrics
[1] 2023/09/08 11:43:56.304984 [INF] STREAM: Starting nats-streaming-server[eventbus-default] version 0.22.1
[1] 2023/09/08 11:43:56.305021 [INF] STREAM: ServerID: 6ajmwy6HUBhvJI8G2RACj8
[1] 2023/09/08 11:43:56.305024 [INF] STREAM: Go version: go1.16.6
[1] 2023/09/08 11:43:56.305026 [INF] STREAM: Git commit: [27f1d60]
[1] 2023/09/08 11:43:56.307166 [INF] Starting nats-server
[1] 2023/09/08 11:43:56.307183 [INF]   Version:  2.3.3
[1] 2023/09/08 11:43:56.307185 [INF]   Git:      [aaba459]
[1] 2023/09/08 11:43:56.307188 [INF]   Name:     NCDKPQTWWW7VIXKBCOP3C6K2VQLHKZW44WN4D3A2TO5ZWQVEBBDDXOCG
[1] 2023/09/08 11:43:56.307190 [INF]   ID:       NCDKPQTWWW7VIXKBCOP3C6K2VQLHKZW44WN4D3A2TO5ZWQVEBBDDXOCG
[1] 2023/09/08 11:43:56.307193 [INF] Using configuration file: /etc/stan-config/stan.conf
[1] 2023/09/08 11:43:56.308710 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2023/09/08 11:43:56.308764 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2023/09/08 11:43:56.308971 [INF] Server is ready
[1] 2023/09/08 11:43:56.308993 [INF] Cluster name is 6ajmwy6HUBhvJI8G2RACoA
[1] 2023/09/08 11:43:56.308997 [WRN] Cluster name was dynamically generated, consider setting one
[1] 2023/09/08 11:43:56.309020 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2023/09/08 11:43:56.319712 [ERR] Error trying to connect to route (attempt 1): lookup for host "eventbus-default-stan-2.eventbus-default-stan-svc.electric-eye.svc": lookup eventbus-default-stan-2.eventbus-default-stan-svc.electric-eye.svc on 10.100.0.10:53: no such host
[1] 2023/09/08 11:43:56.321703 [ERR] Error trying to connect to route (attempt 1): lookup for host "eventbus-default-stan-1.eventbus-default-stan-svc.electric-eye.svc": lookup eventbus-default-stan-1.eventbus-default-stan-svc.electric-eye.svc on 10.100.0.10:53: no such host
[1] 2023/09/08 11:43:56.323879 [ERR] Error trying to connect to route (attempt 1): lookup for host "eventbus-default-stan-0.eventbus-default-stan-svc.electric-eye.svc": lookup eventbus-default-stan-0.eventbus-default-stan-svc.electric-eye.svc on 10.100.0.10:53: no such host
[1] 2023/09/08 11:43:56.336697 [INF] STREAM: Recovering the state...
[1] 2023/09/08 11:43:56.343957 [INF] STREAM: Recovered 1 channel(s)
[1] 2023/09/08 11:43:56.343982 [INF] STREAM: Cluster Node ID : eventbus-default-stan-1
[1] 2023/09/08 11:43:56.343986 [INF] STREAM: Cluster Log Path: /data/stan/logs
[1] 2023/09/08 11:43:56.343988 [INF] STREAM: Cluster known peers:
[1] 2023/09/08 11:43:56.343994 [INF] STREAM: peer 1: "eventbus-default-stan-0"
[1] 2023/09/08 11:43:56.343998 [INF] STREAM: peer 2: "eventbus-default-stan-2"
[1] 2023/09/08 11:43:56.571145 [INF] STREAM: Message store is RAFT_FILE
[1] 2023/09/08 11:43:56.571161 [INF] STREAM: Store location: /data/stan/store
[1] 2023/09/08 11:43:56.571194 [INF] STREAM: ---------- Store Limits ----------
[1] 2023/09/08 11:43:56.571196 [INF] STREAM: Channels:                  100 *
[1] 2023/09/08 11:43:56.571198 [INF] STREAM: --------- Channels Limits --------
[1] 2023/09/08 11:43:56.571200 [INF] STREAM:   Subscriptions:          1000 *
[1] 2023/09/08 11:43:56.571202 [INF] STREAM:   Messages     :       1000000 *
[1] 2023/09/08 11:43:56.571204 [INF] STREAM:   Bytes        :       1.00 GB
[1] 2023/09/08 11:43:56.571206 [INF] STREAM:   Age          :       72h0m0s
[1] 2023/09/08 11:43:56.571209 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2023/09/08 11:43:56.571212 [INF] STREAM: ----------------------------------
[1] 2023/09/08 11:43:57.328169 [INF] 192.168.123.70:6222 - rid:9 - Route connection created
[1] 2023/09/08 11:43:57.329388 [INF] Cluster name updated to 7T4ZpFvRUQ6MCgYOcBulIz
[1] 2023/09/08 11:43:57.329507 [ERR] 192.168.123.70:6222 - rid:9 - Route Error 'Rejecting connection, cluster name "6ajmwy6HUBhvJI8G2RACoA" does not match "7T4ZpFvRUQ6MCgYOcBulIz"'
[1] 2023/09/08 11:43:57.329531 [INF] 192.168.123.70:6222 - rid:9 - Router connection closed: Parse Error
[1] 2023/09/08 11:43:57.329758 [ERR] 192.168.123.70:6222 - rid:9 - Error flushing: writev tcp 192.168.140.6:43064->192.168.123.70:6222: writev: broken pipe
[1] 2023/09/08 11:43:58.367012 [ERR] Error trying to connect to route (attempt 1): lookup for host "eventbus-default-stan-0.eventbus-default-stan-svc.electric-eye.svc": lookup eventbus-default-stan-0.eventbus-default-stan-svc.electric-eye.svc on 10.100.0.10:53: no such host
[1] 2023/09/08 11:43:59.372552 [INF] 192.168.123.70:6222 - rid:10 - Route connection created
[1] 2023/09/08 11:44:00.277869 [INF] 192.168.123.70:55764 - rid:13 - Route connection created
[1] 2023/09/08 11:44:00.278437 [INF] 192.168.123.70:55764 - rid:13 - Router connection closed: Duplicate Route
[1] 2023/09/08 11:44:03.769425 [INF] 192.168.145.118:54188 - rid:18 - Route connection created
[1] 2023/09/08 11:44:03.769678 [INF] 192.168.123.70:6222 - rid:10 - Router connection closed: Client Closed
[1] 2023/09/08 11:44:03.769847 [INF] Cluster name updated to uZ0bjd3otG03yexI0HsfZe
[1] 2023/09/08 11:44:03.770540 [INF] 192.168.145.118:54188 - rid:18 - Router connection closed: Client Closed
[1] 2023/09/08 11:44:04.360737 [INF] 192.168.145.118:6222 - rid:19 - Route connection created
[1] 2023/09/08 11:44:04.841887 [INF] 192.168.123.70:6222 - rid:22 - Route connection created
[1] 2023/09/08 11:44:04.868759 [INF] 192.168.145.118:54196 - rid:23 - Route connection created
[1] 2023/09/08 11:44:04.868977 [INF] 192.168.145.118:54196 - rid:23 - Router connection closed: Duplicate Route
[1] 2023/09/08 11:44:04.869706 [INF] 192.168.123.70:55770 - rid:24 - Route connection created
[1] 2023/09/08 11:44:04.870035 [INF] 192.168.123.70:55770 - rid:24 - Router connection closed: Duplicate Route

```

logs from eventbus-default-stan-2

```bash
Defaulted container "stan" out of: stan, metrics
[1] 2023/09/08 11:44:03.758601 [INF] STREAM: Starting nats-streaming-server[eventbus-default] version 0.22.1
[1] 2023/09/08 11:44:03.758640 [INF] STREAM: ServerID: uZ0bjd3otG03yexI0HsfYJ
[1] 2023/09/08 11:44:03.758643 [INF] STREAM: Go version: go1.16.6
[1] 2023/09/08 11:44:03.758645 [INF] STREAM: Git commit: [27f1d60]
[1] 2023/09/08 11:44:03.761322 [INF] Starting nats-server
[1] 2023/09/08 11:44:03.761338 [INF]   Version:  2.3.3
[1] 2023/09/08 11:44:03.761341 [INF]   Git:      [aaba459]
[1] 2023/09/08 11:44:03.761344 [INF]   Name:     NCUF7BBHWCQRHWH7CSTJQ5TFWWSQICOZH5AIEK4E6RTSXJ5RBT4KLOC3
[1] 2023/09/08 11:44:03.761346 [INF]   ID:       NCUF7BBHWCQRHWH7CSTJQ5TFWWSQICOZH5AIEK4E6RTSXJ5RBT4KLOC3
[1] 2023/09/08 11:44:03.761349 [INF] Using configuration file: /etc/stan-config/stan.conf
[1] 2023/09/08 11:44:03.763550 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2023/09/08 11:44:03.763631 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2023/09/08 11:44:03.764368 [INF] Server is ready
[1] 2023/09/08 11:44:03.764485 [INF] Cluster name is uZ0bjd3otG03yexI0HsfZe
[1] 2023/09/08 11:44:03.764493 [WRN] Cluster name was dynamically generated, consider setting one
[1] 2023/09/08 11:44:03.764527 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2023/09/08 11:44:03.767610 [ERR] Error trying to connect to route (attempt 1): lookup for host "eventbus-default-stan-2.eventbus-default-stan-svc.electric-eye.svc": lookup eventbus-default-stan-2.eventbus-default-stan-svc.electric-eye.svc on 10.100.0.10:53: no such host
[1] 2023/09/08 11:44:03.768458 [INF] 192.168.123.70:6222 - rid:3 - Route connection created
[1] 2023/09/08 11:44:03.768547 [INF] 192.168.140.6:6222 - rid:4 - Route connection created
[1] 2023/09/08 11:44:03.769176 [INF] 192.168.123.70:6222 - rid:3 - Router connection closed: Cluster Name Conflict
[1] 2023/09/08 11:44:03.769721 [INF] 192.168.140.6:6222 - rid:4 - Router connection closed: Cluster Name Conflict
[1] 2023/09/08 11:44:03.789905 [INF] STREAM: Recovering the state...
[1] 2023/09/08 11:44:03.798017 [INF] STREAM: Recovered 1 channel(s)
[1] 2023/09/08 11:44:03.798044 [INF] STREAM: Cluster Node ID : eventbus-default-stan-2
[1] 2023/09/08 11:44:03.798048 [INF] STREAM: Cluster Log Path: /data/stan/logs
[1] 2023/09/08 11:44:03.798050 [INF] STREAM: Cluster known peers:
[1] 2023/09/08 11:44:03.798055 [INF] STREAM: peer 1: "eventbus-default-stan-0"
[1] 2023/09/08 11:44:03.798059 [INF] STREAM: peer 2: "eventbus-default-stan-1"
[1] 2023/09/08 11:44:04.024738 [INF] STREAM: Message store is RAFT_FILE
[1] 2023/09/08 11:44:04.024759 [INF] STREAM: Store location: /data/stan/store
[1] 2023/09/08 11:44:04.024786 [INF] STREAM: ---------- Store Limits ----------
[1] 2023/09/08 11:44:04.024788 [INF] STREAM: Channels:                  100 *
[1] 2023/09/08 11:44:04.024790 [INF] STREAM: --------- Channels Limits --------
[1] 2023/09/08 11:44:04.024792 [INF] STREAM:   Subscriptions:          1000 *
[1] 2023/09/08 11:44:04.024793 [INF] STREAM:   Messages     :       1000000 *
[1] 2023/09/08 11:44:04.024795 [INF] STREAM:   Bytes        :       1.00 GB
[1] 2023/09/08 11:44:04.024796 [INF] STREAM:   Age          :       72h0m0s
[1] 2023/09/08 11:44:04.024798 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2023/09/08 11:44:04.024801 [INF] STREAM: ----------------------------------
[1] 2023/09/08 11:44:04.360913 [INF] 192.168.140.6:34686 - rid:11 - Route connection created
[1] 2023/09/08 11:44:04.829435 [INF] 192.168.123.70:6222 - rid:12 - Route connection created
[1] 2023/09/08 11:44:04.868596 [INF] 192.168.140.6:6222 - rid:13 - Route connection created
[1] 2023/09/08 11:44:04.869297 [INF] 192.168.140.6:6222 - rid:13 - Router connection closed: Duplicate Route
[1] 2023/09/08 11:44:05.300852 [INF] 192.168.123.70:49972 - rid:14 - Route connection created
[1] 2023/09/08 11:44:05.301035 [INF] 192.168.123.70:49972 - rid:14 - Router connection closed: Duplicate Route

```
**Environment (please complete the following information):**
 - Kubernetes: v1.24.7-eks
 - Argo: v3.4.7
 - Argo Events: v2.4.1

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
