### ISSUE TITLE
Event parameter is not overriden when provided from trigger

### ISSUE THREAD

**Issue by unredundant** [argoproj/argo-events#2796]
**Describe the bug**
Hi... i would bet that this is just something dumb I'm doing, but, for the freakin' life of me, cannot figure out what is wrong.  At the _very_ least, some docs could use updating to make this more beginner friendly :')

I have a sensor with an attached trigger

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
  namespace: argo-events
spec:
  eventBusName: main-event-bus
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github
      eventSourceName: github
      eventName: bkbnio
      filters:
        script: |-
          if event.body.repository.name == "hades" and event.body["X-GitHub-Event"] == "pull_request" then
            return true
          else
            return false
          end
  triggers:
    - template:
        name: github-workflow-trigger
        argoWorkflow:
          operation: submit
          parameters:
            - src:
                dependencyName: github
                value: WTFMAN
              dest: spec.arguments.parameters.#(name=git_sha).value
              operation: overwrite
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-bkbnio-hades-pr-
              spec:
                workflowTemplateRef:
                  name: hades-pr-ci-template
```

_EVERYTHING_ that I can find online makes it seem like this should override the parameter `git_sha` with the value WTFMAN (Obviously, I've tried to do this with the actual sha from the payload, but given that I can't even get this to work, I want to just pass a value first, then worry about the actual payload).  

Unfortunately, this simply does not work.  I have a CI pipeline defined as 

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hades-pr-ci-template
  namespace: argo-events
spec:
  entrypoint: ci
  artifactGC:
    strategy: OnWorkflowDeletion
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
  arguments:
    parameters:
      - name: git_sha
        value: wtfmanplsoverride
  templates:
    # CI DAG ...
    - name: ci
      inputs:
        parameters:
          - name: git_sha
      dag:
        tasks:
          - name: git-clone
            template: git-clone
            arguments:
              parameters:
                - name: git_sha
                  value: "{{inputs.parameters.git_sha}}"
          - name: install
            template: install
            dependencies:
              - git-clone
          - name: test
            template: test
            dependencies:
              - install
          - name: lint
            template: lint
            dependencies:
              - install

    # Git Clone Template
    - name: git-clone
      inputs:
        parameters:
        - name: git_sha
        artifacts:
          - name: source
            path: /repo
            git:
              repo: git@github.com:bkbnio/hades.git
              revision: "{{inputs.parameters.git_sha}}"
              sshPrivateKeySecret:
                name: argo-events-github-ssh-key
                key: sshPrivateKey
      container:
        image: alpine:3.18.3
        command: [ sh, -c ]
        args:
          - cp -r /repo/* .
        workingDir: /workdir
        volumeMounts:
          - name: workdir
            mountPath: /workdir

    # Install Template
    - name: install
      container:
        image: node:20-alpine
        workingDir: /workdir
        command: [ sh, -c ]
        args:
          - |
            apk add --no-cache libc6-compat
            yarn install
        volumeMounts:
          - name: workdir
            mountPath: /workdir


    # Test Template
    - name: test
      container:
        image: node:20-alpine
        workingDir: /workdir
        command: [ sh, -c ]
        args:
          - |
            apk add --no-cache libc6-compat
            yarn test
        volumeMounts:
          - name: workdir
            mountPath: /workdir

    # Lint Template
    - name: lint
      container:
        image: node:20-alpine
        workingDir: /workdir
        command: [ sh, -c ]
        args:
          - |
            apk add --no-cache libc6-compat
            yarn lint
            yarn format:check
        volumeMounts:
          - name: workdir
            mountPath: /workdir
```

No matter _what_ I do, my workflows _always_ have the default value of `wtfmanplsoverride` in the actual workflow 

<img width="1145" alt="CleanShot 2023-09-11 at 19 32 14@2x" src="https://github.com/argoproj/argo-events/assets/5607577/f10fae0b-2649-44e2-8f94-efa14802c584">

I am at my wits end, and may have to abandon argo b/c of this :(
 
**To Reproduce**
Code from above should be a good start (you will need to substitute for non-private repo

**Expected behavior**
Code should either work, or give some kind of hint as to why the expected value is not appearing, instead of seeming to vanish into thin air. 

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Kubernetes: 1.24.7
 - Argo: 2.8
 - Argo Events: latest helm chart version

**Additional context**
n/a

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by unredundant** [comment]
It seems to be something specific to working with a workflowtemplate.  For example, running the example trigger side by side with my (bugged) trigger

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
  namespace: argo-events
spec:
  eventBusName: main-event-bus
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github
      eventSourceName: github
      eventName: bkbnio
      filters:
        script: |-
          if event.body.repository.name == "hades" and event.body["X-GitHub-Event"] == "pull_request" then
            return true
          else
            return false
          end
  triggers:
    - template:
        name: github-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-bkbnio-hades-pr-
              spec:
                workflowTemplateRef:
                  name: hades-pr-ci-template
          parameters:
            - src:
                dependencyName: github
                value: "IDFKMAN"
              dest: spec.arguments.parameters.0.value
              operation: overwrite
    - template:
        name: testy-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: message
                      # the value will get overridden by event payload from test-dep
                      value: hello world
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [ cowsay ]
                      args: [ "{{inputs.parameters.message}}" ]
          parameters:
            - src:
                dependencyName: test-dep
                value: WTFMAN
              dest: spec.arguments.parameters.0.value
```

I can see in argo ui that the cowsay _does_ get updated with `WTFMAN`.  So, for whatever reason, this seems to be related only to workflow templates, because as far as I can tell, my trigger and the example trigger should be identical :(

**Comment by unredundant** [comment]
i finally cracked the code... would be nice if this was easier to identify :( 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
  namespace: argo-events
spec:
  eventBusName: main-event-bus
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github
      eventSourceName: github
      eventName: bkbnio
      filters:
        script: |-
          if event.body.repository.name == "hades" and event.body["X-GitHub-Event"] == "pull_request" then
            return true
          else
            return false
          end
  triggers:
    - template:
        name: github-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-bkbnio-hades-pr-
              spec:
                workflowTemplateRef:
                  name: hades-pr-ci-template
                arguments: # <-- this is required
                  parameters:
                    - name: git_sha
                      value: doublewtfman
          parameters:
            - src:
                dependencyName: github
                dataKey: body.pull_request.head.sha
              dest: spec.arguments.parameters.0.value
              operation: overwrite
```

:(
