### ISSUE TITLE
Controller keeps updating eventsource pod deployment thousands of times instead of just once

### ISSUE THREAD

**Issue by popsu** [argoproj/argo-events#2810]
**Describe the bug**
When changing an `eventsource` CustomResource, the `argo-events` `controller` pod keeps updating the deployment multiple times in a row. Sometimes it takes hours/days for these constant updates to stop. It looks like some kind of a race issue where multiple entities are mutating the eventsource at the same time.

What ends up happening that since the deployment keeps getting changed constantly, kubernetes creates a new replicaset and the replicasets are created faster than the kubernetes garbage collector is deleting them (since as default each deployment keeps only 10 replicasets) and we end up having up to 50k replicasets sometimes, until the `argo-events` controller stops mutating the deployment and eventually things calm down and replicasets number goes back to 10.

This happens (almost?) every time when we change our eventsource.

**To Reproduce**
1. The cluster has an `EventSource` deployed:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-managed-analytics-staging
spec:
  template:
    serviceAccountName: webhook-event-sources-sa
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/proxyCPU: 100m
        sidecar.istio.io/proxyMemory: 100Mi
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    analytics-aircraft-detection-stage-gforms:
      port: "12000"
      endpoint: "/aircraft-detection/stage/gforms"
      method: "POST"
      authSecret:
        name: analytics-aircraft-detection-stage-gforms
        key: AUTH_TOKEN
    analytics-dark-vessel-detection-stage-gforms:
      port: "12000"
      endpoint: "/dark-vessel-detection/stage/gforms"
      method: "POST"
      authSecret:
        name: analytics-dark-vessel-detection-stage-gforms
        key: AUTH_TOKEN
    # 11 more webhooks, that have been removed from this snippet, but they're all similar
    # and are all running in same port (each with unique endpoint tho)
```

2. Make changes to the `EventSource`
3. This triggers `argo-events` controller to keep constantly updating the deployment that the `eventsource` has created.

**Expected behavior**
After changing an eventsource, the `argo-events` controller would only update the deployment once, not multiple times in a row.

**Screenshots**

The `argo-events` controller logs is full of these kind of events. By looking at the `ts` field differences from these 5 lines it seems to update the deployment 5 times in 0.2 seconds.  
```yaml
$ k logs controller-manager-5646f99877-x5hwm -n argo-events-analytics-staging --tail 5
{"level":"info","ts":1695032756.2752473,"logger":"argo-events.eventbus-controller","caller":"eventsource/resource.go:84","msg":"deployment is updated","namespace":"argo-managed-analytics-staging","eventSource":"webhook","deploymentName":"webhook-eventsource-88hk6"}
{"level":"info","ts":1695032756.3283284,"logger":"argo-events.eventbus-controller","caller":"eventsource/resource.go:84","msg":"deployment is updated","namespace":"argo-managed-analytics-staging","eventSource":"webhook","deploymentName":"webhook-eventsource-88hk6"}
{"level":"info","ts":1695032756.3805985,"logger":"argo-events.eventbus-controller","caller":"eventsource/resource.go:84","msg":"deployment is updated","namespace":"argo-managed-analytics-staging","eventSource":"webhook","deploymentName":"webhook-eventsource-88hk6"}
{"level":"info","ts":1695032756.4258568,"logger":"argo-events.eventbus-controller","caller":"eventsource/resource.go:84","msg":"deployment is updated","namespace":"argo-managed-analytics-staging","eventSource":"webhook","deploymentName":"webhook-eventsource-88hk6"}
{"level":"info","ts":1695032756.4794028,"logger":"argo-events.eventbus-controller","caller":"eventsource/resource.go:84","msg":"deployment is updated","namespace":"argo-managed-analytics-staging","eventSource":"webhook","deploymentName":"webhook-eventsource-88hk6"}
```

When looking at DataDog the number of replicasets we can see it skyrocket in this namespace. At the time of writing this it's over 50k:
![Screenshot from 2023-09-18 14-45-13](https://github.com/argoproj/argo-events/assets/3270267/3b03b16f-3b08-48ea-84f2-cc2063da003f)

Looking at CloudWatch kubernetes audit logs, we can see that there are tons of 409 errors from this eventsource. Here are daily sums of the number of 409 errors for this resource:
![Screenshot from 2023-09-18 14-49-01](https://github.com/argoproj/argo-events/assets/3270267/fef2249d-d230-441c-8d7d-04e7fb78481b)

The individual 409 errors look all something like this. AWS EKS audit logs don't log the request body, so we cannot see what is the full payload:
![Screenshot from 2023-09-18 14-52-53](https://github.com/argoproj/argo-events/assets/3270267/43e39bdd-98ee-40e3-a496-9eb79b8f03d3)

**Environment (please complete the following information):**
 - Kubernetes: [AWS EKS v1.23]
 - Argo: [v3.4.4] (issue was also when we ran v3.3.8 previously)
 - Argo Events: [v1.7.1]

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
