### ISSUE TITLE
v1.8.1 Error creating consumer group client: kafka: client has run out of available brokers to talk to: EOF

### ISSUE THREAD

**Issue by kmcrawford** [argoproj/argo-events#2813]
**Error connecting to kafka with version v1.8.1

**To Reproduce**

1. Deploy a Kafka Event Source running argo-events v1.8.1
2. Kafka Event source crash loops with the following error:
`Error creating consumer group client: kafka: client has run out of available brokers to talk to: EOF`

v1.8.1 error:
```
caller: kafka/start.go:122
   eventName: my-event
   eventSourceName: my-event-source
   eventSourceType: kafka
   level: error
   logger: argo-events.eventsource
   msg: Error creating consumer group client: kafka: client has run out of available brokers to talk to: EOF
   stacktrace: github.com/argoproj/argo-events/eventsources/sources/kafka.(*EventListener).consumerGroupConsumer
	/home/runner/work/argo-events/argo-events/eventsources/sources/kafka/start.go:122
github.com/argoproj/argo-events/eventsources/sources/kafka.(*EventListener).StartListening
	/home/runner/work/argo-events/argo-events/eventsources/sources/kafka/start.go:87
github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3.1
	/home/runner/work/argo-events/argo-events/eventsources/eventing.go:525
github.com/argoproj/argo-events/common.DoWithRetry.func1
	/home/runner/work/argo-events/argo-events/common/retry.go:106
k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:220
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:233
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:226
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:421
github.com/argoproj/argo-events/common.DoWithRetry
	/home/runner/work/argo-events/argo-events/common/retry.go:105
github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3
	/home/runner/work/argo-events/argo-events/eventsources/eventing.go:524
   ts: 1695379193.6853158
   ```
v1.8.0 error:
``` caller: eventsources/eventing.go:575
   error: failed after retries: kafka: client has run out of available brokers to talk to: EOF
   eventName: my-event
   eventSourceName: my-event-source
   eventSourceType: kafka
   level: error
   logger: argo-events.eventsource
   msg: Failed to start listening eventsource
   stacktrace: github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3
	/home/runner/work/argo-events/argo-events/eventsources/eventing.go:575
   ts: 1695387137.4973483
   ```

**Environment (please complete the following information):**
 - Kubernetes: 1.27
 - Argo: v3.4.5
 - Argo Events: v.1.8.1

**Example Kafka Event Source**

```
spec:
  kafka:
    my-event:
      connectionBackoff:
        duration: 10s
        factor: 2
        jitter: 0.2
        steps: 5
      consumerGroup:
        groupName: my-group
        oldest: false
        rebalanceStrategy: range
      jsonBody: true
      limitEventsPerSecond: 1
      partition: "1"
      sasl:
        mechanism: PLAIN
        passwordSecret:
          key: api-secret
          name: my-secret
        userSecret:
          key: api-key
          name: my-secret
      topic: my-topic
      url: my-broker.confluent.cloud:9092
      version: 2.5.0
```

FYI @wesleyscholl

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
