### ISSUE TITLE
Kafka EventBus not able to connect to EventHub

### ISSUE THREAD

**Issue by katharina-schulze** [argoproj/argo-events#2826]
**Describe the bug**
When trying to deploy a Kafka EventBus, connection cannot be established with the error message:
`{"level":"fatal","ts":1695739474.4047594,"logger":"argo-events.eventsource","caller":"cmd/start.go:67","msg":"failed to start eventsource server","eventSourceName":"test-webhook","error":"failed after retries: kafka: client has run out of available brokers to talk to: read tcp x->x: read: connection reset by peer","stacktrace":"github.com/argoproj/argo-events/eventsources/cmd.Start\n\t/home/runner/work/argo-events/argo-events/eventsources/cmd/start.go:67\ngithub.com/argoproj/argo-events/cmd/commands.NewEventSourceCommand.func1\n\t/home/runner/work/argo-events/argo-events/cmd/commands/eventsource.go:14\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992\ngithub.com/argoproj/argo-events/cmd/commands.Execute\n\t/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19\nmain.main\n\t/home/runner/work/argo-events/argo-events/cmd/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.20.7/x64/src/runtime/proc.go:250"}`

For Kafka, we use an Azure EventHub and the EventBus yaml looks like this:
```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: example
spec:
  kafka:
    url: service-bus-namespace.servicebus.windows.net:9093
    topic: "argo-workflow-event-queue"
    tls:
      insecureSkipVerify: true
    sasl:
      mechanism: PLAIN
      passwordSecret:
        key: password
        name: kafka-event-hub-ns
      userSecret:
        key: user
        name: kafka-event-hub-ns
```
And we have the following secret with the credentials setup as described [here](https://learn.microsoft.com/en-us/azure/event-hubs/azure-event-hubs-kafka-overview#shared-access-signature-sas):
```
apiVersion: v1
kind: Secret
metadata:
  name: kafka-event-hub-ns
  namespace: example
stringData:
  user: "$ConnectionString"
  password: "<eventhub-connection-string>"
```

**To Reproduce**
1. Delete (NATS) EventBus (by also removing the finalizer)
2. Deploy Kafka EventHub
3. Delete EventSource
4. Redeploy EventSource

**Expected behavior**
EventSource can connect to EventHub.

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: 1.26.6
 - Argo: v3.4.11 (using helm chart v0.33.3)
 - Argo Events: v1.8.1 (using helm chart v2.4.1)

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
