### ISSUE TITLE
Argo Workflow Trigger is removing "controller-instanceid" label

### ISSUE THREAD

**Issue by thomas315** [argoproj/argo-events#2829]
**Describe the bug**
We are using ArgoWorkflow controller with [InstanceID](https://argoproj.github.io/argo-workflows/scaling/#instance-id) to separate multiple installations.
The label `workflows.argoproj.io/controller-instanceid` is set within the source of a Sensor configuration in which an `argoWorkflow` trigger is used. But the created Workflow resource does not contain this label afterwards. All other labels are still existing.
By not having this label the Argo Workflow controller is unable to see it and to process it accordingly.

**To Reproduce**
Use an installation with "instance id" enabled. E.g. with https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml#L231

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gitlab-webhook
  labels:
    app.kubernetes.io/part-of: argo-events
spec:
  triggers:
    - template:
        name: webhook-workflow-trigger
        conditions: gitlab-modification
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-
                labels:
                  workflows.argoproj.io/controller-instanceid: my-controller-id # this label is NOT existing in the created Workflow resource
                  workflows.argoproj.io/controller-instanceid-for-testing: test # this label is existing in the created Workflow resource
              spec:
                workflowTemplateRef:
                  name: sometemplate-ci
```

**Expected behavior**
The added label `workflows.argoproj.io/controller-instanceid` should still be present in the created Workflow.

**Environment (please complete the following information):**
 - Kubernetes: v1.24.16
 - ArgoCD: v2.6.7
 - ArgoWorkflow: v3.4.7
 - Argo Events: v1.7.3

**Additional context**
We couldn't pinpoint the root cause but it seems that the environment variable of Argo CLI `ARGO_INSTANCEID` is creating this problem. Because it is unset in the created Deployment by the Sensor resource it's overwriting and deleting the label.
Setting the label in the created Deployment is "fixing" the issue and the `workflows.argoproj.io/controller-instanceid` label is persisted and set in the created Workflow.
This workaround would be fine if there is a way to set the `ARGO_INSTANCEID` environment variable somehow. But it seems there is no option to add it to this dynamically created deployment.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by gokulav137** [comment]
Hi @thomas315, I looked into this issue. Argo workflow trigger doesn't use the `--instanceid` flag while running the operations.
https://github.com/argoproj/argo-events/blob/master/sensors/triggers/argo-workflow/argo-workflow.go#L173-L185
```go
cmd = exec.Command("argo", "-n", namespace, "submit", "--from", fromArg)
	case v1alpha1.Resubmit:
		cmd = exec.Command("argo", "-n", namespace, "resubmit", name)
	case v1alpha1.Resume:
		cmd = exec.Command("argo", "-n", namespace, "resume", name)
	case v1alpha1.Retry:
		cmd = exec.Command("argo", "-n", namespace, "retry", name)
	case v1alpha1.Suspend:
		cmd = exec.Command("argo", "-n", namespace, "suspend", name)
	case v1alpha1.Terminate:
		cmd = exec.Command("argo", "-n", namespace, "terminate", name)
	case v1alpha1.Stop:
		cmd = exec.Command("argo", "-n", namespace, "stop", name)
```
Adding the `--instanceid` flag here would solve this issue.

We can get the instance id by adding a new field `instanceId` to argoWorkflow trigger.

Another way is to parse the labels and set the `--instance-id` flag if `workflows.argoproj.io/controller-instanceid` label is present. But I think it would be better to have a dependency to the `--instanceid` flag than the label name.

If this seems good, I can raise a PR @whynowy.

**Comment by gokulav137** [comment]
Actually further looking into the code. We can pass in the cli arguments using the `arg` filed in workflow trigger. For instanceid we can use  `args: ["--instanceid", "i1"]`

So using a sensor with the following definition should work
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gitlab-webhook
  namespace: test-ns
  labels:
    app.kubernetes.io/part-of: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
    container:
      env:
        - name: DEBUG_LOG
          value: "true"
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        argoWorkflow:
          operation: submit
          args: ["--instanceid", "i1"]
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-
                labels:
                  workflows.argoproj.io/controller-instanceid-for-testing: test # this label is existing in the created Workflow resource
              spec:
                entrypoint: whalesay
                templates:
                - name: whalesay
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["hello world"]
```

I was able to create a workflow with this sensor having the required label
Eventsource log:
```
2023-10-24T07:52:13.296Z        DEBUG   argo-events.sensor      sensors/listener.go:404 executing the trigger resource  {"sensorName": "gitlab-webhook", "triggerName": "webhook-workflow-trigger", "triggerType": "ArgoWorkflow"}
Name:                ci-6xsh6
Namespace:           test-ns
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Pending
Created:             Tue Oct 24 07:52:16 +0000 (now)
Progress:            
2023-10-24T07:52:16.620Z        DEBUG   argo-events.sensor      sensors/listener.go:417 trigger resource successfully executed  {"sensorName": "gitlab-webhook", "triggerName": "webhook-workflow-trigger", "triggerType": "ArgoWorkflow"}
```

Workflow describe:
```
$ kubectl -n test-ns describe workflow ci-6xsh6
Name:         ci-6xsh6
Namespace:    test-ns
Labels:       events.argoproj.io/action-timestamp=1698133933296
              events.argoproj.io/sensor=gitlab-webhook
              events.argoproj.io/trigger=webhook-workflow-trigger
              workflows.argoproj.io/completed=true
              workflows.argoproj.io/controller-instanceid=i1
              workflows.argoproj.io/controller-instanceid-for-testing=test
              workflows.argoproj.io/creator=system-serviceaccount-test-ns-operate-workflow-sa
              workflows.argoproj.io/phase=Succeeded
Annotations:  workflows.argoproj.io/pod-name-format: v2
API Version:  argoproj.io/v1alpha1
Kind:         Workflow
...
...
...
Events:
  Type    Reason                 Age   From                 Message
  ----    ------                 ----  ----                 -------
  Normal  WorkflowRunning        86s   workflow-controller  Workflow Running
  Normal  WorkflowSucceeded      32s   workflow-controller  Workflow completed
  Normal  WorkflowNodeRunning    31s   workflow-controller  Running node ci-6xsh6
  Normal  WorkflowNodeSucceeded  31s   workflow-controller  Succeeded node ci-6xsh6
```

Hope this helps @thomas315
