### ISSUE TITLE
HTTP Trigger Support JSON Payload

### ISSUE THREAD

**Issue by joshadambell** [argoproj/argo-events#2830]
**Is your feature request related to a problem? Please describe.**
It appears the HTTP payload sensor only supports strings to strings. This limits the usability of this trigger if more complex http request bodies are requires. For example:
```
{
  "event-type": "namespace-create",
  "resource-type": "eks",
  "event": {
      ...
  }
}
```
This above is not possible as the "event" field is sent as a string instead of json.

**Describe the solution you'd like**
I think the HTTP payload should support strings or JSON fields.

**Describe alternatives you've considered**
Of course, we can resolve our issue by using a Pod or Workflow, but it would be a much simpler implementation for us to watch resources in K8s, package them up a bit different and send them on to wherever we need to be notified.

**Additional context**
The complete context for our use case is we are watching certain resources and actions in K8s. We then need to modify the events to follow others APIs.

I am happy to dive in and figure this out. Wanted to get some discussion going to see if I'm missing something or there's better ways to accomplish what I want to.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by amhndu** [comment]
Can you not use the content-type using the [headers](https://github.com/argoproj/argo-events/blob/master/api/sensor.md#httptrigger) and build your json payload using [spring templates](https://argoproj.github.io/argo-events/tutorials/02-parameterization/#sprig-templates)?

**Comment by joshadambell** [comment]
Yes but the fields can only be strings unless I'm missing something. So if I take a chunk from the incoming payload then it will send that as a string and not json.
Example:
Incoming
```
{
    "field1": "one",
    "field2": {
        "field21": "21",
        "field22": "22"
    }
}
```

Outgoing wanted with foo as `field2`
```
{
    "hello": "world",
    "foo": {
        "field21": "21",
        "field22": "22"
    }
}
```

But instead `foo` is a string of json
```
{
    "hello": "world",
    "foo": "{\"field21\":\"21\",\"field22\":\"22\"}"
}
```

I can build the json through setting each field but I think it could be useful to grab a chunk from the incoming and send it in the outgoing.

**Comment by amhndu** [comment]
Have you tried using [toJson](https://masterminds.github.io/sprig/)?

**Comment by jalkjaer** [comment]
You can only send JSON objects with the HTTPTemplate, and your payload destinations need to be at least keys in the "root" of the output
You can however cut down on the clunky payload mapping by marking the field2 src with `useRawData: true` : 

I.e. if you have transformed the event to
```json
{ "body":  {
    "hello": "world",
    "field2": {
        "field21": "21",
        "field22": "22"
    }
}
```
Then you only need to map hello and field2 

```yaml
...
    http:
      method: POST
      url: "http://foo.com"
      payload:
      - src: 
         dependencyName: the-dep
         dataKey: body.hello
       dest: hello
      - src: 
         dependencyName: the-dep
         dataKey: body.field2
         useRawData: true
       dest: foo
```

It would be nice if `.`  in `dest` in the [TriggerParameter](https://argoproj.github.io/argo-events/APIs/#argoproj.io/v1alpha1.TriggerParameter) would place the `dataKey` value in the root of the payload, so only a single TriggerParameterSource is needed for complex cases - i.e. above this would be 
```
  payload:
      - src: 
         dependencyName: the-dep
         dataKey: body
         useRawData: true
       dest: "."
```
