### ISSUE TITLE
UPDATE eventype crushes the on 'resource' eventsource 

### ISSUE THREAD

**Issue by erez-levi** [argoproj/argo-events#2838]
Hi,

Trying to create an eventsource for every change in a k8s deployment, when using eventType ADD  it works well but when I’m using eventType UPDATE  I get errors on the eventsource

did anyone encounter this?

**Screenshots**

<img width="1118" alt="image" src="https://github.com/argoproj/argo-events/assets/59343752/8f3ab01a-efaf-488e-a813-35a615f99976">
<img width="984" alt="image" src="https://github.com/argoproj/argo-events/assets/59343752/4a316805-9dca-4b11-8697-107655e5bbbd">

Eventbus configuration:

```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  jetstream:
    version: 2.9.21
```

using argo-helm events chart version - `2.4.1`
**Additional context**

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
