### ISSUE TITLE
Unable to update Argo image updaters annotations via parameters

### ISSUE THREAD

**Issue by hahasheminejad** [argoproj/argo-events#2888]
**Describe the bug**
I am trying to add/update annotations of an ArgoApp created by a sensor to be able to automatically replace a pod once a new image is available. However, because argocd-image-updater annotations have dot (argocd-image-updater.argoproj.io) in the key field, argo event is not able to update them via parameters.

**To Reproduce**
1. Create Sensor which creates an ArgoApp
```yaml
- template:
      conditions: "mr-open"
      name: mr-deploy
      k8s:
        operation: update
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: test
              namespace: argocd
              annotations:
                 argocd-image-updater.argoproj.io/image-list: nginx=nginx:abcdefg
                 argocd-image-updater.argoproj.io/nginx.update-strategy: digest
            spec:
              destination:
```

```yaml
        parameters:
        - src:
            dependencyName: mr-open #argo-image-updater
            dataTemplate: "nginx=nginx:a1b1c1d1"
          dest: metadata.annotations."argocd-image-updater.argoproj.io/image-list" 

```

**Expected behavior**
Be able to update annotations throughout parameters even if they have special characters such as dot or `/`.
