### ISSUE TITLE
ResourceParameters can't override workflow namespace

### ISSUE THREAD

**Issue by Sturgelose** [argoproj/argo-events#289]
I have a trigger which I've been testing lately and works properly. This trigger gets started by the calendar event and then it fetches the workflow from git (using the git) trigger.

Now, my objective is to be able to load this workflow in different namespaces, with the following:

* File WorkflowA in GIT branch "master" should be deployed to namespace DEFAULT
* File WorkflowA in GIT branch "experimental" should be deployed to namespace DEV

The objective is to be able to merge branches without having to take care about the metadata.namespace parameters merging, as this parameter would be given by the trigger itself.

I've tried with many attempts and I have the following, which doesn't seem to work properly...

```
# workflow.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-steps-
  namespace: RANDOM
spec:
  entrypoint: diamond
  templates:
```

```
# calendar-trigger-git.yaml
# SSH key secret
apiVersion: v1
kind: Secret
metadata:
  name:  git-ssh
  namespace: argo-events
stringData:
  key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    <HERE GOES THE KEY
    -----END OPENSSH PRIVATE KEY-----

---

# Known Hosts secret
apiVersion: v1
kind: Secret
metadata:
  name:  git-known-hosts
  namespace: argo-events
stringData:
  ssh_known_hosts: '<KNOWN_HOST>'
---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: trigger-source-git
  namespace: argo-events
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /git/argoproj
              name: argoproj
            - mountPath: /secret
              name: sshkey
            - mountPath: /etc/ssh
              name: known-hosts
      volumes:
        - name: argoproj
          emptyDir: {}
        - name: sshkey
          secret:
            secretName: git-ssh
        - name: known-hosts
          secret:
            secretName: git-known-hosts
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "calendar-gateway:example-with-interval"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        name: calendar-workflow-trigger-dev
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          git:
            url: "git@bitbucket.org:MY_REPO/argo-flow.git"
            branch: "experimental"
            filePath: "dag-diamond-steps.yaml"
            namespace: dev
            cloneDirectory: "/git/argoproj"
            sshKeyPath: "/secret/key"
      resourceParameters:
        - src:
            event: "calendar-gateway:example-with-interval"
            value: "dev"
          dest: metadata.namespace
    - template:
        name: calendar-workflow-trigger-prod
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          git:
            url: "git@bitbucket.org:MY_REPO/argo-flow.git"
            branch: "master"
            filePath: "dag-diamond-steps.yaml"
            namespace: default
            cloneDirectory: "/git/argoproj"
            sshKeyPath: "/secret/key"
        resourceParameters:
          - src:
              event: "calendar-gateway:example-with-interval"
              value: "default"
            dest: metadata.namespace
```

It complains that the RANDOM namespace cannot be found, when it should be replaced.
`error="failed to create resource object. err: namespaces \"RANDOM\" not found" trigger-name=calendar-workflow-trigger-dev`
If I remove the `namespace: RANDOM` parameter from the workflow, then I get the following:
`error="failed to create resource object. err: the namespace of the provided object does not match the namespace sent on the request" trigger-name=calendar-workflow-trigger-dev`

I'm not sure how to pass the namespace to be run in from the trigger, and I'd like to have a single trigger in a namespace that would start workflows in other namespaces...

Also, I'd like to avoid hardcoding the namespace in the workflow itself as I want to be able to merge branches in git without issues between dev and prod

**Comment by VaibhavPage** [comment]
The error makes sense because there is no `metadata.namespace` in the event payload received from calendar gateway. The way you have configured `dest` with `metadata.namespace` is not the correct way as the `resourceParameters` are supposed to be used with the event payload. 

To trigger a workflow in particular namespace,  in your case, you need to define to two calendar event sources with the same interval or schedule, but one will have the `userPayload` set to `namespace_1` and other will have it's `userPayload` set to `namespace_2`. 

e.g.
```
# This configmap contains the event sources configurations for Calendar gateway

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calendar-event-source
  labels:
    # do not remove
    argo-events-event-source-version: v0.10
data:
  schedule-with-namespace_1: |-
    schedule: "30 * * * *"
    # userPayload is a static string that will be send to the the sensor with each event payload
    # whatever you put here is blindly delivered to sensor.
    userPayload: "namespace_1"
  schedule-with-namespace_2: |-
    schedule: "30 * * * *"
    # userPayload is a static string that will be send to the the sensor with each event payload
    # whatever you put here is blindly delivered to sensor.
    userPayload: "namespace_2"

```

and the sensor will refer to `userPayload` in the `dest` of `resourceParameters`

e.g.,

        resourceParameters:
          - src:
              event: "schedule-with-namespace_1"
              value: "default"
            dest: userPayload
