### ISSUE TITLE
Can't package sensor in helm

### ISSUE THREAD

**Issue by comtihon** [argoproj/argo-events#2916]
**Describe the bug**
I'd like to package my sensor & event source in helm chart to be installed via ArgoCD. But helm part doesn't work for some reason. 
If I install it manually resource by resource via kubectl it works.
I took the example pubsub sensor:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: my-pubsub-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: pubsub-dep
      eventSourceName: my-pubsub-event-source
      eventName: example
  triggers:
    - template:
        name: my-pubsub-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: hello-world-
              spec:
                # Workflow specification goes here
                entrypoint: whalesay
                templates:
                  - name: whalesay
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["hello world"]
```
And both Helm and ArgoCD say that create is an invalid operation type:
```
helm install my-api-workflow my-api-workflow-0.2.108.tgz -f values.yaml 
Error: INSTALLATION FAILED: 1 error occurred:
        * admission webhook "webhook.argo-events.argoproj.io" denied the request: template my-pubsub-workflow-trigger is invalid, unknown operation type create
```

**To Reproduce**
1. Package https://github.com/argoproj/argo-events/blob/master/examples/sensors/gcp-pubsub.yaml together with event_source
2. try to install it with helm

**Expected behavior**
both resources installed

**Environment (please complete the following information):**
 - Kubernetes: v1.26.6-gke.1700
 - Argo: 3.5.1
 - Argo Events: 1.8.1

**Additional context**
no context

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
