### ISSUE TITLE
resource-gateway crd not work 

### ISSUE THREAD

**Issue by phantooom** [argoproj/argo-events#292]
**Describe the bug**

ERRO[2019-06-10 11:11:34] error occurred while getting event from event source  error="unknown (get resourcegroups.mskj.cmbc.com.cn)" event-source=test-filters

**To Reproduce**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-event-source
  namespace: argo
  labels:
    # do not remove
    argo-events-event-source-version: v0.10
data:
  test-filters: |-
    namespace: default
    group: mskj.cmbc.com.cn
    version: v1alpha1
    kind: ResourceGroup
```
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcegroups.mskj.cmbc.com.cn
spec:
  group: mskj.cmbc.com.cn
  names:
    kind: ResourceGroup
    listKind: ResourceGroupList
    plural: resourcegroups
    singular: resourcegroup
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
```
**Expected behavior**

no  err 

**Screenshots**

**Environment (please complete the following information):**
k8s v1.11.10

**Comment by VaibhavPage** [comment]
As this is a custom resource, need to compile the sensor binary by registering the scheme for the custom resource.  Please take a look at “how to add custom resource?” subsection within https://argoproj.github.io/argo-events/trigger/

**Comment by tinkerborg** [comment]
@phantooom I'm having this same problem trying to watch a custom resource. Since you closed this, does that mean you got it resolved? If so, could you share the fix?

**Comment by phantooom** [comment]
you shoud add your crd scheme than rebuild argo-event

**Comment by tinkerborg** [comment]
Hmm, the CRD was in place before I set up argo-events or created this gateway. It works if I try to watch a workflows.argoproj.io resource, but not a rollouts.argoproj.io resource (for example). I'll keep digging, thanks.

**Comment by kivio** [comment]
Did you find a reason - I have same issue watching on default resources like Deployments.

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-event-source
  labels:
    # do not remove
    argo-events-event-source-version: v0.10
data:
  new-deploy: |-
    namespace: argo-events
    kind: "Deployment"
    group: "extensions"
    version: "v1beta1"
    type: ADDED
```

And get same error: `error="unknown (get deployments.extensions)"`

Example resource I add:
```bash

marcin@cloudshell:~ (oceanic)$ kubectl get deploy nginx-1 -o=yaml
apiVersion: extensions/v1beta1
kind: Deployment
```
