### ISSUE TITLE
Retry not occurring when trigger fails

### ISSUE THREAD

**Issue by bencompton** [argoproj/argo-events#2928]
**Describe the bug**

When retry trigger configuration is used and the trigger fails (e.g., HTTP trigger receives 500 response), the trigger is not retried.

**To Reproduce**

Create a HTTP trigger and force the HTTP endpoint to return an error response (e.g., HTTP 500).

```
    - template:
        name: failing-trigger
        http:
          # Expect to fail
          url: https://failing-http-response.com/
          method: GET
      atLeastOnce: true
      retryStrategy:
        steps: 3
```

**Additional context**

Looking at the code [here](https://github.com/intuit-data-os/argo-events/blob/9def50653c0bee565619b084c80ac21d0d12443f/sensors/listener.go#L335), it doesn't appear that the result of the trigger is taken into account, only that it completes.
