### ISSUE TITLE
validating-webhook failing on creation of EventBus of type jetstreamExotic

### ISSUE THREAD

**Issue by EirikAskheim** [argoproj/argo-events#2989]
**Describe the bug**
When creating a EventBus of type jetstreamExotic I get the following error
```bash
Error from server (BadRequest): error when creating "jetstream.yaml": admission webhook "webhook.argo-events.argoproj.io" denied the request: invalid spec: either "nats" or "jetstream" needs to be specified
```
I believe `jetstreamExotic` is a third valid choice here.

**To Reproduce**
```
echo '---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  jetstreamExotic:
      url: nats://nats.nats.svc.cluster.local
' | kubectl create -f -
```
**Expected behavior**
EventBus get created

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: 1.29.0
 - Argo: N/A
 - Argo Events: 1.7.6

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
