### ISSUE TITLE
How to directly deliver event's payload to HTTPTrigger?

### ISSUE THREAD

**Issue by sugaf1204** [argoproj/argo-events#3019]
**Is your feature request related to a problem? Please describe.**
I would like to directly delivery payload which GitHub Webhook send to HTTPTrigger.

I can't find out sepecifing root of json objects in [sjson](https://github.com/tidwall/sjson).

**Describe the solution you'd like**
When payload attr of HTTPTrigger is null, payload is empty now.
https://github.com/argoproj/argo-events/blob/83c56bca7a3d2e1c9391b0ff5feb26b783d41802/api/sensor.md#httptrigger

https://github.com/argoproj/argo-events/blob/83c56bca7a3d2e1c9391b0ff5feb26b783d41802/sensors/triggers/http/http.go#L134

When payload attr (of HTTPTrigger or more) is null, deliver raw payload to HTTPTrigger, or add flag to do it.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by fumihito-kan** [comment]
I can resolve below
```yaml
            - src:
                dependencyName: example
                dataKey: body
                useRawData: true
              dest: 
```
