### ISSUE TITLE
Add trigger parameterization to URL sources

### ISSUE THREAD

**Issue by jbmcfarlin31** [argoproj/argo-events#302]
**Is your feature request related to a problem? Please describe.**
Consider a workflow that has multiple steps involved with it. This workflow yaml file could potentially have hundreds (or more) lines of code. This would not be ideal to input into an argo sensor resource kind because you would have the yaml for the sensor itself along with the inline workflow yaml. This is not ideal.

Argo events allows you to specify a url to pull the workflow from - this works great! However, currently I cannot seem to find a way to pass payload variables into the argo sensor through to the workflow template when the URL source is used.

**Describe the solution you'd like**
Consider the following argo sensor definition:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    # do not remove
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "my-gateway:my-event-source"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        name: test-sensor
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: test-workflow-
              namespace: argo-workflow-mgmt
            spec:
              entrypoint: test
              arguments:
                parameters:
                - name: projectname
                  value: REPLACEME
              templates:
              - name: test
                inputs:
                  parameters:
                  - name: projectname
                container:
                  image: ubuntu:16.04
                  command: [sh,-c]
                  args: ["echo '{{inputs.parameters.projectname}}'"]
      resourceParameters:
        - src:
            event: "my-gateway:my-event-source"
            path: projectid
          dest: spec.arguments.parameters.0.value
```
The above yaml would take in a payload passed to the event with the variable `projectid`, and would replace the argument parameter `projectname`. This is an inline example.

The solution I am after would look something like:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: test-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    # do not remove
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "my-gateway:my-event-source"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        name: test
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          url:
            path: "github.com/path/to/my/workflow.yaml"
            verifycert: false
      resourceParameters:
        - src:
            event: "my-gateway:my-event-source"
            path: giturl
           dest: spec.arguments.parameters.0.value
```
where my workflow in the url `github.com/path/to/my/workflow.yaml` has the following defined:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-workflow-
  namespace: argo-workflow-mgmt
spec:
  entrypoint: test-workflow
  arguments:
    parameters:
    - name: url
      value: DEFAULT
  templates:
  - name: test-template
    steps:
    - - name: display-variable
        template: display
        arguments:
          parameters:
          - name: myurl
            value: {{spec.arguments.parameters.0.value}}

  - name: display
    inputs:
      parameters:
      - name: myurl
    container:
      image: ubuntu:16.04
      command: [sh, -c]
      #args: ["echo '{{inputs.parameters.myurl}}'"]
```

I would expect the parameter that is passed into the event/sensor by the name `giturl`, that value would be placed into my workflow yaml that resides in the url and replace the workflow argument `url` with that value.

**Describe alternatives you've considered**
This could also happen potentially at the `templateParameter` level as well.
