### ISSUE TITLE
StandardK8S Trigger - Patch operation failing with json patch

### ISSUE THREAD

**Issue by croziere** [argoproj/argo-events#3032]
**Describe the bug**
Hello,
I tried to use a StandardK8S Trigger with a `patch` operation and `patchStrategy: "application/json-patch+json"` but the request is rejected by Kubernetes API.

My use case is to have the trigger append an entry in a list of a Kubernetes object already present in the cluster.

**To Reproduce**
1. Create a `Sensor` with the following trigger section
```yaml
  triggers:
    - template:
        name: patch-resource
        k8s:
          operation: patch
          patchStrategy: "application/json-patch+json"
          source:
            resource:
              apiVersion: networking.istio.io/v1alpha3
              kind: Gateway
              metadata:
                name: default
                namespace: istio-ingress
              spec:
                servers:
                  - hosts:
                      - my-appended-hostname.tld
```
2. Create `EventBus` and `EventSource` link to the sensor and send a event.
3. In the logs, we get:
```
{"level":"error","ts":1708614355.405782,"logger":"argo-events.sensor","caller":"sensors/listener.go:379","msg":"Failed to execute a trigger","sensorName":"my-sensor","error":"failed to execute trigger, error decoding patch: json: cannot unmarshal object into Go value of type []handlers.jsonPatchOp","triggerName":"update-gateway","triggeredBy":["my-event"],"triggeredByEvents":["REDACTED"],"stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:379\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions.func1\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:360"}
{"level":"error","ts":1708614355.4058595,"logger":"argo-events.sensor","caller":"sensors/listener.go:364","msg":"Failed to execute a trigger","sensorName":"my-sensor","error":"failed to execute trigger, error decoding patch: json: cannot unmarshal object into Go value of type []handlers.jsonPatchOp","triggerName":"patch-resource","stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions.func1\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:364"}
```

**Expected behavior**
The object should be patched successfully.

**Environment (please complete the following information):**
 - Kubernetes: 1.28.3 (GKE)
 - Argo Events: 1.9.0

**Additional context**
After searching in the doc and the code, it seems the issue comes from the way the patch is sent to Kubernetes API.
For a `application/json-patch+json` strategy, the PATCH body should be a [RFC6902 JSONPatch](https://tools.ietf.org/html/rfc6902)  like:
```
[{
    "op": "add",
    "path": "/spec/servers/0/hosts/-",
    "value": "my-appended-hostname.tld"
}]
```

But for now, looks like the code doesn't handle this case, as it's marshalling the whole object every time.

https://github.com/argoproj/argo-events/blob/aa351e4b601198b10d58fc8d83edfa877fcd64b8/sensors/triggers/standard-k8s/standard-k8s.go#L202-L207

Maybe there are other ways to achieve what I want (patch an existing k8s resource by appending a value to a list).
But I think it's a nice feature to support JSONPatch directly and I'd be happy to contribute.
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to priorize.
