### ISSUE TITLE
Sensor isn't able to pass arguments to the WorkflowTemplate

### ISSUE THREAD

**Issue by sidfeiner** [argoproj/argo-events#3046]
I defined a WorkflowTemplate that if I submit from the UI, it asks me for the argument parameters and everything works great.
Now I have a Sensor that needs to run this template and whatever I do, I'm not able to get it to work.

**To Reproduce**
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: exporter-template
  generateName: exporter-
spec:
  entrypoint: YYYY
  arguments:
    parameters:
      - name: s3Key
        default: ""
      - name: isRetry
        default: "true"
      - name: logLevel
        default: "debug"
  templates:
    - name: YYYY
      retryStrategy:
        limit: "0"
      inputs:
        parameters:
          - name: s3Key
            value: {{workflow.parameters.s3Key}}
          - name: isRetry
            value: {{workflow.parameters.isRetry}}
      metadata:
        labels:
          app: XXXXXX
      container:
        image: XXXXX
        command: ["XXXXX"]
        env:
          - name: S3_KEY
            value: "{{inputs.parameters.s3Key}}"
          - name: IS_RETRY
            value: "{{inputs.parameters.isRetry}}"
```

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: exporter-sensor
spec:
  template:
  dependencies:
    - name: exporter-es
      eventSourceName: exporter-es
      eventName: exporter-files-ready
  triggers:
    - template:
        name: exporter-workflow
        conditions: exporter-es
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: exporter-
              spec:
                arguments:
                  parameters:
                    - name: s3Key
                    - name: isRetry
                      default: "false"
                workflowTemplateRef:
                  name: exporter-template
          parameters:
            - src:
                dependencyName: yahoo-exporter-es
                dataKey: body.Records.0.s3.object.key
              dest: spec.workflowTemplateRef.s3Key
            - src:
                dependencyName: yahoo-exporter-es
                value: "false"
              dest: spec.workflowTemplateRef.isRetry
```

In `Addition Context` I've added some more of my attempts, none of them working :(

**Expected behavior**
Once the defined event is fired, workflow template is run

**Screenshots**
I get a log error: `failed to execute trigger, failed after retries: failed to execute submit command for workflow, exit status 1`/

**Environment (please complete the following information):**
 - Kubernetes: v1.24.1
 - Argo: v2.4.7
 - Argo Events: v3.4.4

**Additional context**
I tried many solutions:
1. Based on [this ](https://github.com/argoproj/argo-events/issues/1039), I got a bit closer but got the following issue:
![image](https://github.com/argoproj/argo-events/assets/23147823/b95e5164-325c-4bff-bd27-69cf6e2c7bdc)
2. Then I tried also tried (based on https://github.com/argoproj/argo-events/issues/1678) adding `argument` in the trigger's spec, while changing the way I pass parameters:
```k8s:
  group: argoproj.io
  version: v1alpha1
  resource: workflows
  operation: create
  source:
    resource:
      apiVersion: argoproj.io/v1alpha1
      kind: Workflow
      metadata:
        generateName: exporter-
      spec:
        arguments:
          parameters:
            - name: s3Key
            - name: isRetry
              default: "false"
        workflowTemplateRef:
          name: exporter-template
  parameters:
    - src:
        dependencyName: exporter-es
        dataKey: body.Records.0.s3.object.key
      dest: spec.arguments.parameters.0.s3Key
    - src:
        dependencyName: exporter-es
        value: "false"
      dest: spec.arguments.parameters.1.isRetry
```
And then I got:
![image](https://github.com/argoproj/argo-events/assets/23147823/b5958134-5098-4781-b797-225e767e5865)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sidfeiner** [comment]
Apparently (and obviously), I mixed solutions, so that's how the sensor should be configured for people needing this in the future:

```
 group: argoproj.io
  version: v1alpha1
  resource: workflows
  operation: create
  source:
    resource:
      apiVersion: argoproj.io/v1alpha1
      kind: Workflow
      metadata:
        generateName: exporter-
      spec:
        arguments:
          parameters:
            - name: s3Key
            - name: isRetry
              default: "false"
        workflowTemplateRef:
          name: exporter-template
  parameters:
    - src:
        dependencyName: exporter-es
        dataKey: body.Records.0.s3.object.value
      dest: spec.arguments.parameters.0.value # <---- change to .value
    - src:
        dependencyName: exporter-es
        value: "false"
      dest: spec.arguments.parameters.1.value # <---- change to .value
```
