### ISSUE TITLE
Events Trigger conditions not respected

### ISSUE THREAD

**Issue by ashishkurian** [argoproj/argo-events#3049]
Hi Folks. I am developing an integration of Bitbucket server event and Argo workflows. I have two repositories that are pushing events to my event source.

I have a only one eventsource, one eventbus, one sensor. The bitbucketserver eventsource have two repositories configured. Then in the sensor I have two dependency with the same eventsource name but different events.

However, when I push events from the two repositories, allways only one trigger is getting triggered. My trigger condition is not being respected OR I am doing something very wrong.

I will share my k8s manifest file below. The related resources are not included for brewity. I am also sharing the screen shot of the logs of the sensor.

### Manifest
```yaml
---
# Source: bitbucket-event-workflow/templates/eventbus.yaml
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: ep-project-eventbus
  namespace: ashish-test
spec:
  nats:
    native:
      replicas: 3
      auth: none
---
# Source: bitbucket-event-workflow/templates/eventsource.yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: ep-project-eventsource
  namespace: ashish-test
spec:
  eventBusName: ep-project-eventbus
  bitbucketserver:
    ep-configbase:
      repositories:
        - projectKey: TDEREDPLAY
          repositorySlug: config-tde-tde21270
      events:
        - "repo:refs_changed"
        - "pr:opened"
        - "pr:modified"
        - "pr:reviewer:approved"
        - "pr:reviewer:unapproved"
        - "pr:reviewer:needs_work"
        - "pr:merged"
        - "pr:declined"
        - "pr:deleted"
        - "pr:comment:added"
      webhook:
        endpoint: /events
        port: "12000"
        method: POST
        url: "https://argo-events.tde21270.icp.corproot.net"
      accessToken:
        name: ep-configbase-repo-api-accesstoken-secret
        key: token
      deleteHookOnFinish: true
      bitbucketserverBaseURL: "https://git.swisscom.com/rest"
    ep-secondtest:
      repositories:
        - projectKey: TDEREDPLAY
          repositorySlug: ashish-dummy-delete
      events:
        - "repo:refs_changed"
      webhook:
        endpoint: /events
        port: "12000"
        method: POST
        url: "https://argo-events.tde21270.icp.corproot.net"
      accessToken:
        name: ep-secondtest-repo-api-accesstoken-secret
        key: token
      deleteHookOnFinish: true
      bitbucketserverBaseURL: "https://git.swisscom.com/rest"
---
# Source: bitbucket-event-workflow/templates/sensor.yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: ep-project-sensor
  namespace: ashish-test
spec:
  eventBusName: ep-project-eventbus
  template:
    serviceAccountName: ep-project-sensor-sa
    container:
      volumeMounts:
        - mountPath: /workflows/ep-configbase-repo-api-access-token
          name: ep-configbase-repo-api-access-token
        - mountPath: /workflows/ep-secondtest-repo-api-access-token
          name: ep-secondtest-repo-api-access-token
    volumes:
      - name: ep-configbase-repo-api-access-token
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: ep-configbase-repo-api-accesstoken-secretproviderclass
      - name: ep-secondtest-repo-api-access-token
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: ep-secondtest-repo-api-accesstoken-secretproviderclass
  dependencies:
    - name: ep-configbase-repo-event-dependency
      eventSourceName: ep-project-eventsource
      eventName: ep-configbase
    - name: ep-secondtest-repo-event-dependency
      eventSourceName: ep-project-eventsource
      eventName: ep-secondtest
  triggers:
    - template:
        conditions: "ep-configbase-repo-event-dependency"
        name: ep-configbase-repo-event-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ep-configbase-repo-event-workflow-
              spec:
                entrypoint: echo-git-event
                serviceAccountName: ep-project-sensor-sa
                arguments:
                  parameters:
                    - name: git_event
                      value: value-to-be-overwritten
                workflowTemplateRef:
                  name: ep-configbase-repo-event-clusterworkflowtemplate
                  clusterScope: true
          parameters:
            - src:
                dependencyName: ep-configbase-repo-event-dependency
                dataKey: body.toCommit.message
              dest: spec.arguments.parameters.0.value
    - template:
        conditions: "ep-secondtest-repo-event-dependency"
        name: ep-secondtest-repo-event-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ep-secondtest-repo-event-workflow-
              spec:
                entrypoint: echo-git-event
                serviceAccountName: ep-project-sensor-sa
                arguments:
                  parameters:
                    - name: git_event
                      value: value-to-be-overwritten
                workflowTemplateRef:
                  name: ep-secondtest-repo-event-clusterworkflowtemplate
                  clusterScope: true
          parameters:
            - src:
                dependencyName: ep-secondtest-repo-event-dependency
                dataKey: body.toCommit.message
              dest: spec.arguments.parameters.0.value

```

### Logs from the sensor
```
Name:                ep-secondtest-repo-event-workflow-xgxc5
Namespace:           ashish-test
ServiceAccount:      ep-project-sensor-sa
Status:              Pending
Created:             Fri Mar 08 09:03:26 +0000 (now)
Progress:
Parameters:
  git_event:         dummy comment on dummy repo
{"level":"info","ts":1709888606.560064,"logger":"argo-events.sensor","caller":"sensors/listener.go:423","msg":"Successfully processed trigger 'ep-secondtest-repo-event-trigger'","sensorName":"ep-project-sensor","triggerName":"ep-secondtest-repo-event-trigger","triggerType":"ArgoWorkflow","triggeredBy":["ep-secondtest-repo-event-dependency"],"triggeredByEvents":["66323561613865362d636163642d346464362d626532302d353862646139636134616665"]}



Name:                ep-secondtest-repo-event-workflow-xp8l6
Namespace:           ashish-test
ServiceAccount:      ep-project-sensor-sa
Status:              Pending
Created:             Fri Mar 08 09:03:57 +0000 (now)
Progress:
Parameters:
  git_event:         dummy comment on config repo
{"level":"info","ts":1709888637.3512876,"logger":"argo-events.sensor","caller":"sensors/listener.go:423","msg":"Successfully processed trigger 'ep-secondtest-repo-event-trigger'","sensorName":"ep-project-sensor","triggerName":"ep-secondtest-repo-event-trigger","triggerType":"ArgoWorkflow","triggeredBy":["ep-secondtest-repo-event-dependency"],"triggeredByEvents":["39353339353365362d323235352d343033342d626236652d373538336661316265616261"]}
```
