### ISSUE TITLE
Gateway pod is leaking memory. 

### ISSUE THREAD

**Issue by migggy** [argoproj/argo-events#305]
**Describe the bug**
Gateway pod is leaking memory. 
Is this a bug?
Is there a deployment method to prevent it? 

**Environment (please complete the following information):**

- OS: macOS Mojave 10.14.4
- minikube: v1.0.1
- Helm: v2.14.0
- argo workflow: v2.2.1
- Argo-events: v0.9.2

**To Reproduce**

Setup minikube & helm.
```
minikube start
minikube addons enable ingress
helm init
```

Install argo & argo-events.
```
helm repo add argo https://argoproj.github.io/argo-helm
kubectl create namespace argo
helm install argo/argo --name argo --namespace argo

kubectl create namespace argo-events
helm install argo/argo-events --name argo-events --namespace argo-events
```

Apply [argo-events webhook sample](https://argoproj.github.io/argo-events/getting_started/).
```
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/examples/event-sources/webhook.yaml
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/examples/gateways/webhook.yaml
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/examples/sensors/webhook.yaml
```

Set monitring environment.
Check minikube ip.
```
minikube ip
```

Add minikube IP to /etc/hosts.
```
sudo vim /etc/hosts
192.168.99.106  alertmanager.minikube prometheus.minikube grafana.minkube
```

Prepare prometheus.yaml.
```
alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.minikube
  persistentVolume:
    size: 1Gi
    storageClass: "standard"
server:
  ingress:
    enabled: true
    hosts:
      - prometheus.minikube
  persistentVolume:
    size: 1Gi
    storageClass: "standard"
  retention: "12h"
pushgateway:
  enabled: false
```

Install promehteus
```
kubectl create namespace monitoring
helm install --name prometheus --namespace monitoring -f prometheus.yaml stable/prometheus
```

acesess http://prometheus.minikube and do the following query.
```
container_memory_working_set_bytes{pod_name="webhook-gateway-http"}
```

**Screenshots**
<img width="2551" alt="screenshots" src="https://user-images.githubusercontent.com/5533565/60429233-a2339500-9c35-11e9-8ee2-547e2c48d732.png">

**Comment by VaibhavPage** [comment]
Thanks for reporting, will take a look

**Comment by vcastane** [comment]
Hey wanted to check in to see if there is an update on this? @VaibhavPage 
We are looking to migrate some internal scheduling tools and are in the process of doing some long running tests and this would unfortunately be a blocker.

Else: is there a known workaround?

**Comment by vcastane** [comment]
Any update?

**Comment by VaibhavPage** [comment]
Hey, I didn't have time last couple of weeks to tackle this issue. Will do it asap.

**Comment by ozankabak** [comment]
Thanks for looking into this @VaibhavPage, this has been a problem for us too.

**Comment by ozankabak** [comment]
Do not mean to bug you, but this is a rather key issue (since Argo Events is long-running). Did you find any time to look into this? Are there any workarounds we can employ in the meantime?

**Comment by pdavid31** [comment]
Unfortunately this is seems to be a major problem for us too.
Is there any update on this?

**Comment by pdavid31** [comment]
Are there any updates on this?

**Comment by c-dante** [comment]
Also seeing this with the default event config:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: webhook-gateway
  labels:
    # gateway controller with instanceId "argo-events" will process this gateway
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
    # gateway controller will use this label to match with it's own version
    # do not remove
    argo-events-gateway-version: v0.10
spec:
  type: "webhook"
  eventSource: "webhook-event-source"
  processorPort: "9330"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  template:
    metadata:
      name: "webhook-gateway-http"
      labels:
        gateway-name: "webhook-gateway"
    spec:
      containers:
        - name: "gateway-client"
          image: "argoproj/gateway-client"
          imagePullPolicy: "Always"
          command: ["/bin/gateway-client"]
          resources:
            requests:
              cpu: 0.1
              memory: 4Gi
        - name: "webhook-events"
          image: "argoproj/webhook-gateway"
          imagePullPolicy: "Always"
          command: ["/bin/webhook-gateway"]
          resources:
            requests:
              cpu: 0.1
              memory: 4Gi
      serviceAccountName: "argo-events-sa"
  service:
    metadata:
      name: webhook-gateway-svc
    spec:
      selector:
        gateway-name: "webhook-gateway"
      ports:
        - port: 12000
          targetPort: 12000
      type: ClusterIP
  watchers:
    sensors:
      - name: "webhook-sensor"
```

**Comment by VaibhavPage** [comment]
Is this specific only to webhook gateway?

**Comment by c-dante** [comment]
This is definitely here on `v0.11`

**Comment by emilssolmanis** [comment]
@VaibhavPage I've already flagged this on Slack, but adding another voice here -- pretty sure we're hitting this on the Calendar event source / gateway too, and much more aggressively than 15 days.

**Comment by c-dante** [comment]
My go isn't great, so I give up tracking where stuff is, but I dug into the code a little bit. My current thought is it's related to the re-init watcher codepath when k8s says the config is invalid/old:

```log
2020-02-03T14:02:17.863705Z github.com/argoproj/argo-events/controllers/gateway/config.go:62: watch of *v1.ConfigMap ended with: too old resource version: 131288707 (131291279) W 
2020-02-03T14:02:18.868437199Z [36mINFO[0m[2020-02-03 14:02:18] detected EventSource update. updating the gateway-controller config. 
 I 
2020-02-03T14:07:19.876396Z github.com/argoproj/argo-events/controllers/gateway/config.go:62: watch of *v1.ConfigMap ended with: too old resource version: 131291836 (131293136) W 
2020-02-03T14:07:20.880064915Z [36mINFO[0m[2020-02-03 14:07:20] detected EventSource update. updating the gateway-controller config. 
 I 
```

Which for my deployment, given no changes, trips every 5 minutes or so. This would align with what I'm seeing with the memory usage's steady increase, if the client's codepath from that change has a leak somewhere (it's related to time running, not requests received)


This lead me to the watcher:
https://github.com/argoproj/argo-events/blob/7bc21d811ff237071a719d0c1865fe253354193e/gateways/client/watcher.go#L50-L58


And of course the sync method:
https://github.com/argoproj/argo-events/blob/a069dd836dcab43f09b5a1ebf1a9a6d56d897e26/gateways/client/event-sources.go#L268-L282


So, if I were a gambin' man, I'd say there's a memory leak somewhere in the sync code with either the activate/deactivate, or the `initEventSourceContexts` doing a bad join to the new config (not removing "old" confgis).

**Comment by emilssolmanis** [comment]
@c-dante I'm seeing the same thing in the logs, but I'm trying to get a minikube with `pprof` running to help pinpoint where all that memory is going. In our case, with a calendar gateway, it seems to be blowing out quicker the more schedules we add, with 1 schedule it used to take ~ 10 days to run out of 512Mi, now with something like 30-40 events scheduled we see it blowing past 1Gi in ~ 30h. We also see that consistent memory growth in both the `gateway-client` and `calendar-events` containers, though at slightly different speeds, so I'm not sure it's entirely the client code.

**Comment by emilssolmanis** [comment]
@VaibhavPage @c-dante early days, but we upgraded prod to 0.12 and it seems to not have the leak, at least for the Calendar stuff, so I think somewhere in the refactor that got fixed. It's a fairly non-trivial upgrade though.

**Comment by jhenriquez** [comment]
@emilssolmanis It's been 12 days since your comment. Did the upgrade fix the leak? Did you upgrade from 0.10? Any tips for the upgrade?

**Comment by c-dante** [comment]
Here's my update:

* Migrating from 0.11 to 0.12 was terrible -- no docs and a ton of model changes. Thankfully, the changes were fairly good and well structured, so :raised_hands: for that!

* 0.12 seems to have fixed the memory leaks :tada: :tada: :clinking_glasses:
![image](https://user-images.githubusercontent.com/6332726/75169176-17d4ff80-56f6-11ea-9324-0644e6f620c9.png)

Here are the notes I took while migrating, and a summary of changes I noticed:
* Migrating from 0.11 to 0.12 webhook configs:
  - **Webhook Gateway**
      - "watchers" turned into "subscribes" and points to the service endpoint, not the sensor itself
  - **Webhook Sensor**
    - dependencies specify the gateway in a formalized object of `{ name, gatewayName, eventName }`, EX: old format of `my-gateway:my-event-source` is now `{ name: 'myEventName', gatewayName: 'my-gateway', eventName: 'my-event-source' }`, you can access this in parameters using `myEventName`.
    - Change `eventProtocol` to `subscription` object to attach to the gateway
    - Major changes/formalization of parameterization -- a little more nested and mostly more consistent.
    - **MAJOR** gotcha around what object the parameters apply to. `parameters` as a child of `template` see the entire `template` object. `parameters` as a child of the `k8s` object in the template see `k8s.source` as the object -- so, one extra layer deep.
Example below:

    ```yaml
      triggers:
        - template:
            # all these spaces in is correct
            name: my-webhook-workflow
            k8s:
              group: argoproj.io
              version: v1alpha1
              resource: workflows
              operation: create
              source:
                git:
                  url: "git@github.com:some-github/repo.git"
                  cloneDirectory: "/git"
                  sshKeyPath: "/secret/key"
                  filePath: "TEMPLATED_FILLS_IN"
                  branch: "master"

              # Resource-level paramters - the paths here are rooted at the !!! k8s.source object !!!
              parameters:
                - src:
                    dependencyName: gateway-dep
                    dataKey: body.some.other.path
                  # Notice it is NOT source.spec or k8s.source, but spec.
                  dest: spec.arguments.parameters.0.value
          # Trigger-level parameters -- the paths here are rooted at the entire template object.
          parameters:
            - src:
                dependencyName: gateway-dep
          # dataKey will deserialize the data base64, it is a json object of { body, headers, ... }
                dataKey: body.some.json.path
                value: "master"
          # Notice k8s pathing
              dest: k8s.source.git.branch
    ```

    - **EventSoruce**
      - Actual custom resource as opposed to a config map
      - Formalized the document -- spec types define the event source shape (IE: `webhook`) and the further configs, the example for a webhook event source is easy enough to follow.

Other notes:
* Triggers sources are standardized until k8s standard resources, so they're all nested 1 more deep
* Event source dependencies are formalized, you declare the dependency then use it in params
* Parameterization is formalized as a dependency source and then a `contextKey` or a `dataKey`
	- Events have `{ context, data }` shape where `context` is meta about the event itself.
	- At the event level, `data` is base64 encoded raw of whatever the payload is
	- Depending on the event, `data` can take different forms/values
	- For webhooks, `data` is the JSON of the full http request, IE: `{ header, body }`
	- To extract webhook payload json, you need to do: `dataKey: body.[...]`, like `dataKey: body.some.json.path`
* Be careful about the nesting for `parameters` in a trigger definition -- where is important.
	- https://github.com/argoproj/argo-events/blob/a069dd836dcab43f09b5a1ebf1a9a6d56d897e26/sensors/event-notifications.go#L75-L128
	- The general flow is:
		+ Apply template level parameters
			- `template.parameters` to `template` document
			- IE: `k8s.source.hit` as the dest
		+ Check if switches
		+ Fetch resource
			- This is where `k8s.source` gets resolved/built
		+ apply resource parmeters
			- `template.k8s.parameters` gets applied to `template.k8s.source` object
			- IE: `spec.arguments.parameters.0`
			- So, it doesn't see "source" or other siblings of the `k8s` document
		+ execute trigger
