### ISSUE TITLE
Using git as a source for k8s trigger: git executable not found

### ISSUE THREAD

**Issue by bkanuka** [argoproj/argo-events#3065]
Using `git` as a source for `k8s` trigger fails with error: "failed to fetch artifact, failed after retries: failed to fetch. err: exec: \"git\": executable file not found"

I'm using the following Sensor:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-auto-build
spec:
  template:
    container:
      env:
        - name: DEBUG_LOG
          value: "true"
      volumeMounts:
        - mountPath: /git
          name: git
    volumes:
      - name: git
        emptyDir: {}
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github
      eventSourceName: github
      eventName: github-climateengine
      filters:
        data:
          - path: headers.X-Github-Event
            type: string
            value:
              - push
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            git:
              url: "https://github.com/argoproj/argo-workflows.git"
              cloneDirectory: "/git/argoproj"
              namespace: argo-events
              filePath: "examples/hello-world.yaml"
              branch: "master"
```

The template fails with the message:

```
2024-03-12T21:09:14.490Z ERROR argo-events.sensor sensors/listener.go:379 Failed to execute a trigger {"sensorName": "github-auto-build", "error": "failed to fetch artifact, failed after retries: failed to fetch. err: exec: \"git\": executable file not found in $PATH", "triggerName": "build-workflow", "triggeredBy": ["github"], "triggeredByEvents": ["34383866653034612d383330372d346161312d383264302d633730643666363239613730"]}
```

I can confirm that the Sensor is running a Pod with image `quay.io/argoproj/argo-events:v1.9.1`

**Environment:**
 - Kubernetes: v1.26.13
 - Argo Workflows: v3.5.5
 - Argo Events: v1.9.1

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
