### ISSUE TITLE
Calender Gateway and Sensor pods not created 

### ISSUE THREAD

**Issue by kpulipati** [argoproj/argo-events#309]
@VaibhavPage I am looking to use Calender and following this below doc to deploy the corresponding configmap, Gateway and Sensor :

https://argoproj.github.io/argo-events/gateways/calendar/

I tried to deploy all 3 of them using these commands:
kubectl apply -f -n argo calender-configmap.yaml
kubectl apply -f -n argo calender-gateway.yaml
kubectl apply -f -n argo calender-sendor.yaml

But I do not see any pods created after running these yaml files.Am I missing anything? Also I am deploying these in the same namespace as the argo-events pods (gateway controller and sensor controller) are present .

Here is how my yaml files looks like:

**calender-configmap.yaml**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: calendar-event-source
  labels:
    # do not remove
    argo-events-event-source-version: v0.10
data:
  example-with-interval: |-
    # create an event every 10 seconds
    interval: 10s
```

**calender-gateway.yaml**

```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: calendar-gateway
  labels:
    # gateway controller with instanceId "argo-events" will process this gateway
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
    # gateway controller will use this label to match with it's own version
    # do not remove
    argo-events-gateway-version: v0.10
spec:
  type: "calendar"
  eventSource: "calendar-event-source"
  processorPort: "9330"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  template:
    metadata:
      name: "calendar-gateway"
      labels:
        gateway-name: "calendar-gateway"
    spec:
      containers:
        - name: "gateway-client"
          image: "argoproj/gateway-client"
          imagePullPolicy: "Always"
          command: ["/bin/gateway-client"]
        - name: "calendar-events"
          image: "argoproj/calendar-gateway"
          imagePullPolicy: "Always"
          command: ["/bin/calendar-gateway"]
      serviceAccountName: "argo-events-sa"
  watchers:
    sensors:
      - name: "calendar-sensor"
```

**calender-sensor.yaml**

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: calendar-sensor
  labels:
    # sensor controller with instanceId "argo-events" will process this sensor
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    # do not remove
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "calendar-gateway:example-with-interval"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        name: calendar-workflow-trigger
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              name: k8s-jobs-argo-sparkoperator-usingevents
              namespace: engine-memory
            spec:
              entrypoint: pi-tmpl
              templates:
              - name: pi-tmpl
                resource:                   
                  action: apply            
                  manifest: |       
                    <some-k8-resource>
             
```

**FYI**:
Here is the output of  "kubectl describe gateway calendar-gateway -n argo", I do not see any 'status' in this below message which is weird:

```
Name:         calendar-gateway
Namespace:    argo
Labels:       argo-events-gateway-version=v0.10
              gateways.argoproj.io/gateway-controller-instanceid=argo-events
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"argoproj.io/v1alpha1","kind":"Gateway","metadata":{"annotations":{},"labels":{"argo-events-gateway-version":"v0.10","gateways.argoproj.i...
API Version:  argoproj.io/v1alpha1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2019-07-10T19:43:25Z
  Generation:          1
  Resource Version:    91516308
  Self Link:           /apis/argoproj.io/v1alpha1/namespaces/argo/gateways/calendar-gateway
  UID:                 fb96356a-a34a-11e9-9bdd-1246cae6478e
Spec:
  Event Protocol:
    Http:
      Port:        9300
    Type:          HTTP
  Event Source:    calendar-event-source
  Processor Port:  9330
  Template:
    Metadata:
      Labels:
        Gateway - Name:  calendar-gateway
      Name:              calendar-gateway
    Spec:
      Containers:
        Command:
          /bin/gateway-client
        Image:              argoproj/gateway-client
        Image Pull Policy:  Always
        Name:               gateway-client
        Command:
          /bin/calendar-gateway
        Image:               argoproj/calendar-gateway
        Image Pull Policy:   Always
        Name:                calendar-events
      Service Account Name:  argo-events-sa
  Type:                      calendar
  Watchers:
    Sensors:
      Name:  calendar-sensor
Events:      <none>

```
