### ISSUE TITLE
failed to get value by key: key body.message does not exist to in the event payload

### ISSUE THREAD

**Issue by haim-bp** [argoproj/argo-events#3105]
I configure slack EventSource from the examples  -> https://github.com/argoproj/argo-events/blob/master/examples/event-sources/slack.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: slack
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  slack:
    example-insecure:
      webhook:
        endpoint: "/"
        port: "12000"
        method: POST
      token:
        name: slack-secret
        key: tokenkey
      signingSecret:
        name: slack-secret
        key: signingSecret

```

And crate Sensor that listen to this events from the examples -> https://github.com/argoproj/argo-events/blob/master/examples/sensors/slack.yaml

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: slack
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: slack
      eventName: example-insecure
  triggers:
    - template:
        name: slack-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: slack-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # the value will get overridden by the event payload from test-dep
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.message
              dest: spec.arguments.parameters.0.value

```

After I configure it when I sent new message in slack I can see the event, but the sensor get this error:
`failed to get value by key: key body.message does not exist to in the event payload`

I try to change the dataKey in the block 
```
         parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.message
              dest: spec.arguments.parameters.0.value

```
But I get the same error, with the dataKey I change
Any ideas?

**Comment by haim-bp** [comment]
Ok I remove the dataKey and now I can see the message
```
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.arguments.parameters.0.value

```
