### ISSUE TITLE
A workflow works with argo workflows cli/ui/kubectl but not with argoworkflows sensor

### ISSUE THREAD

**Issue by jorgelon** [argoproj/argo-events#3171]
**Describe the bug**
I have a workflow who calls a workflowtemplate who calls other templates.
If I submit that workflow via argo cli, argo ui or kubectl, the workflow starts with all the parameters ok
But if I launch the same workflow with an argoworkflows sensor, it shows an error

`time="2024-06-19T19:23:29.016Z" level=fatal msg="Failed to submit workflow: rpc error: code = InvalidArgument desc = templates.main.tasks.build-code-backend missing value for parameter 'branch'"`

**To Reproduce**

The sensor part
```
  triggers:
    - template:
        name: argo-workflow-trigger
        conditions: mycondition
        argoWorkflow:
          operation: submit
          source:
            git:
              url: mygitproject
              branch: mybranch
              filePath: workflow.yaml
              creds:
                username:
                  name: secret
                  key: username
                password:
                  name: secret
                  key: password
```

The workflowtemplate part:

```
  templates:
    - name: main
      dag:
        tasks:
          - name: build-code-backend
            templateRef:
              name: whatever
              template: main
              clusterScope: true
            arguments:
              parameters:
                - name: branch
                  valueFrom:
                    configMapKeyRef:
                      name: "{{workflow.parameters.environment}}"
                      key: existingkeyincm
```
**Expected behavior**
The workflow starts

**Screenshots**

**Environment:**
 - Kubernetes: 1.29.1
 - Argo: v3.5.8
 - Argo Events: v1.9.1

**Additional context**
The workflow includes environment as global parameter
I have tried to use "resource" in the sensor and not git source, but the result is the same.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
