### ISSUE TITLE
EventBus JetStream reloader container is not starting on the version 1.9.2

### ISSUE THREAD

**Issue by mrkiani98** [argoproj/argo-events#3208]
**Describe the bug**
After upgrading to the argo-events helm chart v2.4.6 (and also the latest version v.2.4.7), we can see that the `reloader` container in Jetstream EventBus is getting the following error:
```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-pid": executable file not found in $PATH: unknown
```
I can see that the `reloader` container now in the `evetnbus-js` statefulset has the following `args` config (with no `command` defined anymore):
```
  - args:
    - -pid
    - /var/run/nats/nats.pid
    - -config
    - /etc/nats-config/nats-js.conf
```
It seems to be related to this [PR](https://github.com/argoproj/argo-events/pull/3004) on release v1.9.2

**To Reproduce**
1. Use the argo-events helm chart v2.4.7
2. Use following yaml manifest to create a Eventbus:
```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  finalizers:
  - eventbus-controller
  name: temp
  namespace: temp
spec:
  jetstream:
    containerTemplate:
      resources:
        limits:
          cpu: 40m
          memory: 300Mi
        requests:
          cpu: 20m
          memory: 150Mi
    version: 2.9.8
```

**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.30.0]
 - Argo: [e.g. v2.9.7]
 - Argo Events: [e.g. v1.9.2]

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
