### ISSUE TITLE
Data filter in Argo Events does not work properly when using the comparator "not equal" with multiple options

### ISSUE THREAD

**Issue by dyslabpro** [argoproj/argo-events#3215]
**Describe the bug**
Data filter with comparator `!=` and multiple options will always return true.

**To Reproduce**
```
filters:
  data:
    - path: body.value
      type: string
      comparator: "!="
      value:
        - "foo"
        - "bar"
```

**Expected behavior**
The filter should use the logical expression `body.value not in [foo, bar]` instead of `body.value != foo or body.value != bar`.

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
