### ISSUE TITLE
Add support for automountServiceAccountToken for StatefulSet and Pods

### ISSUE THREAD

**Issue by Nataliia5722** [argoproj/argo-events#3216]
**Is your feature request related to a problem? Please describe.**
Can't set the `automountServiceAccountToken: false` for StatefulSet and Pods of EventBus

**Describe the solution you'd like**
`automountServiceAccountToken: false` can be set for JetStream https://github.com/argoproj/argo-events/blob/master/api/event-bus.md#jetstreambus and applied to StatefulSet and Pod as `.spec.automountServiceAccountToken`

**Describe alternatives you've considered**
-

**Additional context**
Example of how it will be added on EventBus level:
```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  jetstream:
    version: 2.9.2
    automountServiceAccountToken: false
```
And then the StatefulSet will be deployed as:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
...
  generation: 3
  name: eventbus-default-js
spec:
  automountServiceAccountToken: false
...
```
and at the same time for Pods it will be also set as `.spec.automountServiceAccountToken`:
```
apiVersion: v1
kind: Pod
metadata:
...
  name: eventbus-default-js-0
spec:
  automountServiceAccountToken: false
...
```
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
