### ISSUE TITLE
Bitbucket Cloud - Invalid json payload data received

### ISSUE THREAD

**Issue by bilyboy785** [argoproj/argo-events#3272]
**Describe the bug**
From what I understand from the documentation: I've deployed argo-events (clusterScope), eventbus, eventsource and sensor for BitbucketCloud with Basic Auth. The Bitbucket Webhook is generated when the eventSource is deployed, but I have no visibility of the token.

I manage to trigger a Workflow that calls a WorkflowTemplate, but the payload retrieved is not usable. Isn't there a problem with the token? 

Did i miss something ?

**To Reproduce**
1. Deploy argo-events with helm, clusterScoped
2. Deploy the EventBus (default exampleà
3. Deploy the eventSource (on bitbucket Cloud, a new Webhook is automatically created) 
4. Deploy the sensor
5. Call the <url>/<endpoint> to trigger the Workflow. 

Here is the example Sensor to get the payload json data : 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: mysensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-controller
  dependencies:
    - name: bitbucket
      eventSourceName: bitbucket
      eventName: myevent
  triggers:
    - template:
        name: debug
        argoWorkflow:
          operation: submit
          parameters:
            - src:
                dependencyName: bitbucket
                dataKey: body
              dest: spec.arguments.parameters.0.value
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: debug-
                namespace: mynamespace
              spec:
                arguments:
                  parameters:
                    - name: payload
                      value: hello world
                workflowTemplateRef:
                  name: debug
```

**Expected behavior**
I should get the json bitbucket payload (like [this one](https://support.atlassian.com/bitbucket-cloud/docs/event-payloads/) repo:push) but i got something not human readable (see above screenshot)

**Screenshots**

Log from the sensor : 
![](https://media.cleanshot.cloud/media/15917/yJy1UPnrt3JxFgNcji5q1SzuyrQhRsTLipBHUyC0.jpeg?Expires=1725504495&Signature=VQi5jdAkdWQXgQ2ElOKGEhBO2yO8HuZu2grwh2-eaGSqlRkhlgirneAQ7alSfG41Vb730XMa-Z11oJFEGZdLHGBc8f0XVCagezO3BK6MS0czC7~vL5GMK0YSQWnsQ~Rsnzp5qMA2HRViIuuj5jNf0zQk14~9GkxoYDENLjUbgbPr0r-TWnC8khXAxfe-rUZil2ThxKOFycAWCyTbHrHkQPeOlBvHRUJ-Ygm1Uugu~wW4hFcpMstjbL1lxpUQob0dfbQY6Yc1VlE3rX-0eCNnpJIR62JJmXU3fdLl5XTZVaO9EZxGOgSaN83pEbxACpSxbTX~oXx~s~ykxMGWoM-zjw__&Key-Pair-Id=K269JMAT9ZF4GZ)

Webhook successfully called on bitbucket : 
![](https://media.cleanshot.cloud/media/15917/bHrasIOrdCUXL8uk0zVc0D0VyziEKfwh6bpG7LYe.jpeg?Expires=1725504918&Signature=dLGGPILkw0Biy-ayk~J-gjwOl6MN7hEKSZaGkU5jPJ9AhF~2G3tpeLuf7rsKWwNNPP43allqbVCyRZ~80Od3m27Gi-7ulKEiCOWguL9lXKigGxq6-9-45E0FGHxRY2vxZ1tXRv3tneBBMiw8PXWCx3XwvOYaGkqlz4i6HPjEVMgKnOVCPxXZiMw1Lv2~3w5vRHxvqIyq0YZjwb4gg29kr8tAxtcweX09~E3aHBmuVMzA6v2KQxUHtN1UV1Hb1x4c-TkM0Cwtx3lv55Tp4hcB7n3n3gqZCpcZOq5IcCITsQm6UBSPWxaMvhgOkOw7gZ-am06oqstApd1WSdW1fwtibQ__&Key-Pair-Id=K269JMAT9ZF4GZ)

**Environment (please complete the following information):**
 - Kubernetes: v1.29.7-gke.1104000
 - Argo Workflows: v3.5.10
 - Argo Events: v1.9.2

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
