### ISSUE TITLE
ERROR: `no resource found` while watching for `Build` events in OpenShift namespace

### ISSUE THREAD

**Issue by CermakM** [argoproj/argo-events#328]
**Describe the bug**

I am getting the following error from the gateway and I am therefore unable to watch for `Build` events in an `OpenShift` cluster

```
ERRO[2019-08-06 16:27:03] no resource found                             kind=Build
ERRO[2019-08-06 16:27:03] error occurred while getting event from event source  error="no resource found" event-source=build
```

My event source looks like this:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-event-source
  labels:
    # do not remove
    argo-events-event-source-version: v0.10
data:
  build: |-
    namespace: argo-events  # FIXME: variable
    group: "build.openshift.io"
    version: "v1"
    kind: "Build"
```

**To Reproduce**
0. minishift cluster running OpenShift 3.11
1. The event source as stated above
2. I am having the resource gateway from [the example](https://github.com/argoproj/argo-events/blob/master/examples/gateways/resource.yaml) (with a slight modification of names)
And I believe the sensor is irrelevant in this case

**Expected behavior**
It is possible to monitor OpenShift `Build` events

**Environment (please complete the following information):**
- minishift
- OpenShift 3.11

Thanks for any help!

---

**UPDATE**

I have assigned the cluster role which allows the SA to watch build events to the `argo-events-sa`, but that doesn't seem to help.
