### ISSUE TITLE
Sensor is not triggering actions for events that occur in rapid succession

### ISSUE THREAD

**Issue by hamza3202** [argoproj/argo-events#3326]
**Describe the bug**
Sensor is not triggering actions for events that occur in rapid succession. If two events are received at roughly the same time then only event is processed by the sensor

**To Reproduce**
1. Create a nats native event bus
```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      replicas: 3
```
2. Create a sensor with log trigger
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor
spec:
  dependencies:
    - name: default
      eventSourceName: webhook
      eventName: start
  triggers:
    - template:
        name: log-trigger
        log: {}
```
3. Create a webhook event source
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 80
        targetPort: 8080
  webhook:
    start:
      endpoint: /start
      port: "8080"
      method: POST

4. Send two events in parallel e.g using curl in a bash script
```
curl_command() {
  curl -X POST{Event source pod ip}:8080/start -H "Content-Type: application/json" -d '{}'
}

(curl_command) &
(curl_command) &

wait
```
**Expected behavior**
Two events are logged by the sensor

**Screenshots**


**Environment (please complete the following information):**
 - Kubernetes: v1.29.8-
 - Argo: Irrelevant
 - Argo Events: v1.6.0

**Additional context**
Sensor not triggering trigger for events that occur very close to each other. If two events are received at roughly the same time then only event is processed by the sensor. I can see in the event source pod logs that it receives and publishes both events to the event bus only one is processed by the sensor

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
