### ISSUE TITLE
Provided AMQP tutorial does not work | PodSecurityPolicy: unable to admit pod: []

### ISSUE THREAD

**Issue by MathewNWSH** [argoproj/argo-events#3329]
**Describe the bug**
workflow trigger returns `error in entry template execution: pods "amqp-mx29f" is forbidden: PodSecurityPolicy: unable to admit pod: []` while trying to launch sample AMQP event source tutorial:
`https://argoproj.github.io/argo-events/eventsources/setup/amqp/`

**Argo Events Installation and service deployment methods**
Argo installation was nicely covered here, so I just followed it: `https://creodias.docs.cloudferro.com/en/latest/kubernetes/Install-and-run-Argo-Workflows-on-Creodias-Magnum-Kubernetes.html`

helm repo add argo https://argoproj.github.io/argo-helm
helm install argo-events argo/argo-events -n argo-events --create-namespace

I edited native eventbus - I just dont understand how token auth works ;/
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      # Optional, defaults to 3. If it is < 3, set it to 3, that is the minimal requirement.
      replicas: 3
      # Optional, authen strategy, "none" or "token", defaults to "none"
      auth: none
```

Then I deployed rabbit as you suggested:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  ports:
    - port: 5672
  selector:
    app: taskQueue
    component: rabbitmq
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
        - image: rabbitmq
          name: rabbitmq
          ports:
            - containerPort: 5672
          resources:
            limits:
              cpu: 100m

```

Then I deployed event source with removed auth capability:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: amqp
spec:
  amqp:
    example:
      # amqp server url
      url: amqp://rabbitmq-service.argo-events:5672
      # jsonBody specifies that all event body payload coming from this
      # source will be JSON
      jsonBody: true
      # name of the exchange.
      exchangeName: test
      # exchange type. more info at https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges
      exchangeType: fanout
      # routing key
      routingKey: hello
      # optional backoff time for connection retries.
      # if not provided, default connection backoff time will be used.
      connectionBackoff:
        # duration in nanoseconds, or strings like "1s", "1m". following value is 10 seconds
        duration: 10s
        # how many backoffs
        steps: 5
        # factor to increase on each step.
        # setting factor > 1 makes backoff exponential.
        factor: 2
        jitter: 0.2
      # optional exchange settings
      # if not provided, default values will be used
      exchangeDeclare:
        durable: true
        autoDelete: false
        internal: false
        noWait: false
      # optional queue settings
      # if not provided, default values will be used
      queueDeclare:
        name: "my-queue-name"
        durable: false
        autoDelete: false
        exclusive: true
        noWait: false
        # example argument to use quorum queues
        # arguments: |-
          # x-queue-type: quorum
      # optional queue binding settings
      # if not provided, default values will be used
      queueBind:
        noWait: false
      # optional consume settings
      # if not provided, default values will be used
      consume:
        consumerTag: "my-consumer-tag"
        autoAck: true
        exclusive: false
        noLocal: false
        noWait: false
      # username and password for authentication
      # use secret selectors
```

and then I deployed default sensor:
`kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/sensors/amqp.yaml`

**also (which is not included in instruction) the `kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/examples/rbac/sensor-rbac.yaml` was needed**

Now When I try to produce message via pika script, my workflow returns:
![image](https://github.com/user-attachments/assets/6f0ee069-1d02-4005-9b9a-2d67d1b13960)
![image](https://github.com/user-attachments/assets/f8e6a460-bf46-420c-a1db-967c069d8fc1)

**Environment:**
 - Kubernetes:v1.23.16]
 - Argo Workflows: [v3.4.4]
 - Argo Events: [v1.9.2]

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
