### ISSUE TITLE
Inject JSON Payload into Workflow

### ISSUE THREAD

**Issue by devstein** [argoproj/argo-events#333]
**Is your feature request related to a problem? Please describe.**
I want to inject the entire JSON payload as a template parameter or artifact; however, currently, all payloads are converted into strings and lose their JSON formatting (double quotes around keys and values). 

This would be especially useful for the Github sensors. 

**Describe the solution you'd like**
I would like a way to inject JSON payload into my workflow without losing its formatting. 

**Describe alternatives you've considered**
If there are an unbounded number of values to inject, such as an array with nested JSON objects, it is no longer feasible to extract and inject individual values from the payload using `resourceParameters.src.path`.

**Additional context**
This can also help simplify sensors when their are many parameters to inject by moving the logic to the workflow itself. 

If this is already possible, please let me know!

**Comment by janschauta** [comment]
I vote for this issue. My exact case it this.

I want to use github sensor to spawn different workflows from different repositories with different sets of parameters. I can parametrize repository, branch, definition file. But how can I parametrize workflows without specifically mentioning every parameter in a sensor definition? Can this be done in a generic way?

**Comment by Neroroms** [comment]
Me too. It difficult to handle real world event, many time we need multiple parameters in one webhook.

**Comment by VaibhavPage** [comment]
Makes sense. I'll add it asap.

**Comment by nirav24** [comment]
Any update on this?

**Comment by VaibhavPage** [comment]
It will be added in v0.13. Right now I am mostly busy with getting #377 ready for v0.12

**Comment by nirav24** [comment]
Awesome. Thanks

**Comment by VaibhavPage** [comment]
Please try `parameter` in v0.12 https://github.com/argoproj/argo-events/tree/master/examples/tutorials/02-parameterization

**Comment by hobti01** [comment]
Did this make it into 0.13?  I see the ability to set key-value pairs in the http trigger payload, but not the ability to set the entire payload.

Attempting to set nested items does not work as might be expected because the payload only allows name/value pairs https://github.com/argoproj/argo-events/blob/v0.14.0/sensors/triggers/params.go#L38
```
          payload:
            - dest: items.0.name
              src:
                dependencyName: some-event
                value: thename
```
Unexpected result:
```
{"items.0.name":"thename"}
```
Expected result:
```
{"items":["name":"thename"]}
```

Can sjson also be used in the payload creation?

**Comment by VaibhavPage** [comment]
As you have pointed out, the payload is a map of string->string. The `dest` is the key within the result payload and it needs to be a valid `key` in the resulting JSON object. 

Consider the sensor is receiving an event payload like,
```

{
       "data": {
          "items": [
              "name": "thename",
              "name": "bar"
           ]
       }
}
```

So you need to apply payload in order to achieve `{"items":["name":"thename"]} `
```

payload:
            - dest: items
              src:
                dependencyName: some-event
                dataKey: data.items.0.name
                value: default-value # if data.items.0.name doesn't exist
```

Take a look at https://argoproj.github.io/argo-events/triggers/http-trigger/#request-payload

**Comment by hobti01** [comment]
thank you for the quick response.

I see I have a typo in my original question.  I intended an array of objects:
```
{"items":[{"name":"thename"}]}
```

Consider that the sensor is receiving an empty payload, or a payload that is not an array.  How can an array be constructed?

If I am not mistaken, your example will not create
```
{"data": {"items": ["name": "default-value"]}}
```
or
```
{"data": {"items": [{"name": "default-value"}]}}
```
But will create
```
{
  "data.items.0": "default-value"
}
```

This is what I'm observing.

I cannot create an array as you describe.
With event payload of (corrected to be array of objects)
```
{
       "data": {
          "items": [
              {"name": "thename"},
              {"name": "bar"}
           ]
       }
}
```
And http trigger
```
payload:
            - dest: items
              src:
                dependencyName: some-event
                dataKey: data.items.0
```
results in:
```
{
  "items": "{\"name\":\"thename\"}"
}
```
Which is not an array or a nested object.

**Comment by VaibhavPage** [comment]
Ok, got it. It may not possible to construct [{"name": "thename"}] as the value as it may not be supported in the underlying library `gjson` https://github.com/tidwall/gjson#path-syntax. The `dataKey` syntax is dervided from `gjson`. as a workaround, I would suggest passing the entire event payload as,
```

payload:
            - dest: items
              src:
                dependencyName: some-event
```
