### ISSUE TITLE
JetStream EventBus with retention: 2 (WorkQueue): Sensor fails to subscribe

### ISSUE THREAD

**Issue by mweibel** [argoproj/argo-events#3377]
**Describe the bug**
```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: eventbus
spec:
  jetstream:
    replicas: 1
    version: 2.10.10
    persistence:
      storageClassName: standard
      volumeSize: 1Gi
    streamConfig: |
      replicas: 1
      retetention: 2
```

Creating this EventBus in argo-events 1.9.3 results in an error when the sensor tries to start the consumer:

```
{"level":"error","ts":1732789254.9938796,"logger":"argo-events.sensor","caller":"sensors/listener.go:307",
"msg":"failed to subscribe to eventbus","sensorName":"my-sensor",
"triggerName":"my-service-trigger","connection":"JetstreamTriggerConn{Sensor:my-sensor,Trigger:my-service-trigger}",
"error":"Failed to subscribe to subject default.my-event-source.mwf using group group-428796809: 
nats: consumer must be deliver all on workqueue stream",
"stacktrace":"github.com/argoproj/argo-events/pkg/sensors.(*SensorContext).listenEvents.func2.6.1\n\t/home/runner/work/argo-events/argo-events/pkg/sensors/listener.go:307"}
```

**To Reproduce**
1. Create that event bus and appropriate EventSource/Sensors
2. Check logs of sensor

**Expected behavior**
Sensor is able to connect and subscribe. 

**Environment (please complete the following information):**
 - Kubernetes: v1.26.6 (local kind cluster)
 - Argo Events: v1.9.3

**Additional context**
v1.9.2 works, possibly the merge of #3151 caused that issue. Seems like the following code would need to change based on the retention policy:
https://github.com/argoproj/argo-events/blob/0494ce77efd0da54f92ac69d47cc104490b831c8/pkg/eventbus/jetstream/sensor/trigger_conn.go#L147

But I haven't investigated if we do have access to this or we'd need a new setting on the sensor instead. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
