### ISSUE TITLE
Trigger source git doesn't work when private repo via HTTPS URL.

### ISSUE THREAD

**Issue by hidekuro** [argoproj/argo-events#338]
**Describe the bug**
Trigger source git doesn't work when using bitbucket private repos via HTTPS URL.

```
ERRO[2019-08-14 01:50:43] trigger failed to execute                     error="failed to clone repository. err: authentication required" trigger-name=my-trigger-1
```

**To Reproduce**

1. import repository https://github.com/argoproj/argo to bitbucket as private repo.
2. create sandbox environments (see below)

create minikube VM and install helm.

```bash
minikube start --memory=4096
helm init

echo "waiting for helm server tiller..."
until (helm version -s); do sleep 3; done
echo "tiller ready."
```

setup argo-workflows, argo-events

```bash
# argo-wf
kubectl create namespace argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml
kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default

# argo-events
kubectl create namespace argo-events
helm repo add argo https://argoproj.github.io/argo-helm
helm install --namespace argo-events --name argo-events argo/argo-events
```

create secret for git.

```bash
# If you using 2FA on bitbucket, you need set "App Password" to set to YOUR_BITBUCKET_PASSWORD.
kubectl -n argo-events create secret generic git-secret --from-literal=username=YOUR_BITBUCKET_USERNAME --from-literal=password=YOUR_BITBUCKET_PASSWORD
```

create argo-events resources.

```bash
kubectl -n argo-events apply -f webhook-event-source.yaml
kubectl -n argo-events apply -f webhook-gateway.yaml
kubectl -n argo-events apply -f webhook-sensor.yaml
```

yaml resources here. (using [examples/sensors/trigger-source-git.yaml](https://github.com/argoproj/argo-events/blob/master/examples/sensors/trigger-source-git.yaml) resouce name modified.)

```yaml
# webhook-event-source.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-event-source1
  labels:
    argo-events-event-source-version: v0.10
data:
  example: |-
    port: "12000"
    endpoint: "/example"
    method: "POST"
```

```yaml
# webhook-gateway.yaml
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: webhook-gateway1
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
    argo-events-gateway-version: v0.10
spec:
  type: "webhook"
  eventSource: "webhook-event-source1"
  processorPort: "9330"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  template:
    metadata:
      name: "webhook-gateway-http1"
      labels:
        gateway-name: "webhook-gateway1"
    spec:
      containers:
        - name: "gateway-client"
          image: "argoproj/gateway-client"
          imagePullPolicy: "Always"
          command: ["/bin/gateway-client"]
        - name: "webhook-events"
          image: "argoproj/webhook-gateway"
          imagePullPolicy: "Always"
          command: ["/bin/webhook-gateway"]
      serviceAccountName: "argo-events-sa"
  service:
    metadata:
      name: webhook-gateway-svc1
    spec:
      selector:
        gateway-name: "webhook-gateway1"
      ports:
        - port: 12000
          targetPort: 12000
      type: LoadBalancer
  watchers:
    sensors:
      - name: "webhook-sensor1"
```

```yaml
# webhook-sensor.yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor1
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /git/argoproj
              name: argoproj
      volumes:
        - name: argoproj
          emptyDir: {}
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "webhook-gateway1:example"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        name: my-trigger-1
        group: test
        version: v1alpha1
        kind: Workflow
        source:
          git:
            url: "https://bitbucket.org/YOUR_BITBUCKET_USERNAME/argo"
            cloneDirectory: "/git/argoproj"
            creds:
              username:
                name: git-secret
                key: username
              password:
                name: git-secret
                key: password
            namespace: argo-events
            filePath: "examples/hello-world.yaml"
            branch: master
```

3. publish webhook event after containers are initialzed.

```
curl -X POST $(minikube service --url webhook-gateway-svc1)/example
```

4. you'll get following logs from pod/webhook-sensor

```
$ kubectl -n argo-events logs webhook-sensor

ERRO[2019-08-14 01:50:43] trigger failed to execute                     error="failed to clone repository. err: authentication required" trigger-name=my-trigger-1
```

it seems failure to authentication via HTTPS.

**Expected behavior**
clone is succeed.

**Environment (please complete the following information):**
- OS: macOS Mojave 10.14.6

```
$ minikube version
minikube version: v1.3.0
commit: 43969594266d77b555a207b0f3e9b3fa1dc92b1f
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
11
