### ISSUE TITLE
Overwrite revisionHistoryLimit for EventSource Deployment

### ISSUE THREAD

**Issue by coldagent** [argoproj/argo-events#3419]
**Is your feature request related to a problem? Please describe.**
When working on an eventsource the ArgoCD UI gets pretty messy showing all these old eventsource replica sets. It would be nice to be able to set the revisionHistoryLimit of the eventsource deployment.

**Describe the solution you'd like**
Use revisionHistoryLimit in eventsource to overwrite/set revisionHistoryLimit in eventsource deployment. I am using a simple webhook as an example

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: eventsource-name
spec:
  eventBusName: eventbus
  revisionHistoryLimit: 0
  webhook:
    example-webhook:
      port: "8080"
      endpoint: /example
      method: GET
```

**Describe alternatives you've considered**
Using a patch to override the revisionHistoryLimit for the eventsource deployment. Setting a global revisionHistoryLimit

**Additional context**
Similar/Related issue: #1786 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
