### ISSUE TITLE
`volumes` doesn't work in Workflow triggered webhook-sensor

### ISSUE THREAD

**Issue by hidekuro** [argoproj/argo-events#342]
**Describe the bug**
`Sensor.spec.triggers[].template.source.*.Workflow.spec.templates[].volumes` doesn't work in Workflow triggered webhook-sensor.

**To Reproduce**

setup argo-workflow + argo-events environments.

```bash
minikube start --memory=4096

helm init
helm repo add argo https://argoproj.github.io/argo-helm

helm install --namespace=default --name=argo argo/argo
kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default

helm install --namespace=default --name=argo-events argo/argo-events \
  --set namespace=default \
  --set singleNamespace=false
```

Create following resources:

```yaml
# init-containers-wf.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: init-container-
spec:
  entrypoint: init-container-example
  templates:
    - name: init-container-example
      volumes:
        - name: workspace
          emptyDir: {}
      container:
        image: alpine:latest
        volumeMounts:
          - name: workspace
            mountPath: /ws
        command: ["sh", "-c"]
        args:
          - |
            echo "main" >> /ws/message.txt
            cat /ws/message.txt
      initContainers:
        - name: init
          image: alpine:latest
          mirrorVolumeMounts: true
          command: ["sh", "-c"]
          args:
            - |
              echo "init" > /ws/message.txt
```

```yaml
# webhook-event-source.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-event-source
  labels:
    argo-events-event-source-version: v0.10
data:
  init-example: |-
    port: "12000"
    endpoint: "/init-example"
    method: "POST"
```

```yaml
# webhook-gateway.yaml
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: webhook-gateway
  labels:
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
    argo-events-gateway-version: v0.10
spec:
  type: webhook
  eventSource: webhook-event-source
  processorPort: "9330"
  eventProtocol:
    type: HTTP
    http:
      port: "9300"
  template:
    metadata:
      name: webhook-gateway-http
      labels:
        gateway-name: webhook-gateway
    spec:
      containers:
        - name: gateway-client
          image: argoproj/gateway-client
          imagePullPolicy: Always
          command: ["/bin/gateway-client"]
        - name: webhook-events
          image: argoproj/webhook-gateway
          imagePullPolicy: Always
          command: ["/bin/webhook-gateway"]
      serviceAccountName: argo-events-sa
  service:
    metadata:
      name: webhook-gateway-svc
    spec:
      selector:
        gateway-name: webhook-gateway
      type: NodePort
      ports:
        - port: 12000
          targetPort: 12000
  watchers:
    sensors:
      - name: webhook-sensor
```

```yaml
# webhook-sensor.yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: sensor
          image: argoproj/sensor
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "webhook-gateway:init-example"
  eventProtocol:
    type: HTTP
    http:
      port: "9300"
  triggers:
    - template:
        name: trigger-init-containers-wf
        group: ""
        version: v1alpha1
        kind: Workflow
        source:
          # same code as init-container-wf.yaml
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: init-container-
            spec:
              entrypoint: init-container-example
              templates:
                - name: init-container-example
                  volumes:
                    - name: workspace
                      emptyDir: {}
                  container:
                    image: alpine:latest
                    volumeMounts:
                      - name: workspace
                        mountPath: /ws
                    command: ["sh", "-c"]
                    args:
                      - |
                        echo "main" >> /ws/message.txt
                        cat /ws/message.txt
                  initContainers:
                    - name: init
                      image: alpine:latest
                      mirrorVolumeMounts: true
                      command: ["sh", "-c"]
                      args:
                        - |
                          echo "init" > /ws/message.txt
```

1. Run via `argo submit`

```
$ argo submit init-container-wf.yaml
Name:                init-container-gkjld
Namespace:           default
ServiceAccount:      default
Status:              Pending
Created:             Mon Aug 19 18:26:47 +0900 (now)

$ argo list
NAME                   STATUS    AGE   DURATION   PRIORITY
init-container-gkjld   Running   6s    6s         0

$ argo logs -f -w init-container-gkjld
init-container-gkjld:   init
init-container-gkjld:   main
```

it seems expected behavior.

2. Run via webhook

```
$ curl -X POST $(minikube service --url webhook-gateway-svc)/init-example
request successfully processed

$ argo list
NAME                   STATUS      AGE   DURATION   PRIORITY
init-container-jsbc2   Error       14s   0s         0

$ argo get init-container-jsbc2
Name:                init-container-jsbc2
Namespace:           default
ServiceAccount:      default
Status:              Error
Message:             volume 'workspace' not found in workflow spec
Created:             Mon Aug 19 18:30:23 +0900 (35 seconds ago)
Started:             Mon Aug 19 18:30:23 +0900 (35 seconds ago)
Finished:            Mon Aug 19 18:30:23 +0900 (35 seconds ago)
Duration:            0 seconds

STEP                     PODNAME               DURATION  MESSAGE
 ⚠ init-container-jsbc2  init-container-jsbc2  0s        volume 'workspace' not found in workflow spec
```

"volume not found" reported.

**Expected behavior**
same behavior as `argo submit`

**Environment (please complete the following information):**

```
$ minikube version
minikube version: v1.3.0
commit: 43969594266d77b555a207b0f3e9b3fa1dc92b1f
```

```
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

$ helm list
NAME       	REVISION	UPDATED                 	STATUS  	CHART            	APP VERSION	NAMESPACE
argo       	2       	Mon Aug 19 18:00:10 2019	DEPLOYED	argo-0.5.0       	v2.3.0     	default
argo-events	1       	Sat Aug 17 03:58:56 2019	DEPLOYED	argo-events-0.4.2	0.9.2      	default
```

```
$ argo version
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:23Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
