### ISSUE TITLE
Argo events 1.9.4 fails to open gRPC connection to custom trigger

### ISSUE THREAD

**Issue by mweibel** [argoproj/argo-events#3420]
**Describe the bug**
After upgrading my local environment to v1.9.4, the custom trigger which used to work before doesn't work anymore. 

Logs show it can't setup the trigger gRPC connection:
```
mysensor-sensor-4bhlg-6c77974c5f-2sbjj main {"level":"info","ts":1736510487.21927,"logger":"argo-events.sensor","caller":"sensor/trigger_conn.go:353","msg":"Triggering actions after receiving dependency my-event-source","sensorName":"mysensor","triggerName":"my-service-trigger","sensorName":"mysensor"}
mysensor-sensor-4bhlg-6c77974c5f-2sbjj main {"level":"info","ts":1736510487.2201834,"logger":"argo-events.sensor","caller":"custom-trigger/custom-trigger.go:70","msg":"instantiating trigger client...","sensorName":"mysensor","triggerName":"my-service-trigger","server-url":"my-service-headless:8082"}
mysensor-sensor-4bhlg-6c77974c5f-2sbjj main {"level":"error","ts":1736510493.324615,"logger":"argo-events.sensor","caller":"sensors/trigger.go:149","msg":"failed to new a Custom trigger","sensorName":"mysensor","triggerName":"my-service-trigger","error":"timed out waiting for the condition","stacktrace":"github.com/argoproj/argo-events/pkg/sensors.(*SensorContext).GetTrigger\n\t/home/runner/work/argo-events/argo-events/pkg/sensors/trigger.go:149\ngithub.com/argoproj/argo-events/pkg/sensors.(*SensorContext).triggerOne\n\t/home/runner/work/argo-events/argo-events/pkg/sensors/listener.go:417\ngithub.com/argoproj/argo-events/pkg/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/pkg/sensors/listener.go:393\ngithub.com/argoproj/argo-events/pkg/sensors.(*SensorContext).triggerActions.func1\n\t/home/runner/work/argo-events/argo-events/pkg/sensors/listener.go:376"}
mysensor-sensor-4bhlg-6c77974c5f-2sbjj main {"level":"error","ts":1736510493.3248565,"logger":"argo-events.sensor","caller":"sensors/listener.go:395","msg":"Failed to execute a trigger","sensorName":"mysensor","error":"invalid trigger my-service-trigger, could not find an implementation","triggerName":"my-service-trigger","triggeredBy":["my-event-source"],"triggeredByEvents":["aeb36a5a096646a0a43df83734861c0b"],"stacktrace":"github.com/argoproj/argo-events/pkg/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/pkg/sensors/listener.go:395\ngithub.com/argoproj/argo-events/pkg/sensors.(*SensorContext).triggerActions.func1\n\t/home/runner/work/argo-events/argo-events/pkg/sensors/listener.go:376"}
```

Pull #3396 upgraded dependencies and adjusted the gRPC connection for custom triggers:
https://github.com/argoproj/argo-events/pull/3396/files#diff-8fcc49ec2c799dbdb5a9a59aa1830eb5c068a03840a7a001058bd7426d0ba46e

Downgrading to 1.9.3 makes it work again. 

ping @whynowy since you worked on that PR. 

**To Reproduce**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: my-event-source
spec:
  replicas: 1
  eventBusName: my-eventbus
  resource:
    myevent:
      namespace: myns
      group: mygroup.example.com
      version: v1alpha2
      resource: myresource
      eventTypes:
        - ADD
        - DELETE
        - UPDATE
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor
spec:
  replicas: 1
  eventBusName: my-eventbus
  dependencies:
    - name: my-event-source
      eventSourceName: my-event-source
      eventName: myevent
  triggers:
    - template:
        name: my-service-trigger
        custom:
          serverURL: my-service-headless:8082
          spec:
            body: ""
            apiVersion: ""
            type: ""
      retryStrategy:
        # Give up after this many times (uses a backoff algo to retry)
        steps: 3
      parameters:
        - src:
            dependencyName: my-event-source
            dataKey: type
          dest: custom.spec.type
        - src:
            dependencyName: my-event-source
            dataKey: body
          dest: custom.spec.body
        - src:
            dependencyName: my-event-source
            dataKey: version
          dest: custom.spec.apiVersion
```

**Expected behavior**
Trigger works.

**Environment (please complete the following information):**
 - Kubernetes: 1.30.8
 - Argo Events: 1.9.4

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
