### ISSUE TITLE
nil pointer dereference when the event is a UPDATE from HPA

### ISSUE THREAD

**Issue by jwillker** [argoproj/argo-events#3494]
**Describe the bug**
Using an EventSource that listens for Kubernetes Deployment with a filter for UPDATE operations works smoothly when a change happens from kubectl, for example. But if the HPA makes the change and changes replicas, the EventSource pod crashes with a nil pointer dereference.

**To Reproduce**
1. Create an EventSource that listens for deployment UPDATES:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: consensus-events-deployment-listener
spec:
  eventBusName: consensus-events
  replicas: 1
  resource:
    deployment-watcher:
      eventTypes:
      - UPDATE
      filter:
        labels:
        - key: app
          value: my-app
      group: apps
      namespace: ""
      resource: deployments
      version: v1
  template:
    container:
      env:
      - name: LOG_LEVEL
        value: debug
    serviceAccountName: consensus-events-deployment-listener
```
3. Create a Deployment and HPA
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: my-namespace
spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - env:
            - name: SERVICE_NAME
              value: my-app
          image: my-app
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /liveness
              port: http-check
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
          name: my-app
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8081
              name: http-check
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readiness
              port: http-check
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: my-app
      serviceAccountName: my-app
      terminationGracePeriodSeconds: 30

```

```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: my-namespace
spec:
  maxReplicas: 6
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app

```

5. Force the HPA scale by changing the max/min replicas.
6. See error:

```log{"level":"info","ts":1740437605.4106703,"logger":"argo-events.eventsource","caller":"resource/start.go:202","msg":"detected update event","eventSourceName":"consensus-events-deployment-listener","eventSourceType":"resource","eventName":"deployment-watcher"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27d2ae5]

goroutine 118 [running]:
github.com/argoproj/argo-events/pkg/eventsources/sources/resource.getEventTime(0xc0000ba268, {0x37820b6?, 0xc001344f60?})
        /home/runner/work/argo-events/argo-events/pkg/eventsources/sources/resource/start.go:368 +0x165
github.com/argoproj/argo-events/pkg/eventsources/sources/resource.passFilters(0xffffffffffffffff?, 0xc0013a30e0, {0x1?, 0x0?, 0x5e3d520?}, 0xc0000bbcb8)
        /home/runner/work/argo-events/argo-events/pkg/eventsources/sources/resource/start.go:303 +0x16d
github.com/argoproj/argo-events/pkg/eventsources/sources/resource.(*EventListener).StartListening.func2(0xc001059ad0)
        /home/runner/work/argo-events/argo-events/pkg/eventsources/sources/resource/start.go:131 +0x6b
github.com/argoproj/argo-events/pkg/eventsources/sources/resource.(*EventListener).StartListening.func3()
        /home/runner/work/argo-events/argo-events/pkg/eventsources/sources/resource/start.go:178 +0x13e
created by github.com/argoproj/argo-events/pkg/eventsources/sources/resource.(*EventListener).StartListening in goroutine 84
        /home/runner/work/argo-events/argo-events/pkg/eventsources/sources/resource/start.go:173 +0x8cd
```

**Expected behavior**
Process the Event usually without the pod dying, or even better, ignore changes from HPA.

**Environment (please complete the following information):**
 - Kubernetes: [v1.30.10]
 - Argo Events: [e.g. v1.9.3]

**Additional context**

Reading the code, I think this problem happens right here: https://github.com/argoproj/argo-events/blob/daaf66081204e81bc1cd2b28c20f41150cefbc4a/pkg/eventsources/sources/resource/start.go#L365-L372

Maybe something is different when the HPA changes the Deployment, and the event doesn't have all the fields. I don't like to know if the HPA alters the Deployment, it would be better to ignore these events.

I'm also thinking about the necessity to do that, even if the AfterStart configuration is false: https://github.com/argoproj/argo-events/blob/daaf66081204e81bc1cd2b28c20f41150cefbc4a/pkg/eventsources/sources/resource/start.go#L303-L304

The verification should only exist if the AfterStart is true.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
