### ISSUE TITLE
templateRef doesn't work

### ISSUE THREAD

**Issue by vdksystem** [argoproj/argo-events#351]
**Describe the bug**
argo-events ignores in source definition (inline, configmap, resource)

**To Reproduce**
1. Create sensor with workflow trigger
2. Use templateRef in workflow definition
3. Created workflow doesn't have templateRef records

**Expected behavior**
Workflow created with exact template, provided in Sensor

**Screenshots**

**Environment (please complete the following information):**
 - Version 0.9.3

**Additional context**
Sensor manifest:

```apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: calendar-sensor
  labels:
    # sensor controller with instanceId "argo-events" will process this sensor
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    # do not remove
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "calendar-gateway:poll-scm"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        name: calendar-workflow-trigger
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          configmap: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              name: grafana-dashboards
              generateName: grafana-dashboard-ci-
            spec:
              entrypoint: ci
              serviceAccountName: argo
              arguments:
                parameters:
                  - name: revision
                    value: master
                  - name: repo
                    value: git@bitbucket.org:***
                  - name: source
                    value: "monitoring/grafana/dashboards/"
                  - name: destination
                    value: s3://***
              templates:
                - name: ci
                  steps:
                    - - name: checkout
                        templateRef:
                          name: checkout
                          template: git
                        arguments:
                          parameters:
                            - name: repo
                              value: "{{workflow.parameters.repo}}"
                            - name: revision
                              value: "{{workflow.parameters.revision}}"
                    - - name: linting
                        templateRef:
                          name: linting
                          template: json
                        arguments:
                          artifacts:
                            - name: source
                              from: "{{steps.checkout.outputs.artifacts.source}}"
                    - - name: publish
                        templateRef:
                          name: publish
                          template: s3
                        arguments:
                          artifacts:
                            - name: source
                              from: "{{steps.checkout.outputs.artifacts.source}}"
                          parameters:
                            - name: source
                              value: "{{workflow.parameters.source}}"
                            - name: destination
                              value: "{{workflow.parameters.destination}}"
```

Workflow created by trigger:
```kind: Workflow
metadata:
  creationTimestamp: "2019-09-03T19:01:29Z"
  generateName: grafana-dashboard-ci-
  generation: 2
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Failed
  name: grafana-dashboards
  namespace: argo
  resourceVersion: "14262677"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/grafana-dashboards
  uid: 3c587af8-ce7d-11e9-b118-06b729ab5488
spec:
  arguments:
    parameters:
    - name: revision
      value: master
    - name: repo
      value: git@bitbucket.org:***
    - name: source
      value: monitoring/grafana/dashboards/
    - name: destination
      value: s3://***
  entrypoint: ci
  serviceAccountName: argo
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: ci
    outputs: {}
    steps:
    - - arguments:
          parameters:
          - name: repo
            value: '{{workflow.parameters.repo}}'
          - name: revision
            value: '{{workflow.parameters.revision}}'
        name: checkout
    - - arguments:
          artifacts:
          - from: '{{steps.checkout.outputs.artifacts.source}}'
            name: source
        name: linting
    - - arguments:
          artifacts:
          - from: '{{steps.checkout.outputs.artifacts.source}}'
            name: source
          parameters:
          - name: source
            value: '{{workflow.parameters.source}}'
          - name: destination
            value: '{{workflow.parameters.destination}}'
        name: publish```

**Comment by logicfox** [comment]
I suppose that's because Agro Events only supports Argo Workflows 2.2.0. See https://github.com/argoproj/argo-events/blob/master/Gopkg.toml#L77-L79

@VaibhavPage Would this only require a version bump and rebuild?

**Comment by VaibhavPage** [comment]
yes, I am working on getting a release out that has latest Argo workflow version

**Comment by sudermanjr** [comment]
@VaibhavPage Is there any update on this? It looks like a release has gone out since your message went out, but I don't seem to be able to get this to work.

**Comment by sudermanjr** [comment]
I was informed on Slack that the 0.11 release that is targeted for Oct. 31 will include the update to Argo 2.4.2

**Comment by skikkh** [comment]
It seems this issue doesn't contain the 0.11 release. Please tell me a roadmap in which you tackle this.

**Comment by opyh** [comment]
This would also help me a lot :)

**Comment by opyh** [comment]
Nevermind. I found out that my `templateRef`s seem to work correctly with v0.11 workflows.

**Comment by skikkh** [comment]
`templateRef` also works well with v0.11. If you like, please show me the corresponding code changes.

**Comment by andy-han** [comment]
Would like to see a functional sensor definition using `templateRef`

**Comment by opyh** [comment]
I had to remove the original code, but this is how my working trigger with a `templateRef` looks in the sensor:

```yaml
triggers:
- template:
    name: foobar-workflow-trigger
    group: argoproj.io
    version: v1alpha1
    resource: workflows
    source:
      inline: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: foobar-
        spec:
          activeDeadlineSeconds: 1200 # timeout after 20 minutes
          ttlSecondsAfterFinished: 86400 # drop k8s resources after one day
          serviceAccountName: argo-events-sa
          entrypoint: foobar-workflow
          templates:
          - name: foobar-workflow
            templateRef:
              name: foobar-workflow
              template: foobar-workflow
            arguments:
              parameters:
              # These values are customized via `resourceParameters` below.
              - name: param1
                value: ""
              - name: param2
                value: ""
  resourceParameters:
    - src:
        # the name of the event dependency
        event: "webhook-gateway:event-source-name"
        # a key within event payload to look for. Supports GJSON path syntax:
        # https://foobar.com/tidwall/gjson/blob/master/SYNTAX.md
        #
        # If you want to supply the whole JSON, use "@ugly" as path
        path: "some.path.in.the.event.json"
        # default value if sensor can't find path in event payload:
        # value: "DEFAULT VALUE"

      # Path to the value to override in the template above, in SJSON syntax
      # See https://foobar.com/tidwall/sjson#path-syntax for more information about how this is used.
      # This overrides the first input parameter in template's arguments.
      dest: spec.templates.0.arguments.parameters.0.value
    - src:
        event: "webhook-gateway:event-source-name"
        path: "some.other.path.in.the.event.json"
      dest: spec.templates.0.arguments.parameters.1.value
```
