### ISSUE TITLE
Trigger fails without configmap namespace

### ISSUE THREAD

**Issue by pdavid31** [argoproj/argo-events#356]
**Describe the bug**
 Trigger fails to execute if the workflow is configured as a configmap and no namespace is provided.

**To Reproduce**
Ommit the namespace in .template.source.configmap ConfigMap specification.

**Expected behavior**
If no namespace is provided the default should be the sensors namespace.

**Logs**
ERRO[2019-09-20 13:01:00] trigger failed to execute - error="an empty namespace may not be set when a resource name is provided" trigger-name=sync-sct-trigger

**Sensor Config:**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sync-sct-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: argo-sa
  dependencies:
    - name: "sync-sct-gateway:default"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        name: sync-sct-trigger
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          configmap:
            name: sync-sct-workflow-configmap
            key: wf
```
