### ISSUE TITLE
Trigger with git source (ssh) failing

### ISSUE THREAD

**Issue by thundergolfer** [argoproj/argo-events#357]
**Describe the bug**

Trying to get the trigger-with-git  example running in our cluster. 

**To Reproduce**

```
apiVersion: v1
data:
  example: 'schedule: 0/2 * * * *'
kind: ConfigMap
metadata:
  name: calendar-gateway-configmap
  namespace: argo
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  labels:
    argo-events-sensor-version: v0.10
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
  name: calendar-sensor-derived
  namespace: argo
spec:
  circuit: false || example
  dependencies:
  - name: calendar-gateway-derived:example
  dependencyGroups:
  - dependencies:
    - calendar-gateway-derived:example
    name: example
  eventProtocol:
    http:
      port: "9300"
    type: HTTP
  template:
    spec:
      containers:
      - image: argoproj/sensor:v0.8.2
        imagePullPolicy: Always
        name: sensor
        volumeMounts:
        - mountPath: /git/data-science
          name: ds-repo
        - mountPath: /secret
          name: sshkey
        - mountPath: /etc/ssh
          name: known-hosts
      serviceAccountName: argo-events-sa
      volumes:
      - emptyDir: {}
        name: ds-repo
      - name: sshkey
        secret:
          secretName: git-ssh
      - name: known-hosts
        secret:
          secretName: git-known-hosts
  triggers:
  - name: example
    resource:
      group: argoproj.io
      kind: Workflow
      namespace: argo
      source:
        git:
          branch: master
          cloneDirectory: /git/data-science
          filePath: examples/hello_world.yaml
          namespace: argo
          sshKeyPath: /secret/key
          url: git@github.com:argoproj/argo.git
      version: v1alpha1
    when:
      all:
      - example
---
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  labels:
    gateway-name: calendar-gateway-derived
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
  name: calendar-gateway-derived
  namespace: argo
spec:
  configMap: calendar-gateway-configmap-derived
  eventProtocol:
    http:
      port: "9300"
    type: HTTP
  eventVersion: "1.0"
  processorPort: "9330"
  template:
    metadata:
      labels:
        gateway-name: calendar-gateway-derived
      name: calendar-gateway-derived
    spec:
      containers:
      - command:
        - /bin/gateway-client
        image: argoproj/gateway-client:v0.8.2
        imagePullPolicy: Always
        name: gateway-client
      - command:
        - /bin/calendar-gateway
        image: argoproj/calendar-gateway:v0.8.2
        imagePullPolicy: Always
        name: calendar-events
      serviceAccountName: argo-events-sa
  type: calendar
  watchers:
    sensors:
    - name: calendar-sensor-derived
```

_known hosts was added with:_ `kubectl -n argo create secret generic git-known-hosts --from-file=ssh_known_hosts=/tmp/argo-events/known_hosts`

_ssh key was added wtih:_ `kubectl -n argo create secret generic git-ssh --from-file=key=/tmp/argo-events/id_rsa`

**Expected behavior**

Argo-events will be properly run the example every 2 minutes.

**Actual behaviour**

No workflows trigger and checking the logs of the sensor shows:

```
2019-09-23T09:14:00Z | info  | msg: all event dependencies are marked completed, processing triggers |  sensor-name:calendar-sensor-derived
2019-09-23T09:14:00Z | error | msg: trigger failed to execute |  error="failed to fetch. err: error creating SSH agent: \"SSH agent requested but SSH_AUTH_SOCK not-specified\"" sensor-name:calendar-sensor-derived trigger-name:example-trigger
2019-09-23T09:14:00Z | info  | msg: sensor state updated successfully |  phase:Active sensor-name:calendar-se...
```

**Additional context**

See below for my comments including more context from my debugging journey.

**Comment by thundergolfer** [comment]
From Googling the error it seems that this error shows up when the `id_rsa` key can't be found, but I have supplied it to the sensor pod and I can see it in the running container.

**Comment by thundergolfer** [comment]
Further strangeness is that I tried this with a private repo and can look in `/git/` and find that the repo has been correctly cloned. If the SSH didn't work, then how is the repo cloned to the container volume?

**Comment by thundergolfer** [comment]
The SSH is also definitely being found and parsed correctly. 

I have tried removing the `/secret` file and get the appropriate error about the missing file, and I have also tried providing garbage in the file that should contain the key and get the appropriate parse error.

**Comment by VaibhavPage** [comment]
This is weird, I'll take a look.

**Comment by dlobue** [comment]
Is there any update on this issue? I'm running into this as well.

**Comment by whynowy** [comment]
What version are you running?@dloble

**Comment by dlobue** [comment]
@whynowy  The sensor container is using image argoproj/sensor:v0.17.0
Actually pretty much every argo-event container is running an image with the v0.17.0 tag.
kubernetes version v1.16.13-eks-2ba888

For the sake of being thorough, my sensor manifest is below, and it is being triggered by a github webhook event from a private repo.

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: gh-event
      eventSourceName: gh-hook
      eventName: ingestion-pipeline
  triggers:
    - template:
        name: github-trigger-workflow
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            git:
              url: THIS_WILL_BE_REPLACED
              cloneDirectory: "/git/k8s-demo"
              filePath: ".argo/ci.yaml"
              sshKeySecret:
                name: ssh-key-github
                key: ssh-privatekey
              branch: master
          parameters:
            - src:
                dependencyName: gh-event
                dataKey: body.head_commit.id
              dest: spec.arguments.parameters.0.value
      parameters:
        - src:
            dependencyName: gh-event
            dataKey: body.repository.name
          dest: name
        - src:
            dependencyName: gh-event
            dataKey: body.repository.ssh_url
          dest: k8s.source.git.url
```
