### ISSUE TITLE
Allow sensors to refer to gateways without specifying individual sources

### ISSUE THREAD

**Issue by jaygorrell** [argoproj/argo-events#359]
**Is your feature request related to a problem? Please describe.**
I have a sensor hooked up to a gateway with about 10 cronjobs, each with their own `userPayload`. In order for my Sensor to handle this using `resourceParameters` to set the arguments to the workflow, I would need each event source to create their own mapping for `userPayload` to the same `dest`.

This is on top of the things you already have to specify when listening to multiple gateways/sources anyway: adding them to `dependencies`, `dependencyGroups` (with a corresponding `circuit` entry), and so on.

**Describe the solution you'd like**
I would love for most references to an event to support an omission of the event source or (ideally) a wildcard pattern of some sort. Some examples:
(1) Current:
```
dependencies:
- name: "my-gateway:srcA"
- name: "my-gateway:srcB"
- name: "my-gateway:srcC"
```
(1) Desired:
```
dependencies:
- name: "my-gateway:src*"
```
(1) Desired: (Alternative)
```
dependencies:
- name: "my-gateway"
```
(2) Current:
```
resourceParameters:
  - src:
      event: "my-gateway:srcA"
      payload: userPayload
    dest: spec.arguments.parameters.0.value
  - src:
      event: "my-gateway:srcB"
      payload: userPayload
    dest: spec.arguments.parameters.0.value
  - src:
      event: "my-gateway:srcC"
      payload: userPayload
    dest: spec.arguments.parameters.0.value
```
(2) Desired:
```
resourceParameters:
  - src:
      event: "my-gateway:src*"
      payload: userPayload
    dest: spec.arguments.parameters.0.value
```
(2) Desired (Alternative):
```
resourceParameters:
  - src:
      event: "my-gateway"
      payload: userPayload
    dest: spec.arguments.parameters.0.value
```
