### ISSUE TITLE
jetstream eventbus does not support `*` as event name in dependencies of sensors

### ISSUE THREAD

**Issue by zlm2012** [argoproj/argo-events#3596]
**Describe the bug**
I've used argo events with stan eventbus, with a wildcard (`*`) config in the sensor and it worked happily. Since stan is deprecated and jetstream is the future, I tried to migrate it but it's just not working at all.

As far as I can tell, it might be `glob.Compile()` is omitted in jetstream driver, not sure if it's on purpose.
Here for stan: https://github.com/argoproj/argo-events/blob/c8e476ae7acf2db0166f5938c72ff9ab47fab6fb/pkg/eventbus/stan/sensor/trigger_conn.go#L400-L402
and here for jetstream: https://github.com/argoproj/argo-events/blob/c8e476ae7acf2db0166f5938c72ff9ab47fab6fb/pkg/eventbus/jetstream/sensor/trigger_conn.go#L520-L521

I just wonder if it's a bug or a new feature.

**To Reproduce**
1. create some sensor like:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-a
spec:
  dependencies:
    - name: calendar-a
      eventSourceName: es-calendar-a
      eventName: "*"
  triggers:
    - ...
```
2. apply it with jetstream eventbus and any event created by event source like
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: es-calendar-a
spec:
  calendar:
    event-a:
      schedule: "* * * * *"
      timezone: Asia/Tokyo
      metadata:
        payload: a
```
3. get error like this:
```json
{"level":"error","ts":1747208460.0185795,"logger":"argo-events.sensor","caller":"sensor/trigger_conn.go:313","msg":"Failed to get the dependency names, discarding it... err: incoming event source and event not associated with any dependencies, event source=es-calendar-a, event=event-a","sensorName":"sensor-a","triggerName":"a-trigger","sensorName":"sensor-a","stacktrace":"github.com/argoproj/argo-events/pkg/eventbus/jetstream/sensor.(*JetstreamTriggerConn).processMsg\n\t/home/runner/work/argo-events/argo-events/pkg/eventbus/jetstream/sensor/trigger_conn.go:313\ngithub.com/argoproj/argo-events/pkg/eventbus/jetstream/sensor.(*JetstreamTriggerConn).processMsgs\n\t/home/runner/work/argo-events/argo-events/pkg/eventbus/jetstream/sensor/trigger_conn.go:244"}
```

**Expected behavior**
the event should be properly handled.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Kubernetes: v1.27.5
 - Argo Events: v1.9.5

**Additional context**
N/A

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
