### ISSUE TITLE
Allow regular expression in event filters

### ISSUE THREAD

**Issue by ptemmer** [argoproj/argo-events#360]
It would be nice if regular expressions could be used as matchers for filter values.
For example, only pass GitHub push events as valid when the branch is like "feature/......." and ignore all other push events.

Afaik there is no other way to achieve this, as branch names are not static.

```  
dependencies:
    - name: "webhook-gateway:example"
      filters:
        name: "data-filter"
        data:
          - path: ref
            type: string
            value:
              - "^feature/.*"
```
