### ISSUE TITLE
Memory leak in Sensor

### ISSUE THREAD

**Issue by grograxa** [argoproj/argo-events#3613]
**Describe the bug**
There appears to be a memory leak in the Sensor component when triggering Argo Workflows. In a HA setup the leader memory usage continually increases until it is OOM killed. The standby memory usage remains constant.

**To Reproduce**
1. Deploy a Sensor that triggers an Argo Workflow. Example triggers definition:
```yaml
triggers:
  - template:
      argoWorkflow:
        operation: submit
        parameters:
          - dest: spec.arguments.parameters.#(name=="message").value
            src:
              dataKey: body
              dependencyName: example
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: example-workflow-
            spec:
              arguments:
                parameters:
                  - name: message
                    value: Will be replaced with SQS payload
                  - name: env
                    value: dev
              workflowTemplateRef:
                name: example
      name: example
```
3. Send event that triggers the sensor
**Expected behavior**
Sensor memory usage is consistent and does not grow over time.

**Screenshots**

<img width="2686" alt="Image" src="https://github.com/user-attachments/assets/2f511d25-7b48-4be5-b83a-52033b5f7131" />

**Environment (please complete the following information):**
 - Kubernetes: 1.32
 - Argo: 3.6.7
 - Argo Events: 1.9.6

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
