### ISSUE TITLE
TriggerParameter Operation is ignored

### ISSUE THREAD

**Issue by ptemmer** [argoproj/argo-events#364]
**Describe the bug**
```
templateParameters:
        - src: 
            event: "webhook-gateway:webhook"
            path: pull_request.id
          dest: source.resource.metadata.name
          operation: append
```
Instead of appending, the destination value is being replaced entirely. Same thing happens when using "prepend".
Moreover, the validator in https://github.com/argoproj/argo-events/blob/1d51b87bd54682f26100ab622e04bc30cdb31d97/controllers/sensor/validate.go#L149 should error out when an invalid operator value ("prepend", "replace", "append", "") is specified. Nonetheless, no error message is shown when introducing a bogus value.

**To Reproduce**
Try a templateParameter or resourceParameter block specifying "prepend" or "append" as operator value.

```
templateParameters:
        - src: 
            event: "webhook-gateway:webhook"
            path: pull_request.id
          dest: source.resource.metadata.name
          operation: append
```

**Expected behavior**
The operation parameter should be respected
