### ISSUE TITLE
Workflow parameters are ignored when triggered through argo-events

### ISSUE THREAD

**Issue by jdeprin** [argoproj/argo-events#373]
**Describe the bug**
Several workflow parameters such as `spec.priority` are stripped from the workflow while passing through argo-events.

**To Reproduce**
*Prereq*: Have argo-events v0.10 gateway and sensor setup to test a workflow submission.  These steps are outlined in the argo-events docs so I won't go into detail here.

1. Create a sample workflow
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: priority-test-
  namespace: argo-events
  name: priority-test
spec:
  entrypoint: whalesay
  priority: 10
  arguments:
    parameters:
    - name: payload
      value: "hello-world"
  templates:
  - container:
      args:
      - hello world
      command:
      - cowsay
      image: docker/whalesay:latest
    name: whalesay
```
2. Submit this workflow
`kubectl -n argo-events create -f workflow.yaml`
3. Describe the workflow
`kubectl -n argo-events describe workflow priority-test`
You can see the Priority fields applied
```
...
Spec:
  Priority:    10
...
```
4. Submit the same workflow through any argo-events gateway/sensor.
5. Describe the workflow that is generated.  No Priority field exists.

**Expected behavior**
Valid Workflow CRD fields should not be stripped from the workflow.

**Environment (please complete the following information):**
 - Version argo-events v0.10 / argo v2.4.0 / kubernetes 1.14.6
