### ISSUE TITLE
Event Sensor got panics if gateway not existed selected in dependency

### ISSUE THREAD

**Issue by SHRJA** [argoproj/argo-events#383]
**Describe the bug**
Event sensor gets panic without showing error logs when I select a dependency in `dependencyGroups` which does not exist in `dependencies:`

This is the error logs found in terminated sensor pod
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12d301c]

goroutine 24 [running]:
github.com/argoproj/argo-events/sensors.(*sensorExecutionCtx).canProcessTriggers(0xc0006c6000, 0xc0006a8a40, 0x17, 0x15e970c)
	/Users/user/go/src/github.com/argoproj/argo-events/sensors/trigger.go:47 +0x14c
github.com/argoproj/argo-events/sensors.(*sensorExecutionCtx).processUpdateNotification(0xc0006c6000, 0xc0004744c0)
	/Users/user/go/src/github.com/argoproj/argo-events/sensors/event-handler.go:106 +0x118b
github.com/argoproj/argo-events/sensors.(*sensorExecutionCtx).WatchEventsFromGateways.func1(0xc0006c6000)
	/Users/user/go/src/github.com/argoproj/argo-events/sensors/event-handler.go:192 +0x57
created by github.com/argoproj/argo-events/sensors.(*sensorExecutionCtx).WatchEventsFromGateways
	/Users/user/go/src/github.com/argoproj/argo-events/sensors/event-handler.go:190 +0x54
```

**To Reproduce**
I am using the webhook.yaml of gateways and event-source in argo-events repository and changed sensor like below
I can reproduce this by putting wrong dependency name in dependencyGroups as I did in `- name: "group_2"`
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    # do not remove
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor:v0.10"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "webhook-gateway:example"
    - name: "webhook-gateway1:example"
  dependencyGroups:
    - name: "group_1"
      dependencies:
        - "webhook-gateway:example"
    - name: "group_2"
      dependencies:
        - "webhook-gateway_wrong:example"
  circuit: "group_1 || group_2"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        when:
          all:
            - "group_1"
        name: webhook-workflow-trigger
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: webhook-
            spec:
              entrypoint: whalesay
              arguments:
                parameters:
                - name: message
                  # this is the value that should be overridden
                  value: hello world
              templates:
              - name: whalesay
                inputs:
                  parameters:
                  - name: message
                container:
                  image: docker/whalesay:latest
                  command: [cowsay]
                  args: ["{{inputs.parameters.message}}"]
    - template:
        when:
          all:
            - "group_2"
        name: webhook-workflow-trigger
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: webhook-
            spec:
              entrypoint: whalesay
              arguments:
                parameters:
                - name: message
                  # this is the value that should be overridden
                  value: hello world
              templates:
              - name: whalesay
                inputs:
                  parameters:
                  - name: message
                container:
                  image: docker/whalesay:latest
                  command: [cowsay]
                  args: ["{{inputs.parameters.message}}"]
      resourceParameters:
        - src:
            event: "webhook-gateway:example"
          dest: spec.arguments.parameters.0.value
```
**Expected behavior**
Event sensor should catch this error without getting panic and let developer know the cause, possibly typo, not correct dependeny etc like below message.
```
error occurred while determining triggers can be processed  error="failed to get a dependency: webhook-gateway_wrong:example"
```

```
INFO[2019-10-20 18:52:52] phase marked as completed                     node-name="webhook-gateway:example" node-type=EventDependency
INFO[2019-10-20 18:52:52] marking node phase                            node-name=group_1 node-type=DependencyGroup phase=""
INFO[2019-10-20 18:52:52] phase marked as completed                     node-name=group_1 node-type=DependencyGroup
ERRO[2019-10-20 18:52:52] error occurred while determining triggers can be processed  error="failed to get a dependency: webhook-gateway_wrong:example"
INFO[2019-10-20 18:52:52] sensor state updated successfully             phase=Active
```
#384
