### ISSUE TITLE
Kafka Event Source: Partition for a topic

### ISSUE THREAD

**Issue by CH-karthikprasad** [argoproj/argo-events#387]
**Is your feature request related to a problem? Please describe.**
I started to use the Kafka event source, gateway and sensor yesterday locally. I have a topic in kafka with a replication factor of 1 and partition of 1. As this is local, the event source config map for this topic looks like 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-event-source
  labels:
    # do not remove
    argo-events-event-source-version: v0.10
data:
  example-with-retry: |-
    url: my-cluster-kafka-brokers:9092
    topic: "incomingftpevents"
    partition: "0"
    backoff:
      # duration in nanoseconds. following value is 10 seconds
      duration: 10000000000
      # how many backoffs
      steps: 5
      # factor to increase on each step.
      # setting factor > 1 makes backoff exponential.
      factor: 2
```
While it works well, in a production use case i would imagine having a partition count greater than 1. Do i need to define an entry per partition ? for example, if i have 4 partitions i would have to define consumer configs in the event source 4 times ?

**Describe the solution you'd like**
I have not used the Go (Shopify's sarama) client library for Kafka. In the Java/Scala client library, you generally dont need to specify the partition and the consumer will spawn threads based on the partition count. I haven't looked at how the Go client works, but i think it would be ideal not to have to replicate configs based on each partition.
