### ISSUE TITLE
Sensor in different namespace 'failed to create resource object'

### ISSUE THREAD

**Issue by automagic** [argoproj/argo-events#407]
When a sensor is triggered in a different namespace than the gateway, kubernetes gives an error on resource creation:

The sensor successfully receives the json payload and decodes it, then hits this error:

```
trigger failed to execute 
error="failed to create resource object. err: namespaces.argoproj.io \"dev\" is forbidden: User \"system:serviceaccount:dev:argo-events-sa\" cannot create resource \"namespaces\" in API group \"argoproj.io\" in the namespace \"dev\"" 
trigger-name=sqs-workflow
```
(apparently the error happens here https://github.com/argoproj/argo-events/blob/afbdba604ef16c93f64612fbd147380f78cb9a1a/sensors/trigger.go#L335)

We have verified that `argo-events-sa` is created in the namespace `dev` where the sensor exists when argo-events deployed.

The sensor manifest looks like:

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sqs-sensor-foo
  labels:
    # sensor controller with instanceId "argo-events" will process this sensor
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    # do not remove
    argo-events-sensor-version: v0.10
    instance: {{ .Release.Name }}
    managed-by: {{ .Release.Service }}
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      annotations:
        'cluster-autoscaler.kubernetes.io/safe-to-evict': 'true'
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  dependencies:
    - name: "aws-sqs-gateway:foo_sqs_queue"
  triggers:
    - template:
        name: sqs-workflow
        group: ""
        version: v1alpha1
        kind: Workflow
        source:
          configmap:
            name: foo-workflow
            namespace: dev
            key: wf
```

I should also mention this workflow is fine when both Sensor and Gateway are in the same namespace

It is unclear to us if this is a configuration issue, or a bug.
