### ISSUE TITLE
GitHub Sensor failed to retrieve api token credentials.

### ISSUE THREAD

**Issue by daniyalj** [argoproj/argo-events#429]
**Describe the bug**
Replicating the GitHub examples from the latest 0.12 release in the master branch.

After creating the github gateway, eventsource sensor getting the following error in the github gateway:

```
$ kubectl logs -f github-gateway-6fd77c4765-jbhvs  -c github-events -n argo-events
starting gateway server
INFO[2019-12-12 16:11:28] started processing the event source...        event-source=example
INFO[2019-12-12 16:11:28] validating the route...                       event-source=example
INFO[2019-12-12 16:11:28] activating the route...                       event-source=example
INFO[2019-12-12 16:11:28] activating the route...                       endpoint=/push event-source=example port=12000
INFO[2019-12-12 16:11:28] route is activated                            endpoint=/push event-source=example port=12000
INFO[2019-12-12 16:11:28] running operations post route activation...   event-source=example
INFO[2019-12-12 16:11:28] retrieving api token credentials...           event-source=example repository=argo-events-webhook
ERRO[2019-12-12 16:11:28] error occurred while performing post route activation operations  error="failed to retrieve api token credentials. err: an empty namespace may not be set when a resource name is provided" event-source=example
```

My secret exists in the same namespace:

```
$ kubectl describe secret github-access -n argo-events
Name:         github-access
Namespace:    argo-events
Labels:       <none>
Annotations:  
Type:         Opaque

Data
====
secret:  9 bytes
token:   40 bytes

```

This was working before the 0.12 release

**To Reproduce**
1. Install argo-events from the master branch including undocumented event source CRD
2. Create the github gateway:

```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: github-gateway
  namespace: argo-events
  labels:
    # gateway controller with instanceId "argo-events" will process this gateway
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
spec:
  replica: 1
  type: "github"
  eventSourceRef:
    name: "github-event-source"
    # optional, if event source is deployed in a different namespace than the gateway
    # namespace: "other-namespace"
  processorPort: "9330"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  template:
    metadata:
      name: "github-gateway"
      labels:
        gateway-name: "github-gateway"
    spec:
      containers:
        - name: "gateway-client"
          image: "argoproj/gateway-client"
          imagePullPolicy: "Always"
          command: ["/bin/gateway-client"]
        - name: "github-events"
          image: "argoproj/github-gateway"
          imagePullPolicy: "Always"
          command: ["/bin/github-gateway"]
      serviceAccountName: "argo-events-sa"
  service:
    metadata:
      name: github-gateway-svc
    spec:
      selector:
        gateway-name: "github-gateway"
      ports:
        - port: 12000
          targetPort: 12000
      type: LoadBalancer
  watchers:
    sensors:
      - name: "github-sensor"
```
3. Create the k8s secret and github event source:

```
# Info on GitHub Webhook: https://developer.github.com/v3/repos/hooks/#create-a-hook
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-event-source
  namespace: argo-events
spec:
  type: "github"
  github:
    example:
      # owner of the repo
      owner: "daniyalj"
      # repository name
      repository: "argo-events-webhook"
      # Github will send events to following port and endpoint
      webhook:
        # endpoint to listen to events on
        endpoint: "/push"
        # port to run internal HTTP server on
        port: "12000"
        # url the gateway will use to register at Github.
        # This url must be reachable from outside the cluster.
        # The gateway pod is backed by the service defined in the gateway spec. So get the URL for that service Github can reach to.
        url: "http://<your-external-ip>"
      # type of events to listen to.
      # following listens to everything, hence *
      # You can find more info on https://developer.github.com/v3/activity/events/types/
      events:
        - "*"
      # apiToken refers to K8s secret that stores the github api token
      apiToken:
        # Name of the K8s secret that contains the access token
        name: github-access
        # Key within the K8s secret whose corresponding value (must be base64 encoded) is access token
        key: token
      # webHookSecret refers to K8s secret that stores the github hook secret
      # type of the connection between gateway and Github
      insecure: false
      # Determines if notifications are sent when the webhook is triggered
      active: true
      # The media type used to serialize the payloads
      contentType: "json"
```

4. Create the sensor:

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
  namespace: argo-events
  labels:
    # sensor controller with instanceId "argo-events" will process this sensor
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "github-gateway:example"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        name: github-workflow-trigger
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: github-
            spec:
              entrypoint: whalesay
              arguments:
                parameters:
                - name: message
                  # this is the value that should be overridden
                  value: hello world
              templates:
              - name: whalesay
                inputs:
                  parameters:
                  - name: message
                container:
                  image: docker/whalesay:latest
                  command: [cowsay]
                  args: ["{{inputs.parameters.message}}"]
      resourceParameters:
        - src:
            event: "github-gateway:example"
          dest: spec.arguments.parameters.0.value
```

5. See error in the github-event container in the github-gateway pod

**Expected behavior**
The webhook works and the above error doesnt occur.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**
This error didnt occur with 0.11

**Comment by VaibhavPage** [comment]
You need to add `namespace` in event source to locate the API secret. I'll update the example in repo. Your event source should look like 
```

  github:
    example:
      # owner of the repo
      owner: "daniyalj"
      # repository name
      repository: "argo-events-webhook"
      # Github will send events to following port and endpoint
      webhook:
        # endpoint to listen to events on
        endpoint: "/push"
        # port to run internal HTTP server on
        port: "12000"
        # url the gateway will use to register at Github.
        # This url must be reachable from outside the cluster.
        # The gateway pod is backed by the service defined in the gateway spec. So get the URL for that service Github can reach to.
        url: "http://<your-external-ip>"
      # type of events to listen to.
      # following listens to everything, hence *
      # You can find more info on https://developer.github.com/v3/activity/events/types/
      events:
        - "*"
      # apiToken refers to K8s secret that stores the github api token
      apiToken:
        # Name of the K8s secret that contains the access token
        name: github-access
        # Key within the K8s secret whose corresponding value (must be base64 encoded) is access token
        key: token
     namespace: <namespace_where_api_token_is_stored>
      # webHookSecret refers to K8s secret that stores the github hook secret
      # type of the connection between gateway and Github
      insecure: false
      # Determines if notifications are sent when the webhook is triggered
      active: true
      # The media type used to serialize the payloads
      contentType: "json"

```
