### ISSUE TITLE
Enable passing labels and annotations to service exposing sensor

### ISSUE THREAD

**Issue by Shreyam** [argoproj/argo-events#438]
**Is your feature request related to a problem? Please describe.**
Our k8s setup requires us to add some labels to the service which the sensor exposes to communicate with the gateway for HTTP protocol. Otherwise it fails in our admission controller. It'll be nice to allow users to pass labels and annotations as part of the sensor spec

**Describe the solution you'd like**
Modify the `sensor` spec, specifically the [`eventProtocol (http)`](https://github.com/argoproj/argo-events/blob/master/examples/sensors/calendar.yaml#L18) part to allow labels and annotations. Along these lines maybe - 
```
eventProtocol:
    type: "HTTP"
    http:
      labels:
        label-key: "label-value"
      annotations:
        annotation-key: "annotation-value"
      port: "9300"
```

**Describe alternatives you've considered**
Alternatively, we can add a `metadata` field to the `eventProtocol` key. Or we can duplicate the `sensor` level labels and annotations to the service
