### ISSUE TITLE
error looking up service account default/argo-events-sa

### ISSUE THREAD

**Issue by eramirez51** [argoproj/argo-events#462]
**Describe the bug**
Could not install using the instruction provided in [One Command Installation](https://argoproj.github.io/argo-events/installation/#one-command-installation)

**To Reproduce**
1. Run `kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/master/hack/k8s/manifests/installation.yaml` as written on 
[One Command Installation](https://argoproj.github.io/argo-events/installation/#one-command-installation)
2. This error appears for both gateway-controller and sensor-controller `Pods "gateway-controller-xxxxx-" is forbidden: error looking up service account default/argo-events-sa: serviceaccount "argo-events-sa" not found; Deployment does not have minimum availability.`

**Expected behavior**
Argo events is installed without problems.

**Environment (please complete the following information):**
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-gke.22", GitCommit:"27d90409ce8ea2357fbb836191844d9f01d4de19", GitTreeState:"clean", BuildDate:"2019-11-26T00:38:04Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I am running this on GKE

**Comment by VaibhavPage** [comment]
You need to grant `admin` permissions for the service account on GCP in order to use `ClusterRole`.

```
kubectl create clusterrolebinding cluster-admin-binding \
  --clusterrole cluster-admin \
  --user argo-events-sa
```
Source: https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control

If you don't want to grant admin perms, you can switch to Roles and RoleBindings - https://github.com/argoproj/argo-events/blob/master/hack/k8s/manifests/argo-events-role.yaml

**Comment by eramirez51** [comment]
That did not help. I get the same error even after granting `admin` permissions. Upon checking, `installation.yaml` does not use `ClusterRole`.
https://raw.githubusercontent.com/argoproj/argo-events/master/hack/k8s/manifests/installation.yaml

**Comment by VaibhavPage** [comment]
Looks like you are creating deployments in `default` namespace. 

`error looking up service account default/argo-events-sa: serviceaccount "argo-events-sa" not found;`

Can you create the controller deployments in `argo-events` namespace?

**Comment by eramirez51** [comment]
That did not work either. Doing so have following problem
```
panic: configmaps "gateway-controller-configmap" is forbidden: User "system:serviceaccount:argo-events:argo-events-sa" cannot get resource "configmaps" in API group "" in the namespace "argo-events"

```

**Comment by eramirez51** [comment]
Errors disappeared by changing the ServiceAccount and RoleBinding to following. But I am not sure if it a good idea.

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-events-role
subjects:
  - kind: ServiceAccount
    name: argo-events-sa
    namespace: default
```
Fixed the problem

**Comment by eramirez51** [comment]
Apologies, previous modification did not fix the problem, I get this in the logs of the controller
```
system:serviceaccount:default:argo-events-sa" cannot list resource "gateways" in API group "argoproj.io" in the namespace "argo-event
```

**Comment by VaibhavPage** [comment]
Because the `gateway-controller-configmap` is trying to listen to `gateways` in `argo-events` namespace. Given you are deploying everything in `default` namespace, please change the `namespace` key within `gateway-controller-configmap` to `default`. Also, make the similar change to `sensor-controller-configmap`

**Comment by eramirez51** [comment]
I fixed with the following changes. I haven't ran any events yet, but it looks normal now in both logs
```
@@ -61,6 +61,7 @@
 kind: RoleBinding
 metadata:
   name: argo-events-role-binding
+  namespace: argo-events
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: Role
@@ -74,6 +75,7 @@
 kind: Role
 metadata:
   name: argo-events-role
+  namespace: argo-events
 rules:
   - apiGroups:
       - argoproj.io
@@ -144,6 +146,7 @@
 kind: ConfigMap
 metadata:
   name: gateway-controller-configmap
+  namespace: argo-events
 data:
   config: |
     instanceID: argo-events
@@ -154,6 +157,7 @@
 kind: Deployment
 metadata:
   name: gateway-controller
+  namespace: argo-events
 spec:
   replicas: 1
   selector:
@@ -184,6 +188,7 @@
 kind: ConfigMap
 metadata:
   name: sensor-controller-configmap
+  namespace: argo-events
 data:
   config: |
     instanceID: argo-events
@@ -193,6 +198,7 @@
 kind: Deployment
 metadata:
   name: sensor-controller
+  namespace: argo-events
 spec:
   replicas: 1
   selector:
```
