### ISSUE TITLE
Sensor Inline Templates errors when parsing booleans

### ISSUE THREAD

**Issue by delwaterman** [argoproj/argo-events#463]
**Describe the bug**
Sensors fail to parse boolean values in inline yaml temlates with the following error:
```
v1alpha1.WorkflowSpec.Arguments: v1alpha1.Arguments.Parameters: []v1alpha1.Parameter: v1alpha1.Parameter.Value: ReadString: expects \" or n, but found f, error found in #10 byte of ...|,\"value\":false}]},\"e|..., bigger context ...|:{\"parameters\":[{\"name\":\"sample-boolean\",\"value\":false}]},\"entrypoint\":\"decision\",\"templates\":[{\"nam|..."
```
Follow the sensor logs to see the error

**To Reproduce**
Argo Events: 0.11
Argo: 2.4.3

**Sensor**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: "dev-staging-argo-calendar-parse-fails-calendar"
  labels:
    release: dev-staging-argo-calendar-parse-fails
    app: argo-event-workflow
    argo-events-sensor-version: v0.11
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  dependencies:
    - name: "dev-staging-argo-calendar-parse-fails-calendar:calendar"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  template:
    metadata:
      name: "dev-staging-argo-calendar-parse-fails-calendar-sensor"
      labels:
        release: dev-staging-argo-calendar-parse-fails
        app: argo-event-workflow
        gateway-name: "dev-staging-argo-calendar-parse-fails-calendar"
    spec:
      containers:
        - name: sensor
          image: "argoproj/sensor:v0.11"
      serviceAccountName: "argo-events"
  triggers:
    - template:
        name: calendar
        namespace: "argo"
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: calendar-parse-fails-
            spec:
              arguments:
                parameters:
                - name: sample-boolean
                  value: false
              entrypoint: decision
              templates:
              - name: decision
                steps:
                - - name: do-the-true
                    template: true-task
                    when: '{{workflow.parameters.sample-boolean}}'
                  - name: do-the-false
                    template: false-task
                    when: '!{{workflow.parameters.sample-boolean}}'
              - name: true-task
                script:
                  command:
                  - bash
                  image: debian:stretch
                  source: |
                    echo  "boolean is True. YAY!!!!"
              - name: false-task
                script:
                  command:
                  - bash
                  image: debian:stretch
                  source: |
                    echo  "boolean is False. BOOOO!!!!"

      resourceParameters:
```

**Gateway**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: "dev-staging-argo-calendar-parse-fails-calendar"
  labels:
    release: dev-staging-argo-calendar-parse-fails
    app: argo-event-workflow
    argo-events-gateway-version: v0.11
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
spec:
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  eventSource: "dev-staging-argo-calendar-parse-fails-calendar-event-source"
  processorPort: "9330"
  template:
    metadata:
      name: "dev-staging-argo-calendar-parse-fails-calendar-gateway"
      labels:
        release: dev-staging-argo-calendar-parse-fails
        app: argo-event-workflow
        gateway-name: "dev-staging-argo-calendar-parse-fails-calendar"
    spec:
      containers:
        - name: calendar-gateway
          image: "argoproj/calendar-gateway:v0.11"
          command: ["/bin/calendar-gateway"]
        - name: gateway-client
          image: "argoproj/gateway-client:v0.11"
          command: ["/bin/gateway-client"]
      serviceAccountName: "argo-events"
  type: calendar
  watchers:
    sensors:
      - name: "dev-staging-argo-calendar-parse-fails-calendar"
```

**ConfigMap**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "dev-staging-argo-calendar-parse-fails-calendar-event-source"
  labels:
    release: dev-staging-argo-calendar-parse-fails
    app: argo-event-workflow
    argo-events-event-source-version: v0.11
    gateway-name: "dev-staging-argo-calendar-parse-fails-calendar"
data:
  calendar: |-
    schedule: "* * * * *"
```

**Expected behavior**
The Sensor should be able to parse valid yaml.

**Screenshots**

**Environment (please complete the following information):**
- Argo 2.4.3
- Argo Events 0.11
