### ISSUE TITLE
More concise way of using circuit and switch with OR operation

### ISSUE THREAD

**Issue by lennon310** [argoproj/argo-events#469]
I was following the example of circuit and switch [here](https://github.com/argoproj/argo-events/blob/master/examples/tutorials/06-circuit-and-switches/sensor-01.yaml) and it works.

However, I was wondering if it's necessary to have several templates if the process are all the same except the specific parameter.

I was trying to write this way:

```

- template:
        switch:
           any:
            - group_1
            - group_2
        ......
  resoureParameters
     - src:
            event: "calendar-gateway:event1"
               path: "userPayload"
            dest: spec.arguments.parameters.0.value
     - src:
            event: "calendar-gateway:event2"
               path: "userPayload"
            dest: spec.arguments.parameters.0.value
```

where `event1` refers to `group_1` and `event2` refers to `group_2`. Event source looks like this:

```
data:
  group_1: |-
    schedule: "0 17 * * *"
    userPayload: "payload1"
  group_2: |-
    schedule: "0 17 * * *"
    userPayload: "payload2"
```

However it seems like `spec.arguments.parameters.0.value` in event1 was overridden by the value in event2. Is there a way that each group is using its own payload when it is triggered?
