### ISSUE TITLE
SNS TLS handshake error

### ISSUE THREAD

**Issue by nfickas** [argoproj/argo-events#472]
**Describe the bug**
A TLS handshake error occurs when running the SNS example.

**To Reproduce**
sns-gateway.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: aws-sns-gateway
  labels:
    # gateway controller with instanceId "argo-events" will process this gateway
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
spec:
  type: sns
  eventSourceRef:
    name: sns-event-source
  template:
    metadata:
      name: aws-sns-gateway
      labels:
        gateway-name: aws-sns-gateway
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: gateway-secret
      containers:
        - name: gateway-client
          image: argoproj/gateway-client:v0.12
          volumeMounts:
          - mountPath: /etc/nginx/ssl
            name: secret-volume
          imagePullPolicy: Always
          command: ["/bin/gateway-client"]
        - name: aws-sns-events
          image: argoproj/aws-sns-gateway:v0.12
          volumeMounts:
          - mountPath: /etc/nginx/ssl
            name: secret-volume
          imagePullPolicy: Always
          command: ["/bin/aws-sns-gateway"]
      serviceAccountName: argo-events-sa
  service:
    metadata:
      name: aws-sns-gateway-svc
    spec:
      selector:
        gateway-name: aws-sns-gateway
      ports:
        - port: 443
          targetPort: 12000
      type: LoadBalancer
  subscribers:
    http:
      - "https://aws-sns-sensor.argo-events.svc:9300/"
```

sns event source
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: sns-event-source
spec:
  type: "sns"
  sns:
    example:
      namespace: argo-events
      example:
      region: "us-east-1"
      topicArn: MY_TOPIC_ARN
      webhook:
        endpoint: "/"
        # gateway can run multiple HTTP servers, just define a unique port.
        port: "12000"
        url: "https://aws-sns-gateway-svc.argo-events.svc"
        # path to file that is mounted in gateway pod which contains certs
        serverCertPath: "/etc/nginx/ssl/tls.crt"
        # path to file that is mounted in gateway pod which contains private key
        serverKeyPath: "/etc/nginx/ssl/tls.key"
      accessKey:
        name: SECRET_NAME
        key: access_key_id
      secretKey:
        name: SECRET_NAME
        key: secret_access_key
```

SNS sensor
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sns-sensor
  labels:
    # sensor controller with instanceId "argo-events" will process this sensor
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: gateway-secret
      containers:
        - name: sensor
          image: argoproj/sensor:v0.12
          volumeMounts:
          - mountPath: /etc/nginx/ssl
            name: secret-volume
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  subscription:
    http:
      port: 9300
  dependencies:
    - name: test-dep
      gatewayName: aws-sns-gateway
      eventName: example
  triggers:
    - template:
        name: sns-workflow
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: aws-sns-worfklow-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # value will be overridden by the event payload
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.arguments.parameters.0.value
```

**Expected behavior**
Argo Events to run a workflow when a SNS message is received.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**
