### ISSUE TITLE
Dependency handling via same gateway

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-events#478]
Argo-events v0.11.
Running test for RabbitMQ, and would like to trigger the same workflow (sensor) via 2 different incoming events (either event1 or event 2 should trigger, not and) via the same AMQP Gateway. Trying dependency group and circuit, but can't get it to work. 
```
 dependencies:
    - name: "amqp-gateway:ci"
      filters:
        name: "data-filter"
        data:
          - path: meta.type
            type: string
            value:
              - "EiffelSourceChangeSubmittedEvent" 
          - path: data.gitIdentifier.repoName
            type: string
            value:
              - "GERRITREPONAME_SED"         
    - name: "amqp-gateway:ci"
      filters:
        name: "data-filter"
        data:
          - path: meta.type
            type: string
            value:
              - "EiffelSourceChangeCreatedEvent" 
          - path: data.gitIdentifier.repoName
            type: string
            value:
              - "GERRITREPONAME_SED"                            
  dependencyGroups:
    - name: "group_1"
      dependencies:
        - "amqp-gateway:ci"
  circuit: "group_1"         
  triggers:
    - template:
        when:
          any:
            - "group_1"   
        name: argo-workflow
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        source:
          inline: |
...
```
Workaround using amqp-gateway:ci & amqp-gateway:c2, then issue with resourceParameters for ci & c2, see below!

```
 dependencies:
    - name: "amqp-gateway:ci2"
      filters:
        name: "data-filter"
        data:
          - path: meta.type
            type: string
            value:
              - "EiffelSourceChangeSubmittedEvent" 
          - path: data.gitIdentifier.repoName
            type: string
            value:
              - "GERRITREPONAME_SED"         
    - name: "amqp-gateway:ci"
      filters:
        name: "data-filter"
        data:
          - path: meta.type
            type: string
            value:
              - "EiffelSourceChangeCreatedEvent" 
          - path: data.gitIdentifier.repoName
            type: string
            value:
              - "GERRITREPONAME_SED"                            
  dependencyGroups:
    - name: "group_1"
      dependencies:
        - "amqp-gateway:ci"
    - name: "group_2"
      dependencies:
        - "amqp-gateway:ci2"        
  circuit: "group_1 || group_2"         
  triggers:
    - template:
        when:
          any:
            - "group_1"   
            - "group_2"

```
How to handle resourceParameters for amqp-gateway:ci & amqp-gateway:ci2 when using circuit/dependencygroups ?  The below generates error. tried with :* and also without :ci & :c2. neither works!

```
resourceParameters:
        - src:      
            event: "amqp-gateway:ci"
            path: data.customData.3.value                    
            value: No Event (patchSet.ref) data.customData.3.value In PayLoad
          dest: spec.arguments.parameters.0.value
        - src:      
            event: "amqp-gateway:ci2"
            path: data.customData.3.value                    
            value: No Event (patchSet.ref) data.customData.3.value In PayLoad
          dest: spec.arguments.parameters.0.value
```

**Comment by emichaf** [comment]
Upgradede to Argo-events v0.12 & Argo 2.4.2, but same issue. Can't trigger same workflow with 2 different incoming payloads (via data-filter) and using paramters in payload to set same   spec.arguments.parameters.X.value in workflow.


First try same amqp gateway same eventName: ci

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: circuit-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: sensor
          image: argoproj/sensor:v0.12
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: test-amqp-1
      gatewayName: amqp-gateway
      eventName: ci
    - name: test-amqp-2
      gatewayName: amqp-gateway
      eventName: ci

  # group event dependencies
  dependencyGroups:
    - name: group_1
      dependencies:
        - test-amqp-1
    - name: group_2
      dependencies:
        - test-amqp-2

  # trigger when either group_1 or group_2 resolves
  circuit: "group_1 || group_2"

  subscription:
    http:
      port: 9300
  triggers:
    - template:
        # when is the switch that determines whether to execute the trigger or not
        switch:
          # all is boolean equivalent of AND.
          # you can use `any` as well which is boolean equivalent of OR.
          all:
            - group_1
        name: workflow-trigger-1
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: group-1-
              spec:
                serviceAccountName: argo-events-sa
                entrypoint: whalesay
                templates:
                  - name: whalesay
                    container:
                      args:
                        - "hello world"
                      command:
                        - cowsay
                      image: "docker/whalesay:latest"
          parameters:
            - src:
                dependencyName: test-amqp-1
                dataKey: body
              dest: spec.templates.0.container.args.0
            - src:
                dependencyName: test-amqp-2
                dataKey: body
              dest: spec.templates.0.container.args.0              
   ```
Second try same amqp gateway 2 different eventName: ci

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: circuit-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: sensor
          image: argoproj/sensor:v0.12
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: test-amqp-1
      gatewayName: amqp-gateway
      eventName: ci
    - name: test-amqp-2
      gatewayName: amqp-gateway
      eventName: ci2

  # group event dependencies
  dependencyGroups:
    - name: group_1
      dependencies:
        - test-amqp-1
    - name: group_2
      dependencies:
        - test-amqp-2

  # trigger when either group_1 or group_2 resolves
  circuit: "group_1 || group_2"

  subscription:
    http:
      port: 9300
  triggers:
    - template:
        # when is the switch that determines whether to execute the trigger or not
        switch:
          # all is boolean equivalent of AND.
          # you can use `any` as well which is boolean equivalent of OR.
          all:
            - group_1
        name: workflow-trigger-1
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: group-1-
              spec:
                serviceAccountName: argo-events-sa
                entrypoint: whalesay
                templates:
                  - name: whalesay
                    container:
                      args:
                        - "hello world"
                      command:
                        - cowsay
                      image: "docker/whalesay:latest"
          parameters:
            - src:
                dependencyName: test-amqp-1
                dataKey: body
              dest: spec.templates.0.container.args.0
            - src:
                dependencyName: test-amqp-2
                dataKey: body
              dest: spec.templates.0.container.args.0              
   ```

**Comment by emichaf** [comment]
Went for the solution of filtering (data-filter) for 2 different identifiers, and then aligning incoming data fields (payload) for usage in parameters section.


```
  dependencies:    
    - name: test-amqp-1
      gatewayName: amqp-gateway
      eventName: ci
      filters:
        name: data-filter
        data:
          - path: meta.type
            type: string
            value:
              - "Eventx"         <---- Eventx or Eventy will trigger same pipeline
              - "Eventy"              
          - path: data.gitIdentifier.repoName
            type: string
            value:
              - "GERRITREPONAME_SED"

..

 parameters:
            - src:
                dependencyName: test-amqp-1
                dataKey: meta.id     <------ key required in both Event x & y payload
              dest: spec.arguments.parameters.0.value


```
