### ISSUE TITLE
Webhook JSON payload not working v0.12

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-events#479]
Upgrading to Argo 2.4.3 and Argo-events v0.12.

Using webhook setup with incoming JSON payload fetched in sensors via :

in v0.11 via
```
      resourceParameters:
        - src:
            event: "webhook-gateway-http:mschassissamplesgenerateeiffelevent"
          dest: spec.arguments.parameters.0.value
```
and in v0.12 via
```
          parameters:   
            - src:
                dependencyName: webhook-gateway-http-mschassissamplesgenerateeiffelevent
              dest: spec.arguments.parameters.0.value
```
but now my payload is not JSON anymore, but more like a bin in a json "data" key field! 
what changed from v0.11 to v0.12 ?

```
{'context': {'type': 'webhook', 'specVersion': '0.3', 'source': 'webhook-gateway-http', 'id': '31353965613332642d636161642d343938652d626535622d373534666639326334613239', 'time': '2020-
01-31T15:00:05.504247Z', 'dataContentType': 'application/json', 'subject': 'mschassissamplesgenerateeiffelevent'}, 'data': 'eyJoZWFkZXIiOnsiQWNjZXB0LUVuY29kaW5nIjpbImd6aXAsZGVmbGF0ZSJd
LCJDb25uZWN0aW9uIjpbIktlZXAtQWxpdmUiXSwiQ29udGVudC1MZW5ndGgiOlsiMTA2MCJdLCJDb250ZW50LVR5cGUiOlsiYXBwbGljYXRpb24vanNvbjsgY2hhcnNldD11dGYtOCJdLCJVc2VyLUFnZW50IjpbIkFwYWNoZS1IdHRwQ2xpZW50
LzQuNC4xIChKYXZhLzEuOC4wXzIxMikiXSwiWC1PcmlnaW4tVXJsIjpbImh0dHA6Ly9jeC1nZXJyaXQtZWlmZmVsMi50b2RkMDA0LnJuZC5naWMuZXJpY3Nzb24uc2UvIl19LCJib2R5Ijp7InVwbG9hZGVyIjp7Im5hbWUiOiJFYXN5IFVzZSIs
ImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImVhc3kydXNlIn0sInBhdGNoU2V0Ijp7Im51bWJlciI6MSwicmV2aXNpb24iOiI3MDJkZjU5YjU3OGQ5NTFhNmM1ZjcwMjg3M2NmMWJhNDdhZWU0ZmI5IiwicGFyZW50cyI6
WyIxOTQyMjFiMzFlNDZiY2FlNWNkNzk0NzJkYWEyYzI4MmYzZWVkYzU4Il0sInJlZiI6InJlZnMvY2hhbmdlcy8wNC8xMDQvMSIsInVwbG9hZGVyIjp7Im5hbWUiOiJFYXN5IFVzZSIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJ1c2Vy
bmFtZSI6ImVhc3kydXNlIn0sImNyZWF0ZWRPbiI6MTU4MDQ4MjgwNSwiYXV0aG9yIjp7Im5hbWUiOiJFYXN5IFVzZSIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImVhc3kydXNlIn0sImlzRHJhZnQiOmZhbHNlLCJr
aW5kIjoiUkVXT1JLIiwic2l6ZUluc2VydGlvbnMiOjIsInNpemVEZWxldGlvbnMiOi00MDZ9LCJjaGFuZ2UiOnsicHJvamVjdCI6InppcHBlci1tc2NoYXNzaXMtc2FtcGxlLXNlcnZpY2VzIiwiYnJhbmNoIjoibWFzdGVyIiwiaWQiOiJJNmEx
YzhlOTUxYTg0ZThjZGE2ODFkMTJjZmVmZDY2MzMxYWQ3MzJhNSIsIm51bWJlciI6MTA0LCJzdWJqZWN0IjoiMzAwMCIsIm93bmVyIjp7Im5hbWUiOiJFYXN5IFVzZSIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImVh
c3kydXNlIn0sInVybCI6Imh0dHA6Ly9jeC1nZXJyaXQtZWlmZmVsMi50b2RkMDA0LnJuZC5naWMuZXJpY3Nzb24uc2UvMTA0IiwiY29tbWl0TWVzc2FnZSI6IjMwMDBcbiIsImNyZWF0ZWRPbiI6MTU4MDQ4MjgwNSwic3RhdHVzIjoiTkVXIn0s
InByb2plY3QiOnsibmFtZSI6InppcHBlci1tc2NoYXNzaXMtc2FtcGxlLXNlcnZpY2VzIn0sInJlZk5hbWUiOiJyZWZzL2hlYWRzL21hc3RlciIsImNoYW5nZUtleSI6eyJpZCI6Ikk2YTFjOGU5NTFhODRlOGNkYTY4MWQxMmNmZWZkNjYzMzFh
ZDczMmE1In0sInR5cGUiOiJwYXRjaHNldC1jcmVhdGVkIiwiZXZlbnRDcmVhdGVkT24iOjE1ODA0ODI4MDV9fQ=='}
```
