### ISSUE TITLE
s3.object.key in minio sensor example does not resolve correctly

### ISSUE THREAD

**Issue by nmandery** [argoproj/argo-events#481]
The current minio sensor example (examples/sensors/minio.yaml) does not pass the s3 object key to the container. Instead a JSON string in the form of

```
{"context":{"type":"minio","specVersion":"0.3","source":"minio-gateway","id":"....8","time":"2020-02-065T16:53:24.16
3752Z","dataContentType":"application/json","subject":"in-event"},"data"...."}
```

ends up as the containers argument.

What works is replacing `path` with `dataKey`:

```
          # The container args from the workflow are overridden by the s3 notification key
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: s3.object.key
              dest: spec.templates.0.container.args.0
```

The documentaion also does not mention the `path` option.
