### ISSUE TITLE
Allow for comparators in data filters

### ISSUE THREAD

**Issue by nfickas** [argoproj/argo-events#487]
**Is your feature request related to a problem? Please describe.**
From the documentation here: https://argoproj.github.io/argo-events/tutorials/07-filters/. We have to use exact values when filtering on a bool or float data type. I would like the ability to use comparators to filter on my data values being passed in.

**Describe the solution you'd like**

```
dependencies:
    - name: test-dep
      gatewayName: webhook-gateway
      eventName: example
      filters:
        name: data-filter
        data:
          - path: body.value
            type: float
            comparator: '>'
            value: 
             - 50.0 
```

**Describe alternatives you've considered**

**Additional context**
