### ISSUE TITLE
Event source for resource gateway firing for wrong event types

### ISSUE THREAD

**Issue by monsiper** [argoproj/argo-events#495]
We are trying to set up a resource trigger that will respond to node deletion in Kubernetes. After setting up the required RBAC settings, we modified the example event source snippet to achieve our purpose. Below is the snippet we added to the example event-source manifest:
```
spec:
  type: resource
  resource:
    node-delete:
      group: ""
      version: v1
      resource: nodes
      eventType: DELETE
      filter:
        prefix: mehmet
```
Such an event source keeps firing even for non-deletion events, such as periodic updates of node metadata.

Note that we tried both `type` and `eventType` fields to restrict the trigger to DELETE events but couldn't get anywhere. In all cases, when we check out resource-gateway logs, we see the following message every minute, even though we do not make any attempts to delete a node. 
```
WARN[2020-02-17 21:13:12] failed to apply the filter  error="resource name does not match prefix. resource-name: ip-172-33-149-250.us-west-2.compute.internal, prefix: mehmet" event-source=node-delete
```
These messages coincide with periodic updates to node metadata by the Kubelet, which are apparently picked up even though they shouldn't -- they are not DELETE events after all.

Any suggestions on what could be the cause of this behavior? Thanks!
