### ISSUE TITLE
Reference a workflow in a sensor.yaml

### ISSUE THREAD

**Issue by aleeshadawson** [argoproj/argo-events#502]
**Is your feature request related to a problem? Please describe.**
I have found no documentation on how to reference a workflow within a `sensor.yaml`. For example, a `gateway.yaml` can reference an event-source as follows:

```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: kafka-gateway
  labels:
    # gateway controller with instanceId "argo-events" will process this gateway
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
spec:
  replica: 1
  type: kafka
  eventSourceRef:
    name: kafka-event-source
...
```
Can we do this for sensors as well?

**Describe the solution you'd like**

Is it possible to do somewhere in a sensor configuration already? That is, rather than putting an entire workflow in the yaml, can we house it elsewhere and reference in `spec.triggers.template.k8s.source.resource`? Perhaps as `resourceRef`? If this is not yet possible, I think it would be a good addition.
