### ISSUE TITLE
data.body from redis and aws-sqs are different: sqs data.body base64 encoded

### ISSUE THREAD

**Issue by miyanaga** [argoproj/argo-events#520]
**Describe the bug**
A sensor receives raw payload from redis gateway but base64 encoded from aws-sqs gateway.

**To Reproduce**
1. Create a sensor like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: the-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: sensor
          image: argoproj/sensor:v0.13.0-rc
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  subscription:
    http:
      port: 9300
  dependencies:
    - name: test-dep
      gatewayName: the-gateway
      eventName: example
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: event-job-
                namespace: default
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: message
                      value: hello world
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
```

If the-gateway is redis and publish like this:
```
PUBLISH the_channel "hello from redis"
```
cowsay: "hello from redis"

But the-gateway is aws-sqs and send message like this:
```
aws sqs send-message --queue-url="https://queue-url" --message-body="hello from sqs"
```
cawsay: "aGVsbG8gZnJvbSBzcXM="

"aGVsbG8gZnJvbSBzcXM=" is base64 encoded "hello from sqs"

**Expected behavior**
I think the body should not to be encoded.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: v0.13.0-rc
