### ISSUE TITLE
Support go templating for trigger parameters

### ISSUE THREAD

**Issue by tinyzimmer** [argoproj/argo-events#541]
**Is your feature request related to a problem? Please describe.**

I'm toying with the idea of using `argo-events` and `argo-workflows` for CI. However, with many developers utilizing the console, I would need a clear and concise way for them to see which workflows are theirs. When using the github event hook, some key payload parameters contain special characters (/) that cannot be used inside names or labels of workflow objects. This sucks because it'd be awesome if the developer could view jobs by a label containing the ref of the branch that's building.

**Describe the solution you'd like**

I'd like to be able to optionally pass the event/context payloads through a go template (with sprig functions) before inserting them into the workflow yaml definition. In what I've tried locally the trigger definition becomes like this (`contextTemplate` is also implemented):

```yaml
  dependencies:
    - name: event-payload
      gatewayName: github-gateway
      eventName: my-repo
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: my-repo-
                labels:
                  ref:
                  commitSHA:
              spec:
                entrypoint: cicd
                arguments:
                  parameters:
                  - name: payload
                templates:
                - name: cicd
                  steps:
                  - - name: run-cicd
                      templateRef:
                        name: cicd-workflow-templates
                        template: cicd-template
                      arguments:
                        parameters:
                          # ...
          parameters:
            - src:
                dependencyName: event-payload
                dataKey: head_commit.id
              dest: metadata.labels.commitSHA
            - src:
                dependencyName: event-payload
                dataTemplate: '{{ .Event.ref | replace "/" "-" }}'
              dest: metadata.labels.ref
            - src:
                dependencyName: event-payload
                dataTemplate: '{{ .Event.ref | replace "refs/heads/" "" | replace "/" "-" }}-{{ trunc 7 .Event.head_commit.id }}-'
              dest: metadata.generateName
              operation: append
```

**Describe alternatives you've considered**

Not a whole lot at the moment. Other than perhaps building a custom container that does formatting on the incoming event before passing it to the gateways/sensors. 

**Additional context**

I've implemented this on a local copy of the code, and can open a PR for further discussion if we want.
