### ISSUE TITLE
Installing Webhook Sensor in a helm chart causes an error

### ISSUE THREAD

**Issue by cristianoveiga** [argoproj/argo-events#562]
Hi,

I'm trying to pack my sensors in a helm chart, but I am getting an error during the chart installation:

Error: UPGRADE FAILED: parse error in "argo-apps/templates/webhook.yaml": template: argo-apps/templates/webhook.yaml:52: function "inputs" not defined

I am using the example described [here](https://github.com/argoproj/argo-events/blob/master/examples/sensors/webhook.yaml).

The error happens due to the line: args: ["{{inputs.parameters.message}}"]. It seems that helm is trying to parse "inputs" as a function, since both of them use Go Templates.

Does anyone know how to go around it?

Any help is appreciated.

Thanks,

Cristiano

**Comment by VaibhavPage** [comment]
As a tactical solution,  instead of using the `input.parameters`, you can opt-in for container args, e.g.,


```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: file-sensor
  labels:
    # sensor controller with instanceId "argo-events" will process this sensor
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: sensor
          image: argoproj/sensor:v0.13.0
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      gatewayName: file-gateway
      eventName: example
  subscription:
    http:
      port: 9300
  triggers:
    - template:
        name: file-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: file-watcher-
              spec:
                entrypoint: whalesay
                templates:
                  -
                    container:
                      args:
                        - "hello" # it will get replaced by the event payload
                      command:
                        - cowsay
                      image: "docker/whalesay:latest"
                    name: whalesay
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.templates.0.container.args.0

```
