### ISSUE TITLE
Multiple Dependencies and Triggers for Calendar Sensor

### ISSUE THREAD

**Issue by pixalynx** [argoproj/argo-events#577]
**Is your feature request related to a problem? Please describe.**
I cannot find any guide/tutorial on how to implement a calendar sensor with multiple dependencies and triggers.

**Describe the solution you'd like**
We want to have one single calendar sensor that listens to multiple calendar events and based on that event we want a specific workflow to trigger that is relevant to the event. Currently while attempting this by having

```yaml
dependencies:
    - name: sales-toolkit-dep
      gatewayName: calendar-gateway
      eventName: sales-toolkit
    - name: courtsync-billing-dep
      gatewayName: calendar-gateway
      eventName: court-sync-billing
```

it requires all dependencies to be met before triggering any workflow templates.

I've looked on the website and noticed that there is circuits which I tried implementing but that doesn't appear to be working. Is there any solution for this?``
