### ISSUE TITLE
Triggers inside a Sensor.yml to be broken down into seperate files

### ISSUE THREAD

**Issue by pixalynx** [argoproj/argo-events#578]
**Is your feature request related to a problem? Please describe.**
Breakdown triggers within a sensor to separate files. I am not sure if I can find any guides/examples to be able to do this inside argo.

**Describe the solution you'd like**
I would like break be able to breakdown the templates that are inside the trigger section in a sensor.

For example  :

```yaml
subscription:
    http:
      port: 9300
  triggers:
    - template:
        switch:
          all:
            - salestoolkit
        name: calendar-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: calendar-workflow-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: message
                      # value will get overridden by the event payload
                      value: hello world
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
```

I want to be able to populate the data inside

```yaml
templates:
                  - name: whalesay
```
from another file, so I can easily separate all my templates into its own individual workflow.

Is there any guide on how to do this?

**Comment by VaibhavPage** [comment]
You can use `workflowTemplate` to separate out templates from workflow definition https://github.com/argoproj/argo/blob/master/examples/workflow-template/hello-world.yaml. And, you can store the workflow artifact on Git, S3, etc and refer it in the sensor https://argoproj.github.io/argo-events/tutorials/03-trigger-sources/

**Comment by pixalynx** [comment]
Ok thank you so much this makes a lot of sense now. I just have another question to see if this is possible. Looking at the trigger sources link you sent, the best option for me would probably be the config-map as we want to keep everything inside kubernetes.

However my calendar event looks like this :

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: calendar-event-source
  namespace: data-tools
spec:
  type: "calendar"
  calendar:
    # example-with-interval:
    #   # creates an event every 10 seconds
    #   # interval: "30s"
    #   # interval: "15m"
    #   schedule: 16 2 * * *
    sales-toolkit:
      schedule: 15 23 * * *
    court-sync-billing:
      schedule: 25 23 * * *
```

And it is being referenced in my Calendar Sensor as : 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: calendar-sensor
  namespace: data-tools
  labels:
    # sensor controller with instanceId "argo-events" will process this sensor
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: sensor
          image: argoproj/sensor:v0.13.0
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: sales-toolkit-dep
      gatewayName: calendar-gateway
      eventName: sales-toolkit
    - name: courtsync-billing-dep
      gatewayName: calendar-gateway
      eventName: court-sync-billing
```

and my calendarGateway is
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: calendar-gateway
  namespace: data-tools
  labels:
    # gateway controller with instanceId "argo-events" will process this gateway
    gateways.argoproj.io/gateway-controller-instanceid: argo-events
spec:
  type: calendar
  eventSourceRef:
    name: calendar-event-source
  template:
    metadata:
      name: calendar-gateway
      namespace: data-tools
      labels:
        gateway-name: calendar-gateway
    spec:
      containers:
        - name: gateway-client
          image: argoproj/gateway-client:v0.12.1
          imagePullPolicy: Always
          command: ["/bin/gateway-client"]
        - name: calendar-events
          image: argoproj/calendar-gateway:v0.12.1
          imagePullPolicy: Always
          command: ["/bin/calendar-gateway"]
      serviceAccountName: argo-events-sa
  # service:
  #   metadata:
  #     name: calendar-gateway-svc
  #     namespace: data-tools
  #   spec:
  #     selector:
  #       gateway-name: calendar-gateway
  #     ports:
  #       - port: 12000
  #         targetPort: 12000
  #     type: ClusterIP
  subscribers:
    http:
      - "http://calendar-sensor.data-tools.svc:9300/"
```
That being said it looks like the calendar-gateway is referencing the calendar-event-source via : 
```yaml
spec:
  type: calendar
  eventSourceRef:
    name: calendar-event-source
```

As you can see its not using a configmap in this case and everything is within K8's.

Would the above be possible to do with templates? without creating configmaps but referencing based on the "kind" and "name" of the k8 resource?

**Comment by atombender** [comment]
@VaibhavPage Piggybacking on this issue: Can the sensor reference a `WorkflowTemplate` directly?

From what I can tell, the sensor has to embed a `Workflow` that contains steps that then uses `templateRef` to reference another `WorkflowTemplate` that exists in the cluster. Seems a bit unnecessary complicated? Especially as it needs to repeat the parameters from the event source that will already be declared in the referenced workflow template.

I was hoping I could do something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: my-sensor
spec:
  dependencies:
  - ...

  triggers:
  - template:
      name: my-trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit

        parameters:
        - ...

        source:
          resourceRef:
            workflowTemplate: my-workflow-template
```
