### ISSUE TITLE
Sprig Functions don't work on dataKey or contextKey

### ISSUE THREAD

**Issue by ericmeadows** [argoproj/argo-events#588]
**Is your feature request related to a problem? Please describe.**
Input Type:  GitHub webhook
Content-type: application/json

I am trying to extract substrings from inputs to make searching via labels easier; for example I am trying to get the branch name, standardize it, and use it as a metadata label.  The same can be said for extracting the Git Commit short hash.

**Describe the solution you'd like**
dataKey can use Spring functions.
e.g.
```
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.head_commit.id | substr 0 7
              dest: metadata.labels.commit-id
```

**Describe alternatives you've considered**
There aren't any other options.

**Additional context**

**Comment by ericmeadows** [comment]
For example:
```
          parameters:
            - src:
                dependencyName: test-dep
                dataTemplate: "{{ body.head_commit.id | substr 0 7 }}"
              dest: metadata.labels.commit-id
```
Does not work, nor removing the leading and trailing spaces from the Sprig template.
