### ISSUE TITLE
Set nested JSON properties in sensor payload JSON object

### ISSUE THREAD

**Issue by hobti01** [argoproj/argo-events#597]
**Is your feature request related to a problem? Please describe.**
I would like to construct a complete JSON object in the sensor payload, not only an object of name/value pairs.  Almost handled in #333 but that's a slightly different use case to set the payload from objects provided in the input.  In this case the object I want to set in the payload does not exist in the input.

**Describe the solution you'd like**
I would like to set the payload using sjson syntax (as now) but have the resulting payload be a serialized JSON object instead of an object of name/value pairs.

**Describe alternatives you've considered**
* using existing code, but name/value pairs do not meet my needs
* setting JSON from a templated field, but it still results in a string value, not a nested value
* writing a function or service external to argo events - but seems like overkill for a small transformation

**Comment by marcstreeter** [comment]
@hobti01 would you clarify usage of this nested json object?  I am trying to access a nested object value using `withParam` but am only able to go as deep as the value. Here's an example of the content output, `deets`, by the preceding task, `some-workflow`:


where `drop-details` is a list of nested objects

```
[
        {
            "spam": {
                "foo": "blue",
                "bar": [
                    "thing1",
                    "thing2",
                ],
                "baz": [
                    "something",
                    "something2,
                    "something3,
                ]
            },
            "eggs": {
                "beans": "black",
                "size": {
                    "measure": 15600,
                    "unit": "bytes",
                },
                "time": "10:00am",
                "format": "purple",
            },
        },
    ]
    ```


```
                  - name: another-workflow
                    template: another-workflow-template
                    dependencies: [some-workflow]
                    arguments:
                      parameters:
                      - name: spam
                        value: "{{item.spam}}"
                      - name: eggs
                        value: "{{item.eggs}}"
                    withParam: "{{tasks.some-workflow.outputs.parameters.deets}}"
```

here's what does not work, but I wish it did
```
                  - name: another-workflow
                    template: another-workflow-template
                    dependencies: [some-workflow]
                    arguments:
                      parameters:
                      - name: foo
                        value: "{{item.spam.foo}}"
                      - name: bar
                        value: "{{item.spam.bar}}"
                      - name: size
                        value: "{{item.eggs.size.measure}}"
                    withParam: "{{tasks.some-workflow.outputs.parameters.deets}}"
```

**Comment by hobti01** [comment]
hi @marcstreeter , we're not actively using this (and it has been a while since I looked into this code).  This issue and merged fix allows creating a nested JSON object in the trigger payload so that the payload could be created with:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
spec:
  triggers:
    - policy:
        status:
          allow:
            - 200
      template:
        http:
          method: POST
          payload:
            - dest: nameValue
              src:
                dependencyName: doesNotMatter
                value: value1
            - dest: arrayProperty.0.firstArrayItem
              src:
                dependencyName: doesNotMatter
                value: value2
```
to result in a payload of
```
{
  "nameValue": "value1",
  "arrayProperty": [
    "firstArrayItem": "value2"
  ]
}
```
It seems to me that you're dealing with the ability for Workflow to read members of the array, so I'm not sure that it's related.

I'm not an expert, but perhaps you can reference by array position?
```
                  - name: another-workflow
                    template: another-workflow-template
                    dependencies: [some-workflow]
                    arguments:
                      parameters:
                      - name: foo
                        value: "{{item.0.spam.foo}}"
                      - name: bar
                        value: "{{item.0.spam.bar}}"
                      - name: size
                        value: "{{item.0.eggs.size.measure}}"
                    withParam: "{{tasks.some-workflow.outputs.parameters.deets}}"
```
