### ISSUE TITLE
Failed to list *v1alpha1.Sensor: the server could not find the requested ressource (get sensors.argoproj.io)

### ISSUE THREAD

**Issue by DrissiReda** [argoproj/argo-events#626]
I deployed argo and argo events, the only difference is that my CRDs are cluster scoped instead of namespace scoped. I get this output in all of the pods:

sensor-controller: 
```
E0428 09:32:20.361028       1 reflector.go:125] github.com/argoproj/argo-events/controllers/sensor/controller.go:169: Failed to list *v1alpha1.Sensor: the server could not find the requested resource (get sensors.argoproj.io)
```
gateway-controller:
```
E0428 09:32:54.592437       1 reflector.go:125] github.com/argoproj/argo-events/controllers/gateway/controller.go:172: Failed to list *v1alpha1.Gateway: the server could not find the requested resource (get gateways.argoproj.io)
```

workflow-controller
```
E0428 09:33:30.564819       1 reflector.go:126] github.com/argoproj/argo/workflow/ttlcontroller/ttlcontroller.go:75: Failed to list *unstructured.Unstructured: the server could not find the requested resource
```

My CRD manifests:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    singular: gateway
    shortNames:
      - gw
  scope: Cluster
  version: "v1alpha1"
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sensors.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: Sensor
    listKind: SensorList
    plural: sensors
    singular: sensor
    shortNames:
      - sn
  scope: Cluster
  version: "v1alpha1"
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventsources.argoproj.io
spec:
  group: argoproj.io
  scope: Cluster
  names:
    kind: EventSource
    plural: eventsources
    singular: eventsource
    listKind: EventSourceList
    shortNames:
      - es
  version: "v1alpha1"

```

argo version: 2.4.3
gateway/sensor controller versions: 0.12

I plan on catching argo events from different namespaces so I also added roles and role bindings for each of those namespaces and linked them all to the same service account that's inside the same namespace where argo is deployed. What am I doing wrong?
