### ISSUE TITLE
Combine EventSource and Gateway CRD

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#628]
**Is your feature request related to a problem? Please describe.**
After simplifying Gateway spec and introducing EventBus to the picture, a simple Gateway spec will look like below, which only contains `type` and `eventSourceRef`.

```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: webhook-gateway
spec:
  type: webhook
  eventSourceRef:
    name: webhook-event-source
```

**Describe the solution you'd like**
A Combined EventSource and Gateway CRD looks better.

**Describe alternatives you've considered**

**Additional context**
