### ISSUE TITLE
Deleting a deployment

### ISSUE THREAD

**Issue by lueenavarro** [argoproj/argo-events#638]
So i was a able to create a deployment using argo-events, but I could not find any example on how to delete a deployment and if it is even possible. Do you have examples? I believe I just have to add a few lines on the yaml config below but I do not know what to add. 

Lets say what if I want to delete `example-deployment` in the `default` namespace

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor-http
spec:
  template:
    spec:
      containers:
        - name: sensor
          image: argoproj/sensor:v0.13.0
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      gatewayName: webhook-gateway
      eventName: example
  subscription:
    http:
      port: 9300
  triggers:
    - template:
        name: webhook-deployment-trigger
        k8s:
          group: apps
          version: v1
          resource: deployments
          operation: delete
```
