### ISSUE TITLE
Not able to give Annotation on Gateway deployment

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#668]
**Describe the bug**
In v0.15.0, annotation can not be given on gateway deployment with the new spec, this blocks the use cases like using `kiam` or `kube2iam` for `sqs` events.

**Expected behavior**
Following spec should be supported.

```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: aws-sqs
spec:
  type: sqs
  eventSourceRef:
    name: aws-sqs-event-source
  template:
    serviceAccountName: argo-events-sa
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::xxxxxx:role-name
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**
