### ISSUE TITLE
DAG tasks outputs result

### ISSUE THREAD

**Issue by elocke** [argoproj/argo-events#673]
I have a sensor that triggers a git-based workflow. It's nested a few templates deep but I included the relevant sections below. I am on argo-events v0.15.0 and argo v2.8

My error: `Failed to submit workflow: templates.t.tasks.t templates.process.tasks.create failed to resolve {{tasks.get-version.outputs.result}}`

From what I gather, this is a new feature in argo v2.8. does this project stay relatively in sync with the latest version of argo?

I was able to work around the issue by changing spec.triggers.template.argoWorkflow to ...k8s to create a generic resource

relevant sensor:
```
  triggers:
    - template:
        name: gcp-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            git:
              url: "git@github.com:org/repo.git"
              cloneDirectory: "/git/git"
              sshKeyPath: "/secret/sshkey"
              namespace: workflows
              filePath: "dag.yaml"
              branch: "master"
```

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: thing
spec:
  arguments:
    parameters:
    - name: p
      value: default
    - name: a
      value: default
  templates:
  - name: process
    dag:
      failfast: true
      tasks:
      - name: get-version
        templateRef:
          name: template-t
          template: get-version
        arguments:
          parameters:
          - name: xxx
            value: "{{workflow.parameters.p}}"
      - name: build-jobs
        templateRef:
          name: template-d
          template: gen-cmds
        dependencies: [get-version]
        arguments:
          parameters:
          - name: p
            value: "{{workflow.parameters.p}}"
          - name: a
            value: "{{workflow.parameters.a}}"
      - name: create
        dependencies: [build-jobs]
        templateRef:
          name: template-d
          template: create
        withParam: "{{tasks.build-jobs.outputs.result}}"
        arguments:
          parameters:
          - name: z
            value: "{{item.z}}"
```
