### ISSUE TITLE
failed to save outputs: Failed to establish pod watch: unknown (get pods)

### ISSUE THREAD

**Issue by jrinvictus** [argoproj/argo-events#705]
I'm running a webhook event, the task runs successfully but I keep getting this error when I run it. 

```failed to save outputs: Failed to establish pod watch: unknown (get pods)```

My runs are also not showing when I submit argo list, I have to look at the argo-event pods

```kubectl get pods -n argo-events```

Yaml
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-event-source
spec:
  type: webhook
  webhook:
    # gateway can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    example:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /example
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST
```
```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: webhook
spec:
  replica: 1
  type: webhook
  eventSourceRef:
    name: webhook-event-source
  template:
    serviceAccountName: argo-events-sa
  service:
    ports:
      - port: 12000
        targetPort: 12000
  subscribers:
    http:
      - "http://webhook-sensor.argo-events.svc:9300/"
```
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      gatewayName: webhook
      eventName: example
  subscription:
    http:
      port: 9300
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: data-transform-encoder-
              spec:
                entrypoint: encoder
                templates:
                - name: encoder
                  dag:
                    # failFast: false
                    tasks:
                    - name: transform-encoder
                      template: transform-encoder
                      
                - name: transform-encoder
                  inputs:
                    parameters:
                    - name: schema_uri
                      value: "transform_schema.txt"
                  container:
                    image: transform-encoder:latest
                    imagePullPolicy: Never
                    args: ["{{inputs.parameters.schema_uri}}"]
```

Versions
```
argo: v2.8.0
  BuildDate: 2020-05-11T22:55:43Z
  GitCommit: 8f696174746ed01b9bf1941ad03da62d312df641
  GitTreeState: clean
  GitTag: v2.8.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

 - OS: mac
