### ISSUE TITLE
GitHub Webhook event was parsed incorrectly

### ISSUE THREAD

**Issue by hnq90** [argoproj/argo-events#707]
**Describe the bug**
We have a Sensor for GitHub which will receive an event when a PR was merged (`action: closed`, `merged: true`) and do some workflows based on PR labels.

As you know, `labels` in a PR returns an array: https://developer.github.com/webhooks/event-payloads/#pull_request

```
[{\\\"color\\\":\\\"fef2c0\\\",\\\"default\\\":false,\\\"description\\\":\\\"nobuild\\\",\\\"id\\\":2142094044,\\\"name\\\":\\\"nobuild\\\",\\\"node_id\\\":\\\"MDU6TGFiZWwyMTQyMDk0MDQ0\\\",\\\"url\\\":\\\"https://api.github.com/repos/xxx/yyy/labels/nobuild\\\"}]"
```

I retrieved `name` of each label by:

```
'body.pull_request.labels.0.name',
'body.pull_request.labels.1.name',
'body.pull_request.labels.2.name',
```

```
{{inputs.parameters.label0}}
{{inputs.parameters.label1}}
{{inputs.parameters.label2}}
```

And I got `label0: nobuild` but `label1` & `label2` is the body event of GitHub webhook:

```
{\"name\":\"label1\",\"value\":\"{\\\"headers\\\":{\\\"Accept\\\":[\\\"*/*\\\"],\\\"Content-Length\\\":[\\\"22636\\\"],\\\"Content-Type\\\":[\\\"application/json\\\"],\\\"User-Agent\\\":[\\\"GitHub-Hookshot/74f00b2\\\"],\\\"X-Amzn-Trace-Id\\\":[\\\"Root=1-5edc-7c61646ff977f9eac0372909375e\\\"],\\\"X-Forwarded-For\\\":[\\\"140.15.251.82\\\"],\\\"X-Forwarded-Port\\\":[\\\"13333\\\"],\\\"X-Forwarded-Proto\\\":[\\\"http\\\"],\\\"X-Github-Delivery\\\":[\\\"97e9ff80-8141-b101-11ea-bdfad191cefd\\\"],\\\"X-Github-Event\\\":[\\\"pull_request\\\"]},\\\"body\\\":{\\\"X-GitHub-Delivery\\\":\\\"97e9ff80-8141-b101-11ea-bdfad191cefd\\\",\\\"X-GitHub-Event\\\":\\\"pull_request\\\",\\\"action\\\":\\\"closed\\\",\\\"number\\\":117,\\\"organization\\\":{\\\"avatar_url\\\"
...
```

**To Reproduce**
1. Create Sensor for GitHub PR.
2. Get labels by:
```
'body.pull_request.labels.0.name',
'body.pull_request.labels.1.name',
'body.pull_request.labels.2.name',
```
```
{{inputs.parameters.label0}}
{{inputs.parameters.label1}}
{{inputs.parameters.label2}}
```
3. See error

**Expected behavior**
```
label0: nobuild
label1: ''
label2: ''
```

**Environment (please complete the following information):**
 - Version 0.16.0

**Comment by VaibhavPage** [comment]
Can you post your `EventSource` yaml?

**Comment by hnq90** [comment]
@VaibhavPage Yes, here's my `EventSource`

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-event-source
  namespace: nearme
spec:
  github:
    myApiPullRequest:
      active: true
      apiToken:
        key: token
        name: github-access
      contentType: json
      events:
        - pull_request
      insecure: true
      owner: hnq90
      repository: my-api
      webhook:
        endpoint: /my-api/pull_request
        method: POST
        port: "12000"
        url: http://endpoint:12000
```

**Comment by whynowy** [comment]
@hnq90 do you still see this issue?

**Comment by whynowy** [comment]
Close it as no response.

**Comment by hnq90** [comment]
@whynowy Yes, I still got that issue. Here's how I retrieved the labels from GitHub:

```yaml
parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dataKey: body.repository.name
                dependencyName: xxx-merged-dep
            - dest: spec.arguments.parameters.1.value
              src:
                dataKey: body.pull_request.merge_commit_sha
                dependencyName: xxx-merged-dep
            - dest: spec.arguments.parameters.2.value
              src:
                dataKey: body.pull_request.head.ref
                dependencyName: xxx-merged-dep
            - dest: spec.arguments.parameters.3.value
              src:
                dataKey: body.pull_request.html_url
                dependencyName: xxx-merged-dep
            - dest: spec.arguments.parameters.4.value
              src:
                dataKey: body.pull_request.title
                dependencyName: xxx-merged-dep
            - dest: spec.arguments.parameters.5.value
              src:
                dataKey: body.pull_request.body
                dependencyName: xxx-merged-dep
            - dest: spec.arguments.parameters.6.value
              src:
                dataKey: body.pull_request.labels.0.name
                dependencyName: xxx-merged-dep
            - dest: spec.arguments.parameters.7.value
              src:
                dataKey: body.pull_request.labels.1.name
                dependencyName: xxx-merged-dep
            - dest: spec.arguments.parameters.8.value
              src:
                dataKey: body.pull_request.labels.2.name
                dependencyName: xxx-merged-dep
            - dest: metadata.name
              operation: append
              src:
                dataTemplate: "{{ .Input.body.repository.name }}-{{ .Input.body.pull_request.number }}-{{ .Input.body.pull_request.head.sha | substr 0 7 }}"
                dependencyName: xxx-merged-dep
```

**Comment by andreimahu** [comment]
I think this should be re-opened. I have also encountered this issue on both v1.7.0 and v1.7.1
Getting the label like below returns the entire webhook request content instead of just the label name.

```
          parameters:
            - src:
                dependencyName: pr-opened
                dataTemplate: "{{ .Input.body.pull_request.labels.0.name }}"
              dest: spec.arguments.parameters.0.value
```
