### ISSUE TITLE
invalid templateRef when sensor triggers a workflow depending on a cluster template

### ISSUE THREAD

**Issue by iMoses** [argoproj/argo-events#711]
**Describe the bug**
*UPDATE* this bug seems to be unrelated to the configmap source..

Using a sensor that trigger a `configmap` source fails to run with the following status while manually submitting the same workflow works as expected.

```
Status:              Failed
Message:             invalid spec: templates.connector-workflow.steps[0].ensure-db-schema template reference cluster-cli-templates.customer-cli-template not found
```

**To Reproduce**
Create a workflow file which uses `templateRef` and upload the directory to your ns as a configmap.
```
kubectl create configmap my-cm --from-file ./argo-dir
```
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  subscription:
    http:
      port: 9300
  dependencies:
    - name: test-dep
      gatewayName: webhook
      eventName: example
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            configmap:
              name: my-cm
              key: workflow.yaml
```

Trigger the sensor using a webhook and see that the workflow is created but fails with the error above.

(I'm using cluster workflow templates in this case, haven't tested on regular workflow templates)

**Expected behavior**
```
argo submit ./argo-dir/workflow.yaml
```
should work the same as the trigger, but while submit acts as expected the trigger does not.

**Environment (please complete the following information):**
k8s: 1.16.9
argo-events: 0.16
argo: 2.8.2

**Comment by iMoses** [comment]
logs from the workflow controller (log level debug):
```
time="2020-06-23T00:32:01Z" level=info msg="Processing workflow" namespace=stage0 workflow=google-workflow-z4rfm
time="2020-06-23T00:32:01Z" level=info msg="Updated phase  -> Running" namespace=stage0 workflow=google-workflow-z4rfm
time="2020-06-23T00:32:01Z" level=debug event="{{ } {google-workflow-z4rfm.161b04eff7f3eb4e      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []} {Workflow stage0 google-workflow-z4rfm 5833aa41-1821-4f19-a0c6-8e8082181b79 argoproj.io/v1alpha1 4827191 } WorkflowRunning Workflow Running {google-workflow-z4rfm } 2020-06-23 00:32:01.90925499 +0000 UTC m=+61.160212923 2020-06-23 00:32:01.90925499 +0000 UTC m=+61.160212923 1 Normal 0001-01-01 00:00:00 +0000 UTC nil  nil  }" reason=WorkflowRunning type=Normal workflow=google-workflow-z4rfm
time="2020-06-23T00:32:01Z" level=debug msg="Getting the template by name"
time="2020-06-23T00:32:01Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=stage0,name=google-workflow-z4rfm)" depth=0 tmpl="*v1alpha1.WorkflowStep (google-connector-workflow)"
time="2020-06-23T00:32:01Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=stage0,name=google-workflow-z4rfm)" depth=0 tmpl="*v1alpha1.WorkflowStep (google-connector-workflow)"
time="2020-06-23T00:32:01Z" level=debug msg="Getting the template by name" base="*v1alpha1.Workflow (namespace=stage0,name=google-workflow-z4rfm)" depth=0 tmpl="*v1alpha1.WorkflowStep (google-connector-workflow)"
time="2020-06-23T00:32:01Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=stage0,name=google-workflow-z4rfm)" depth=0 tmpl="*v1alpha1.WorkflowStep (cluster-authomize-cli-templates/authomize-customer-cli-template)"
time="2020-06-23T00:32:01Z" level=debug msg="Getting the template" base="*v1alpha1.Workflow (namespace=stage0,name=google-workflow-z4rfm)" depth=0 tmpl="*v1alpha1.WorkflowStep (cluster-authomize-cli-templates/authomize-customer-cli-template)"
time="2020-06-23T00:32:01Z" level=debug msg="Getting the template from ref" base="*v1alpha1.Workflow (namespace=stage0,name=google-workflow-z4rfm)" depth=0 tmpl="*v1alpha1.WorkflowStep (cluster-authomize-cli-templates/authomize-customer-cli-template)"
time="2020-06-23T00:32:01Z" level=info msg="Updated phase Running -> Failed" namespace=stage0 workflow=google-workflow-z4rfm
time="2020-06-23T00:32:01Z" level=info msg="Updated message  -> invalid spec: templates.google-connector-workflow.steps[0].ensure-db-schema template reference cluster-authomize-cli-templates.authomize-customer-cli-template not found" namespace=stage0 workflow=google-workflow-z4rfm
time="2020-06-23T00:32:01Z" level=info msg="Marking workflow completed" namespace=stage0 workflow=google-workflow-z4rfm
time="2020-06-23T00:32:01Z" level=debug event="{{ } {google-workflow-z4rfm.161b04eff90a7a20      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []} {Workflow stage0 google-workflow-z4rfm 5833aa41-1821-4f19-a0c6-8e8082181b79 argoproj.io/v1alpha1 4827191 } WorkflowFailed invalid spec: templates.google-connector-workflow.steps[0].ensure-db-schema template reference cluster-authomize-cli-templates.authomize-customer-cli-template not found {google-workflow-z4rfm } 2020-06-23 00:32:01.92751056 +0000 UTC m=+61.178468493 2020-06-23 00:32:01.92751056 +0000 UTC m=+61.178468493 1 Warning 0001-01-01 00:00:00 +0000 UTC nil  nil  }" reason=WorkflowFailed type=Warning workflow=google-workflow-z4rfm
time="2020-06-23T00:32:01Z" level=info msg="Checking daemoned children of " namespace=stage0 workflow=google-workflow-z4rfm
time="2020-06-23T00:32:01Z" level=info msg="Workflow update successful" namespace=stage0 phase=Failed resourceVersion=4827195 workflow=google-workflow-z4rfm
time="2020-06-23T00:32:01Z" level=debug msg="Resolving the template" base="*v1alpha1.Workflow (namespace=stage0,name=google-workflow-z4rfm)" depth=0 tmpl="*v1alpha1.WorkflowStep (cluster-authomize-cli-templates/authomize-customer-cli-template)"
```

**Comment by gladdiologist** [comment]
Hi,
Same for me, it seems that clusterScope templateRef is drop.  When describing such a workflow submitted from cli:

`[map[arguments:map[parameters:[map[name:message value:{{workflow.parameters.message}}]]] name:call-create templateRef:map[clusterScope:true name:create template:create]]]`

When describing the same workflow submitted from sensor:

`[map[arguments:map[parameters:[map[name:message value:{{workflow.parameters.message}}]]] name:call-create templateRef:map[name:create template:create]]]`

I noted the same thing when trying to use clusterworkflowtemplate with argo < 2.8. 

I tried with an argoWorflow template, without luck.

I see [here](https://github.com/argoproj/argo-events/blob/145fd9a940833c6e5b398994305d85847215d957/sensors/triggers/argo-workflow/argo-workflow.go) that argoWorkflow template launch an argo cli command, but the argo cli embedded in sensor image is old (5 months)
I will try with a custom sensor image with the same argo cli version i use (2.8.1) and see if there is a difference.

**Comment by iMoses** [comment]
@gladdiologist see #714 and #715

**Comment by gladdiologist** [comment]
Thanks :) 
I was planning to fix this as you did.

**Comment by gladdiologist** [comment]
hi, same problem after upgrading to your version. @iMoses .
The jsonUnmarshalling step drops the clusterScope field from templateRef because, go dependencies needs to be updated as well.
[here](https://github.com/argoproj/argo-events/blob/master/go.mod): github.com/argoproj/argo v2.5.2+incompatible

I will try to update it & rebuild to see if it's better

**Comment by iMoses** [comment]
@gladdiologist good catch!
Keep me updated, if it works I can update my PR

**Comment by gladdiologist** [comment]
@iMoses better with argo updated :) 
I updated argo/pkg also but i think it's not mandatory.
so: go get github.com/argoproj/argo@release-2.8 

2.9 release offers workflowTemplateRef, but it can wait :)

**Comment by whynowy** [comment]
https://github.com/argoproj/argo-events/issues/733

**Comment by jonnylangefeld** [comment]
Is there an update on this? I was actually trying to use `workflowTemplateRef` and ran into this issue.

**Comment by jonnylangefeld** [comment]
also what's interesting even if this is deployed via k8s resource like so:
```
triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                namespace: argo
                generateName: paas-cluster-
              spec:
                apiVersion: argoproj.io/v1alpha1
                kind: Workflow
                metadata:
                  namespace: argo
                  generateName: paas-cluster-
                spec:
                  workflowTemplateRef:
                    name: paas-cluster
                    clusterScope: true
```

It creates a workflow resource without any templates:
```
kubectl get wf -n argo paas-cluster-bx9d9 -o yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-07-17T00:59:35Z"
  generateName: paas-cluster-
  generation: 2
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Failed
  name: paas-cluster-bx9d9
  namespace: argo
  resourceVersion: "29613844"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/paas-cluster-bx9d9
  uid: 041ec1ac-60ea-44b2-b1d7-85d564a2e1d3
spec:
  arguments: {}
  templates: null
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-07-17T00:59:35Z"
  message: 'invalid spec: spec.entrypoint is required'
  phase: Failed
  startedAt: "2020-07-17T00:59:35Z"
```

If I copy and paste the resource and replace generatedName with name and apply with kubectl, it works just fine.
