### ISSUE TITLE
ArgoWorkflowTrigger with retryStrategy failing to Unmarshal.

### ISSUE THREAD

**Issue by igordrnobrega** [argoproj/argo-events#716]
**Describe the bug**
When using the `argoWorkflow` trigger together with `retryStrategy` like the following config. I get an error in the sensor `Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "backoff"`.
The configuration `retryStrategy` was added in Argo v2.5.0, I saw that there are some changes from the version I'm now in argo events, currently 0.16 and I'm on 0.14. Nevertheless, I'm waiting for the helm chart be updated
Workflow configuration took from https://argoproj.github.io/docs/argo/examples/readme.html#retrying-failed-or-errored-steps
```
triggers:
    - template:
        [...]
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                [...]
              spec:
                parallelism: 1
                entrypoint: process
                arguments:
                  parameters:
                    - name: tuple
                      value:
                templates:
                  - name: process
                    serviceAccountName: workflows
                    inputs:
                      parameters:
                        [...]
                    retryStrategy:
                      limit: 10
                      retryPolicy: "Always"
                      backoff:
                        duration: "10"
                        factor: 2
                        maxDuration: "5m"
                    container:
                      image: "image"
                      imagePullPolicy: Always
                      command: [/app/dag]
                      args:
                        [...]
                      env:
                        [...]
```

**To Reproduce**
1. Using the above configuration or any template and adding the following configuration to the templates will throw the error.
```
               retryStrategy:
                      limit: 10
                      retryPolicy: "Always"
                      backoff:
                        duration: "10"
                        factor: 2
                        maxDuration: "5m"
```

**Expected behavior**
Marshaling JSON should be fine.

**Environment (please complete the following information):**
 - Version Argo 2.5.0
 - Version Argo Events 0.14.0

I appreciate any help. 

Thanks in advance.
