### ISSUE TITLE
Sensor dependency change from gateway to eventsource

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#717]
**Is your feature request related to a problem? Please describe.**

`gatewayName` in sensor dependencies needs to be updated to `eventSourceName` before merging Gateway to EventSource.

```
  dependencies:
    - name: test-dep
      gatewayName: aws-sns
      eventName: example
```

to 

```
  dependencies:
    - name: test-dep
      eventSourceName: aws-sns-source-name
      eventName: example
```
