### ISSUE TITLE
Payload data limit when passing through webhook API to Argo Workflow

### ISSUE THREAD

**Issue by prateekkhera** [argoproj/argo-events#728]
**Describe the bug**
I have observed a limit to data for a parameter that one can send in a payload over a webhook API call. I have tried sending a parameter of 10,000 char length and seen it consistently capped to 1686 chars at the end of sensor.

**To Reproduce**

I have followed the tutorial `Event Data` under https://argoproj.github.io/argo-events/tutorials/02-parameterization/. I have just added my image to argo workflow sensor definition and different args, cmd:

```
                    container:
                      image: XXX
                      command:
                        - bash
                        - '-c'
                      args: ["echo {{inputs.parameters.message}}"]

```
I have used postman to send the API request. The output as a result of this workflow was capped to 1686 chars for a message with length of 10,000 chars.

**Expected behavior**
I am not sure what should be the expected behaviour as there's got to be some limit.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Browser:
 - Version: v0.15.0

**Additional context**
