### ISSUE TITLE
Support time filter which spans across UTC midnight

### ISSUE THREAD

**Issue by tmshn** [argoproj/argo-events#729]
**Is your feature request related to a problem? Please describe.**
Sensor dependencies can have a time filter so that workflows are triggered only by events during specific time range, such as 9AM-11AM. However, you cannot specify a time range that spans across midnight, like 11PM-2AM.
We should support such use cases.

Due to this, some of business requirements cannot be expressed by the time filter, simply because its time range position (note that the time range must be written in UTC).
The notion of "day" is a circular thing, rather than has a concrete and global start/end.

**Describe the solution you'd like**
Allow `start > stop`, in which case, the day of the stop time is treated as next day of one of the start time.

```yaml
filters:
  time:                # E.g. (on 2020-07-08)
    start: "23:00:00"  # 2020-07-08 23:00:00
    stop:  "02:00:00"  # 2020-07-09 02:00:00
```

- pros:
    - looks natural
- cons:
    - hard for users to notice the bug that swapping start and stop (e.g.: intended 9AM-11AM (2 hours), but actually written 11AM-9AM (22 hours)).

**Describe alternatives you've considered**
Another choice is to allow hour of `stop` to be in [0, 48) while keeping the restriction of `start < stop`.

```yaml
filters:
  time:                # E.g. (on 2020-07-08)
    start: "23:00:00"  # 2020-07-08 23:00:00
    stop:  "26:00:00"  # 2020-07-09 02:00:00
```

- pros:
    - less bug-prone of swapping start and stop
- cons:
    - looks relatively natural for say 26:00 (2AM), but weird to see like 33:00 (9AM)

One more choise: introduce `duration` field instead of `stop`

```yaml
filters:
  time:                  # E.g. (on 2020-07-08)
    start:    "23:00:00" # 2020-07-08 23:00:00
    duration: "3h"       # 2020-07-09 02:00:00
    # or maybe
    duration: "3:00:00"
```

- pros:
    - looks natural
    - less bug-prone of swapping start and stop
- cons:
    - if format is like `3h` which is supported by `ParseDuration`, hard to represent granular time range. If format is like `3:00:00`, bit confusing among stop vs. duration

**Additional context**
In any case, internal implementation will be quite easy, so the decision can be made solely on ergonomic aspect.

I'm happy to fix this.
