### ISSUE TITLE
Every 2min I get an Workflow Update event although nobody updated anything

### ISSUE THREAD

**Issue by lukaslentner** [argoproj/argo-events#730]
**Describe the bug**
I use a resource Event-Source/Gateway/Sensor and a Kafka Trigger to stream changes in workflow objects in a namesapce (namespace1) to Kafka. Everything works, but all 2 min a message is created with an UPDATE event. What puzzles me is that I do not update the workflow. So I do not understand why my long finished workflow produces every 2min a new event. I guess that there are NOT really new events because if I make `kubectl -n namespace1 describe wf` I see no more new events. Similarly a watch does not create new lines (unsure if new events would create new lines).
Also: The events are byte-by-byte the same ....

So my guess is that The sensor/Gateway etects the same event over and over again. And I ask myself WHY ...

**To Reproduce**
Use my the template at the bottom.

**Expected behavior**
One Add event on creation and one update event on completion.

**Environment (please complete the following information):**
Argo Version: v2.9.1
Argo events version: v0.15.0

**Additional context**
My YAML:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: resource
spec:
  type: resource
  resource:
    example:
      namespace: namespace1
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      eventTypes:
        - UPDATE
        - ADD
---
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: resource
spec:
  type: resource
  eventSourceRef:
    name: resource
  template:
    serviceAccountName: argo-events-sa
  subscribers:
    http:
      - "http://resource-sensor.argo-events.svc:9300/"
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: resource
spec:
  template:
    serviceAccountName: argo-events-sa
    container:
      env:
        - name: DEBUG_LOG
          value: "true"
      volumeMounts:
        - name: kafka
          mountPath: /etc/kafka
    volumes:
      - name: kafka
        secret:
          secretName: kafka
  subscription:
    http:
      port: 9300
  dependencies:
    - name: test-dep
      gatewayName: resource
      eventName: example
  triggers:
    - template:
        name: kafka-trigger
        kafka:
          url: mykafkahost:28282
          topic: mytest1.events
          partition: 0
          tls:
            caCertPath: /etc/kafka/ca
            clientCertPath: /etc/kafka/cert
            clientKeyPath: /etc/kafka/key
          payload:
            - src:
                dependencyName: test-dep
              dest: content
```
