### ISSUE TITLE
GCP Pub/Sub auto mount credentials from Secret

### ISSUE THREAD

**Issue by tmshn** [argoproj/argo-events#742]
**Is your feature request related to a problem? Please describe.**
To use GCP Pub/Sub with JSON credentials, you have to write numbers of lines like this, which us quite bothersome:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gcp-pubsub
spec:
  pubsub:
    projectID: foo
    topicID: bar
    credentialsFile: /gcp-pubsub-creds-dir/serviceAccount.json
  template:
    container:
      volumeMounts:
        - mountPath: /gcp-pubsub-creds-dir
          name: gcp-pubsub-data
    volumes:
      - name: gcp-pubsub-data
        secret:
          secretName: gcp-pubsub
```

**Describe the solution you'd like**

The manifest can be simplified like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gcp-pubsub
spec:
  pubsub:
    projectID: foo
    topicID: bar
    credentials:
      secretName: gcp-pubsub
      # secretKey: serviceAccount.json # optional
```

Event source controller mount the secret to the event source pod appropriately according to this.

**Describe alternatives you've considered**
None.

**Additional context**
None.
