### ISSUE TITLE
File gateway not triggered when using PV and PVC

### ISSUE THREAD

**Issue by lueenavarro** [argoproj/argo-events#746]
**Describe the bug**
The gateway does not work when using PV and PVC

**To Reproduce**
1. Do the setup here: https://argoproj.github.io/argo-events/setup/file/
2. It will work when you create a file on the indicated volume mount in file gateway.
3. Now use PV and PVC in file-gateway
4. It will not work anymore.

**Expected behavior**
The file-gateway should be triggered when using PV and PVC

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: Argo-events v.0.15

**Additional context**
This works:

```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: file
spec:
  type: file
  eventSourceRef:
    name: file-event-source
  template:
    container:
      volumeMounts:
        - mountPath: /inbound
          name: cos-pv
    volumes:
      - name: cos-pv
        emptyDir: {}
    serviceAccountName: argo-events-sa
  subscribers:
    http:
      - "http://file-sensor:9300"
```

but this doesn't work:
```
apiVersion: argoproj.io/v1alpha1
kind: Gateway
metadata:
  name: file
spec:
  type: file
  eventSourceRef:
    name: file-event-source
  template:
    container:
      volumeMounts:
        - mountPath: /inbound
          name: cos-pv
    volumes:
      - name: cos-pv
        persistentVolumeClaim:
          claimName: cos-pvc
    serviceAccountName: argo-events-sa
  subscribers:
    http:
      - "http://file-sensor:9300"
```

This is my event source:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: file-event-source
spec:
  file:
    example:
      eventType: CREATE
      watchPathConfig:
        directory: /inbound/
        path: x.txt
  type: file
```

and my sensor:
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: file
spec:
  dependencies:
    - eventName: example
      gatewayName: file
      name: test-dep
  subscription:
    http:
      port: 9300
  template:
    serviceAccountName: argo-events-sa
  triggers:
    - policy: null
      template:
        k8s:
          group: argoproj.io
          operation: create
          parameters:
            - dest: spec.templates.0.container.args.0
              src:
                dependencyName: test-dep
          resource: workflows
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: file-watcher-
              spec:
                entrypoint: whalesay
                templates:
                  - container:
                      args:
                        - hello
                      command:
                        - cowsay
                      image: 'docker/whalesay:latest'
                    name: whalesay
          version: v1alpha1
        name: file-workflow-trigger
```

There are no errors on the gateway or sensor  logs when I create the file and I'm using PV and PVC. It's just nothing happens.
