### ISSUE TITLE
Add docs for multiple types of event configuration within single eventsource

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#779]

**Comment by whynowy** [comment]
It's been implemented in #755

Rules:
```
a.) Event source with rollingUpdate and recreate are not allowed in one EventSource object - Otherwise when the EventSource is updated, there will be downtime for those rollingUpdate type event sources such as webhook.
b.) Event name (the map key) needs to be unique in one EventSource object, even different type of event source can not use same name - Because we use EventSourceName and EventName in Sensor as dependency.
c.) rollingUpdate types use replicas defined in the spec, defaults to 1;
d.) recreate ignores replica field in the spec, it always uses 1
```

**Comment by hisener** [comment]
Just for my understanding, would that allow something like the following?
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: event-source
spec:
  calendar:
    cron:
      interval: 10s
  github:
    webhook:
      ...
```
