### ISSUE TITLE
Ability to specify EventSource service name

### ISSUE THREAD

**Issue by ptemmer** [argoproj/argo-events#784]
**Is your feature request related to a problem? Please describe.**
Currently service names for EventSources are generated automatically. This makes it harder to "templatize" resources that have dependencies on those service names. For example: ingress resource to make the service accessible from the outside requires the name of the backend service to be specified. 

**Describe the solution you'd like**
Apart from allowing the ports to be set, allow the service name to be specified
```
  service:
   metadata:
     name: someservicename
    ports:
      - port: 12000
        targetPort: 12000
```
