### ISSUE TITLE
Auto detect service ports for EventSource

### ISSUE THREAD

**Issue by ptemmer** [argoproj/argo-events#785]
**Is your feature request related to a problem? Please describe.**
Port specification is duplicated in the EventSource resource.

```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: example
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  replica: 1
  webhook:
    github-branch:
      port: "12000"
      endpoint: "/webhook"
      method: "POST"
```

**Describe the solution you'd like**
Wouldn't it make sense to automatically detect the ports used by the event source specified?
