### ISSUE TITLE
[Question] How to achieve at most one job at any time

### ISSUE THREAD

**Issue by hisener** [argoproj/argo-events#786]
Firstly, sorry for not using the issue template, I hope it's fine since it is not a bug report.

I have a sensor that triggers a k8s job, I am trying to limit parallel runs and queue new events if there is a running job. Is there a way to achieve that using k8s jobs?

I also tried _submitting_ a workflow, which creates a Job, with `parallelism: 1` (just like the example below) but I guess it tries to _create_ a new workflow each time.

https://github.com/argoproj/argo-events/blob/527a45fa661c4c6d8315a170225e724f26582d44/examples/sensors/special-workflow-trigger.yaml#L18-L23

```
2020/07/29 16:13:00 Failed to submit workflow: workflows.argoproj.io "workflow" already exists
ERRO[2020-07-29 16:13:00] failed to operate on the event notification   error="failed to execute submit command for workflow workflow: exit status 1"
```

**Comment by hisener** [comment]
I have tried [synchronization](https://github.com/argoproj/argo/blob/master/docs/synchronization.md) but seems like the trigger ignores and doesn't pass `synchronization` parameters.

**Comment by VaibhavPage** [comment]
Are you using v0.17.0?

**Comment by hisener** [comment]
Also, another thing I observed is that setting `replicas` to `1` also doesn't work. It ignores that value and creates 3 instances.

https://github.com/argoproj/argo-events/blob/099ed605dd80db9f3b607c7987d945b428068095/examples/eventbus/native.yaml#L7-L11

**Comment by VaibhavPage** [comment]
@whynowy can you help with eventbus auth? @hisener v0.14.0 has an old version of Argo so maybe synchronization params are ignored

**Comment by hisener** [comment]
Yes, it's definitely getting ignored. I just tried `k8s` instead of `argoWorkflow` but the same result. First I will try to upgrade only the sensor controller to `v0.17.0`.

**Comment by hisener** [comment]
@VaibhavPage I want to go back to my initial question, is there a way to achieve maximum concurrency of triggers in v0.14.0?

**Comment by VaibhavPage** [comment]
The triggers do not have the concept of concurrency. We offload to those decisions to downstream operators like Workflow controller

**Comment by hisener** [comment]
Totally makes sense. However, the old version ignores the synchronization and the new version fails even for the simplest configuration. I think I am missing an important part of the puzzle. 🤔 

```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: {{ $top.Release.Namespace }}
spec:
  nats:
    native:
      replicas: 1 # which is ignored. Still creates 3 replicas.

---

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: "{{ $top.Release.Name }}-calendar-event-source-{{ $repo.name }}"
  namespace: {{ $top.Release.Namespace }}
spec:
  type: calendar
  calendar:
    cron:
      schedule: "{{ $repo.schedule }}"
      timezone: "{{ $repo.timezone }}"
```

```
$ kubectl describe eventbus default
Name:         default
Namespace:    renovate
Labels:       <none>
Annotations:  <none>
API Version:  argoproj.io/v1alpha1
Kind:         EventBus
Metadata:
  Creation Timestamp:  2020-07-31T15:59:09Z
  Finalizers:
    eventbus-controller
  Generation:        8
  Resource Version:  112644047
  Self Link:         /apis/argoproj.io/v1alpha1/namespaces/renovate/eventbus/default
  UID:               c4cec390-d346-11ea-8a2e-027e4d0fe61e
Spec:
  Nats:
    Native:
      Replicas:  1
Status:
  Conditions:
    Last Transition Time:  2020-07-31T16:02:39Z
    Status:                True
    Type:                  Configured
    Last Transition Time:  2020-07-31T16:02:39Z
    Message:               NATS is deployed
    Reason:                Succeeded
    Status:                True
    Type:                  Deployed
  Config:
    Nats:
      Auth:        none
      Cluster ID:  eventbus-default
      URL:         nats://eventbus-default-stan-svc:4222
Events:            <none>

$ kubectl get pods                                                               
NAME                                                              READY   STATUS             RESTARTS   AGE
eventbus-default-stan-0                                           2/2     Running            0          7m48s
eventbus-default-stan-1                                           2/2     Running            0          7m47s
eventbus-default-stan-2                                           2/2     Running            0          7m44s
```

```
$ kubectl logs -f event-source
{"level":"info","msg":"Starting event source server...","time":"2020-07-31 16:04:13"}
{"error":"failed to load auth.yaml. err: Config File \"auth\" Not Found in \"[/etc/eventbus/auth]\"","level":"error","msg":"failed to get eventbus driver","time":"2020-07-31 16:04:13"}
{"error":"failed to load auth.yaml. err: Config File \"auth\" Not Found in \"[/etc/eventbus/auth]\"","level":"error","msg":"failed to start eventsource server","time":"2020-07-31 16:04:13"}
```

**Comment by whynowy** [comment]
@hisener - It looks like there's a bug in eventbus driver that when `authStrategy` is `none`, it somehow still check the auth.conf, I'll fix it. As a workaround, please add `auth: token` to your EventBus.


About the `replicas`, the minimal number for NATS streaming is 3, so when the number < 3, we set it to 3.

**Comment by whynowy** [comment]
https://github.com/argoproj/argo-events/issues/786

**Comment by hisener** [comment]
> @hisener - It looks like there's a bug in eventbus driver that when authStrategy is none, it somehow still check the auth.conf, I'll fix it. As a workaround, please add auth: token to your EventBus.

That worked. Thanks for fixing.

> About the replicas, the minimal number for NATS streaming is 3, so when the number < 3, we set it to 3.

👍 

Let's not close the issue for now. I'll post my solution to limit the parallel execution using [synchronization](https://github.com/argoproj/argo/blob/master/docs/synchronization.md) for future readers.

**Comment by hisener** [comment]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: synchronization-test
data:
  workflow: "1"

---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-test
spec:
  dependencies:
    - name: cron
      eventSourceName: calendar-event-source
      eventName: cron
  triggers:
    - template:
        name: renovate-workflow-trigger
        # Using `argoWorkflow` causes deserialization error: unknown field “synchronization”. 
        # See https://github.com/argoproj/argo-events/issues/800
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: workflow-
              spec:
                entrypoint: tmpl
                synchronization:
                  semaphore:
                    configMapKeyRef:
                      name: synchronization-test
                      key: workflow
                templates:
                  - name: tmpl
                    container:
                      image: busybox
```

See [Sychronization doc](https://github.com/argoproj/argo/blob/master/docs/synchronization.md) for more information.
