### ISSUE TITLE
Simplify conditions for triggers

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#790]
**Is your feature request related to a problem? Please describe.**
If multiple triggers and dependencies are aggregated in a sensor object, we can use `Circuit` and `Switch` to trigger actions based on different conditions, see https://github.com/argoproj/argo-events/blob/master/docs/tutorials/06-circuit-and-switch.md

With this, the real conditions to trigger an action is `Circuit && Swithc`, for example, if the sensor spec looks like below:

```
spec:
  dependencies:
    - name: dep1
      eventSourceName: xxx
      eventName: xxx
    - name: dep2
      eventSourceName: xxx
      eventName: xxxx
    - name: dep3
      eventSourceName: xxx
      eventName: xxxx

  # group event dependencies
  dependencyGroups:
    - name: group_a
      dependencies:
        - dep1
        - dep2
    - name: group_b
      dependencies:
        - dep3
  circuit: "group_a || group_b"
  triggers:
    - template:
        switch:
          any:
            - group_a
        name: trigger1
```

The condition to trigger the action is `(group_a || group_b) && (group_a)`, which is actually `group_a`, and finally translated to `dep1 && dep2`. So it would be better to define the condition directly to `group_a` or `dep1 && dep2`.

**Describe the solution you'd like**
1. Expose a new field in triggers named `conditions`
2. `conditions` could use group names or dependency names directly, examples:

`conditions: "group_a"`
`conditions: "group_a || group_b"` which equals to `conditions: "(dep1 && dep2) || dep3"`
`conditions: "group_a && group_b && dep7"`

3. Deprecate `circuit` and `switch`.

4. If no `conditions` (or 'circuit' and `switch`) defined, the default conditions for the trigger is `&&` for all the dependencies defined, this is backward compatible.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
