### ISSUE TITLE
DependencyGroup enhancement

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#791]
**Is your feature request related to a problem? Please describe.**

This is an extension thought of #790 

The dependencies in a group is `&&` logic, for example, following group definition means `dep1 && dep2`.

```
  dependencyGroups:
    - name: group_a
      dependencies:
        - dep1
        - dep2
```

Would it good to support `||` logic, or even a free style logic like "(dep1 && dep2) || dep3" since dependencyGroup is just like a shortcut for re-use purpose?

**Describe the solution you'd like**

I would suggest either one of following 

1.) `dependencyAlias: "(dep1 && dep2) || dep3"` to replace `dependencyGroup`

2.) If 1.) is not acceptable, extend `dependencyGroup` as following:
```
  dependencyGroups:
    - name: group_a
      all:
        - dep1
        - dep2
```
or 
```
  dependencyGroups:
    - name: group_a
      any:
        - dep1
        - dep2
```

**Describe alternatives you've considered**

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
