### ISSUE TITLE
Calendar Catchup

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-events#793]
**Is your feature request related to a problem? Please describe.**

Users want to be able to pretend that a calendar was running in the past and produces the events it would have. E

**Describe the solution you'd like**

Some way to configure the calendar to include the backfill information

```yaml
backfill:
  from: date
  to: date
```

And some way to determine if we have already run the backfill:

```yaml
status:
  backfill:
    lastDate: date
```

Note -  we cannot store this status in the event source resource as it must be in user namespace.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: same-name-as-resource  
data:
  calender.backfill.lastDate: date
```

**Describe alternatives you've considered**

This could be a feature in Argo Cron workflows.

**Additional context**

We need to determine how to store executions.

We can generate them as follows:

https://github.com/robfig/cron/issues/333
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
