### ISSUE TITLE
Support inequality comparison in data filters

### ISSUE THREAD

**Issue by hisener** [argoproj/argo-events#808]
**Is your feature request related to a problem? Please describe.**
[DataFilter](https://github.com/argoproj/argo-events/blob/master/api/sensor.md#datafilter) in Sensor does not support `!=` even though it's supported in https://github.com/tidwall/gjson.

**Describe the solution you'd like**
Add support for inequality comparison (`!=`) in `filters.data[].comparator` in Sensor spec.

```
      filters:
        data:
          - path: body.sender.id
            type: number
            comparator: "!="
            value:
              - "3"
```

**Describe alternatives you've considered**
N/A

**Additional context**
Actually, I am not sure if this is a bug or a missing feature. `comparator: "!="` didn't work for me but for instance `comparator: "<"` works.

**Environment (please complete the following information):**
 - Argo: v2.10.0-rc4
 - Argo Events: v0.17.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
