### ISSUE TITLE
Sensor with resource signal for config-map fails

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo-events#82]
**Describe the bug**
I created a sensor that was supposed to run a workflow when a config-map was created in the `default` namespace. However, when the config-map is created, the sensor controller failed with the following error:
```
time="2018-08-06T23:37:29Z" level=info msg="sensor message  -> listening for signal events" namespace=default sensor=resource-example-l4kvz
time="2018-08-06T23:37:29Z" level=error msg="Event Stream (resource-example-l4kvz/worklow-1) Msg: (Action:IGNORED) - Failed to filter event: unsupported event content type: "
```

**To Reproduce**
1. Create the following sensor
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  generateName: resource-example-
  labels:
    sensors.argoproj.io/controller-instanceid: axis
spec:
  signals:
    - name: worklow-1
      resource:
        namespace: default
        group: ""
        version: "v1"
        kind: "ConfigMap"
        filter:
          prefix: my-cm
  triggers:
    - name: ns-workflow
      resource:
        namespace: default
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: hello-world-
              spec:
                entrypoint: whalesay
                templates:
                  -
                    container:
                      args:
                        - "hello world"
                      command:
                        - cowsay
                      image: "docker/whalesay:latest"
                    name: whalesay
```

2. Create the following config-map
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  my-life: |
      my-rules
```

**Expected behavior**
1. After the config-map is created, the hello-world workflow should be executed.
