### ISSUE TITLE
Simple health check endpoint for webhook related eventsources

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#820]
**Is your feature request related to a problem? Please describe.**
When the webhook related event sources such as `github`, `sns`, `slack` expose the endpoint to internet through cloud provider's load balancer, a health check endpoint is needed for configuration.

**Describe the solution you'd like**
Expose an endpoint `/health` with the same port for each configured event, it accepts GET request and simply returns "OK" with 200.

For example, an EventSource like below will expose `:12000/health` and `:13000/health` as simple health check endpoints.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  webhook:
    example:
      port: "12000"
      endpoint: /example
      method: POST
    example-foo:
      port: "13000"
      endpoint: /example2
      method: POST
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
