### ISSUE TITLE
Better approach to deal with ~/.ssh/known_hosts for triggers pulling resources from git.

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#841]
**Is your feature request related to a problem? Please describe.**
To trigger a workflow or k8s resource with source from github, if git URL is configured as "git://xxxxx", it requires `~/.ssh/known_hosts` is configured, which means following spec is needed currently.

```yaml
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /etc/ssh
          name: known-hosts
    volumes:
      # The name of the key in the secret must be "ssh_known_hosts"
      # Make sure you have your git provider added in the known hosts
      # e.g. create the secret by running, kubectl -n argo-events create secret generic git-known-hosts --from-file=ssh_known_hosts=.ssh/known_hosts
      - name: known-hosts
        secret:
          secretName: git-known-hosts
```

**Describe the solution you'd like**

1. Ignore the host key check;

2. If approach 1 is not doable, add a filed (secretKeySelector) for known_hosts to git trigger, so that user don't need to mount the volume with `spec.template.container.volumes`

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
