### ISSUE TITLE
Documentation for quickstart is not accurate

### ISSUE THREAD

**Issue by bappr** [argoproj/argo-events#85]
The doc `docs/quickstart.md` seems wrong.

Here are the steps I had to do in order to generate the images:

1. `go get github.com/argoproj/argo-events`
2. `cd ~/go/src/github.com/argoproj/argo-events/`
3. `dep ensure -vendor-only`

Then I was able to build the image.

**Comment by bappr** [comment]
Furthermore, on step 10, due to sensor config from `webhook-with-resource-param`, webhook-signal is listening on `/hello`. Need to add `/hello` in the curl command.

=>
```
signals:
    - name: webhook
      webhook:
        endpoint: /hello
        method: POST
```
