### ISSUE TITLE
EventHub event-source fails while gathering the hub runtime information

### ISSUE THREAD

**Issue by rgbusato** [argoproj/argo-events#874]
**Describe the bug**
I am trying to use the Azure EventHub event-source but cannot seem to get it to work. I've used some of the examples in the repo and have tried many different configurations on the Azure side as well with no luck.
Based on my initial debugging it seems like the connection does take place however the event-source fails in the "gathering the hub runtime information..." step. The reason why i say that is because I can see the connections open metric in Azure and a new connection shows up that matches the time window from the event-source logs.
So I don't think it's a problem with the authentication itself, it appears to do that successfully.

**To Reproduce**
1. Create an Azure Event Hub
2. Gather SAS connection string information
3. Using EventHub connection string, create 2 kubernetes secrets: `shared-access-key-name-secret` and `shared-access-key-secret`.
4. Create `EventSource` using the example in the argo-events repo and referencing the kubernetes secrets previously created:
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: azure-events-hub
spec:
  azureEventsHub:
    example:
      # FQDN of the EventsHub namespace you created
      # More info at https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-get-connection-string
      fqdn: my-eventhub-namespace.servicebus.windows.net
      sharedAccessKeyName:
        name: shared-access-key-name-secret
        key: value
      sharedAccessKey:
        name: shared-access-key-secret
        key: value
      # Event Hub path/name
      hubName: my-eventhub-01
```
5. Error from event-source logs
```
{"eventName":"example","eventSourceName":"azure-events-hub","eventSourceType":"azureEventsHub","level":"info","msg":"gathering the hub runtime information...","time":"2020-09-03 20:18:29"}
{"error":"failed to get the hub runtime information for example: server error link c669c591-026f-4ca6-b23d-45525508bfa0: status code 500 and description: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101","eventName":"example","eventSourceName":"azure-events-hub","level":"error","msg":"failed to start service.","time":"2020-09-03 20:18:32"}
```

**Expected behavior**
I would expect the EventHub event-source to initialize correctly without any errors and start listening for new events. When a new event is detected by the event-source it places in the eventbus for further processing.

**Environment (please complete the following information):**
 - Kubernetes: v1.17
 - Argo: v2.4.2
 - Argo Events: v0.17 and v1.0.0-rc3

**Additional context**
I've tested argo events with the webhook as well as the kafka event-source successfully and was able to listen and trigger argo workflows as expected.
Based on my initial debugging it seems like the issue is coming from the [EventHub Go sdk ](https://github.com/Azure/azure-event-hubs-go)that argo-events uses.
I've noticed that we are not version locking the go SDK for EventHub. I'm wondering if maybe things have changed in that library that broke this argo-events functionality.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
