### ISSUE TITLE
[user error] Github EventSource not finding secret for apiToken

### ISSUE THREAD

**Issue by tomoyat1** [argoproj/argo-events#890]
**Describe the bug**
EventSource is not finding the Secret which contains the GItHub API token I have configured for it to use.

**To Reproduce**
1. Create `github-access` secret with following contents
```yaml
apiVersion: v1
stringData:
  token: xxx # this is redacted, of course ;)
kind: Secret
metadata:
  name: github-access
  namespace: argo-events
type: Opaque
```

2. Create following EventSource
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: my-github
spec:
  replica: 1
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    my-github-push:
      events:
      - push
      webhook:
        port: "12000"
        method: "POST"
        url: argoevents.example.com
        endpoint: /webhooks/my-repo
      insecure: true
      apiToken:  # I intend this to point to the secret created in step 1
        key: token
        name: github-access
      namespace: argo-events
      owner: "tomoyat1"
      repository: "my-repo"
      contentType: "json"
```

3. The logs for the Pod  `my-github-eventsource-xxxxx-yyyyyyyyyy-zzzzz` will have the following entry, even though the `apiToken` field in the EventSource clearly points to the Secret created in 1.
```json
{"level":"error","ts":1600852573.710982,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:327","msg":"failed to start listening eventsource","eventSourceName":"my-github","eventSourceType":"github","eventName":"my-github-push","error":"failed to retrieve api token credentials. err: open /argo-events/secrets/github-access/token: no such file or directory\nfailed to get secret value of name: github-access, key: token\ngithub.com/argoproj/argo-events/common.GetSecretFromVolume\n\t/home/runner/work/argo-events/argo-events/common/util.go:154\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*Router).getCredentials\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:55\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*Router).PostActivate\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:146\ngithub.com/argoproj/argo-events/eventsources/common/webhook.ManageRoute\n\t/home/runner/work/argo-events/argo-events/eventsources/common/webhook/webhook.go:231\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*EventListener).StartListening\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:282\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func2\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:306\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/asm_amd64.s:1373\ntoken not founnd\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*Router).getCredentials\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:57\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*Router).PostActivate\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:146\ngithub.com/argoproj/argo-events/eventsources/common/webhook.ManageRoute\n\t/home/runner/work/argo-events/argo-events/eventsources/common/webhook/webhook.go:231\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*EventListener).StartListening\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:282\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func2\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:306\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/asm_amd64.s:1373","errorVerbose":"failed to retrieve api token credentials. err: open /argo-events/secrets/github-access/token: no such file or directory\nfailed to get secret value of name: github-access, key: token\ngithub.com/argoproj/argo-events/common.GetSecretFromVolume\n\t/home/runner/work/argo-events/argo-events/common/util.go:154\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*Router).getCredentials\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:55\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*Router).PostActivate\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:146\ngithub.com/argoproj/argo-events/eventsources/common/webhook.ManageRoute\n\t/home/runner/work/argo-events/argo-events/eventsources/common/webhook/webhook.go:231\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*EventListener).StartListening\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:282\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func2\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:306\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/asm_amd64.s:1373\ntoken not founnd\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*Router).getCredentials\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:57\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*Router).PostActivate\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:146\ngithub.com/argoproj/argo-events/eventsources/common/webhook.ManageRoute\n\t/home/runner/work/argo-events/argo-events/eventsources/common/webhook/webhook.go:231\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*EventListener).StartListening\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:282\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func2\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:306\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/asm_amd64.s:1373\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*Router).PostActivate\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:148\ngithub.com/argoproj/argo-events/eventsources/common/webhook.ManageRoute\n\t/home/runner/work/argo-events/argo-events/eventsources/common/webhook/webhook.go:231\ngithub.com/argoproj/argo-events/eventsources/sources/github.(*EventListener).StartListening\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/github/start.go:282\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func2\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:306\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func2\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:327"}
```

**Expected behavior**
Since the EventSource and secret are correctly configured, the resulting EventSource pod should be able to find the secret and carry on.

**Screenshots**
None.

**Environment (please complete the following information):**
 - Kubernetes: v1.16.13-eks-2ba888
 - Argo: Not used
 - Argo Events: v1.0.0

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Can you check the deployment or pod yaml of `my-github-eventsource-xxxxx-xxx`, to see if it has a volume to that secret attached?

**Comment by tomoyat1** [comment]
```
    volumeMounts:
    - mountPath: /etc/eventbus/auth
      name: auth-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-tddfd
      readOnly: true
  volumes:
  - name: auth-volume
    secret:
      defaultMode: 420
      items:
      - key: client-auth
        path: auth.yaml
      secretName: eventbus-default-client
  - name: default-token-tddfd
    secret:
      defaultMode: 420
      secretName: default-token-tddfd
```

Seems like the volume with the secret is missing.

**Comment by whynowy** [comment]
I used exact the same yaml you posted, it works for me.

```
          volumeMounts:
          - mountPath: /etc/eventbus/auth
            name: auth-volume
          - mountPath: /argo-events/secrets/github-access
            name: secret-github-access
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: auth-volume
          secret:
            defaultMode: 420
            items:
            - key: client-auth
              path: auth.yaml
            secretName: eventbus-default-client
        - name: secret-github-access
          secret:
            defaultMode: 420
            secretName: github-access
```

Could you check the log of eventsource-controller to see if there's any clue?
