### ISSUE TITLE
Cannot trigger from ConfigMap if its ref name is parameterized

### ISSUE THREAD

**Issue by tmshn** [argoproj/argo-events#908]
**Describe the bug**
As described in the following document, Sensor supports to parameterize its trigger template. This allows us to change artifact location based on received events.

https://argoproj.github.io/argo-events/tutorials/02-parameterization/#trigger-template-parameterization

However, if the artifact location is ConfigMap, and its name is parameterized, it wont't work because non-hardcoded ConfigMap is not mounted starting from https://github.com/argoproj/argo-events/pull/792.

**To Reproduce**

Deploy following Sensor (along with an appropriate EventSource and ConfigMap)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: tmshn-test-sensor
spec:
  dependencies:
    - name: dep
      eventSourceName: tmshn-test-webhook1
      eventName: main
  triggers:
    - template:
        name: workflow-trigger
        argoWorkflow:
          source:
            configmap:
              name: tmshn-test-template1
              key: workflow
      parameters:
        - src:
            dependencyName: dep
            dataKey: body.cfname
            value: tmshn-test-template1
          dest: argoWorkflow.source.configmap.name
```

Post event to the EventSource with message like `{"cfname": "another-configmap"}`, and you'll see an error in the Sensor pod.

```
open /argo-events/config/another-configmap/workflow: no such file or directory
failed to get configMap value of name: another-configmap, key: workflow
github.com/argoproj/argo-events/common.GetConfigMapFromVolume
	/home/runner/work/argo-events/argo-events/common/util.go:176
github.com/argoproj/argo-events/store.(*ConfigMapReader).Read
	/home/runner/work/argo-events/argo-events/store/configmap.go:21
github.com/argoproj/argo-events/store.FetchArtifact
	/home/runner/work/argo-events/argo-events/store/store.go:36
github.com/argoproj/argo-events/sensors/triggers.FetchKubernetesResource
	/home/runner/work/argo-events/argo-events/sensors/triggers/fetch.go:39
github.com/argoproj/argo-events/sensors/triggers/argo-workflow.(*ArgoWorkflowTrigger).FetchResource
	/home/runner/work/argo-events/argo-events/sensors/triggers/argo-workflow/argo-workflow.go:70
github.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions
	/home/runner/work/argo-events/argo-events/sensors/listener.go:240
github.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.3
	/home/runner/work/argo-events/argo-events/sensors/listener.go:149
runtime.goexit
	/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/asm_amd64.s:1373
```

**Expected behavior**
A workflow is submitted referring the ConfigMap named `another-configmap`.

**Environment (please complete the following information):**
 - Kubernetes: 1.14.10
 - Argo: 2.11.0
 - Argo Events: 1.0.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
