### ISSUE TITLE
In case gcp pubsub eventsource, sensor workflow was duplicately created when pubsub message came.

### ISSUE THREAD

**Issue by duluong** [argoproj/argo-events#929]
**Describe the bug**
I need a job run when got message from gcp pubsub.
So I've created a eventsource and sensor to handle it.
The trigger ran well and made the right workflow.
But the workflow was alway duplicately created.

**To Reproduce**
My yamls as bellow.

eventsource-gcp-pubsub.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gcp-pubsub-argo-test
spec:
  pubSub:
    decode-data:
      jsonBody: true
      projectID: abc-xyz
      subscriptionID: abc-xyz-topic-sub
      credentialSecret:
        name: service-account-abc-xyz
        key: service-account-abc-xyz.json
```

sensor-job.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: rawdataprocess-job
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: rawdataprocess-job-dep
      eventSourceName: gcp-pubsub-argo-test
      eventName: decode-data
  triggers:
    - template:
        name: rawdataprocess-job-workflow-trigger
        k8s:
          namespace: aaa-xxxx
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                namespace: grdsys-dev
                generateName: rawdataprocess-job-
              spec:
                entrypoint: rawdataprocess-job
                arguments:
                  parameters:
                    - name: bucketId
                      value: ""
                    - name: objectId
                      value: ""
                templates:
                  - name: rawdataprocess-job
                    inputs:
                      parameters:
                        - name: bucketId
                        - name: objectId
                    container:
                      image: asia.gcr.io/abc-xyz/data-process:argo
                      command: ["sh", "-c"]
                      args:
                      - |
                        /app/rawdataprocess --bucket-id "{{inputs.parameters.bucketId}}" --object-id "{{inputs.parameters.objectId}}"
          parameters:
          - src:
              dependencyName: rawdataprocess-job-dep
              dataKey: attributes.bucketId
            dest: spec.arguments.parameters.0.value
          - src:
              dependencyName: rawdataprocess-job-dep
              dataKey: attributes.objectId
            dest: spec.arguments.parameters.1.value
```

**Screenshots**
wf job was duplicated
<img width="769" alt="Screen Shot 2020-10-27 at 15 14 30" src="https://user-images.githubusercontent.com/6425063/97264521-78f63980-1868-11eb-9c0f-110cfdf8a12e.png">

**Environment (please complete the following information):**
 - Kubernetes: [v1.18.9]
 - Argo: [v2.11.6]
 - Argo Events: [v1.0.0]

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
