### ISSUE TITLE
NPE in artifact s3

### ISSUE THREAD

**Issue by akranga** [argoproj/argo-events#93]
**Describe the bug**
Artifact sensor controller throws NullPointerException when S3 sensor

**To Reproduce**
1. Apply sensor (see example)
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: bucket-trigger
  labels:
    sensors.argoproj.io/controller-instanceid: axis
spec:
  signals:
  - name: s3Created
    artifact:
      s3:
        bucket: validS3Bucket
        event: s3:ObjectCreated:*
        endpoint: s3-eu-west-1.amazonaws.com
        insecure: false
        accessKey:
          key: accessKey
          name: argo-repo-argo
        secretKey:
          key: secretKey
          name: argo-repo-argo
      target:
        type: NATS
        url: nats://nats-nats-client.argoproj.svc.cluster.local:4222
        attributes:
          subject: s3 object creted
  triggers: 
  ...
```
2. See error in `signal-artifact` pod logs
```
runtime error: invalid memory address or nil pointer dereferencegoroutine 13 [running]:
runtime/debug.Stack(0xc420257210, 0xde6de0, 0x154bb30)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc.(*grpcServer).accept.func1.1.1(0xc4202b49e0, 0xc4200c2500)
	/Users/mmagaldi/go/src/github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc/grpc.go:159 +0x79
panic(0xde6de0, 0x154bb30)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/argoproj/argo-events/signals/artifact.(*s3).Listen(0xc4203a97c0, 0xc4200f8000, 0xc420084de0, 0x0, 0xc420084de0, 0xdc6c60)
	/Users/mmagaldi/go/src/github.com/argoproj/argo-events/signals/artifact/s3.go:99 +0x254
github.com/argoproj/argo-events/sdk.(*microSignalServer).handshake(0xc4203a97d0, 0xfe4320, 0xc4202eec40, 0xc420084de0, 0x410379, 0xc4202eec40, 0x10)
	/Users/mmagaldi/go/src/github.com/argoproj/argo-events/sdk/micro_server.go:84 +0xe4
github.com/argoproj/argo-events/sdk.(*microSignalServer).Listen(0xc4203a97d0, 0xfe1fe0, 0xc420421290, 0xfe4320, 0xc4202eec40, 0xe41ca0, 0xc4200ec6c0)
	/Users/mmagaldi/go/src/github.com/argoproj/argo-events/sdk/micro_server.go:34 +0x82
github.com/argoproj/argo-events/sdk.(*signalServiceHandler).Listen(0xc4203a97e0, 0xfe1fe0, 0xc420421290, 0x7fe7b61d8218, 0xc4200ec6c0, 0xc4204395f8, 0x4116ac)
	/Users/mmagaldi/go/src/github.com/argoproj/argo-events/sdk/signal.micro.go:174 +0x90
reflect.Value.call(0xc4200dc7e0, 0xc4200e2458, 0x13, 0xf0e5ca, 0x4, 0xc4204399d0, 0x3, 0x3, 0xe319e0, 0xe41ca0, ...)
	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc4200dc7e0, 0xc4200e2458, 0x13, 0xc4203b19d0, 0x3, 0x3, 0x38, 0x38, 0xc4203d6ac0)
	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:308 +0xa4
github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc.(*grpcServer).processStream.func1(0xfe1fe0, 0xc420421290, 0xfe44a0, 0xc4200e19f0, 0xe41ca0, 0xc4200ec6c0, 0x14, 0xc420324e68)
	/Users/mmagaldi/go/src/github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc/grpc.go:434 +0x189
github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc.(*grpcServer).processStream(0xc4200c2500, 0xfea500, 0xc42039da00, 0xc42029c200, 0xc420457c80, 0xc4200ec240, 0xfe1660, 0x15814d8, 0xc420258600, 0x16, ...)
	/Users/mmagaldi/go/src/github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc/grpc.go:446 +0x42b
github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc.(*grpcServer).serveStream(0xc4200c2500, 0xfea500, 0xc42039da00, 0xc42029c200)
	/Users/mmagaldi/go/src/github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc/grpc.go:249 +0x708
github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc.(*grpcServer).accept.func1.1(0xc4202b49e0, 0xc4200c2500, 0xfea500, 0xc42039da00, 0xc42029c200)
	/Users/mmagaldi/go/src/github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc/grpc.go:163 +0x7d
created by github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc.(*grpcServer).accept.func1
	/Users/mmagaldi/go/src/github.com/argoproj/argo-events/vendor/github.com/micro/go-plugins/server/grpc/grpc.go:153 +0xbe
```

**Additional info**
Deployed from: 
- `docker.io/argoproj/artifact-signal:latest`
- `docker.io/argoproj/sensor-controller:latest`
