### ISSUE TITLE
global-outputs fail to resolve inside sensor triggered workflow

### ISSUE THREAD

**Issue by sgrimes-stackod** [argoproj/argo-events#932]
**Describe the bug**
global-outputs fail to resolve when creating a workflow from `source` as part of a Sensor triggers.k8s workflows create

**To Reproduce**
The following abbreviated workflow runs correctly when instantiated using `argo submit --from wftmpl/build`.

```
kind: WorkflowTemplate
spec:
  onExit: exit-handler
  entrypoint: build
  templates:
  - name: build
    outputs:
      parameters:
      - name: image-tag
        globalName: image-tag
        valueFrom:
          path: /tmp/image_tag
    script:
      command:
        - bash
      source: |
        DOCKER_TAG=<computed>
        echo "${DOCKER_TAG}" > /tmp/image_tag
  - name: exit-handler
    steps:
    - - name: notify-build-success
        template: notify-build-success
        when: "{{workflow.status}} == Succeeded"
        ...
  - name: notify-build-success
    steps:
      - - arguments:
            parameters:
            - name: message
              value: "Docker build success {{workflow.outputs.parameters.image-tag}}"
          ...
  ...
```

But same workflow fails with `Failed: invalid spec: templates.exit-handler.steps[0].notify-build-success templates.notify-build-success.steps failed to resolve {{workflow.outputs.parameters.image-tag}}` when the workflow is created via a sensor receiving a webhook ala:

```
kind: Sensor
spec:
  triggers:
    - template: 
        k8s:
          resource: workflows
          operation: create
          source:
            resource:
              kind: Workflow 
              spec:
                onExit: exit-handler
                entrypoint: build
                templates:
                - name: build
                  outputs:
                    parameters:
                    - name: image-tag
                      globalName: image-tag
                      valueFrom:
                        path: /tmp/image_tag
                  script:
                    command:
                      - bash
                    source: |
                      DOCKER_TAG=<computed>
                      echo "${DOCKER_TAG}" > /tmp/image_tag
                - name: exit-handler
                  steps:
                  - - name: notify-build-success
                      template: notify-build-success
                      when: "{{workflow.status}} == Succeeded"
                      ...
                - name: notify-build-success
                  steps:
                    - - arguments:
                          parameters:
                          - name: message
                            value: "Docker build success {{workflow.outputs.parameters.image-tag}}"
                        ...
                ...
```
**Expected behavior**
Per the [example global outputs file](https://github.com/argoproj/argo/blob/master/examples/global-outputs.yaml) I should be able to reference `{{workflow.outputs.parameters.image-tag}}` in templates within the created workflow.

**Environment (please complete the following information):**
 - Kubernetes: v1.17.9
 - Argo: v2.11.3
 - Argo Events: v1.0.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sgrimes-stackod** [comment]
Full Functioning Workflow Template 
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build
  namespace: argo
spec:
  arguments:
    parameters:
    - name: destination-helmrelease-file
      value: kubernetes/flux/release.yaml
  entrypoint: build
  onExit: exit-handler
  serviceAccountName: argo-workflow
  templates:
  - inputs:
      artifacts:
      - git:
          depth: 1
          repo: redacted
          sshPrivateKeySecret:
            key: identity
            name: argo-git-ssh-key
        name: git
        path: /src
    name: build
    outputs:
      parameters:
      - globalName: image-tag
        name: image-tag
        valueFrom:
          path: /tmp/image_tag
    script:
      command:
      - bash
      env:
      - name: DOCKER_HOST
        value: 127.0.0.1
      image: redacted
      source: |
        DOCKER_TAG="blerg"
        echo "${DOCKER_TAG}" > /tmp/image_tag
    sidecars:
    - image: docker:18.09.4-dind
      mirrorVolumeMounts: true
      name: dind
      securityContext:
        privileged: true
    workingDir: /src
  - name: exit-handler
    steps:
    - - name: notify-build-success
        template: notify-build-success
        when: '{{workflow.status}} == Succeeded'
      - name: notify-build-failure
        template: notify-build-failure
        when: '{{workflow.status}} != Succeeded'
  - inputs:
      parameters:
      - name: update-result
    name: update-exit-handler
    steps:
    - - name: notify-update-success
        template: notify-update-success
        when: '{{inputs.parameters.update-result}} == Succeeded'
      - name: notify-update-failure
        template: notify-update-failure
        when: '{{inputs.parameters.update-result}} != Succeeded'
  - name: notify-build-failure
    steps:
    - - arguments:
          parameters:
          - name: message
            value: Docker build failed
          - name: workflow-name
            value: '{{workflow.name}}'
          - name: notification-type
            value: failure
        name: external-ref-notify
        templateRef:
          name: notify
          template: notify
  - name: notify-build-success
    steps:
    - - arguments:
          parameters:
          - name: message
            value: Docker build success {{workflow.outputs.parameters.image-tag}}
          - name: workflow-name
            value: '{{workflow.name}}'
          - name: notification-type
            value: success
        name: external-ref-notify-build
        templateRef:
          name: notify
          template: notify
    - - arguments:
          parameters:
          - name: helmrelease-file
            value: '{{workflow.parameters.destination-helmrelease-file}}'
          - name: image-tag
            value: '{{workflow.outputs.parameters.image-tag}}'
        name: external-ref-update
        templateRef:
          name: update
          template: update
    - - arguments:
          parameters:
          - name: update-result
            value: '{{steps.external-ref-update.status}}'
        name: update-result
        template: update-exit-handler
  - name: notify-update-failure
    steps:
    - - arguments:
          parameters:
          - name: message
            value: HelmRelease {{workflow.parameters.destination-helmrelease-file}} was *not* updated to {{workflow.outputs.parameters.image-tag}}
          - name: workflow-name
            value: '{{workflow.name}}'
          - name: notification-type
            value: failure
        name: external-ref-notify
        templateRef:
          name: notify
          template: notify
  - name: notify-update-success
    steps:
    - - arguments:
          parameters:
          - name: message
            value: HelmRelease {{workflow.parameters.destination-helmrelease-file}} updated to {{workflow.outputs.parameters.image-tag}}
          - name: workflow-name
            value: '{{workflow.name}}'
          - name: notification-type
            value: success
        name: external-ref-notify
        templateRef:
          name: notify
          template: notify
  ttlStrategy:
    secondsAfterCompletion: 600
```

**Comment by sgrimes-stackod** [comment]
Full (failing) Sensor
```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: build
  namespace: argo
spec:
  dependencies:
  - eventName: build
    eventSourceName: build
    name: webhook
  template:
    metadata: {}
    serviceAccountName: argo-events-sa
  triggers:
  - template:
      name: build
      k8s:
        group: argoproj.io
        version: v1alpha1
        operation: create
        resource: workflows
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: body.ref
            dependencyName: webhook
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: build-
            spec:
              arguments:
                parameters:
                - name: pushed-branch
                  value: NOT-SET
                - name: build-branch
                  value: development
                - name: destination-helmrelease-file
                  value: kubernetes/flux/release.yaml
              entrypoint: build
              onExit: exit-handler
              serviceAccountName: argo-workflow
              templates:
              - inputs:
                  artifacts:
                  - git:
                      depth: 1
                      repo: redacted
                      sshPrivateKeySecret:
                        key: identity
                        name: argo-git-ssh-key
                    name: git
                    path: /src
                name: build
                outputs:
                  parameters:
                  - globalName: image-tag
                    name: image-tag
                    valueFrom:
                      path: /tmp/image_tag
                script:
                  command:
                  - bash
                  env:
                  - name: DOCKER_HOST
                    value: 127.0.0.1
                  image: redacted
                  source: |
                    DOCKER_TAG="blerg"
                    echo "${DOCKER_TAG}" > /tmp/image_tag
                sidecars:
                - image: docker:18.09.4-dind
                  mirrorVolumeMounts: true
                  name: dind
                  securityContext:
                    privileged: true
                when: '{{inputs.parameters.pushed-branch}} == refs/tags/{{inputs.parameters.build-branch}}'
                workingDir: /src
              - name: exit-handler
                steps:
                - - name: notify-build-success
                    template: notify-build-success
                    when: '{{workflow.status}} == Succeeded'
                  - name: notify-build-failure
                    template: notify-build-failure
                    when: '{{workflow.status}} != Succeeded'
              - inputs:
                  parameters:
                  - name: update-result
                name: update-exit-handler
                steps:
                - - name: notify-update-success
                    template: notify-update-success
                    when: '{{inputs.parameters.update-result}} == Succeeded'
                  - name: notify-update-failure
                    template: notify-update-failure
                    when: '{{inputs.parameters.update-result}} != Succeeded'
              - name: notify-build-failure
                steps:
                - - arguments:
                      parameters:
                      - name: message
                        value: Docker build failed
                      - name: workflow-name
                        value: '{{workflow.name}}'
                      - name: notification-type
                        value: failure
                    name: external-ref-notify
                    templateRef:
                      name: notify
                      template: notify
              - name: notify-build-success
                steps:
                - - arguments:
                      parameters:
                      - name: message
                        value: Docker build success {{workflow.outputs.parameters.image-tag}}
                      - name: workflow-name
                        value: '{{workflow.name}}'
                      - name: notification-type
                        value: success
                    name: external-ref-notify-build
                    templateRef:
                      name: notify
                      template: notify
                - - arguments:
                      parameters:
                      - name: helmrelease-file
                        value: '{{workflow.parameters.destination-helmrelease-file}}'
                      - name: image-tag
                        value: '{{workflow.outputs.parameters.image-tag}}'
                    name: external-ref-update
                    templateRef:
                      name: update
                      template: update
                - - arguments:
                      parameters:
                      - name: update-result
                        value: '{{steps.external-ref-update.status}}'
                    name: update-result
                    template: update-exit-handler
              - name: notify-update-failure
                steps:
                - - arguments:
                      parameters:
                      - name: message
                        value: HelmRelease {{workflow.parameters.destination-helmrelease-file}}  was *not* updated to {{workflow.outputs.parameters.image-tag}}
                      - name: workflow-name
                        value: '{{workflow.name}}'
                      - name: notification-type
                        value: failure
                    name: external-ref-notify
                    templateRef:
                      name: notify
                      template: notify
              - name: notify-update-success
                steps:
                - - arguments:
                      parameters:
                      - name: message
                        value: HelmRelease {{workflow.parameters.destination-helmrelease-file}}
                          updated to {{workflow.outputs.parameters.image-tag}}
                      - name: workflow-name
                        value: '{{workflow.name}}'
                      - name: notification-type
                        value: success
                    name: external-ref-notify
                    templateRef:
                      name: notify
                      template: notify
              ttlStrategy:
                secondsAfterCompletion: 600
```
