### ISSUE TITLE
Http Trigger Sensor -- Allow Specification of Http Headers

### ISSUE THREAD

**Issue by cbartram** [argoproj/argo-events#960]
**Is your feature request related to a problem? Please describe.**
I am frustrated because within a Http Trigger sensor I **can** specify the body and request method but **cannot** specify any http headers. The event sent to my endpoint does not include a `Content-Type` header and so in my Spring Boot Application when I try to handle the event within my endpoint I get the error: 

```
Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content type '' not supported]
```

**Describe the solution you'd like**
I would like to be able to specify http headers in my sensors (much like I can specify the payload and request method). For example:

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: wf
  namespace: default
spec:
  template:
    serviceAccountName: argo
  dependencies:
  - name: workflow
    eventSourceName: workflow
    eventName: feedback
  triggers:
  - template:
      name: http-trigger
      http:
        url: http://localhost:8080/my/custom/endpoint
        headers:
          - Content-Type: "application/json" # THIS IS WHAT I WANT TO BE ABLE TO SPECIFY
        payload:
          - src:
              dependencyName: {{ .Values.feedback.sensorDependencyName }}
              contextKey: id
            dest: contextEventID
          - src:
              dependencyName: {{ .Values.feedback.sensorDependencyName }}
              contextKey: type
            dest: eventSourceType
        method: POST

```

**Describe alternatives you've considered**
I have tried to dynamically add the header in a `ServletRequestFilter` through Spring however, I still receive the same issue. I have also tried to change the serialization/deserialization mechanisms in spring but nothing works if the header isn't present in the original request.

**Additional context**
In postman I have been able to replicate the same functionality by disabling the `Content-Type` header. I receive the same error **until** I re-enable the Content-Type header which resolves the issue and the event is processed normally.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
