### ISSUE TITLE
Sensor with a git trigger source does not execute correctly fetched Argo workflow

### ISSUE THREAD

**Issue by Atharex** [argoproj/argo-events#962]
**Describe the bug**
Argo events does not create a workflow, after fetching it from a git repository
The stated error is **cannot unmarshall spec: json: cannot unmarshal bool into Go value of type int**
The workflow works correctly when I use it with Argo directly, but not over Argo Events
 
**To Reproduce**
I am using the following setup to create a webhook for a mnist images project:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mnist-images-ingress
  namespace: argo-events
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: argo-api.<my-domain>
    http:
      paths:
      - path: /
        backend:
          serviceName: mnist-images-webhook-eventsource-svc
          servicePort: 12000

---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: argo-eventbus
  namespace: argo-events
spec:
  nats:
    native:
      replicas: 3
      auth: none
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: mnist-images-webhook
  namespace: argo-events
spec:
  eventBusName: argo-eventbus
  type: webhook
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    mnist-images-project-rebuild:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /mnist-images-e2e-rebuild
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST

---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: mnist-images-sensor
  namespace: argo-events
spec:
  eventBusName: argo-eventbus
  dependencies:
    - name: mnist-images-dependencies
      eventSourceName: mnist-images-webhook
      eventName: mnist-images-project-rebuild
  template:
    serviceAccountName: argo-events-sa
    container:
      volumeMounts:
        - mountPath: /git/argoproj
          name: argoproj
    volumes:
      - name: argoproj
        emptyDir: {}
  triggers:
    - template:
        name: git-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            git:
              url: "<my-private-bitbucket-repo>"
              cloneDirectory: "/git/argoproj"
              sshKeySecret:
                name: git-ssh
                key: key
              filePath: "mnist-images-e2e-rebuild.argo"
              branch: "master"
```

I trigger the workflow with the following command:
```
>>> curl -i -d '{"message":"ok"}' -H "Content-Type: application/json" -X POST https://argo-api.<my-domain>/mnist-images-e2e-rebuild
HTTP/1.1 200 OK
Content-Length: 7
Content-Type: text/plain; charset=utf-8
Date: Thu, 19 Nov 2020 17:31:49 GMT
Vary: Accept-Encoding

success
```

The cloning part seems correct as I can see my workflow in plaintext in the argo logs, but it is not executed.

**Expected behavior**
The workflow is cloned from the repository and correctly created in Argo.

**Environment (please complete the following information):**
 - Kubernetes: v1.19.4
 - Argo: v2.11.7
 - Argo Events: v1.1.0

**Additional context**
After applying the webhook manifest I see all pods running correctly.

```
>>> kubectl get pods -n argo-events
NAME                                                      READY   STATUS    RESTARTS   AGE
eventbus-argo-eventbus-stan-0                             2/2     Running   0          87s
eventbus-argo-eventbus-stan-1                             2/2     Running   0          85s
eventbus-argo-eventbus-stan-2                             2/2     Running   0          81s
eventbus-controller-56857d4bd6-jqsc4                      1/1     Running   0          43m
eventsource-controller-846d95d5fd-h8hp7                   1/1     Running   0          43m
mnist-images-sensor-sensor-fj27l-58b9c8dd5f-8wzxk         1/1     Running   2          86s
mnist-images-webhook-eventsource-s82h7-78945f6c89-x7k7w   1/1     Running   2          86s
sensor-controller-cdf9bc49-gfj9z                          1/1     Running   0          43m
```

Logs of Argo Events pods check out fine:
```
>>> kubectl logs -f -n argo-events mnist-images-sensor-sensor-fj27l-58b9c8dd5f-8wzxk
{"level":"info","ts":1605806659.236074,"logger":"argo-events.sensor","caller":"sensors/listener.go:350","msg":"Dependency expression for trigger git-workflow-trigger before simlification: mnist-images-dependencies","sensorName":"mnist-images-sensor"}
{"level":"info","ts":1605806659.236832,"logger":"argo-events.sensor","caller":"sensors/listener.go:357","msg":"Dependency expression for trigger git-workflow-trigger after simlification: mnist-images-dependencies","sensorName":"mnist-images-sensor"}
{"level":"info","ts":1605806659.23697,"logger":"argo-events.sensor","caller":"sensors/listener.go:211","msg":"Sensor started.","sensorName":"mnist-images-sensor"}
{"level":"info","ts":1605806659.237307,"logger":"argo-events.sensor","caller":"driver/nats.go:96","msg":"NATS auth strategy: None","sensorName":"mnist-images-sensor","clientID":"client-2063974121"}
{"level":"info","ts":1605806659.2465043,"logger":"argo-events.sensor","caller":"driver/nats.go:105","msg":"Connected to NATS server.","sensorName":"mnist-images-sensor","clientID":"client-2063974121"}
{"level":"info","ts":1605806659.2515335,"logger":"argo-events.sensor","caller":"driver/nats.go:118","msg":"Connected to NATS streaming server.","sensorName":"mnist-images-sensor","clientID":"client-2063974121"}
{"level":"info","ts":1605806659.2518098,"logger":"argo-events.sensor","caller":"sensors/listener.go:177","msg":"starting eventbus connection daemon for client client-2063974121...","sensorName":"mnist-images-sensor"}
{"level":"info","ts":1605806659.2520154,"logger":"argo-events.sensor","caller":"sensors/listener.go:165","msg":"started subscribing to events for triggers [git-workflow-trigger] with client client-2063974121","sensorName":"mnist-images-sensor"}
{"level":"info","ts":1605806659.256881,"logger":"argo-events.sensor","caller":"driver/nats.go:159","msg":"Subscribed to subject eventbus-argo-events ...","sensorName":"mnist-images-sensor","clientID":"client-2063974121"}
{"level":"info","ts":1605806659.2571614,"logger":"argo-events.sensor","caller":"driver/nats.go:167","msg":"starting ExactOnce cache clean up daemon ...","sensorName":"mnist-images-sensor","clientID":"client-2063974121"}
{"level":"info","ts":1605806693.678034,"logger":"argo-events.sensor","caller":"standard-k8s/standar-k8s.go:163","msg":"creating the object...","sensorName":"mnist-images-sensor"}
{"level":"info","ts":1605806693.692932,"logger":"argo-events.sensor","caller":"sensors/listener.go:267","msg":"successfully processed the trigger","sensorName":"mnist-images-sensor","triggerName":"git-workflow-trigger","triggeredBy":["mnist-images-dependencies"]}
{"level":"info","ts":1605806719.2573955,"logger":"argo-events.sensor","caller":"driver/nats.go:187","msg":"finished evicting 0 cached IDs, time cost: 0 ms","sensorName":"mnist-images-sensor","clientID":"client-2063974121"}
```

```
>>> kubectl logs -f -n argo-events mnist-images-webhook-eventsource-s82h7-78945f6c89-x7k7w
{"level":"info","ts":1605806655.4720867,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:263","msg":"Starting event source server...","eventSourceName":"mnist-images-webhook"}
{"level":"info","ts":1605806655.4722717,"logger":"argo-events.eventsource","caller":"driver/nats.go:96","msg":"NATS auth strategy: None","eventSourceName":"mnist-images-webhook","clientID":"mnist-images-webhook-eventsource-s82h7-78945f6c89
-x7k7w"}
{"level":"info","ts":1605806655.479151,"logger":"argo-events.eventsource","caller":"driver/nats.go:105","msg":"Connected to NATS server.","eventSourceName":"mnist-images-webhook","clientID":"mnist-images-webhook-eventsource-s82h7-78945f6c89-x7k7w"}
{"level":"error","ts":1605806657.4802878,"logger":"argo-events.eventsource","caller":"driver/nats.go:115","msg":"Failed to connect to NATS streaming server","eventSourceName":"mnist-images-webhook","clientID":"mnist-images-webhook-eventsource-s82h7-78945f6c89-x7k7w","error":"stan: connect request timeout (possibly wrong cluster ID?)","stacktrace":"github.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).Connect\n\t/home/runner/work/argo-events/argo-events/eventbus/driver/nats.go:115\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:271\ngithub.com/argoproj/argo-events/common.Connect.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:75\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.6-beta.0/pkg/util/wait/wait.go:292\ngithub.com/argoproj/argo-events/common.Connect\n\t/home/runner/work/argo-events/argo-events/common/retry.go:74\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:270\nmain.main\n\t/home/runner/work/argo-events/argo-events/eventsources/cmd/main.go:60\nruntime.main\n\t/opt/hostedtoolcache/go/1.14.11/x64/src/runtime/proc.go:203"}
{"level":"info","ts":1605806659.36061,"logger":"argo-events.eventsource","caller":"driver/nats.go:96","msg":"NATS auth strategy: None","eventSourceName":"mnist-images-webhook","clientID":"mnist-images-webhook-eventsource-s82h7-78945f6c89-x7k7w"}
{"level":"info","ts":1605806659.4078135,"logger":"argo-events.eventsource","caller":"driver/nats.go:105","msg":"Connected to NATS server.","eventSourceName":"mnist-images-webhook","clientID":"mnist-images-webhook-eventsource-s82h7-78945f6c89-x7k7w"}
{"level":"info","ts":1605806659.411682,"logger":"argo-events.eventsource","caller":"driver/nats.go:118","msg":"Connected to NATS streaming server.","eventSourceName":"mnist-images-webhook","clientID":"mnist-images-webhook-eventsource-s82h7-78945f6c89-x7k7w"}
{"level":"info","ts":1605806659.4117584,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:361","msg":"Eventing server started.","eventSourceName":"mnist-images-webhook"}
{"level":"info","ts":1605806659.411954,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:286","msg":"starting eventbus connection daemon...","eventSourceName":"mnist-images-webhook"}
{"level":"info","ts":1605806659.4126294,"logger":"argo-events.eventsource","caller":"webhook/start.go:139","msg":"started processing the webhook event source...","eventSourceName":"mnist-images-webhook","eventSourceType":"webhook","eventName":"mnist-images-project-rebuild"}
{"level":"info","ts":1605806659.412711,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:214","msg":"validating the route...","eventSourceName":"mnist-images-webhook","eventSourceType":"webhook","eventName":"mnist-images-project-rebuild","eventSourceName":"mnist-images-webhook","eventName":"mnist-images-project-rebuild"}
{"level":"info","ts":1605806659.4127405,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:220","msg":"listening to payloads for the route...","eventSourceName":"mnist-images-webhook","eventSourceType":"webhook","eventName":"mnist-images-project-rebuild","eventSourceName":"mnist-images-webhook","eventName":"mnist-images-project-rebuild"}
{"level":"info","ts":1605806659.412761,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:227","msg":"activating the route...","eventSourceName":"mnist-images-webhook","eventSourceType":"webhook","eventName":"mnist-images-project-rebuild","eventSourceName":"mnist-images-webhook","eventName":"mnist-images-project-rebuild"}
{"level":"info","ts":1605806659.413165,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:177","msg":"route is activated","eventSourceName":"mnist-images-webhook","eventSourceType":"webhook","eventName":"mnist-images-project-rebuild","eventSourceName":"mnist-images-webhook","eventName":"mnist-images-project-rebuild","port":"12000","endpoint":"/mnist-images-e2e-rebuild"}
{"level":"info","ts":1605806659.4132104,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:230","msg":"running operations post route activation...","eventSourceName":"mnist-images-webhook","eventSourceType":"webhook","eventName":"mnist-images-project-rebuild","eventSourceName":"mnist-images-webhook","eventName":"mnist-images-project-rebuild"}
{"level":"info","ts":1605806692.9221575,"logger":"argo-events.eventsource","caller":"webhook/start.go:91","msg":"a request received, processing it...","eventSourceName":"mnist-images-webhook","eventSourceType":"webhook","eventName":"mnist-images-project-rebuild","eventSourceName":"mnist-images-webhook","eventName":"mnist-images-project-rebuild","endpoint":"/mnist-images-e2e-rebuild","port":"12000","http-method":"POST"}
{"level":"info","ts":1605806692.9223318,"logger":"argo-events.eventsource","caller":"webhook/start.go:119","msg":"dispatching event on route's data channel...","eventSourceName":"mnist-images-webhook","eventSourceType":"webhook","eventName":"mnist-images-project-rebuild","eventSourceName":"mnist-images-webhook","eventName":"mnist-images-project-rebuild","endpoint":"/mnist-images-e2e-rebuild","port":"12000","http-method":"POST"}
{"level":"info","ts":1605806692.9223487,"logger":"argo-events.eventsource","caller":"webhook/start.go:121","msg":"successfully processed the request","eventSourceName":"mnist-images-webhook","eventSourceType":"webhook","eventName":"mnist-images-project-rebuild","eventSourceName":"mnist-images-webhook","eventName":"mnist-images-project-rebuild","endpoint":"/mnist-images-e2e-rebuild","port":"12000","http-method":"POST"}
{"level":"info","ts":1605806692.9224741,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:187","msg":"new event received, dispatching it...","eventSourceName":"mnist-images-webhook","eventSourceType":"webhook","eventName":"mnist-images-project-rebuild","eventSourceName":"mnist-images-webhook","eventName":"mnist-images-project-rebuild"}
{"level":"info","ts":1605806692.9241624,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:350","msg":"succeeded to publish an event","eventSourceName":"mnist-images-webhook","eventName":"mnist-images-project-rebuild","eventSourceType":"webhook"}
```

And when I check the argo workflow controller pod I see the following warning:
```
>>> kubectl logs -f -n argo workflow-controller-57556db964-kmkqg
time="2020-11-19T17:31:49Z" level=warning msg="Failed to unmarshal key to workflow object" error="json: cannot unmarshal bool into Go value of type int" key=argo/mnist-images-e2e-rebuild-5lk9z
time="2020-11-19T17:31:49Z" level=info msg="Updated phase  -> Failed" namespace=argo workflow=mnist-images-e2e-rebuild-5lk9z
time="2020-11-19T17:31:49Z" level=info msg="Updated message  -> cannot unmarshall spec: json: cannot unmarshal bool into Go value of type int" namespace=argo workflow=mnist-images-e2e-rebuild-5lk9z
time="2020-11-19T17:31:49Z" level=info msg="Marking workflow completed" namespace=argo workflow=mnist-images-e2e-rebuild-5lk9z
time="2020-11-19T17:31:49Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=13398 workflow=mnist-images-e2e-rebuild-5lk9z
time="2020-11-19T17:31:49Z" level=warning msg="Invalid workflow object" key="&{map[apiVersion:argoproj.io/v1alpha1 kind:Workflow **<full workflow output>** ]}"
```
The **<full workflow output>** part is where Argo logs my full workflow spec in yaml as it fetched it from the git repository.
So the webhook trigger correctly fetches the workflow, but it does not execute it. Is this a problem with my configuration, or is it a bug with Events? The workflow works normally with Argo Workflows.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
