### ISSUE TITLE
Parameters in Sensor to support object operation

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#970]
**Is your feature request related to a problem? Please describe.**
Parameters make it possible to set string values in Triggers, however it can not do object operations, e.g. set a list to the parameter.

Following spec will set the value of `withItems` as `'[item1 item2 item3]'`.

```
          parameters:
            - src:
                dependencyName: test-dep
                dataTemplate: "{{ .Input.body.message | splitList \"$\" }}"
              dest: spec.templates.0.steps.0.0.withItems
```

**Describe the solution you'd like**
Spec above will set `withItems` as `[item1 item2 item3]`, which is a list.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.
