### ISSUE TITLE
Duplicate eventSourceName/eventName validation in Sensor

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#971]
**Is your feature request related to a problem? Please describe.**
Same `eventSourceName` + `eventName` are not allowed to define multiple times in one Sensor object, this should be validated in sensor-controller.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by jomach** [comment]
this is very useful: 
```
    - name: kafka-message
      eventSourceName: kafka
      eventName: datahub-notify-event-source
      # https://github.com/argoproj/argo-events/blob/master/examples/sensors/filter-with-expressions.yaml
      filters:
        expr:
          - expr: component == "data-service" && eventType == "commit-dataset"
            fields:
              - name: component
                path: component
              - name: eventType
                path: eventType
    - name: dataset_id
      eventSourceName: kafka
      eventName: datahub-notify-event-source
      transform:
        jq: ".datasetId"
    - name: tenant
      eventSourceName: kafka
      eventName: datahub-notify-event-source
      transform:
        jq: "tenant"
```
